config/test/test.config.js, package.json, packages/kas/src/__tests__/index.test.ts, packages/kas/src/__tests__/units.test.ts, packages/perseus/src/widget-type-utils.test.ts, packages/perseus/src/widgets/__tests__/dropdown.test.ts, packages/perseus/src/widgets/__tests__/image.test.ts, packages/perseus/src/widgets/__tests__/input-number.test.ts, packages/perseus/src/widgets/__tests__/numeric-input.test.ts, packages/perseus/src/widgets/__tests__/radio/choice.test.tsx, yarn.lock
When we moved Perseus out of webapp and back into this repo, we kept a dependency on `jest-extended`. Today, Perseus' use of this package is minimal and there are obvious Jest-native matchers that we can use instead. 
So, today we drop the `jest-extended` dependency.
Issue: "none"
`yarn test` ✅
=> Remove jest-extended package

packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, types/global.d.ts
At the end of the React 18 work I noticed two failing tests in the Interactive Graph suite. I found that its the two tests that had to be customized to pass related to `startCoords`. 
If I remove this customization, all tests pass. My hunch is that with React 16 and the older `@testing-library` package, there was some async DOM updates/events that didn't flush all the way leaving the graph in a non-final state after keypresses, thus failing the tests. 
Issue: LEMS-2186
`yarn test` ✅✨🎉😍
=> Resolve LEMS-2186 - no longer need 'off by 0.5' startCoords

.github/workflows/maintenance.yml
This PR introduces a new Github Action that will run weekly (on Monday's at 7:30 am UTC - which maps to somewhere in the night in North America).
We will still need to manually approve and land these PRs to merge the changes (#security). Also, if we do not land the PR before this action runs again, the PR will simply be updated.
Issue: "none"
We can run this action manually to test. Upon running it, a new PR with the title 'chore: update browserslist' should appear.
=> Update browserslist and caniuse-lite packages weekly

.changeset/few-trainers-march.md, packages/perseus/src/widgets/interactive-graphs/protractor.css
During a playtest, Nicole noted that the rotation handle for the new
interactive graph protractor had a hover animation that felt out of
place. The animation was faster than the hover animation for movable
points. The protractor handle also enlarged more than the points do when
you hovered over it.
This commit brings the protractor handle animation in line with the
movable point animations.
Issue: none
Test plan:
Copy this data into the interactive graph flipbook:
```json
{"content":"**Construct a $130^\\circ$ angle.**\n\n[[☃ interactive-graph 1]]\n\n\n","images":{"https://ka-perseus-images.s3.amazonaws.com/02564832cdaa56aa507437df41dd13e1fefbe595.png":{"height":160,"width":398},"https://ka-perseus-images.s3.amazonaws.com/37521922ea42bbbf67622075e1ea51e095f37479.png":{"height":291,"width": …
```
=> Lower the intensity of the protractor handle hover animation

.changeset/curvy-crabs-march.md, packages/math-input/package.json, packages/math-input/src/components/keypad/__tests__/__snapshots__/keypad.test.tsx.snap, packages/math-input/src/components/keypad/keypad-mathquill.stories.tsx, packages/math-input/src/components/tabbar/item.tsx, packages/perseus/package.json, packages/perseus/src/components/__tests__/math-input.test.tsx, packages/perseus/src/components/math-input.tsx, packages/perseus/src/widgets/expression.tsx, yarn.lock
This update includes:
- Updating @khanacademy/wonderblocks-popover package version
- Disabiling portaling popover functionality, ensuring keyboard navigation works for expression widget.
- Removing timeout logic for portal-hack.
Issue: LEMS-2087
- Navigate to /?path=/story/perseus-widgets-expression--desktop-kitchen-sink
- Open expression widget
- Notice that you can't hit tab key to navigate all tabs in expression widget. Tab will get you to the first element, then use left and right arrow-keys to navigate to other tab keys. Hit tab again to go to tab content.
=> [Expression Widget] Disabling portal functionality on Popover implementation

.changeset/pretty-points-drop.md, packages/perseus-editor/src/__stories__/editor-page-with-storybook-preview.tsx, packages/perseus/src/__stories__/hints-renderer.stories.tsx, packages/perseus/src/hint-renderer.tsx, packages/perseus/src/mixins/widget-prop-denylist.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widget-container.tsx, packages/perseus/src/widgets/__stories__/expression.stories.tsx, packages/perseus/src/widgets/__tests__/passage.test.tsx, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
=> Add hintMode to widget and Renderer props

packages/perseus/src/widgets/__tests__/interactive-graph.test.tsx
Matthew noticed that these tests fail sometimes in CI. They also fail sporadically (especially, it seems, on older/slower laptops). 
Extending the timeout for the final `waitFor()` calls seems to fix them and give the graph enough time to process the actions that are dispatched by the keypresses. 
Issue: LEMS-1802 
All tests pass. 
All tests pass in CI. 
All tests pass in CI again.
=> Fix flaky tests (following React 18/RTL upgrade)

packages/perseus/src/widgets/__tests__/interactive-graph.test.tsx
In PR #1440 we thought we'd fixed these flaky tests in CI. After landing it though, the tests failed in the "Version Packages" PR actions failed. So, that wasn't the fix. 
This PR now skips them. This is not great, but I intend this to be very short-lived (ie. it's the next thing I will work on).
Issue: LEMS-1802
Tests pass... all the time. :fingers-crossed:
=> Skip flaky tests again

.changeset/stale-geese-protect.md, packages/perseus/src/widgets/interactive-graphs/graphs/use-draggable.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/use-draggable.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
While @nicolecomputer and I were investigating why the `interactive-graph.test.tsx` tests _sometimes_ failed in CI and other slower environments, we found that the `useDraggable()` hook was handling both `keydown` as well as `keyup` events.
Through some testing we discovered also that the browser sends only a `keydown` event for a single keypress. When the key is held down, we saw a series of `keydown` events and then a single `keyup` event when the key was released. 
To that end, we've adjusted `useDraggable` to ignore all `keyup` events.
Issue: LEMS-1820, LEMS-1934
`yarn test` all tests pass
In storybook, you can notice that there's one fewer moves when selecting a point and then holding down the arrow key to move it. Previously, there was a final move because of the `keyup` processing. …
=> Fix use-draggable hook to ignore 'keyup' events

.github/workflows/maintenance.yml
After landing the new Github Action to periodically update the `caniuse` database, I noticed the action failing. It turns out that the `GITHUB_TOKEN` is scoped to this repo only and we need a token that has Org permissions so that we can tag teams defined at the org level. 
See: https://khanacademy.slack.com/archives/CEA6W0F6F/p1721743441208509?thread_ts=1721692544.947749&cid=CEA6W0F6F
This PR switches to a token that has those permissions.
Issue: "none"
=> [🔥AUDIT🔥] Use github token that has repo access so we can tag Org teams

.changeset/great-planets-fix.md, .changeset/twelve-pianos-collect.md, packages/perseus-editor/src/components/__tests__/start-coords-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/start-coords-line.tsx, packages/perseus-editor/src/components/start-coords-multiline.tsx, packages/perseus-editor/src/components/start-coords-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
The StartCoordsSettings file was getting unruly and hard to follow. I'm refactoring
it here to make it easier to add more types, and to make it generally more
maintainable.
- Broke out the main UI input section for each graph type into its own file
- Removed the unnecessary switch statement (only need to pass in `undefined` to
reset to default coords)
- Updated the button to "Use default start coordinates" instead of "Use default
start coords" as per Sarah Third's recommendation
- Updated the labels from "x/y coords" to just "x/y" to save space and look
cleaner. (I did get [permission from the content authors](https://khanacademy.slack.com/archives/C04EA1QAKN0/p1721860247138389) for this.)
- Removed all the checks for the graph type. The feature is behind a feature
flag, so no one should …
=> [Interactive Graph Editor] Refactor and clean up start coords UI implementation

.changeset/lemon-carpets-grab.md, package.json, packages/math-input/package.json, yarn.lock
Updating mathjax-renderer to the latest version to remove the incorrect highlighting color of math.
Before
After
Issue: none
- Run `yarn dev`
- Highlight any text containing mathjax on the gallery
- Confirm all the text is highlighted the same color
=> Update mathjax-renderer to latest version

.changeset/new-fireants-draw.md, packages/perseus/package.json, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/__stories__/locked-functions.stories.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, yarn.lock
With this upgrade, Mafs now supports domain restrictions when plotting functions. Once this upgrade is in place, locked functions will have domain restrictions as an option.
Issue: LEMS-2140
1. Launch Storybook (yarn start)
1. Navigate to Perseus => Widgets => Interactive Graph => Locked Functions
* [Minimum domain](http://localhost:6006/?path=/story/perseus-widgets-interactive-graph-locked-functions--domain-restricted-min): Starts at x=-5 and plots all values greater (i.e. to the right).
* [Maximum domain](http://localhost:6006/?path=/story/perseus-widgets-interactive-graph-locked-functions--domain-restricted-max): Ends at x=5 and plots all values less than (i.e. to the left).
* [Combined restrictions](http://localhost:6006/?path=/story/perseus-widgets-interactive-graph-locked-functions-- …
=> Upgrade Mafs to v0.19.0 (Domain-restricted functions)

.changeset/quiet-moose-arrive.md, packages/perseus/src/widgets/explanation.tsx, packages/perseus/src/widgets/label-image.tsx, packages/perseus/src/widgets/label-image/marker.tsx
This PR makes sure that we don't call `matchMedia` during the initial render. This is because `matchMedia` is not available during the initial render, and calling it will throw an error.
Issue: FEI-5743
1. Put up this PR and await the pre-release packages
2. Update webapp with the pre-release packages
3. Put up a webapp PR and check that the ZND is working on URLs that were previously erroring
=> Guard against matchMedia access during initial render

.changeset/young-clocks-walk.md, packages/math-input/src/components/keypad/__tests__/__snapshots__/keypad.test.tsx.snap, packages/math-input/src/components/keypad/keypad-mathquill.stories.tsx, packages/math-input/src/components/tabbar/item.tsx, packages/perseus/src/components/__tests__/math-input.test.tsx, packages/perseus/src/components/math-input.tsx
Adding back portal functionality for Expression Widget to ensure it does not get clipped.
This implementation was originally added in this PR: https://github.com/Khan/perseus/pull/1424
Issue: LEMS-2224
Go to https://khan.github.io/perseus/?path=/story/perseus-widgets-expression--desktop-kitchen-sink
Confirm that you have to tab through all the tab pannels to get the the main keypad, instead of going directly to the keypad.
=> Reverting portal disable functionality, causing clipping behavior.

.changeset/wicked-rocks-exist.md, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
The stories are broken because of a missing null check.
Adding that here.
Issue: none
`yarn start`
Check that the following stories work
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph-editor--default
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph-editor--controlled
=> [Interactive Graph Editor - Stories] Fix broken default and controlled stories

.changeset/slow-taxis-give.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/components/start-coords-settings.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/types.ts
We want to be able to release the start coords UI even if
only a subset of graph types are ready. To accomodate this,
I'm adding individual flags for each graph type.
Issue: none
Storybook
- http://localhost:6006/?path=/docs/perseuseditor-widgets-interactive-graph--docs
- Confirm that the UI shows up for the currently landed graphs - segment, ray, linear, linear-system, circle
- Confirm that the UI does not show up for the graphs that are not done yet - sinusoid, quadratic, angle, polygon, point
=> [Hint Mode: Start Coords] Add separate flags for graph types

.changeset/sweet-seas-dance.md, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts
The new Mafs-based Angle graphs were being marked as incorrect if the user moves the bottom point clockwise, which was not caught earlier as there was a bug in the implementation of the legacy Angle graphs that allowed users to create reflexive angles when they were not supposed to be able to. 
The new Mafs-based Angle graph solves this issue, but it uncovered a bug in our scoring that fails to handle this particular state. 
This ticket adds the logic necessary to reverse the coordinates (for scoring purposes) when they're clockwise and reflexive graphs are not allowed. This will be the approach used until we are able to remove/deprecate the legacy Angle graphs. 
When the legacy Angle graph is removed, it's highly recommended that this logic be moved directly to the scoring function in …
=> Ensure the new Mafs-based Angle Graphs score correctly 

.changeset/grumpy-rivers-draw.md, packages/perseus-editor/src/components/__tests__/start-coords-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/start-coords-quadratic.tsx, packages/perseus-editor/src/components/start-coords-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/index.ts, packages/perseus/src/widgets/interactive-graphs/reducer/initialize-graph-state.ts
Add the UI to specify start coords for Quadratic graph type.
- Add the quadratic graph type to start-coord-settings.tsx
- Create a start-coords-quadratic.tsx file with the main UI
- Add a utility for getting the quadratic equation from coordinates (less complex
than the static method on InteractiveGraph that does the same)
- Add quadratic graph to the phase 2 flag
Issue: https://khanacademy.atlassian.net/browse/LEMS-2210
`yarn jest`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-quadratic-with-starting-coords
=> [Hint Mode: Start Coords] Add start coords UI for quadratic graphs

.changeset/gentle-melons-jam.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/components/__stories__/locked-figures-section.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-figures-section.test.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-ellipse-settings.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-figure-select.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-figure-settings-actions.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-figure-settings.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-figures-section.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-line-settings.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-point-settings.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-polygon-settings.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-vector-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/types.ts
Now that locked figures m2 has been released for a while with no issues coming up,
we can remove the flag conditionals from the code.
After this, I'll remove the flag from webapp and growthbook as well.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2016
`yarn jest`
Scour the Perseus repo for instances of `m2Features`, `features-m2`, and other
variations. Confirm they no longer exist.
Look for m2b and make sure m2 is no longer next to it in each location.
=> [Interactive Graph Locked Figures] Remove m2 flag from the code

.changeset/blue-moons-carry.md, packages/perseus/src/components/__stories__/image-loader.stories.tsx, packages/perseus/src/components/image-loader.tsx, packages/perseus/src/components/svg-image.tsx, packages/perseus/src/server-item-renderer.tsx
While chasing down a question from LearningEquality, I noticed some `@ts-expect-error` usages that made me wonder. After removing them I found it was quite easy to make the types correct.
This is also a common problem in our codebase following the port from Flow to TypeScript. We often set props to have the type `SomeType | null | undefined`. However, often we don't need to support it being `null`. In this case, removing the assignment of a default value (`null`) fixed the main issue.
Issue: "none"
`yarn lint`
=> ImageLoader: fix types and remove @ts-expect-error instances

.changeset/young-suns-beg.md, packages/perseus-editor/src/__tests__/item-extras-editor.test.tsx, packages/perseus-editor/src/item-extras-editor.tsx, packages/perseus-editor/src/styles/perseus-editor.less
While working in the Perseus Editor I took a few minutes to convert the item extras editor to use WB checkboxes. This results in much nicer layout (checkboxes all on the left, better typography).
|---|---|
| <img alt="Screenshot 2024-08-01 at 4 09 02 PM" src="https://github.com/user-attachments/assets/6ceb926b-fb45-45f8-9c28-f3d5b8d1e378"> | <img alt="Screenshot 2024-08-01 at 4 08 52 PM" src="https://github.com/user-attachments/assets/a6b1937e-b8d5-4adc-a8b4-bb1fde40f152"> | 
Run storybook and look at the Editor Page or Item Extras Editor stories. 
I also verified that it still serializes the right data out and that nested checkboxes work.
=> Migrate ItemExtrasEditor to Wonder-Blocks

.changeset/tasty-eggs-drop.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/components/__tests__/start-coords-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/start-coords-circle.tsx, packages/perseus-editor/src/components/start-coords-point.tsx, packages/perseus-editor/src/components/start-coords-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/index.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graphs/reducer/initialize-graph-state.ts
Add the UI to specify start coords for Point graph type.
- Add the point graph type to start-coord-settings.tsx
- Create a start-coords-point.tsx file with the main UI
- Add the start coords UI point flag
- Move the logic for determining whether the UI should be
shown based on the feature flags out into the util file.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2209
`yarn jest`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-point
=> [Hint Mode: Start Coords] Add start coords UI for point graphs (limited only)

.changeset/unlucky-lamps-draw.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/components/__tests__/start-coords-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/start-coords-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/index.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graphs/reducer/initialize-graph-state.ts
Add the UI to specify start coords for Polygon graph type (not unlimited, snap to grid only)
- Add the polygon graph type go start-coords-settings.tsx
- No need to create a separate start-coord-polygon.tsx file because
it's identical to start-coord-point.tsx. Reusing that component.
- Update the selection logic in interactive-graph-editor.tsx so it
properly updates the graph with the new snapTo value. (It was stuck
on the previously selected value before.)
- Add the start coords UI polygon flag
- Update the flag tests so they actually test what they're supposed to
Issue: https://khanacademy.atlassian.net/browse/LEMS-2072
`yarn jest`
Storybook
- Polygon story without default graph settings
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-polygo …
=> [Hint Mode: Start Coords] Add start coords UI for polygon graphs (snap to grid only)

.changeset/four-laws-wash.md, packages/perseus-editor/src/article-editor.tsx, packages/perseus-editor/src/editor.tsx, packages/perseus-editor/src/hint-editor.tsx, packages/perseus-editor/src/item-editor.tsx, packages/perseus-editor/src/widgets/__stories__/radio-editor.stories.tsx, packages/perseus/src/__stories__/server-item-renderer.stories.tsx, packages/perseus/src/components/__stories__/button-group.stories.tsx, packages/perseus/src/components/__stories__/fixed-to-responsive.stories.tsx, packages/perseus/src/components/__stories__/graph.stories.tsx, packages/perseus/src/components/__stories__/graphie.stories.tsx, packages/perseus/src/components/__stories__/hud.stories.tsx, packages/perseus/src/components/__stories__/icon.stories.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts
This PR contains several more type fixes following #1474:
* `ImageUploader` deduped and parameter type fixed
* Some stories moved to modern Storybook types (allowing us to eliminate some manual component prop type declarations). See [docs](https://storybook.js.org/docs/writing-stories#defining-stories).
* `question` type on ItemEditor properly typed as `PerseusRenderer` type
Issue: "none"
`yarn lint`
=> Type fixes

.changeset/clean-glasses-watch.md, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx
I noticed that the "Reset to default coordinates" button still shows up for
polygon graphs with unlimited sides, but it's not supposed to. I figured out
that this is because I accidentally used `numPoints` instead of `numSides` in
the logic.
- Fix the flags logic
- Add tests
Issue: https://khanacademy.atlassian.net/browse/LEMS-2072
`yarn jest packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx`
Storybook
- Go to http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-polygon
- Set number of sides to "unlimited sides"
- Confirm that the start coords UI no longer shows up
=> [Hint Mode: Start Coords] Correct flag logic for polygon graph start coords UI

.changeset/gentle-planes-rest.md, packages/perseus-editor/src/hint-editor.tsx, packages/perseus/src/hints-renderer.tsx, packages/perseus/src/index.ts, packages/perseus/src/multi-items/multi-renderer.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/__testdata__/grapher.testdata.ts, packages/perseus/src/widgets/__testdata__/interaction.testdata.ts, packages/perseus/src/widgets/__testdata__/video.testdata.ts
Our `hints` type on `ItemRenderer` used the `PerseusRenderer` type. That's mostly correct, except that a Hint can also have the `replace` key. 
Issue: "none"
`yarn typecheck` ✅
=> Hints: fix hints type on PerseusItem to be correct

.changeset/flat-badgers-matter.md, packages/math-input/src/components/key-handlers/key-translator.ts, packages/math-input/src/components/keypad/button-assets.tsx, packages/math-input/src/data/key-configs.ts, packages/math-input/src/data/keys.ts, packages/math-input/src/enums.ts, packages/math-input/src/types.ts
These are the buttons that were in the old keypad but not the new keypad. They were never properly handled because we never needed them.
=> remove buttons that were only in the old keypad

.changeset/eleven-paws-serve.md, .changeset/friendly-lemons-battle.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/start-coords-angle.tsx, packages/perseus-editor/src/components/start-coords-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus/src/index.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/interactive-graphs/reducer/initialize-graph-state.ts
This PR includes the foundation/prerequisites for adding the start coords UI for angle graphs.
- Add the polygon graph type to start-coords-settings.tsx
- Create a WORK IN PROGRESS start-coords-angle.tsx file. This will be properly filled in
in the following PR, whose main purpose will be adding the body for the UI.
- Add the start coords UI angle flag
- Add a storybook story for angle graphs (and update polygon story to start with start coords)
- Update the angle initializer to account for start coords
Issue: https://khanacademy.atlassian.net/browse/LEMS-2073
`yarn jest`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-angle
=> [Hint Mode: Start Coords] Build the foundation for adding start coords UI for angle graphs

.changeset/neat-days-remain.md, packages/perseus/src/widgets/__stories__/interactive-graph.stories.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/angle.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/use-draggable.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/use-draggable.ts, packages/perseus/src/widgets/interactive-graphs/math/angles.ts, packages/perseus/src/widgets/interactive-graphs/math/geometry.test.ts, packages/perseus/src/widgets/interactive-graphs/math/geometry.ts, packages/perseus/src/widgets/interactive-graphs/protractor.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
This PR makes it so angle graph questions can be solved with only a keyboard -
no mouse required!
There are several tricky constraints to this problem:
- Every distinct state of the graph needs to be reachable using only the
keyboard.
- In order for the movement to feel natural, pressing an arrow key should
always move the point in the corresponding direction: up, down, left, or right.
- However, the points need to snap, not to a grid, but to angle measures
(in degrees).
- The side points of the angle should not be allowed to get too close to the
vertex - if they overlap the vertex there's no way to drag them away again.
- The points shouldn't be able to move outside the graph bounds
- It should never be possible for an edge point to get "stuck" or blocked in its
movement by the edge of …
=> Add keyboard controls to angle graphs

.changeset/wise-lamps-tell.md, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
The builder should not be setting the `coords` inside the graph's `correct` field by default.
The correct answer `coords` get set after the content authors interact with the graph's
"correct answer" preview.
When the coords are undefined, the graph renders with the default starting coords. If we were
to pass in the coords explicitly in the builder, it would (a) not be an accurate representation
of the initial state of a graph, and (b) we would have to make sure we use the initialization
logic to confirm that we're setting coords based on the number of segments, sides, or points
for segment graphs, polygon graphs, and point graphs respectively.
Updating the coords to be undefined by default inside the builder also fixes an issue where
the "correct answer" preview was showing the wrong …
=> [Interactive Graph: test utils] Do not set the coords field by default in the builder

.changeset/smooth-hornets-march.md, packages/math-input/src/components/tabbar/item.tsx, packages/perseus/src/components/math-input.tsx
- Removes hover color from math input tabs 
- Adds white border to open math keyboard button to increase contrast between icon and active state border
Issue: LEMS-2083
1. Navigate to [Math Input in storybook ](https://650db21c3f5d1b2f13c02952-edopglbcau.chromatic.com/)
2. Open the expression widget 
3. Hover over tabs 
4. Close expression widget 
(Step 3)
- On Hover, tabs should not have a background color 
(Step 4)
- Focus state (active) for math keyboard button should have extra white space between the border of the input and the icon
https://github.com/user-attachments/assets/05bd0962-5bd6-4875-bbb3-f519ab4bdc93
https://github.com/user-attachments/assets/701a0ec5-3449-4800-9e47-3531546b2a52
=> fix(LEMS-2083): fix color contrast issues

.changeset/light-islands-lick.md, packages/perseus-editor/src/components/__tests__/start-coords-settings.test.tsx, packages/perseus-editor/src/components/start-coords-circle.tsx
The Radius input in the Circle graph start coords UI is not allowing
people to type in non-numbers, even mid-typing a valid number.
For example, when typing "0" to start "0.5", it auto-updates to 2 (default radius),
and it doesn't allow typing "." to start ".5".
This is happening because the radius is only reading the prop updates and passing
the evaluated value instead of storing the state for the input.
Adding a `React.useState` in the `start-coords-circle.tsx` file to fix this.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2073
`yarn jest packages/perseus-editor/src/components/__tests__/start-coords-settings.test.tsx`
Storybook
- Before: https://khan.github.io/perseus/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-circle
- After: …
=> [Start Coords] Fix the radius input in circle graph start coords UI

.changeset/nine-ducks-enjoy.md, packages/math-input/package.json, packages/perseus-editor/package.json, packages/perseus/package.json
Recently we changed some of our packages to use the modern syntax for declaring packge exports: namely the `exports` key. When a package defines this key, it no longer allows arbitrary relative exports (ie. `import X from '@khanacademy/perseus/dist/some-file.js';`). 
This: 
Becomes: 
As a result, our bundled CSS was no longer exported. In webapp today, we need to import the bundled CSS using a fully-relative path (ie. `import '../../node_modules/@khanacademy/perseus/dist/index.css''`). This is clunky and the import paths are not portable. 
So, this PR fixes it by exporting all CSS files from our bundles.
Issue: "none"
Update webapp with the snapshot npm package and then check if we can change our CSS imports to `import '@khanacademy/perseus/index.css';`
=> Export compiled CSS in package.json

.changeset/shy-toes-hug.md, packages/perseus-linter/src/__tests__/rules.test.ts, packages/perseus-linter/src/rules/all-rules.ts, packages/perseus-linter/src/rules/static-widget-in-question-stem.ts
We have logic in the Perseus renderer that prevents widgets from being static
in question stems. This logic was put in place to prevent content creators from
accidentally creating exercises that couldn't be answered (because all their
widgets were static). However the implementation is pretty hacky (it checks
problemNum to know if the renderer is in a question stem), and doesn't work in
the exercise editor preview, or in Perseus storybook. The resulting behavior is
very surprising: `static` widgets in question stems are non-interactive in the
exercise editor but are interactive in the learner experience.
Because this is so confusing, we want to remove the special-case logic and let
`static` always do what it says on the tin. But we still want to ensure that
unanswerable exercises aren't …
=> Lint against static widgets in question stems

.changeset/gentle-dragons-hide.md, packages/perseus-editor/src/__stories__/editor-page-with-storybook-preview.tsx, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/hint-renderer.tsx, packages/perseus/src/mixins/widget-prop-denylist.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/__stories__/expression.stories.tsx, packages/perseus/src/widgets/__stories__/interactive-graph.stories.tsx, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/__tests__/passage.test.tsx, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
Some of our widgets (e.g. Radio) have a "static" mode which can be toggled on
in the exercise editor. When a widget is in static mode, the "answer" to the
widget is displayed, the widget is not graded, and the learner cannot alter
the widget's state.
Content creators need to be able to set interactive graphs to static mode so
that graphs can be added to hints, to demonstrate the solution steps for an
exercise. Previously, we implemented a special "hint mode" for interactive
graphs to accommodate this use case. Hint mode was based on a couple faulty
assumptions:
- We did not clearly understand what static mode was or when it was turned on.
We confused static mode with the "read only" state of a widget, which occurs
when a learner has successfully answered the question. Similar to static …
=> Add "static" toggle to Interactive Graph widget

.changeset/lovely-crabs-talk.md, packages/perseus-editor/src/components/__tests__/start-coords-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/start-coords-angle.tsx, packages/perseus-editor/src/components/util.ts
Implement the body of the start coords UI for angle graphs (replace the "WIP" placeholder).
The implementation for `getAngleEquation()` util function is taken from [interactive-graph.tsx](https://github.com/Khan/perseus/blob/f083200340545f41275f0696dbfc967f45028b0c/packages/perseus/src/widgets/interactive-graph.tsx#L2354)
and rewritten to work here without having to import the InteractiveGraphWidget component from
perseus. Using this custom implementation, we can pass in just the coordinates to get our equation
instead of having to pass in all the graph props in the original function, which leads to a whole 
slew of TypeScript errors.
There's also the consideration of adding an "angle" field to allow content authors to edit the angle
directly, but this adds a lot of complexity. If this …
=> [Start Coords] Implement start coords UI for angle graphs

.changeset/stupid-steaks-flow.md, packages/perseus-editor/src/components/widget-editor.tsx
We discussed this [in slack][1], and Charlie thought it was a good idea.
[1]: https://khanacademy.slack.com/archives/C067UM1QAR4/p1723576041577949?thread_ts=1723487579.845949&cid=C067UM1QAR4
Issue: none
Run `yarn storybook`
View: http://localhost:6006/?path=/docs/perseuseditor-widgets-interactive-graph--docs
Verify that you can toggle the "Static" switch. The graph in the preview should
be interactive when the switch is turned off, and should be non-interactive
(and display the answer) when the switch is on.
=> Replace the 'Set as static' button with a switch

.storybook/preview-head.html
While working in Storybook and looking at the dev tools, I noticed that the `Lato-Regular.woff2` font wasn't loading. I believe the path is wrong so I've fixed it. And now it loads according to the browser dev tools.
Issue: "none"
Run storybook: `yarn start`
Open dev tools and filter the network requests by `lato-regular`.
The font file should be loaded.
=> [🔥AUDIT🔥] Fonts: fix path to Lato-Regular.woff2 in Storybook

.changeset/tough-bananas-arrive.md, packages/perseus/src/interactive2/__tests__/movable-mock.ts, packages/perseus/src/interactive2/arrowhead.ts, packages/perseus/src/interactive2/get-clip-point.ts, packages/perseus/src/interactive2/movable-point.tsx, packages/perseus/src/util/test-utils.testdata.ts, packages/perseus/src/widgets/__stories__/interactive-graph-regression.stories.tsx, packages/perseus/src/widgets/__stories__/interactive-graph.stories.tsx, packages/perseus/src/widgets/__stories__/random-widgets.stories.tsx, packages/perseus/src/widgets/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/reducer/initialize-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/types.ts, packages/perseus/src/widgets/measurer.tsx
I noticed we had quite a few places in the Perseus package that imported things using the `@khanacademy/perseus` package name. This seems odd and is a bit misleading when reading the code ("why do we import usign the public package name here?").
Issue: "none"
=> [🔥AUDIT🔥] Import internally using relative paths instead of package name

packages/kas/src/__tests__/evaluating.test.ts
While working on [this PR](https://github.com/Khan/perseus/pull/1507), I noticed tests were passing when they shouldn't have been.
That PR might be a dead end, so I wanted to submit a fix in a separate PR.
=> Fix broken KAS expect

.changeset/nasty-cobras-try.md, .changeset/quiet-glasses-join.md, .changeset/wise-cougars-hunt.md, dev/vite.config.ts, packages/perseus-editor/package.json, packages/perseus-editor/src/__stories__/content-preview.stories.tsx, packages/perseus-editor/src/content-preview.tsx, packages/perseus-editor/src/index.ts, packages/perseus/src/__testdata__/article-renderer.testdata.ts, packages/perseus/src/__tests__/server-item-renderer.test.tsx, packages/perseus/src/components/lint.tsx
This PR introduces a new editor component: `ContentPreview`. It is a thin wrapper around `ServerItemRenderer` which provides an easy way for editors to preview a given Perseus Item. 
It should be noted that due to current Perseus styling, the preview will _not_ match production 100%. This is because Perseus styles are adjusted based `@media` queries on device width.
View the prevew in Storybook. `yarn start` ==> http://localhost:6006/?path=/docs/perseuseditor-content-preview--docs
=> Perseus Editor: Add ContentPreview component

.changeset/unlucky-carrots-sparkle.md, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Currently, graphs can be selected and copied when the user drag-selects them.
We don't want this to be the case. It causes a bunch of graph information to
be awkwardly copied, such as the background image or all the axis tick labels.
Here, I'm adding `user-select: none` to the Mafs graph to stop this behavior.
NOTE: This works perfectly in Safari and Firefox, but there is a known bug
in Chrome that makes it so that the drag-selected element (which does
successfully look non-selected) still gets copied to the clipboard.
As this is a browser-specific issue, I did not try to fix it here. I think
there might be a super roundabout way to to this, like blocking mouse events
on specific parts of the graph, but I'm not sure that's worth it for a
behavior like this that's out of our control. …
=> [Interactive Graph] Stop the Mafs graphs from being user selectable

.changeset/fifty-owls-grin.md, packages/perseus-editor/src/components/__tests__/locked-polygon-settings.test.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-polygon-settings.tsx
Right now, if someone wants to move an entire locked polygon, they’d have to
manually change every single point’s coordinate pair.
I added some arrow buttons to accomplish this.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2115
`yarn jest packages/perseus-editor/src/components/__tests__/locked-polygon-settings.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-figures-current
- Open the locked polygon settings
- Play around with the buttons and confirm that the polygon moves accordingly
NOTE: The arrows might look like they're too far to the right, but it doesn't look like this
in prod where the width of the settings is shortened to 306px by webapp styles.
https://github.com/user-attachments/assets/87b6a085-24a2-4085-9 …
=> [Interactive Graph Locked Figures] Add controls to move a whole locked polygon

.changeset/chilled-moose-design.md, packages/perseus/src/widgets/__tests__/phet-sim.test.ts, packages/perseus/src/widgets/phet-sim.tsx
Update PhET widget design:
* Draws an outline around the entire widget, connecting the iframe and fullscreen button into a cohesive unit 
* Displays simulation load error message as a banner
* Displays empty iframe if the simulation did not load
* Disables fullscreen button if the simulation did not load 
* Adds space between the banner and iframe
* Removes iframe outline
* Makes iframe larger and closer to 16:9 ratio instead of square
Issue: [LEMS-2279](https://khanacademy.atlassian.net/browse/LEMS-2279)
- Verify that the widget shows up appropriately in Storybook
- Set URL to a valid PhET simulation (like https://phet.colorado.edu/sims/html/projectile-data-lab/latest/projectile-data-lab_all.html) and verify that the simulation appears correctly
- Change URL to a non-PhET origin and …
=> Design updates

.changeset/stupid-parrots-chew.md, packages/perseus/src/article-renderer.tsx, packages/perseus/src/hint-renderer.tsx, packages/perseus/src/index.ts, packages/perseus/src/server-item-renderer.tsx, packages/perseus/src/types.ts
I don't know how useful this is, but this is my motivation: https://github.com/Khan/webapp/pull/24684
Nothing should change but types
=> Make a SharedRendererProps type

.changeset/orange-rules-knock.md, packages/math-input/src/components/input/math-wrapper.ts, packages/math-input/src/components/input/mathquill-helpers.ts, packages/math-input/src/components/key-handlers/key-translator.ts, packages/math-input/src/components/keypad/__tests__/keypad-v2-mathquill.test.tsx, packages/math-input/src/components/keypad/keypad-mathquill.stories.tsx, packages/math-input/src/components/keypad/keypad-pages/geometry-page.tsx, packages/perseus/src/components/math-input.tsx, packages/perseus/src/strings.ts, packages/perseus/src/widgets/__tests__/expression.test.tsx
So basically:
- These two PRs ([1](https://github.com/Khan/perseus/pull/921) and [2](https://github.com/Khan/webapp/pull/19111)) helped add support for Portuguese trig functions when typed in the input.
- This [PR](https://github.com/Khan/perseus/pull/1497) added support for the text of trig buttons to be translated, however the input would still update with "sin" if the "sen" button was pressed.
- The PR being reviewed updates the input correctly; so if the "sen" button is pressed, the input is updated with "sen"
How this works:
- When a button is pressed, the keypad yells into the void that "SIN" was pressed
- The keypad translator has a callback for updating the input when "SIN" is pressed
- BEFORE: it would just updated the input with `sin()`
- NOW: it looks for the translated version …
=> Update Mathquill Mathfield with Portuguese trig functions

packages/perseus-editor/src/__stories__/editor-page-with-storybook-preview.tsx
Something caused the storybook preview to collapse horizontally.
Adding a fixed width here so that the graph can be viewed.
Issue: none
Storybook
- http://localhost:6006/?path=/docs/perseuseditor-widgets-interactive-graph--docs
| --- | --- |
| ![Screenshot 2024-08-22 at 11 58 29 AM](https://github.com/user-attachments/assets/d483be2d-bced-4a7a-be86-6ea95bc0d32a) | <img width="571" alt="Screenshot 2024-08-22 at 12 01 42 PM" src="https://github.com/user-attachments/assets/8d77a2e3-b6a7-40d0-b43a-010d769d95f1"> |
=> [Interactive Graph Storybook] Give Storybook preview a fixed width

.changeset/green-otters-lick.md, packages/perseus-editor/src/components/graph-locked-figures/locked-figures-section.tsx
Somehow I messed up a merge and it added back the line that
stops the locked label settings from showing up.
Removing that check so that the locked label settings show up again.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1795
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-labels-flag
| --- | --- |
| <img width="383" alt="Screenshot 2024-08-23 at 2 06 13 PM" src="https://github.com/user-attachments/assets/6e62e23d-a711-489d-9c82-1cf4bbfbe734"> | <img width="379" alt="Screenshot 2024-08-23 at 2 06 21 PM" src="https://github.com/user-attachments/assets/9530faac-4e6c-456d-a3bb-390a67c4dcbf"> |
=> [Locked labels] Bugfix from merge conflict: Add back locked label settings

.changeset/lemon-mugs-teach.md, packages/perseus-editor/src/article-editor.tsx
This PR migrates the `ArticleEditor` from string refs to proper React refs. This improves type safety.
`yarn tsc`
`yarn test`
=> ArticleEditor: migrate to React refs

.changeset/rude-meals-cough.md, packages/perseus-editor/src/editor-page.tsx, packages/perseus-editor/src/editor.tsx, packages/perseus-editor/src/hint-editor.tsx, packages/perseus-editor/src/item-editor.tsx
This PR improves typing of the `serialize()` methods on the various editors. This function is used to return the edited data to higher-up components (and ultimately out of Perseus itself). 
Better typing helps us to ensure that we're returning the right data in the right format/structure.
`yarn tsc`
`yarn test`
=> Editors: better type serialize() functions

.changeset/four-ladybugs-act.md, packages/perseus-editor/src/editor-page.tsx, packages/perseus-editor/src/hint-editor.tsx, packages/perseus-editor/src/iframe-content-renderer.tsx, packages/perseus-editor/src/item-editor.tsx
This PR improves typing on the editor's `sendNewData` method. This method is used to push edits to the preview iframe. Prior to this PR the data being sent was not clearly typed and hard to understand. 
`yarn tsc`
`yarn test`
=> IframeContentRenderer: strongly type sendNewData()

.changeset/violet-squids-sit.md, packages/perseus-editor/src/iframe-content-renderer.tsx
The IframeContentRenderer used to assign itself an `iframeID` in `componentDidMount`. There's no reason it can't assign that to itself when the component is contructed. I've moved the id generation to be in the member declaration, which means the type can be implicitly, but strongly, defined there. 
`yarn tsc`
`yarn test`
=> IframeContentRenderer: simplify iframeID assignment so typing can improve

.changeset/lemon-grapes-invent.md, packages/perseus-editor/src/__tests__/__snapshots__/iframe-content-renderer.test.tsx.snap, packages/perseus-editor/src/__tests__/iframe-content-renderer.test.tsx, packages/perseus-editor/src/iframe-content-renderer.tsx
The iframe preview used to pass parameters to the iframe content page by setting attributes on the `<iframe>` element. This is not allowed when the hosted page has a different url host than the parent page (which is what we're aiming to do by loading the preview page(s) from `kasandbox.org`). 
As a result, I've changed the preview to use search params on the URL instead. This is easily accessible in the preview page.
`yarn tsc`
`yarn test`
=> IframeContentRenderer: pass iframe preview params by search params on url

.changeset/yellow-zoos-trade.md, packages/perseus/src/widgets/interactive-graphs/types.ts
The doc comment for `allowReflexAngles` was wrong. This PR fixes it.
Issue: none
`yarn test`
=> Fix incorrect comment

.github/workflows/node-ci.yml
I noticed this last step in our CI runs takes a bit of time for what amounts to downloading 2 files and then uploading them to Codecov. 
This action uses only other Github shared actions and so it doesn't need to checkout the source or install node_modules. This should speed up this last step in our CI runs somewhat. 
Issue: "none"
I'll need to land this and then watch the next PR that runs this action.
=> The final 'Upload Coverage' step doesn't need local source or node_modules

.changeset/chilled-brooms-begin.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
We want this behavior so you can click to select a point on a point graph with
unlimited points, and then press backspace to delete it.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2204
View:
http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-point
Clicking on a point should focus it (the focus ring should appear and you
should be able to move the point with the keyboard)
=> Focus movable points when you click on them

.changeset/big-plums-confess.md, packages/perseus-editor/src/hint-editor.tsx
This PR migrates the HintEditor to use React refs instead of legacy string refs. This improves safety.
`yarn tsc`
`yarn test`
=> HintEditor: migrate to React refs

.changeset/afraid-colts-sneeze.md, packages/perseus/src/widgets/phet-simulation.tsx
Remove `simpleValidate()` from the PhET widget because it is a non-answerable widget.
* Because widgets without a `simpleValidate()` are handled correctly by our grading infrastructure (they are simply not graded), as per Jeremy's suggestion, we will remove the function from PhET!
* Also resolves `TypeError: JE.validate is not a function` error on PhET simulation content
Issue: LEMS-2287
* `yarn jest packages/perseus/src/widgets/__tests__/phet-simulation.test.ts`
* `yarn jest packages/perseus-editor/src/widgets/__tests__/phet-simulation-editor.test.tsx`
* Verify that the widget and editor still show up in Storybook
* Verify that the widget shows up and remains ungraded on [Test Everything](https://www.khanacademy.org/internal-courses/test-everything/test-everything-1/x6df8cbb5b9ebc9c6:phet …
=> PhET widget: remove simpleValidate

.github/actions/shared-node-cache/action.yml, .github/workflows/maintenance.yml, .github/workflows/node-ci-main.yml, .github/workflows/node-ci.yml, .github/workflows/release.yml, .github/workflows/storybook.yml
We've been seeing intermittent CI test failures in that appear to be caused by incorrect
NPM packages being installed. Clearing the node_modules cache used by our GitHub actions
resolves the issue... temporarily.
In the case of a cache miss, we restore node_modules from the "wrong" cache and
`yarn install` on top of that. Usually, this installs the correct versions of any
packages that need updating, and everything works. But we think that sometimes, it might
not.
The setup-node action from GitHub implements node_modules caching, and doesn't restore
from fallback caches. This PR switches our CI jobs to use `setup-node`, which we hope
will resolve the caching issues.
Look. See CI. See CI run. Run, CI, run.
=> Use setup-node to install and cache node_modules

.changeset/thirty-pans-hammer.md, packages/perseus-editor/src/widgets/phet-simulation-editor.tsx, packages/perseus/src/index.ts, packages/perseus/src/widgets/phet-simulation/index.ts, packages/perseus/src/widgets/phet-simulation/phet-simulation.tsx
* Add `getSaveWarnings()` function to PhET widget editor so that a widget cannot be saved with a non-PhET URL
* Unhide the widget from the content editor
Issue: LEMS-2292
* `yarn jest packages/perseus/src/widgets/__tests__/phet-simulation.test.ts`
* `yarn jest packages/perseus-editor/src/widgets/__tests__/phet-simulation-editor.test.tsx`
* Verify that the widget and editor still show up in Storybook
* Verify that the editor displays an error when a non-PhET URL is typed into the PhET widget content editor
=> Add save warnings to PhET widget editor and unhide widget

.changeset/nervous-singers-reply.md, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/util.ts, packages/perseus/src/widgets/interactive-graph.tsx
`Util.DeprecationMixin` was only being used to remove a deprecated `showGraph`
prop from the InteractiveGraph widget and its editor component. `showGraph` no
longer appears anywhere in our content, so the "mixin" (which, given the
naming, is likely a relic from the `React.createClass` era) is not needed
anymore.
Issue: none
Edit and save an interactive graph in the editor.
=> Remove Util.DeprecationMixin

.changeset/neat-avocados-change.md, packages/perseus/src/widgets/phet-simulation/phet-simulation.tsx
* Make PhET widget iframe maintain a 16:9 ratio while responsively matching the width of its container
Issue: LEMS-2322
* `yarn jest packages/perseus/src/widgets/phet-simulation/phet-simulation.test.ts`
* Verify in Storybook that the widget maintains a 16:9 aspect ratio in Storybook and expands to fill available width
=> PhET widget: responsive iframe sizing

.changeset/pretty-garlics-give.md, packages/perseus-editor/src/widgets/interaction-editor/arrow-picker.tsx, packages/perseus-editor/src/widgets/interaction-editor/color-picker.tsx, packages/perseus-editor/src/widgets/interaction-editor/dash-picker.tsx, packages/perseus-editor/src/widgets/interaction-editor/element-container.tsx, packages/perseus-editor/src/widgets/interaction-editor/function-editor.tsx, packages/perseus-editor/src/widgets/interaction-editor/interaction-editor.tsx, packages/perseus-editor/src/widgets/interaction-editor/label-editor.tsx, packages/perseus-editor/src/widgets/interaction-editor/line-editor.tsx, packages/perseus-editor/src/widgets/interaction-editor/parametric-editor.tsx, packages/perseus-editor/src/widgets/interaction-editor/point-editor.tsx, packages/perseus-editor/src/widgets/interaction-editor/rectangle-editor.tsx, packages/perseus/src/index.ts
There were 4 components declared in `perseus` but only used in `perseus-editor` so I moved them.
Issue: LEMS-2321
Nothing should change, implementation nit
=> Move some editor-only components into `perseus-editor`

packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx
I noticed a test that was jumping through hoops with spies in order to manage a ref in tests. Using `React.createRef()` is simpler and avoids needing to mock a hook. 
Issue: "none"
`yarn test` ✅
=> Switch from using useRef() to createRef()

.changeset/rude-mangos-boil.md, packages/perseus-editor/src/widgets/interactive-graph-editor/interactive-graph-editor.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
Previously, `correct` was typed as `any` to suppress an error. TypeScript
complained that the InteractiveGraph component might pass the wrong subtype of
`PerseusGraphType` to its `onChange` callback, causing us to create a
nonsensical chimera graph when we do stuff like `correct = {...correct,
...newGraph};`
This PR adds runtime checks (mostly using `tiny-invariant`) to ensure that
graphs have the type we expect.
In doing this refactoring, I discovered a second problem: the
InteractiveGraphEditor sometimes sets the `coords` of the graph to `null`,
which wasn't allowed by `PerseusGraphType` - only `undefined` was allowed.
This PR fixes that by updating `PerseusGraphType` to allow null coords. The
interactive graph code can (thankfully) already handle null values just fine.
Issue: none
Edit …
=> Type the `correct` prop passed to InteractiveGraphEditor

.changeset/ninety-laws-decide.md, packages/perseus-editor/src/components/__tests__/interactive-graph-description.test.tsx, packages/perseus-editor/src/components/interactive-graph-description.tsx
Right now, we are using a native HTML <textarea> element inside the
graph description settings, since there were some issues importing
TextArea from wonder blocks.
It seems those issues have been resolved (or were local the whole
time and therefore nonexistent), so now we can update the element
we're using for the description input.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2332
`yarn jest packages/perseus-editor/src/components/__tests__/interactive-graph-description.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-with-aria-label
- Confirm that the screenreader reads out the label and description as
expected in Safari and Firefox.
=> [Interactive Graph Editor] Use Wonder Blocks TextArea in the graph description settings UI

.changeset/tame-ways-reply.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/components/__stories__/locked-figures-section.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-figures-section.test.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-figure-select.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-figure-settings.tsx, packages/perseus-editor/src/components/graph-locked-figures/locked-figures-section.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/interactive-graph-editor.tsx, packages/perseus/src/types.ts
Now that locked functions have been safely out for a while now, we can
remove the `interactive-graph-locked-features-m2b` flag from Perseus.
Next, we can remove it from webapp Growthbook.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2107
`yarn jest`
- In the Perseus repo in your IDE, search for all instances of `m2b` and confirm there are none left.
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-figures-current
- Confirm that the locked functions are still available in the graph and editor
=> [Interactive Graph] Remove the interactive-graph-locked-feature-m2b flag

.changeset/tiny-rules-sleep.md, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
We were throwing an error with the message `"FIXME implement circle reducer"`
when `doMovePointInFigure` was called with a circle graph. The error message
didn't make sense because there's no need to implement `doMovePointInFigure`
for circles. The `throw` statement was redundant because without it, the circle
case just falls through to the `throw` below.
Issue: none
`yarn test`
=> Delete redundant throw statement

.changeset/wicked-spiders-call.md, packages/perseus/src/util/graphie.ts
The work done in LEMS-2022 addressed the scaling problems with graphie labels in one specific use-case. There are actually two use-cases for Graphie. The second use-case didn't include elements that the original solution relied upon. This bugfix accounts for the second use case, and adds in safeguards for any potential other use-case so that a default of 100% scale is used instead of a possible NaN.
Issue: LEMS-2373
1. Launch Storybook
2. Review the following examples (labels should be in their proper location):
* Grapher widget (specifically the [Linear Question](http://localhost:6006/?path=/story/perseus-widgets-grapher--linear-question), which doesn't use a background)
* [Number Line](http://localhost:6006/?path=/story/perseus-widgets-number-line--question-1) widget
* Plotter widget …
=> BUGFIX - Some Graphie Labels Were Misaligned

.changeset/thick-eels-wait.md, packages/perseus/src/widgets/phet-simulation/phet-simulation.test.ts
Add new tests to ensure maximal code coverage of the PhET widget. This is based on the new code from the [a11y update, PR #1619](https://github.com/Khan/perseus/pull/1619) and should be merged in after the a11y update is merged in.
* Check that fullscreen button renders when the simulation loads successfully
* Check that fullscreen button does not render when the simulation fails to load
* Check that the locale warning banner renders when the `kaLocale` is not available for the requested PhET simulation
Issue: LEMS-2277
* `yarn jest packages/perseus/src/widgets/phet-simulation/phet-simulation.test.ts`
=> Add PhET widget code coverage

.changeset/red-roses-brush.md, packages/perseus/package.json, packages/perseus/src/components/number-input.tsx, packages/perseus/src/util.ts, packages/perseus/src/widgets/radio/base-radio.tsx, yarn.lock
We didn't have types for the `classnames` package. That led us to try to define the types for it's return value in-place. That led us to suppress Typescript errors incorrectly. 
I added the version of the types used by webapp for the same version of `classnames` package we're using and voila, fixes.
Issue: "none"
`yarn tsc`
`yarn test`
=> Fix types for 'classnames' package

.changeset/perfect-taxis-do.md, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
While deploying Perseus, it was discovered that there was a regression related to the bounding of the interactive elements and the protractor in the Interactive Graph widget. 
Upon investigation, it seems like the nested svg (which is containing the overlow) was accidentally removed. This PR adds the nested svg back.
Issue: LEMS-2392
- Manual Testing
=> Adding back a nested svg element to fix Interactive Graph regression

.changeset/few-moles-obey.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graphs/graph-locked-labels-layer.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts
- Add a feature flag for locked line labels
- Add `labels` to LockedLineType
- Update builder
- Updates stories and tests
Issue: https://khanacademy.atlassian.net/browse/LEMS-2347
- Go to the following story: http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-line-labels-flag
- Confirm there is a label "B" next to the locked line
- Go to the following story: http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-point-labels-flag
- Confirm there is no "B" next to the line (there should be an "A" for the point)
- Go to the following story: http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-labels-flag
- Confirm there is no A or B label next to the point or the line
=> [Locked Figure Labels] View locked line labels

.changeset/violet-scissors-punch.md, packages/perseus/src/widgets/definition/definition.tsx, packages/perseus/src/widgets/explanation/explanation.test.ts, packages/perseus/src/widgets/explanation/explanation.tsx, packages/perseus/src/widgets/image/image.tsx, packages/perseus/src/widgets/interaction/interaction.tsx, packages/perseus/src/widgets/measurer/measurer-validator.test.ts, packages/perseus/src/widgets/measurer/measurer-validator.ts, packages/perseus/src/widgets/measurer/measurer.tsx, packages/perseus/src/widgets/molecule/molecule.tsx, packages/perseus/src/widgets/passage-ref-target/passage-ref-target.tsx, packages/perseus/src/widgets/passage-ref/passage-ref.tsx, packages/perseus/src/widgets/passage/passage.tsx, packages/perseus/src/widgets/video/video.tsx
- Split out Measurer validation logic
- Go back to other non-interactive widgets and detach `staticValidate` from `validate`
Nothing should change, just some tweaks
=> Small tweaks to non-interactive validation logic

.changeset/smart-bottles-listen.md, packages/perseus/src/widgets/categorizer/categorizer-validator.test.ts, packages/perseus/src/widgets/categorizer/categorizer-validator.ts, packages/perseus/src/widgets/categorizer/categorizer.test.ts, packages/perseus/src/widgets/categorizer/categorizer.tsx, packages/perseus/src/widgets/categorizer/categorizer.types.ts
For the servier-side scoring project, we are moving validation logic out of each widget component. This moves the validation logic for the categorizer widget.
Issue: LEMS-2341
- All tests should pass
- Nothing should chang as code is just being moved into separate files
=> Split out validation logic for categorizer

.changeset/nine-dingos-appear.md, packages/perseus/src/types.ts
Static widgets can now appear in question stems. This behavior was
changed here:
https://github.com/Khan/perseus/pull/1503/files#diff-2630b3a01f66b4e66fb891ac29f5676d40759b290607f4f0e628701f37bf665dR658
The rationale for the change is explained in the [description of another PR](https://github.com/Khan/perseus/pull/1511)
Issue: none
Test plan:
CI should pass.
=> Delete outdated comment about static widgets being banned from questions

.changeset/eleven-elephants-trade.md, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-state-to-interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graphs/mafs-state-to-interactive-graph.ts, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
Previously, we were passing the entire Mafs graph state to onChange.  Since
the onChange callback data is used by the Interactive Graph widget editor to
set the correct answer for the graph, a bunch of extra data like
`"hasBeenInteractedWith": true` was getting saved in the `correct` field of
the Widget data.
This extra data is not used, so its presence in datastore is potentially
confusing to future maintainers trying to understand the data. It might
also cause bugs in the future - e.g. if some code merges it into another
object in which those properties _are_ meaningful.
This PR ensures that we only save relevant data in the `correct` field of
interactive graph widgets.
Issue: none
Edit, save and publish an interactive graph widget in an exercise. As a
learner, you should be able to …
=> Omit extra properties from InteractiveGraph onChange arg

.changeset/strange-houses-breathe.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graphs/graph-locked-labels-layer.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts
- Add feature flag for locked vector labels
- Add `labels` to LockedVectorType
- Update builder
- Update stories and tests
Issue: https://khanacademy.atlassian.net/browse/LEMS-2348
- Go to http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-vector-labels-flag
- Confirm that the visible label is on the locked vector _only_
- Go to the point and line stories and confirm that the locked
vector does not have a visible label (make sure the flags are
separating the behaviors correctly)
=> [Locked Figure Labels] View locked vector labels

.changeset/tough-snails-double.md, packages/perseus-editor/src/iframe-content-renderer.tsx, packages/perseus/src/__tests__/renderer-api.test.tsx, packages/perseus/src/perseus-api.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/expression/expression-validator.test.ts, packages/perseus/src/widgets/expression/expression-validator.ts, packages/perseus/src/widgets/expression/expression.tsx, packages/perseus/src/widgets/expression/expression.types.ts, packages/perseus/src/widgets/input-number/input-number-validator.ts, packages/perseus/src/widgets/input-number/input-number.tsx
I didn't see that it was actually being used except in the protowebapp repo...which is obviously legacy.
Issue: LEMS-2422
Nothing should functionally change
=> Remove onInputError

.changeset/breezy-rockets-greet.md, packages/perseus/src/widgets/interactive-graphs/protractor.tsx
We're updating the protractor's default position from 5% above the bottom of the graph to 25%. This is necessary because with the new angle Mafs implementation, the angle graph cannot reach the bottom of the graph, due to saving room for multiple angle options. To improve this we can simply position the graph slightly higher to make it accessible for keyboard users, while still preserving the need for students to properly position the graph and protractor.
Before: (default position of protractor.)
After:
Issue: LEMS-2372
1. Go to http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph-editor--with-mafs
2. Select `Answer type: Angle` and check `Show protractor`
3. See that the protractor is higher (25% from the bottom of the graph) and you can use your keyboard to …
=> Updating protractor to default position.

.changeset/many-apricots-repair.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
- Reserves space for "Remove point" button
- Translations for strings
Issue: https://khanacademy.atlassian.net/browse/LEMS-1670
- Run tests
- All is well
=> Translations and polish for unlimited points

.changeset/violet-icons-breathe.md, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-description.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-description.tsx
For consistency's sake, I'm updating the fullGraphAriaLabel and
fullGraphAriaDescription to save as `undefined` instead of
`""` when they're cleared. This will be consistent with their
values when they haven't been edited yet.
Issue: none
Test plan:
`yarn jest packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-description.test.tsx`
- Go to http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-figure-labels-all-flags
- Confirm that the title and description can still be
updated and cleared without any errors.
=> [Interactive Graph Editor] Save empty full graph aria label/description as undefined

.changeset/yellow-poets-poke.md, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/interactive-graphs/graph-locked-labels-layer.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
Since the `labels` field was added to the interactive graph
locked figures after they were released and used by content
authors, there are already exercises saved with locked figures
that don't have a `labels` field.
If we make this a required field, this can lead to issues with
the existing exercises in the future. To increase type safety,
I'm making `labels` optional. We should also do this with
new types added in the future. (Labels haven't been released
for use yet, so we can still fix this now without issue.)
Issue: none
`yarn jest`
=> [Locked Figures Labels] Make labels optional to increase type safety

.changeset/great-lions-switch.md, packages/perseus/src/widgets/definition/definition.test.ts, packages/perseus/src/widgets/interactive-graph.test.tsx
We made a custom matcher to make score tests easier to grok. This ports some existing tests over to that.
=> Port tests to custom matcher

.changeset/honest-games-do.md, packages/perseus/src/widgets/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graph.tsx
This parameter appeared to be used to score point graphs. It was passed to
`getPointCoords()`. However, on closer inspection, there was no way this code
could have worked: `getPointCoords` takes the interactive graph props as an
argument, but we were passing it the entire component. This props param was
only being used if the rubric contained no coords. Maybe that's a realistic
case, or maybe it's not, but either way, it was throwing an error trying to
access `props.range[0]`.
Long story short, we lose nothing by deleting the `component` param and
explicitly throwing an error if the rubric has no coords.
Issue: LEMS-2448
Run this script to copy point graph data to your clipboard:
```
grep -rl '"type":"point"' data/questions/ | xargs cat | pbcopy
```
Paste it into …
=> Delete unused component param of InteractiveGraph.validate()

.changeset/eleven-elephants-trade.md, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-state-to-interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graphs/mafs-state-to-interactive-graph.ts, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
This change was previously implemented in PR #1654, then reverted in #1663 due
to a bug. This PR reimplements the change without the bug. The original PR
summary follows.
---
Previously, we were passing the entire Mafs graph state to onChange. Since
the onChange callback data is used by the Interactive Graph widget editor to
set the correct answer for the graph, a bunch of extra data like
"hasBeenInteractedWith": true was getting saved in the correct field of
the Widget data.
This extra data is not used, so its presence in datastore is potentially
confusing to future maintainers trying to understand the data. It might
also cause bugs in the future - e.g. if some code merges it into another
object in which those properties are meaningful.
This PR ensures that we only save relevant data in …
=> Reimplement mafsStateToInteractiveGraph

.changeset/hot-geese-look.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/__stories__/interactive-graph-editor.stories.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.tsx, packages/perseus/src/widgets/interactive-graphs/graph-locked-layer.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts, packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-label.tsx, packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-point.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
- Add `locked-figures-aria` flag
- Add `ariaLabel` field to LockedPointType
- Add the aria label behavior to the LockedPoint on the mafs graph
- Minor updates to the screen reader behvaior
Issue: https://khanacademy.atlassian.net/browse/LEMS-2375
`yarn jest packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx`
Storybook
- Go to http://localhost:6006/iframe.html?args=&id=perseuseditor-widgets-interactive-graph--mafs-with-locked-figure-labels-all-flags&viewMode=story
- Use a screen reader to navigate through the preview graph
- Using tab should _only_ navigate to the interactive elements, NOT the locked point
- Using the screenreader controls (VO + arrow keys) should be able to navigate to
the locked point. It should read out as "Point A". …
=> [Locked Figure Aria] Implement locked point aria label behavior on graph

.changeset/hot-carrots-eat.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/expression/expression-validator.ts
We're trying to make the Rubric type only include the things it needs for scoring. This is Expression.
Issue: LEMS-2462
Nothing should change, just a type tweak.
Author: handeyeco
Reviewers: Myranae
Required Reviewers:
Approved By: Myranae
Checks: ✅ Publish npm snapshot (ubuntu-latest, 20.x), ✅ Check builds for changes in size (ubuntu-latest, 20.x), ✅ Lint, Typecheck, Format, and Test (ubuntu-latest, 20.x), ✅ Check for .changeset entries for all changed files (ubuntu-latest, 20.x), ✅ Cypress (ubuntu-latest, 20.x), ✅ gerald, 🚫 Publish npm snapshot (ubuntu-latest, 20.x), 🚫 Cypress (ubuntu-latest, 20.x), 🚫 Check for .changeset entries for all changed files (ubuntu-latest, 20.x), 🚫 Lint, Typecheck, Format, and Test (ubuntu-latest, 20.x), 🚫 Check builds for changes in size (ubuntu-latest, …
=> Refine Expression Rubric type (#1698)

.changeset/nine-roses-enjoy.md, packages/perseus/src/widgets/iframe/iframe-validator.test.ts, packages/perseus/src/widgets/iframe/iframe-validator.ts, packages/perseus/src/widgets/iframe/iframe.tsx
For the server-side scoring project, we are moving validation logic out of each widget component. This moves the validation logic for the iframe widget and adds tests for the validator function.
Issue: LEMS-2480
- Confirm all tests pass
- Confirm iframe stories still work in a ZND
=> Split out validation logic for iframe

.changeset/tall-scissors-pay.md, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.test.ts, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.tsx
Decimal labels for the Axis Ticks in the Interactive Graph Widget are experiencing a bug in relation to the shouldShowLabel logic, where the -1 is being hidden when it should not be. Additionally, decimal tick steps would often result in overlapping labels. 
This PR updates the shouldShowLabel logic to always hide the negative tickStep on the y-axis if it is within the graph bounds. This should solve both of the issues above, and result in a cleaner graph experience. 
Issue: LEMS-2406
- yarn jest
- Updated test to test the edge case
=> [Bug Fix] Update shouldShowLabel logic to better handle decimal tickSteps 

packages/perseus/src/widgets/radio/__tests__/radio.test.ts, packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
We were worried about SSS and shuffling, but it seems Radio's `getUserInput` is smart about un-shuffling answers before scoring.
Issue: LEMS-2435
This PR is just tests
=> Add renderer level tests for shuffled scoring

.changeset/heavy-steaks-count.md, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.test.ts, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.tsx
A bug with the axis tick labels was discovered when using decimal-based tickSteps in an interactive graph. In order to help alleviate this floating point issue, I've added a new function that counts the number of significant figures after the decimal point in the tickStep, so that we can generate tickSteps with the same level of specificity.
**Note:**
While investigating this issue, I discovered we have several floating point issues when dealing with very small decimals that seem to actually be stemming from the Content Editor experience itself. I'll start a separate discussion on that, but I believe it to be low priority as I don't expect content creators to be working with numbers smaller than 3-4 sig figs after the decimal. If you try to enter small numbers into the grid/snap/tick …
=> [Bug fix] - Ensuring decimal axis tick labels display with the same level of granularity as the tick step. 

.changeset/lovely-ants-itch.md, packages/perseus-core/src/analytics.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Missing two addtional event details fired from interactive graph
Issue: LEMS-2324
N/A
=> Fix to event details fired from interactive graph.

.changeset/calm-eggs-speak.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/cs-program/cs-program.tsx
As part of the Server Side Scoring project, this refactors the CS-Program Rubric type to show it is not particularly needed and could most likely be removed. Adds a comment to come back to it with LEMS-2440.
Issue: LEMS-2464
- Confirm tests pass
- Confirm CS-Program widgets still work locally or via znd if locally doesn't work
=> Refine CS-Program Rubric type

.changeset/twelve-rockets-taste.md, packages/math-input/src/components/keypad/__tests__/keypad.test.tsx, packages/math-input/src/components/keypad/keypad.tsx, packages/math-input/src/components/keypad/mobile-keypad-internals.tsx, packages/math-input/src/components/keypad/shared-keys.tsx, packages/math-input/src/types.ts, packages/perseus-editor/src/widgets/__tests__/expression-editor.test.tsx, packages/perseus-editor/src/widgets/expression-editor.tsx, packages/perseus/src/components/__tests__/math-input.test.tsx, packages/perseus/src/components/math-input.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/expression/expression.stories.tsx, packages/perseus/src/widgets/expression/expression.test.tsx, packages/perseus/src/widgets/expression/expression.tsx
Adds scientific notation to basic keypad using toggle on expression editor
Issue: LEMS-2272
1. [Navigate to expression editor story](https://650db21c3f5d1b2f13c02952-evogyhpohm.chromatic.com/?path=/docs/perseuseditor-widgets-expression-editor--docs)
2. Toggle `scientific` in the editor to see the scientific notation added to the basic keypad.
When adding other keypads, if scientific notation is toggled, the scientific notation button will remain visible. This includes when scientific and pre-algebra are toggled simultaneously, causing there to be 2 scientific notation buttons displayed on the screen. 
If we decide to pursue this further - it would be key to identify the use cases when we would display and hide the button, despite the toggle being set to `true` …
=> feat(LEMS-2722): Add scientific option to basic keypad

.changeset/mighty-students-pay.md, packages/perseus/src/__tests__/widgets.test.ts, packages/perseus/src/types.ts, packages/perseus/src/util/extract-perseus-data.ts, packages/perseus/src/widgets.ts, packages/perseus/src/widgets/expression/expression.test.tsx, packages/perseus/src/widgets/expression/expression.tsx, packages/perseus/src/widgets/input-number/input-number.test.ts, packages/perseus/src/widgets/input-number/input-number.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.test.ts, packages/perseus/src/widgets/numeric-input/numeric-input.tsx
Rather than calling a static method on a React component, move `getOneCorrectAnswerFromRubric` to the `WidgetExport` object.
Issue: Prework for [LEMS-2387](https://khanacademy.atlassian.net/browse/LEMS-2387)
Just moving some code. There were already tests and they should keep passing.
[LEMS-2387]: https://khanacademy.atlassian.net/browse/LEMS-2387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move getOneCorrect... to WidgetExport

.changeset/twelve-chairs-listen.md, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.tsx
Moves the position of the visible label
New aria label structure will be:  
`Element Type` `Visible Label(s)` `Math Details` `Visual Traits`
Issue: LEMS-2525
1. Navigate to [storybook](https://650db21c3f5d1b2f13c02952-ebxxnqlnis.chromatic.com/?path=/docs/perseuseditor-editorpage--docs)
2. Select "Interactive Graph" from the `Add widget` dropdown 
3. Scroll down to the `Add locked figure` dropdown - select any from the dropdown 
4. Click 'auto generate' button to see basic auto generated aria label 
5. Click 'add visible label' button to expand section and add visible label
6. Regenerate aria label by clicking 'auto generate' button to see updated label text
https://github.com/user-attachments/assets/47fa43db-d065-41d4-b97c-8cb6bd3da9b1
=> feat(LEMS-2525): move position of visible label in aria label

.changeset/green-pants-hear.md, packages/perseus-editor/src/editor.tsx, packages/perseus-editor/src/hint-editor.tsx, packages/perseus/src/index.ts, packages/perseus/src/multi-items/item-types.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/orderer/orderer.tsx
After releasing the PR to migrate the `Widget` type to an interface, I noticed that we have several different ways of typing the `widgets` key in our main Perseus render type (`PerseusRenderer`) and throughout the codebase. 
Today, we have the really useful `PerseusWidgetsMap` type which maintains the correct widget options type for each widget. So this PR removes the less-specific `WidgetDict` type and other bespoke typings (such as `{[key: string]: Widget}`) in favour of the `PerseusWidgetsMap`.
Issue: "none"
`yarn tsc`
=> Remove inaccurate WidgetDict type and bespoke typings for `widgets` key

.changeset/violet-bulldogs-shout.md, packages/perseus/src/util/graphie.ts, packages/perseus/src/widgets/number-line/__snapshots__/number-line.test.ts.snap, packages/perseus/src/widgets/number-line/number-line.test.ts, packages/perseus/src/widgets/number-line/number-line.testdata.ts, packages/perseus/src/widgets/number-line/number-line.tsx
A regression was introduced during the last bugfix ([PR 1695](https://github.com/Khan/perseus/pull/1695)) that caused the tick labels to not show for endpoints when the "Show label ticks" options is deselected. This PR fixes that regression by refactoring how the ticks and their labels are generated.
Issue: LEMS-2532
1. Launch Storybook
1. Review the [Editor Demo](http://localhost:6006/?path=/story/perseuseditor-editorpage--demo) page
1. Add a Number line widget
* A number line should show with the default 0 - 10 scale
* Tick marks and labels are provided in steps of 2 (i.e. 0, 2, 4...)
1. Toggle the "Show label ticks" checkbox off
* All the labels should now be removed except for the endpoints of zero (0) and ten (10)
1. Enter label values that are different than the endpoints
* For …
=> BUGFIX: [Number Line] - Tick labels not showing in some exercises

.changeset/long-baboons-hide.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/input-number/input-number-validator.test.ts, packages/perseus/src/widgets/input-number/input-number-validator.ts
As part of the Server Side Scoring project, this refactors InputNumber's Rubric type to contain only what is needed for scoring. Also adds the UserInput type to the validator as it was defined already but not referenced.
Issue: LEMS-2467
- Confirm all tests pass
- Confirm InputNumber still works as expected via Storybook
=> Refine InputNumber's Rubric type

.changeset/red-points-call.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/label-image/label-image-validator.ts, packages/perseus/src/widgets/label-image/label-image.tsx
As part of the Server Side Scoring project, this refactors Label Image's Rubric type based on current usage. It is not currently used in this widget. As we plan to review the use of rubric during LEMS-2440, the Rubric type was left in but changed to `Empty`. It was also added in one place where rubric was listed as a parameter (but was not in use).
Issue: LEMS-2468
- Confirm all tests pass
- Confirm the label image widget still works in Storybook
=> Refine Label Image Rubric type

.changeset/fifty-queens-teach.md, packages/kas/src/nodes.js
I had tried this previously but failed because I tried to convert all of the classes to ES6 classes at once.  This time around I converted them one at a time and made sure that all of the tests were passing after each class was converted.  In the next PR I will convert this file to TypeScript.
Issue: None
- yarn test packages/kas/src
=> Update KAS nodes.js to use ES6 classes

.changeset/sour-horses-scream.md, packages/perseus/src/widgets/number-line/__snapshots__/number-line.test.ts.snap, packages/perseus/src/widgets/number-line/number-line.test.ts, packages/perseus/src/widgets/number-line/number-line.tsx
The code that generates the list of tick marks on the number line assumed an integer value for the number of ticks. Exercises with fractions could generate a seed value (`numDivisions`) that is a decimal value (i.e. 7.000001). This fix ensures that an integer value is used.
Issue: LEMS-2549
1. Launch Storybook
1. Open the [Editor Page demo](http://localhost:6006/?path=/story/perseuseditor-editorpage--demo)
1. Add a Number Line widget
1. Configure the widget as shown in the image:
1. The number line in the preview should be visible
=> BUGFIX: [Number Line] - Some exercises with fractions would not render

.changeset/tricky-wasps-hug.md, knip.config.ts, package.json, packages/math-input/src/components/input/mathquill-helpers.ts, packages/math-input/src/components/input/mathquill-types.ts, packages/math-input/src/components/key-handlers/handle-arrow.ts, packages/math-input/src/components/key-handlers/handle-backspace.ts, packages/math-input/src/components/key-handlers/handle-exponent.ts, packages/math-input/src/components/key-handlers/handle-jump-out.ts, packages/math-input/src/components/key-handlers/key-translator.ts, packages/math-input/src/types.ts, yarn.lock
Knip detected some of these unused enums, which helped me realize there was a duplicate type declaration; so I was able to consolidate them into one type.
=> Knip 5: consolidate Mathquill Field types

.changeset/proud-ligers-learn.md, knip.config.ts, package.json, packages/perseus/src/styles/constants.ts, yarn.lock
I could see an argument for keeping these since they define a palette we could choose from. However, we're trying to more closely align with WB so I think we should think of that as our palette rather than maintaining our own.
=> Knip 7: remove unused style constants

.changeset/rotten-turkeys-pump.md, knip.config.ts, package.json, packages/math-input/src/components/aphrodite-css-transition-group/util.ts, packages/math-input/src/components/tabbar/item.tsx, packages/perseus-linter/src/rules/lint-utils.ts, packages/perseus/src/multi-items/prop-type-builders.ts, packages/perseus/src/sigfigs.ts, packages/perseus/src/widgets/interactive-graphs/graphs/use-transform.ts, packages/perseus/src/widgets/numeric-input/numeric-input.testdata.ts, testing/wait.ts, yarn.lock
Knip identified these as both unused internally and not exported through our main export files, but please double check!
As far as I can tell, a lot of this was copy/pasted from Webapp where there are duplicate declarations there.
=> Knip 8: remove unused exports

.changeset/polite-pigs-look.md, packages/math-input/src/components/i18n-context.tsx, packages/perseus/src/components/i18n-context.tsx
`process` is a NodeJS thing, so it's not guaranteed to be on the FE. This checks that it exists before accessing it.
=> Check if process exists before accessing it

.changeset/smart-phones-rush.md, packages/perseus/src/types.ts, testing/test-dependencies.tsx
Remove isMobile from Dependencies since it's now on APIOptions
=> Remove isMobile from Dependencies

.changeset/perfect-guests-raise.md, packages/perseus-editor/src/components/dropdown-option.tsx
As I was working in the code I noticed that the `optionRenderer` prop is never passed to the Option nor OptionGroup components. So I'm removing it. 
Issue: "none"
`yarn test`
`rg optionRenderer` (in hosting applications - webapp, mobile)
=> Remove unused optionRenderer prop on dropdown's Option component

.changeset/forty-otters-check.md, packages/math-input/src/components/keypad/keypad.tsx, packages/perseus/src/components/tooltip.tsx, packages/perseus/src/widgets/label-image/__stories__/answer-choices.stories.tsx, packages/perseus/src/widgets/radio/base-radio.tsx, packages/perseus/src/widgets/radio/choice-none-above.tsx, packages/perseus/src/widgets/radio/focus-ring.tsx
While working in Storybook this week, I kept seeing warnings about components using `defaultProps` and it would be removed in the next version of React. 
The migration is straightforward to use default parameters so I've made those changes in this PR. 
Issue: "none"
`yarn start` -> I visted each story for the affected component
=> Remove deprecated defaultProps

.changeset/tame-insects-return.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/__snapshots__/movable-line.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/use-control-point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
Note to reviewers: it will probably be easiest to review this PR one commit at
a time.
When I started to add aria labels to movable points, I hit a snag: some of
our graph types make the movable point SVG itself tab-focusable, while other
graph types (e.g. segment) add a focusable dummy element so the visual
render order of the points can be different from the tabindex order. This
means that we'd want aria labels in different locations for each of these
graph types. Sometimes, the aria label would need to be on the movable point
itself, and sometimes it would need to be on the dummy element.
The solution implemented in this PR is to use the dummy element for all movable
points. That way we will only need to add accessible stuff to the dummy
element.
This PR is just refactoring; it doesn't …
=> Make `MovablePoint` use `useControlPoint`

.changeset/clever-crews-fly.md, packages/perseus-linter/src/__tests__/rule.test.ts
While working on something else, I saw TypeScript errors coming from this file.
The error was:
```
packages/perseus-linter/src/__tests__/rule.test.ts:83:32 - error TS2339: Property 'check' does not exist on type 'never'.
83                 const lint = r.check(node, state, content);
```
I'm not sure why this just started erroring, but the types are definitely *weird*, so I'm
taking the opportunity to fix them.
There was also a test that depended on a previous test having been run. I fixed
that too.
Issue: none
`yarn test`
=> Fix types in test for perseus-linter

.changeset/swift-trees-flash.md, packages/kas/.eslintrc.js, packages/keypad-context/.eslintrc.js, packages/kmath/.eslintrc.js, packages/math-input/.eslintrc.js, packages/perseus-core/.eslintrc.js, packages/perseus-core/package.json, packages/perseus-editor/.eslintrc.js, packages/perseus-editor/package.json, packages/perseus-linter/.eslintrc.js, packages/perseus/.eslintrc.js, packages/perseus/package.json, packages/perseus/src/multi-items/multi-renderer.tsx, packages/perseus/src/util/graphie.test.ts, packages/pure-markdown/.eslintrc.js, packages/simple-markdown/.eslintrc.js, yarn.lock
Check types for import/no-extraneous-dependencies eslint check
Found by Knip and after talking with Jeremy we think this is the way to go.
=> Add types to no-extraneous-dependencies check

.changeset/spicy-grapes-bathe.md, packages/perseus-editor/src/widgets/grapher-editor.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/interactive-graph-editor.tsx, packages/perseus/src/index.ts
Some things from `sizing-utils` were getting exported from `perseus` when they didn't need to be.
Nothing should change
=> Refine sizing-utils exports

.changeset/wise-keys-explode.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/components/__snapshots__/movable-line.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/components/use-control-point.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
This is step one toward implementing screenreader interactions
for the Interactive Graph widget.
This PR does *not* implement everything described in LEMS-1725.  Notably
missing is the description of the entire graph (listing all points).
I will open another PR for that.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1725
- Use VoiceOver
- `yarn dev`
- `open https://localhost:5173`
Navigate to the Point graph and tab to focus the movable point.  VoiceOver
should read the coordinates.
Move the point with the arrow keys. VoiceOver should play a sound effect and
read the new coordinates with each keypress.
=> Add aria-label to movable points

.changeset/rude-spies-doubt.md, packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer.test.tsx.snap, packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap, packages/perseus/src/widgets/radio/__tests__/__snapshots__/radio.test.ts.snap, packages/perseus/src/widgets/radio/choice-icon/choice-icon.tsx
[It looks like Google Translate doesn't play nicely with React.](https://martijnhols.nl/gists/everything-about-google-translate-crashing-react)
There is [a known issue that Google plans to address](https://issues.chromium.org/issues/41407169)... one day, maybe.
In the short term, it looks like if we wrap text nodes in elements, we should be good to go.
Issue: LEMS-2574
Testing:
Use Google Translate on any radio widget exercise and do something that causes the radio widgets to change state to render a text node (the easiest way was showing rationales). The red bar of doom doesn't show.
=> Wrap text node to reduce Google Translate bug

.changeset/real-suns-fail.md, packages/perseus/src/components/i18n-context.tsx, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/use-control-point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/point.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/ray.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/screenreader-text.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/screenreader-text.ts, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css, packages/perseus/src/widgets/interactive-graphs/types.ts
When a user focuses a whole interactive graph, they should be able to
hear a description of all the interactive elements. This PR implements
this feature for point graphs.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1725
Test plan:
- Use VoiceOver
- `yarn dev`
- `open http://localhost:5173`
- Tab to the point graph. You should hear a description including the
coordinates of the interactive point.
=> Add screenreader description for point graph elements

.changeset/four-seas-shave.md, packages/perseus/src/index.ts
Export the PerseusDependenciesV2 type so I can use it in Webapp
See: https://github.com/Khan/webapp/pull/26667#pullrequestreview-2413596030
=> export PerseusDependenciesV2

.changeset/light-shirts-warn.md, packages/perseus-editor/src/widgets/label-image-editor.tsx
There's a race condition in the editing experience. I actually think the root of the issue has to do with code outside of Perseus, but CP is currently rewriting the editor so I'm just trying to patch for now and hope the real issue is resolved in the future.
Details are written out in the ticket, but the tl;dr is that there's some kind of race condition when changing the image and getting the image size. The outcome of the race condition was that `imageUrl` would become `""` when immediately calling `onChange` with an updated measurement. So to be doubly sure, I'm sending `imageUrl` with the measurements now.
**Risk:** I think there's a risk for a different type of race condition:
1. User changes URL
2. We start to measure the image size (async since we have to load the image)
3. User …
=> Attempt bug fix for LabelImageEditor

.changeset/witty-hounds-melt.md, packages/perseus/src/__tests__/init.test.ts, packages/perseus/src/index.ts, packages/perseus/src/init.ts, packages/perseus/src/widgets/explanation/explanation.cypress.ts, packages/perseus/src/widgets/grapher/grapher.cypress.ts
While investigating a regression on Webapp related to our Deprecated Stand-in Widget, we discovered we were initializing MathJax unnecessarily! This initialization is specifically for MathJax2 so it is safe to remove entirely. 
Issue: LEMS-2588
- Manual testing 
- Knowledge that this code has not been running for 2 months, and we've had zero issues with our MathJax rendering
- Knowledge that this is unused due to being MathJax2
=> Remove unnecessary MathJax 2 logic from Perseus.Init

.changeset/good-ghosts-invite.md, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-label-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-label-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.test.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts, packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-label.tsx, packages/perseus/src/widgets/interactive-graphs/utils.test.ts, packages/perseus/src/widgets/interactive-graphs/utils.ts
In the rest of the exercise editor, content authors need to surround text in `$` for it to be denoted as TeX.
For consistency, we want to add that functionality to the interactive graph editor as well.
- Update LockedLabelSettings to say "text" instead of "TeX" and have an infotip to explain it.
- Update LockedLabel so that it surrounds the non-$ part of the string with \text{} before
wrapping the whole thing in <TeX>
Note: This is a prerequisite for auto-generating spoken math details with the MathJax speech engine
for the aria labels, because the non-TeX text needs to be differentiated in the label for the label
to be generated correctly for non-TeX text. If it's all TeX, the speech engine reads every letter
separately (example: "<TeX>square A</TeX>" ==> "s q u a r e upper A")
Issue: …
=> [Locked Figures] Use $ symbols to denote TeX within locked labels and locked figure labels

.changeset/tough-buses-tell.md, packages/perseus/src/__tests__/widgets.test.ts, packages/perseus/src/widgets/radio/radio-component.tsx
In my prior PR [where I updated this function signature](https://github.com/Khan/perseus/commit/614425b129dfbd04160215d9026a6666e03deddc), I wasn't aware that it was called outside of the component anywhere. It turns out in Web App, [there are calls to getUserInputFromProps](https://github.com/Khan/webapp/blob/master/services/static/javascript/coach-report-package/responses/utils.ts#L75) and this change to the function signature breaks those calls.
- Ensure the tests pass
=> Update function signature for getUserInputFromProps

.changeset/healthy-years-dream.md, docs/architecture.md, packages/perseus/src/article-renderer.tsx, packages/perseus/src/index.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/renderer.tsx
This PR adds a bit more to the architecture documentation. I've tried to explain some of our type conventions for widgets and how `WidgetProps` is fulfilled for widgets.
While doing this documentation, I realized that we don't have any type that represents the concept of an Article. Although it's simply a `PerseusRenderer` or `ReadonlyArray<PerseusRenderer>` I thought it worthwhile to add. 
Issue: "none"
=> More architecture documentation

.changeset/small-pots-kick.md, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts, packages/perseus/src/widgets/interactive-graphs/utils.test.ts, packages/perseus/src/widgets/interactive-graphs/utils.ts
With the current implementation, all `$` symbols are removed when
they are used to denote TeX inside `$...$` blocks. There is no way
to denote something like `$50` within TeX with this crude implementation.
To remedy this, I'm using the simple markdown parser to correctly
and more sophisticatedly determine which blocks are math.
- `{$}` and `\$` both show up as a regular dollar sign in the labels
Issue: https://khanacademy.atlassian.net/browse/LEMS-2591
`yarn jest packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx`
Storybook
- Go to http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-figure-labels-all-flags
- Use `{$}` within the locked label and locked figure labels,
with a combination of TeX and non-TeX
=> [Locked Labels] Make `{$}` show up as regular symbols inside TeX

.changeset/curvy-glasses-poke.md, docs/architecture.md, packages/perseus/src/util/answer-types.ts, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/table/score-table.test.ts, packages/perseus/src/widgets/table/score-table.ts, packages/perseus/src/widgets/table/utils.ts, packages/perseus/src/widgets/table/validate-table.test.ts, packages/perseus/src/widgets/table/validate-table.ts
This PR is a test run for extracting validation logic from scoring (using `table` as the test subject). I've used a pattern where the validator still returns a `PerseusScore`. This means that we can call the validator as the first step in scoring and return the score if it's `invalid`.  
Issue: LEMS-2606
All tests should still pass.
=> Table: Extract validation out of scoring

.changeset/dry-moles-notice.md, packages/perseus/src/widgets/interactive-graphs/utils.ts
I need to add a null check after my $ TeX updates in https://github.com/Khan/perseus/pull/1847.
This is actually already added in a larger PR, but this fix needs to get out ASAP.
Issue: none
- Go to http://localhost:6006/iframe.html?id=perseuseditor-widgets-interactive-graph--mafs-with-locked-figure-labels-all-flags&viewMode=story
- Backspace in the locked point visible label input field
- Confirm that there is no crash
=> [Locked Figure Labels] Fix bug that's causing the editor to crash when the label input is empty (and on load)

.changeset/many-boxes-wave.md, packages/perseus-editor/src/article-editor.tsx, packages/perseus-editor/src/editor-page.tsx, packages/perseus-editor/src/util/deprecated-widgets/modernize-widgets-utils.ts
This PR adds an alert banner to the editors to notify Content Editors when pre-existing content has been converted into modern widgets. (ie Input Number has become Numeric Input) 
- Manual testing
=> Addition of new alert when json is converted.

.github/REVIEWERS
This PR adds [`TUT`](https://github.com/orgs/Khan/teams/tut) as a reviewer to any pull requests for `widget-ai-utils/*` code.
Issue: "none"
Open a PR with changes in `widget-ai-utils/` and notice that `TUT` is tagged by Gerald
=> Add TUT team as owner of widget-ai-utils/ code

.changeset/many-boxes-wave.md, .changeset/moody-dingos-relate.md, .changeset/quick-mangos-end.md, packages/perseus-editor/src/article-editor.tsx, packages/perseus-editor/src/util/deprecated-widgets/input-number.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/numeric-input/numeric-input.tsx
Discovered a regression after addressing some PR feedback for the InputNumber Conversion project. This small change ensures that we're getting the proper result for `conversionWarningRequired` in the Article Renderer. 
Issue: None
- Manual Testing 
- Snapshot testing in Webapp
=> Noticed a regression for Input Number while testing on webapp. Testing this logic fix

.changeset/green-suns-battle.md, package.json, packages/perseus/src/util/parse-perseus-json/exhaustive-test-tool/index.ts, yarn.lock
Before we deploy the parsing code described in [ADR 773][1] to production, we
want to make sure it can handle all our production data.
[1]: https://khanacademy.atlassian.net/wiki/spaces/ENG/pages/3318349891/ADR+773+Validate+widget+data+on+input+in+Perseus
This PR adds a tool that will run an exhaustive set of tests, checking the
parser code against every single content item. It tries to summarize the parse
errors intelligently, uniquing them by object path. The output of this tool can
be used to create a suite of regression tests for the parser, which will ensure
it can handle old data formats in perpetuity.
Issue: LEMS-2581
Run the test tool as described in the comment in
`exhaustive-test-tool/index.ts`. (Note: this will take approximately 4 hours to
run, plus a couple hours to download …
=> ADR 773: Add exhaustive test tool for PerseusItem parser

.changeset/proud-horses-wave.md, packages/perseus/src/renderer-util.ts, packages/perseus/src/util/deprecated-widgets/input-number.ts, packages/perseus/src/util/deprecated-widgets/modernize-widgets-utils.ts
While performing regression testing on the latest changes related to a conflict between our Server Side Scoring and Input Number Conversion projects, I found an edge case bug that needed to be handled. 
This bug was only reproducible on a test course that had an `input-number 2` and no `input-number 1`. As a result of the key mismatch between the `perseusRenderData` and `userInputMap`, the exercise became blocked / locked and unable to be continued after attempting to score. (If you would like a link to this exercise, please reach out to me!)
This PR updates the conversion logic in `renderer-utils.ts` to update both the `perseusRenderData` and `userInputMap` at the same time, so that the widget keys are identical between the two formats. This should cover any additional edge cases (such …
=> Ensuring UserInput and Rubric widget keys match

.changeset/late-sheep-rush.md, packages/perseus/src/util/parse-perseus-json/exhaustive-test-tool/index.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/perseus-item.ts
The exhaustive test tool for PerseusItem parsing outputs the `assessmentItem`s
that can't be parsed. The plan is to generate regression tests from these
assessment items.
Previously, the tool would output an arbitrary `assessmentItem` for each
failure.  This PR makes it keep the *shortest* `assessmentItem` instead. That
way, our regression test data won't be over-complicated.
Issue: none
Run the exhaustive test tool on a subset of data.
=> ADR 773: Look for the shortest assessment item to repro each parse error

.changeset/great-jobs-flash.md, packages/perseus/src/util/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-snapshot.test.ts.snap, packages/perseus/src/util/parse-perseus-json/regression-tests/parse-perseus-json-snapshot.test.ts
The other regression tests only assert that we can successfully parse each
assessmentItem in the regression dataset. However, a successful parse doesn't
necessarily mean we preserved all input data or migrated it correctly to the
latest format.
This PR adds snapshot tests to fix that gap in our coverage.
Issue: none
`yarn test`
=> Add snapshot tests for parseAndTypecheckPerseusItem

.changeset/violet-melons-sneeze.md, packages/perseus/src/__stories__/server-item-renderer.stories.tsx, packages/perseus/src/__testdata__/server-item-renderer.testdata.ts, packages/perseus/src/widgets/numeric-input/numeric-input.tsx
This PR fixes an issue with the Input Number Conversion project that specifically pertains to widgets that have a value of 0, as it results in a falsy situation. As a result of this issue, exercises that contain the offending widget settings would fail to render. 
This PR updates the logic to a safer key, and ensures that it is not undefined. 
- Manual testing both in Storybook and Webapp to confirm that failing cases now render properly.
=> Fixing issue with Input Numbers that have a value of 0 

.changeset/mighty-cobras-kick.md, packages/perseus/src/index.ts, packages/perseus/src/widgets/interactive-graphs/utils.test.ts, packages/perseus/src/widgets/interactive-graphs/utils.ts
We want to be able to parse a string meant for TeX into its most basic
essential parts. To do this, we are creating a `mathOnlyParser()` parser.
Using the default `parse()` function from SimpleMarkdown breaks up
text into too many sections, and parsing from scratch can get very
complicated. The ideal way to do this is to use the existing `parserFor()`
function from SimpleMarkdown that lets us customize the parser.
This will be used in
- Generating the TeX for Locked Labels and Locked Figure labels so that
it shows up correctly on the graph. Non-TeX should show up with regular
text styling and allow spaces.
- Generating the aria label for locked figures with TeX labels. The speech
rule engine will only be run on the math sections of the parsed output.
Issue: …
=> [Locked Labels + Aria] Create math only parser to help parse TeX how we want

.changeset/warm-llamas-tease.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/expression/expression.tsx, packages/perseus/src/widgets/expression/score-expression.test.ts, packages/perseus/src/widgets/expression/score-expression.ts, packages/perseus/src/widgets/expression/validate-expression.test.ts, packages/perseus/src/widgets/expression/validate-expression.ts
Arguably, this validator is quite useless in that it does nothing. However, I was thinking that we'd be better off if all of our widgets had a validator, even if it does nothing, rather than have some widgets have a validator and some not. In my mind, we're better off with the same convention everywhere.
This PR introduces the concept of "validation data" that we discussed earlier today (November 18). This represents _only_ the data needed by the validator. It intersects that type into the ScoringData type (nee Rubric) to ensure that the scoring function has all the data it needs to score (but also validate).
* `PerseusExpressionRubric` - the data needed to score the `expression` user input (Note: this will be renamed to `PerseusExpressionScoringData` in the near future)
* …
=> Expression: Extract validation from scorer

.changeset/giant-vans-notice.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/matrix/score-matrix.test.ts, packages/perseus/src/widgets/matrix/score-matrix.ts, packages/perseus/src/widgets/matrix/validate-matrix.test.ts, packages/perseus/src/widgets/matrix/validate-matrix.ts
This PR extracts validation from the `matrix`'s scorer function. In reality, it's an empty function, but it follows our conventions for having the scorer call a validator first. I've created the standard tests to ensure that scorer calls the validator.
Issue: LEMS-2602
`yarn test`
=> Matrix: Extract validation from scorer

.changeset/chilled-pianos-cheat.md, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
For keyboard users if they're drawing a polygon and it places a point at 0,0. There are cases where it could cross the sides of the polygon they are actively creating and cause the polygon to break. Mouse uses can get around this a bit. But it's not idea. This fix checks whether the polygon type allows intersecting sides and disables the rejection logic.
This PR also includes improvements to:
- Screen readers announcing instructions to enable graph (was not reading out before).
- Disabled buttons are not tabbable now.
Issue: LEMS-2618
Go to /?path=/story/perseus-widgets-interactive-graph--unlimited-polygon-with-mafs in Storybook.
Use your keyboard to add points.
Move a few points in a way that a new point would cause the sides to intersect.
Add a new point and make sure you can still move …
=> Fix: Open unlimited polygon does not restrict crossing sides.

.changeset/selfish-spies-film.md, packages/perseus/src/strings.ts
Add a comment to the `strings.ts` file so it's easy
to keep track of which strings will need to be
finalized before translation tickets are made.
We want to wait until all the interactive element
strings for interactive graph have been written
and confirmed before creating their respective
translation tickets.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2660
N/A
=> [SR] Add comment about creating translation tickets

.changeset/sharp-radios-burn.md, packages/perseus/src/widgets/orderer/score-orderer.test.ts, packages/perseus/src/widgets/orderer/score-orderer.ts, packages/perseus/src/widgets/orderer/validate-orderer.test.ts, packages/perseus/src/widgets/orderer/validate-orderer.ts
To complete server-side scoring, we are separating out validation logic from scoring logic. This separates that logic and updates associated tests.
Issue: LEMS-2603
- Confirm widget still works as expected
=> Orderer: Extract validation out of scoring

.changeset/sweet-trainers-drop.md, packages/perseus/src/widgets/sorter/score-sorter.test.ts, packages/perseus/src/widgets/sorter/score-sorter.ts, packages/perseus/src/widgets/sorter/validate-sorter.test.ts, packages/perseus/src/widgets/sorter/validate-sorter.ts
To complete server-side scoring, we are separating out validation logic from scoring logic. This separates that logic for the sorter widget and updates associated tests.
Issue: LEMS-2605
- Confirm widget still works as expected via Storybook
=> Sorter: Extract validation out of scoring

.changeset/nice-fans-swim.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/plotter/plotter.tsx, packages/perseus/src/widgets/plotter/score-plotter.test.ts, packages/perseus/src/widgets/plotter/score-plotter.ts, packages/perseus/src/widgets/plotter/validate-plotter.test.ts, packages/perseus/src/widgets/plotter/validate-plotter.ts
To complete server-side scoring, we are separating out validation logic from scoring logic. This PR separates that logic and associated tests for the plotter widget.
Issue: LEMS-2604
- Confirm checks pass
- Confirm widget still works as expected
=> Plotter: Extract validation out of scoring

.changeset/spotty-moles-reply.md, packages/perseus/src/widgets/radio/score-radio.test.ts, packages/perseus/src/widgets/radio/score-radio.ts, packages/perseus/src/widgets/radio/validate-radio.test.ts, packages/perseus/src/widgets/radio/validate-radio.ts
To complete server-side scoring, we are separating out validation logic from scoring logic. This PR separates validation logic that does not depend on answer information and also separates associated tests for the radio widget.
Issue: LEMS-2594
- Confirm checks pass
- Confirm widget still works as expected
- Confirm the validation logic remaining in the scoring function cannot be removed from scoring
=> Radio: Extract validation out of scoring

.changeset/green-ghosts-burn.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/categorizer/categorizer.tsx, packages/perseus/src/widgets/categorizer/score-categorizer.test.ts, packages/perseus/src/widgets/categorizer/score-categorizer.ts, packages/perseus/src/widgets/categorizer/validate-categorizer.test.ts, packages/perseus/src/widgets/categorizer/validate-categorizer.ts
In order to complete scoring server-side, we need to separate out the validation logic from the scoring logic. This work separates those two functions and updates associated tests.
Issue: LEMS-2596
- Confirm the widget still behaves as it should.
=> Categorizer: Extract validation out of scoring

.changeset/chilled-turtles-drive.md, packages/perseus/src/perseus-types.ts, packages/perseus/src/util/parse-perseus-json/general-purpose-parsers/defaulted.ts, packages/perseus/src/util/parse-perseus-json/parse-perseus-json.test.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/categorizer-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/dropdown-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/expression-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/graded-group-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/hint.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/iframe-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/images-map.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/matrix-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/perseus-item.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/perseus-renderer.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/radio-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/widget.ts, packages/perseus/src/util/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-snapshot.test.ts.snap, packages/perseus/src/util/parse-perseus-json/regression-tests/data/categorizer-missing-static.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/dropdown-missing-version.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/hint-missing-images.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/iframe-missing-static.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/item-missing-answerArea.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/matrix-missing-version.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/orderer-option-missing-images.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/question-missing-content.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/radio-choice-missing-content.json, packages/perseus/src/widgets/graded-group/graded-group.tsx, packages/perseus/src/widgets/matrix/matrix.tsx
=> Add and pass regression tests for PerseusItem parser

.changeset/yellow-ducks-march.md, packages/perseus/src/util/parse-perseus-json/perseus-parsers/expression-widget.test.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/expression-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/widgets-map.test.ts
This demonstrates how we can upgrade/migrate widget options in the parsing
code, obviating the need for `propUpgrades`.
The fact that `version` is an object makes this really annoying because
TypeScript can't discriminate unions based on nested properties like
`version.major`. Given that constraint, I think the approach I came up with is
reasonable, but I'm certainly open to feedback on how to improve it.
Issue: LEMS-2582
`yarn test`
=> Migrate expression widget to latest version in PerseusItem parser

.changeset/few-jokes-travel.md, config/test/test-setup.ts, packages/kas/src/nodes.ts, packages/perseus-editor/src/__stories__/item-editor.stories.tsx, packages/perseus-editor/src/multirenderer-editor.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.test.tsx, packages/perseus-editor/src/widgets/orderer-editor.tsx, packages/perseus/src/hints-renderer.tsx, packages/perseus/src/interactive2/wrapped-drawing.ts, packages/perseus/src/perseus-markdown.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/util.ts, packages/perseus/src/util/graphie.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/orderer-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/widgets-map.test.ts, packages/perseus/src/widgets/grapher/util.tsx, packages/perseus/src/widgets/orderer/orderer.tsx, packages/simple-markdown/src/index.ts
idk, just following some threads by un-excepting errors.
=> remove some error suppressions

.changeset/giant-tables-impress.md, packages/perseus/src/components/text-input.tsx
`findDOMNode` is deprecated and React whines about it constantly when running tests, so I'm trying to chip away at removing uses of it.
=> remove findDOMNode from text-input

.changeset/chilly-carrots-wink.md, packages/perseus/src/components/number-input.tsx
When running tests, I was tired of seeing:
> Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
So I thought I'd start chipping away at them.
Nothing should change, just an implementation detail.
=> remove use of findDOMNode in number-input

.changeset/two-feet-care.md, packages/perseus/src/widgets/expression/expression.test.tsx, packages/perseus/src/widgets/measurer/measurer.test.tsx, packages/perseus/src/widgets/measurer/measurer.tsx, packages/perseus/src/widgets/radio/__tests__/radio.test.ts, packages/perseus/src/widgets/radio/radio.ts
Only 3 widgets seem to use the `propUpgrades` mechanism:
- Radio
- Expression
- Measurer
None of them seemed to have tests (at least not direct tests), so this adds them.
I also took out underscore after I wrote the tests.
This is the test plan
=> Add tests for propUpgrades functions

.changeset/seven-owls-explain.md, packages/perseus/src/util/parse-perseus-json/perseus-parsers/expression-widget.ts
The Expression widget imports the KAS parser, which contains generated code
with some syntax that `@swc-node/register` (which we use to run TypeScript from
the command line) can't parse. The parse error was preventing the exhaustive
tests for the parsers (packages/perseus/src/util/parse-perseus-json/exhaustive-test-tool/index.ts)
from running.
Since we can't change the generated code, the solution is to avoid importing
the version number from the Expression widget, and hardcode it instead. I think
this is okay, because the migration function that used the version number is
called `migrateV0ToV1`, so we actually want to hardcode version 1 rather than
taking the current version from the widget.
Issue: none
Run the exhaustive test tool according to the instructions in the file.
=> Inline version in expression widget parser

.changeset/mighty-rules-talk.md, .eslintrc.js, .github/dependabot.yml, packages/perseus-editor/src/components/__stories__/device-framer.stories.tsx, packages/perseus-editor/src/components/widget-editor.tsx
Juan and I were discussing keeping Perseus dependnecies up to date with webapp (especially WB and WS). This is a trial run to see if Dependabot will help us. It should open up a new PR any time WB or WS packages are released. And all WB or WS packages that received an update should be updated together in the same Perseus PR. 
Issue: "none"
I suspect I'll need to land this and monitor it to test. Github action infra is notoriously difficult to test locally.
=> Enable dependabot updates for WB/WS (and group them)

.changeset/strong-flies-thank.md, packages/perseus/src/index.ts, packages/perseus/src/perseus-types.ts
I was working in the `perseus-types.ts` file a bit and noticed a few types that defined options for widgets that have been deleted. This PR cleans up the types. 
Issue: "none"
`yarn typecheck` is fine
=> Remove unused types for widgets that no longer exist

.github/dependabot.yml
I set up Dependabot updates for WonderBlocks and WonderStuff packages last week and set them so they'd be updated in groups. However, I missed adding them to the `allow` list, which prevented any updates to them. This PR adds them to the `allow` list so that Dependabot actually works. 
Issue: "none"
Land and watch tonights Dependabot run.
=> Allow WB/WS packages otherwise groups don't match anything

package.json, tsconfig-common.json, yarn.lock
Wonder Blocks is updating Storybook to 8.x which requires using "moduleResolution": "bundler" in its tsconfig, see https://stackoverflow.com/questions/72193784/why-doesnt-the-exports-field-of-npm-work-in-typescript for details.  To fix this, I decided to update TypeScript in Wonder Blocks.  Instead of updating to the minimally required version I figured I may as well upgrade to the most recent version since I'm upgrading anyways.
Although we probably don't need to update TypeScript in all of our repos at the same time (unless we start using new syntax), we may as well.  That way, if a new Wonder Blocks package is published with new TS syntax it its types, Perseus will be ready.
In theory, this shouldn't change the output of any of the packages since we're using babel for compilation. …
=> Update TypeScript to version 5.7.2

.changeset/tall-pianos-tap.md, packages/perseus/src/perseus-types.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/tsconfig-shared.json
As it says, just some comments that I wanted to improve as I was working on SSS.
Issue: "none"
Read the comments.
=> Improve some comments

.changeset/early-phones-remain.md, packages/perseus-editor/src/article-editor.tsx, packages/perseus-editor/src/components/__stories__/color-select.stories.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/color-select.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/line-stroke-select.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-figure-select.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-figures-section.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-label-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/__testutils__/renderQuestion.tsx, packages/perseus/src/widgets/radio/__stories__/radio.stories.tsx
I was running unit tests and came across some TS suppressions that were fairly easy to resolve.
Issue: "none"
`yarn lint`
`yarn test`
=> Fix types so that we can remove a bunch of TS suppressions

.changeset/calm-chefs-boil.md, .changeset/large-melons-deny.md, .eslintrc.js, packages/perseus-editor/src/__stories__/content-preview.stories.tsx, packages/perseus-editor/src/components/__stories__/device-framer.stories.tsx, packages/perseus-editor/src/components/graph-settings.tsx, packages/perseus-editor/src/tex-error-view.tsx, packages/perseus-editor/src/widgets/__stories__/image-editor.stories.tsx, packages/perseus-editor/src/widgets/cs-program-editor.tsx, packages/perseus-editor/src/widgets/definition-editor.tsx, packages/perseus-editor/src/widgets/dropdown-editor.tsx, packages/perseus-editor/src/widgets/expression-editor.tsx, packages/perseus-editor/src/widgets/input-number-editor.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-label-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.tsx, packages/perseus-editor/src/widgets/measurer-editor.tsx, packages/perseus-editor/src/widgets/numeric-input-editor.tsx, packages/perseus-editor/src/widgets/orderer-editor.tsx, packages/perseus-editor/src/widgets/plotter-editor.tsx, packages/perseus-editor/src/widgets/radio/editor.tsx, packages/perseus/src/components/__stories__/zoomable.stories.tsx, packages/perseus/src/components/visibility-observer/__stories__/visibility-observer.stories.tsx, packages/perseus/src/util/tex.ts, testing/ke-score-ui.tsx
While running tests I saw warnings that React components rendered in a list were missing `key`s. This lead me down a path of "is there an ESLint rule for this?" Turns out, there's a nice ruleset for the React ESLint plugin that includes a rule for ensuring JSX elements have a `key` when in a list. 
So, this PR enables the `react/recommended` ESLint rules and fixes/suppresses things. 
Issue: "none"
`yarn lint`
Also, I opened the affected stories to double-check things.
=> Enable "react/recommended" lint ruleset and fix/suppress violations

.github/workflows/storybook.yml
EDIT: We _cannot_ enable TurboSnap for Perseus because we already use [`onlyStoryFiles`](https://www.chromatic.com/docs/configure/#onlystoryfiles) (which restricts the set of stories to run, but is incompatible with the `onlyChanged` setting.
As a result of ☝️, this PR has been updated to document that `onlyStoryFiles` prevents use of `onlyChanged`.
~~This PR enables TurboSnap for the Perseus repo. TurboSnap is already enabled or the Perseus project on Chromatic.com, but we noticed it wasn't enabled for the Github Action that runs it.~~
Issue: "none"
Watch the actions on this build. We might have to land this and monitor future builds to see it working as I'm not sure if there'll be a proper baseline for TurboSnap to work off of.
=> Enable TurboSnap for Chromatic

.changeset/metal-readers-impress.md, .changeset/stupid-apricots-retire.md, packages/perseus-editor/src/components/graph-settings.tsx, packages/perseus/src/renderer-util.ts, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/group/group.tsx, packages/perseus/src/widgets/group/score-group.ts
This PR refactors the scoring around `group` so that it follows the same pattern as all the other widgets. This means that our main `scoreWidgetsFunctional` can be simplified to remove the special case for the `group` widget. 
All tests still pass!
`yarn test`
=> SSS: Move group scoring into group scorer

.changeset/chilled-cameras-play.md, packages/perseus/src/interactive2/movable-line.ts, packages/perseus/src/interactive2/movable-point.tsx, packages/perseus/src/interactive2/movable-polygon.ts, packages/perseus/src/interactive2/objective_.ts, packages/perseus/src/renderer-util.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/traversal.ts
I was working in an area where these "objective_" utils were used and it got annoying that I couldn't jump to the functions. So this PR adjusts the file to use the more modern ES6 `export` syntax instead of exporting an object. 
Issue: "none"
`yarn test`
=> Switch to standard ES exports for objective utils

.changeset/calm-chefs-boil.md, .changeset/chilled-cameras-play.md, .changeset/early-phones-remain.md, .changeset/hip-pandas-argue.md, .changeset/large-melons-deny.md, .changeset/many-keys-smash.md, .changeset/mean-fans-boil.md, .changeset/metal-readers-impress.md, .changeset/odd-moons-remember.md, .changeset/shiny-sloths-obey.md, .changeset/smooth-taxis-mate.md, .changeset/stupid-apricots-retire.md, .changeset/sweet-ligers-arrive.md, .changeset/tall-pianos-tap.md, .changeset/tender-planets-greet.md, .changeset/tiny-feet-give.md, .changeset/two-turtles-return.md, packages/perseus-editor/CHANGELOG.md, packages/perseus-editor/package.json, packages/perseus/CHANGELOG.md, packages/perseus/package.json
The last release failed because the `yarn.lock` file was changed when `yarn install` ran (See #1957). 
This PR reverses (`git revert 5963ea185`) the release commit so that we can get a new Version Packages PR and land it (and trigger a new release).
PR #1957 must be landed after this PR, but _before_ we do a release. 
Issue: "none"
=> Reverses PR #1944 (last Version Packages PR)

yarn.lock
This morning I landed a farily benign [PR](https://github.com/Khan/perseus/pull/1939) that is [generated periodically](https://github.com/Khan/perseus/actions/workflows/maintenance.yml) to update our browserslist reference. After landing it, it appears that running `yarn install` introduces changes to the `yarn.lock` file. 
This PR was created by running `yarn install` locally on a clean repo and committing the changes `yarn` made. 
The reason is not clear yet, but this PR applies the changes that `yarn` wants so that `main` can be clean again. 
Issue: "none"
`yarn install` 
Git repo is still clean
=> Update yarn.lock after browserslist update broke it

.changeset/poor-numbers-reflect.md, packages/perseus/src/styles/perseus-renderer.less, packages/perseus/src/styles/variables.less
The text in the numeric input tooltip was slightly out of spec for accessibility. This change ensures that the text has a minimum 4.5:1 contrast ratio.
1. Launch Storybook
2. Navigate to Perseus Editor => Editor => [Demo](http://localhost:6006/?path=/story/perseuseditor-editorpage--demo)
3. Add a Numeric Input widget
4. Configure the widget to have any number of format options
5. Place focus in the input field in the preview for the widget
6. Check the color value in the browser inspector for the text in the tooltip (it should be greater than 4.5:1)
=> [Numeric Input] - BUGFIX - Adjust color contrast for tooltip text

.github/dependabot.yml
*sigh* I can't read. 
`assignees` => https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#assignees
> Use assignees to specify individual assignees for all pull requests raised for a package manager.
`reviewers` ==> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers
> Use reviewers to specify individual reviewers or teams of reviewers for all pull requests raised for a package manager. You must use the full team name, including the organization, as if you were @mentioning the team.
Issue: "none"
=> Fix reviewers for dependabot - 'assignees' is only for individuals

.changeset/seven-planets-matter.md, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.tsx
All our interactive graph aria labels are spelling out commas
in coordinate pairs for clarity. When using a coordinate pair
as is, the screen reader may skip the comma and read
ambiguously.
Example: (1000, 975) ==> "one thousand nine hundred seventy-five" (sounds like 1975)
To fix this issue and be consistent with all the other
interactive graph aria labels, the locked labels' autogeneration
should also spell out commas.
- Spell out commas in locked figures' auto-generated aria label text
Issue: none
`yarn jest --silent`
Storybook
- Go to http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-figure-labels-all-flags
- Go through all the different locked figures and click "auto-generate"
- Note that their coordinates should all spell out the comma …
=> [Locked Figures Aria] Update the auto-generated text to spell out commas

.changeset/large-flies-divide.md, config/test/custom-matchers.ts, packages/perseus/src/__tests__/renderer-api.test.tsx, packages/perseus/src/components/__tests__/sorter.test.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/util/test-utils.ts, packages/perseus/src/widgets/categorizer/categorizer.test.ts, packages/perseus/src/widgets/definition/definition.test.ts, packages/perseus/src/widgets/deprecated-standin/__tests__/deprecated-standin.test.ts, packages/perseus/src/widgets/dropdown/dropdown.test.ts, packages/perseus/src/widgets/expression/expression.test.tsx, packages/perseus/src/widgets/graded-group/graded-group.test.ts, packages/perseus/src/widgets/grapher/grapher.cypress.ts, packages/perseus/src/widgets/image/image.test.ts, packages/perseus/src/widgets/input-number/input-number.test.ts, packages/perseus/src/widgets/interaction/interaction.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/matcher/matcher.test.tsx, packages/perseus/src/widgets/matrix/matrix.test.ts, packages/perseus/src/widgets/number-line/number-line.test.ts, packages/perseus/src/widgets/numeric-input/numeric-input.test.ts, packages/perseus/src/widgets/orderer/orderer.test.ts, packages/perseus/src/widgets/passage-ref/passage-ref.test.ts, packages/perseus/src/widgets/radio/__tests__/radio.test.ts
Remove `guessAndScore` from Renderer. This hasn't been used in learner-facing logic for a little bit now. The bulk of this PR is updating internal usage - tools for testing exercise correctness were using this (specifically in Cypress and our custom matchers for Jest); so most of the work was porting tests to use `scorePerseusItem` instead.
From a learner's perspective, this is dead code. So while this is a major API change, it's mostly removing dead code and updating tests. Tests should continue to run successfully.
=> Remove `guessAndScore`

.changeset/chilly-pigs-clean.md, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-label-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-label-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts
Now that TeX needs $s around it to render as TeX,
update the placeholder in the interactive graph editor
label settings to reflect that.
While I'm here, I also updated the starting text on
the locked label settings to be "label" so that it's
easier to prevent empty labels. Charlie also expressed
that this makes it easier to tell the labels' tab orders.
The placeholder will still show up if the text is deleted.
Issue: none
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--mafs-with-locked-figure-labels-all-flags
- Go to locked label's settings
- Clear the text field
- Confirm that the placeholder says "ex. $x^2$ or $\frac{1}{2}$"
| --- | --- |
| ![Screenshot 2024-12-11 at 1 50 20 PM](https://github.com/user-attachments/assets/ffa1cbbc-77f9-4c5e …
=> [Locked Figure Labels] Update placeholder to include TeX $s

.changeset/cool-moons-reply.md, packages/perseus/src/components/__tests__/__snapshots__/graph.test.tsx.snap, packages/perseus/src/util/graphie.ts, packages/perseus/src/widgets/grapher/__snapshots__/grapher.test.ts.snap, packages/perseus/src/widgets/interaction/__snapshots__/interaction.test.ts.snap, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/number-line/__snapshots__/number-line.test.ts.snap
This is a simple PR that adds an aria-hidden tag to our graphie container so that we don't read out axis labels or "Made by Raphael" on screen readers. As a result, screen readers should have an easier time navigating the website. 
While this may hide some labels within graphie, we've taken the position that the alt tags should be the sole source of truth for our screen readers. 
Issue: LEMS-2712
=> One weird trick that delights screen readers

.changeset/gentle-ties-drum.md, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/components/__tests__/__snapshots__/svg-image.test.tsx.snap, packages/perseus/src/components/__tests__/svg-image.test.tsx, packages/perseus/src/components/svg-image.tsx, packages/perseus/src/index.ts, packages/perseus/src/renderer-util.test.ts, packages/perseus/src/util/graphie-utils.test.ts, packages/perseus/src/util/graphie-utils.testdata.ts, packages/perseus/src/util/graphie-utils.ts, packages/perseus/src/widget-ai-utils/graded-group-set/graded-group-set-ai-utils.test.ts, packages/perseus/src/widget-ai-utils/group/group-ai-utils.test.ts, packages/perseus/src/widget-ai-utils/image/image-ai-utils.test.ts, packages/perseus/src/widget-ai-utils/interactive-graph/interactive-graph-ai-utils.test.ts, packages/perseus/src/widget-ai-utils/label-image/label-image-ai-utils.test.ts, packages/perseus/src/widgets/graded-group-set/graded-group-set.test.ts, packages/perseus/src/widgets/grapher/grapher.test.ts, packages/perseus/src/widgets/group/group.test.tsx, packages/perseus/src/widgets/image/image.test.ts, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/label-image/__tests__/label-image.test.ts, packages/perseus/src/widgets/radio/__tests__/__snapshots__/radio.test.ts.snap, packages/perseus/src/widgets/radio/__tests__/radio.test.ts
This PR updates our approach to loading graphie images for svg-image. 
An error will be thrown if the labels are not found, but should not impede users. Many tests were added using the failed cases provided on the ticket, in order to ensure that this new approach works for nearly all use cases. 
Issue: LEMS-2524
- New svg-image tests 
- New graphie-utils tests that include (most) of the test cases provided.
=> New approach to svg-image

.changeset/nervous-zoos-lick.md, packages/perseus/src/types.ts, packages/perseus/src/widgets/categorizer/validate-categorizer.ts, packages/perseus/src/widgets/dropdown/validate-dropdown.ts, packages/perseus/src/widgets/expression/validate-expression.ts, packages/perseus/src/widgets/matrix/validate-matrix.ts, packages/perseus/src/widgets/orderer/validate-orderer.ts, packages/perseus/src/widgets/plotter/validate-plotter.ts, packages/perseus/src/widgets/radio/validate-radio.ts, packages/perseus/src/widgets/sorter/validate-sorter.ts, packages/perseus/src/widgets/table/validate-table.ts
This is a tiny PR to introduce a validation result which is a subset of the `PerseusScore`, but since we use it all over the validation code, it seemed useful to create a type for it. 
`yarn test`
=> SSS: Introduce ValidationResult type so things are standardized

.changeset/spicy-cups-join.md, packages/perseus/src/__testdata__/renderer.testdata.ts, packages/perseus/src/__tests__/perseus-markdown.test.ts, packages/perseus/src/__tests__/renderer.test.tsx
The `input-number` widget is deprecated and was causing issues in the work I'm doing for validation and SSS. Swapping them out for the `numeric-input` so that I have a path forward. 
`yarn test`
=> Swap out deprecated input-number with numeric-input in some tests

.changeset/quiet-adults-look.md, packages/perseus/src/__testdata__/renderer.testdata.ts, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/renderer-util.ts, packages/perseus/src/types.ts, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets.ts, packages/perseus/src/widgets/categorizer/categorizer.tsx, packages/perseus/src/widgets/dropdown/dropdown.tsx, packages/perseus/src/widgets/expression/expression.tsx, packages/perseus/src/widgets/group/group.testdata.ts, packages/perseus/src/widgets/group/group.tsx, packages/perseus/src/widgets/group/validate-group.ts, packages/perseus/src/widgets/matrix/matrix.tsx, packages/perseus/src/widgets/number-line/number-line.tsx, packages/perseus/src/widgets/orderer/orderer.tsx, packages/perseus/src/widgets/plotter/plotter.tsx, packages/perseus/src/widgets/radio/radio.ts, packages/perseus/src/widgets/sorter/sorter.tsx, packages/perseus/src/widgets/table/table.tsx
This PR begins connecting the validation functions that have been built to the existing `emptyWidgets()` function that already exists on the `Renderer` (as well as `emptyWidgesFunctional()`). This function powers the `APIOptions.answerableCallback` which is what the exercise chrome using Perseus uses to detect if a question is at a point where it can be scored. 
Note that some widget's "emptiness" checks depend on scoring data and so those checks are not included in the empty checking now. 
yarn test
yarn typecheck
=> SSS: Hook emptyWidgets() up to validation functions

.changeset/slow-rules-unite.md, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx
Moving the Polygon component lower in the stack to ensure the rect component is on top. This is necessary to allow users to draw a polygon that is concaved, because the Polyline blocks the click events.
https://github.com/user-attachments/assets/181a987f-c0a2-4ff9-bc08-cbf57df44fe9
Issue: LEMS-2679
Go to: http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--unlimited-polygon-with-mafs.
Draw a polygon that is concave and notice it should allow you to draw it.
=> [Unlimited Polygon] Fix for creating concave polygons.

.changeset/rare-bobcats-type.md, dev/gallery.tsx, packages/perseus-editor/src/components/widget-editor.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/labeled-switch.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-figures-section.tsx, packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap, packages/perseus/src/util/react-render.tsx, packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap, packages/perseus/src/widgets/dropdown/dropdown.tsx, packages/perseus/src/widgets/explanation/__snapshots__/explanation.test.ts.snap, packages/perseus/src/widgets/explanation/explanation.tsx, packages/perseus/src/widgets/label-image/answer-pill.tsx, packages/perseus/src/widgets/label-image/hide-answers-toggle.tsx
This migrates Perseus off the deprecated ID APIs and onto the `useId`-based approach.
The lint rules remain in place until Wonder Blocks is released without the old APIs and Perseus has been updated to that version of Wonder Blocks. This won't happen until webapp has been migrated off the old APIs.
Issue: WB-1812
`yarn lint`
`yarn test`
=> Migrate off deprecated ID APIs

packages/perseus/src/widgets/numeric-input/score-numeric-input.test.ts
RendererUtil: remove unnecessary cast to UserInput
=> Add test to document empty expression can be a correct answer

.changeset/shiny-houses-promise.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx
- Update the variable names to start with `sr` prefix.
- Use `srFormatNumber()` to make sure the numbers are
formatted correctly.
- Update the coordinate types to `string` in the strings
instead of `number` since they are now using
`srFormatNumber()` (which returns a string)
Issue: https://khanacademy.atlassian.net/browse/LEMS-1706
`yarn jest`
- Go to http://localhost:6006/iframe.html?globals=&args=&id=perseuseditor-widgets-interactive-graph--interactive-graph-circle&viewMode=story
- Confirm nothing has changed from before
=> [SR] Minor improvements to Circle graph SR strings

.changeset/wet-bugs-sip.md, packages/perseus/src/widgets/interactive-graphs/interactive-graph.stories.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts
Refining scoring behavior for unlimited point to ensure it treats an empty graph as unscorable.
Issue: LEMS-2682
Go to http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--point-with-mafs
Add a bunch of points and remove them until there is none left.
Check your answer and notice the score is defined as `invalid`.
=> Fixing scoring for unlimited point to ensure there 1 or more points for it to be considered scorable.

.changeset/fifty-laws-hear.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/cs-program/cs-program.tsx
This removes an unused rubric type. The iframe tells the widget if the user's input is correct or not, so a rubric is not needed.
Additionally, validation happens after scoring, so it won't be possible to create a validation function for this widget at this time either.
Issue: LEMS-2440
- Confirm widget still works as expected via a ZND (CS Program works via iFrame, which tens not to be testable locally)
=> Remove unused rubric type for CS Program

.changeset/quick-apes-crash.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx
Add the full graph aria label and description for Linear graphs, based on the [SRUX doc](https://khanacademy.atlassian.net/wiki/spaces/LC/pages/3460366348/Linear).
This includes four different cases for the slope description, and
four different cases for the intercepts.
- increasing slope
- decreasing slope
- horizontal slope
- vertical slope
- origin intercept
- different x and y intercepts
- only x intercept
- only y intercept
Upcoming in a separate PR:
- focus, aria label, and aria live management for the movable middle part between the two points on the line
Issue: https://khanacademy.atlassian.net/browse/LEMS-1726
`yarn jest packages/perseus/src/widgets/interactive-graphs/graphs/linear.test.tsx`
Storybook
- http://localhost:6006/iframe.html?id=perseuseditor-widgets-interactive-graph-- …
=> [SR] Linear graph - add full graph aria label and description

.changeset/soft-lizards-lie.md, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.tsx, packages/perseus/src/widget-ai-utils/interactive-graph/interactive-graph-ai-utils.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
Right now, the x and y labels when an interactive graph is
first created show up as text. They should be showing up as
text.
- Add `$` around the "x" and "y" to make them show up as TeX
Issue: none
`yarn jest packages/perseus/src/widget-ai-utils/interactive-graph/interactive-graph-ai-utils.test.ts`
`yarn jest packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.test.tsx`
Before
After
=> [Interactive Graph][Axis labels] Make default x & y axis labels TeX on load

.changeset/nine-planes-relax.md, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/group/score-group.ts, packages/perseus/src/widgets/matcher/score-matcher.test.ts, packages/perseus/src/widgets/matrix/score-matrix.ts, packages/perseus/src/widgets/orderer/score-orderer.ts
Noticed some discrepanies in naming relating to calling the validation function and also noticed some scoring types still reference their widgetOptions. The scoring types for the group widgets still references widgetOptions, but here I updated the scoring type for Matcher to be more specific to what is actually used.
Issue: LEMS-2734
- Will do more manual testing after merging to the feature branch
=> Fix some naming discrepancies and simplify Matcher scoring type

.changeset/fluffy-needles-leave.md
In order to verify our existing release protection, that prevents snapshot releases from releasing non-snapshot versions, and to verify the additional workflow change in #2044 that should fail the snapshot release if a main release is in progress, we need a new release to kick off.
This PR bumps a patch version to make that happen.
1. [THIS PR] ~Audit a version bump and land that~
2. Wait for the Version Packages PR to be ready
3. Merge Version Packages
4. Immediately update my two PRs (#2039 and #2044) to match main and kickstart their actions
- `git pull && git merge --no-edit origin/main && git push && git switch snapshotsvsrelease.2 && git merge --no-edit origin/main && git push`
5. See what happens. With the fix, the script should error on …
=> [🔥AUDIT🔥] docs(changeset): Version bump to verify release protections

.changeset/red-bugs-build.md, packages/perseus-editor/src/widgets/__tests__/expression-editor.test.tsx, packages/perseus-editor/src/widgets/expression-editor.tsx
- Converts expression editor keys to strings
- Updates `onDelete` handler to use index instead of key
Issue: LEMS-2738
https://github.com/user-attachments/assets/60424f5a-f654-4afc-901f-de47505e053c
=> fix(LEMS-2738): Convert Expression Editor Answer keys to strings

.changeset/few-rings-cover.md, docs/architecture.md, packages/perseus/src/__tests__/validation.typetest.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/validation.types.ts, packages/perseus/src/widgets/group/group.tsx
This PR begins working out the types for Scoring, Validation, and how they relate to our full widget options types. There are currently three "trees" of types that are shaped as a map of `widgetId` to something. They are: 
* Full widget options (starting from `PerseusRenderer`)
* Scoring data - used to score the learner's guess (user input)
* Validation data - a shared subset (of Render and Scoring data) used to do empty widget checking (aka validation). This helps the frontend to know if the question is scorable yet. 
Finally, there is also a widget map known as User Input. This map is a map of widget ids from the item to the user input the learner has entered so far. 
`yarn typecheck` (especially, the new `validation.typetest.ts` file!)
`yarn test` (just to be sure)
=> SSS: Improve types for validation

.changeset/config.json
I recently updated our Changesets config to auto-commit the `.md` file when using `yarn changset` to describe a set of changes. This broke our releases as the default behaviour is that Changesets adds `[skip ci]` to the commit created when running `yarn changesets version`. No CI on that PR/commit, meant that none of our release Github Actions ran!
So this PR fixes the config so that Changesets no longer adds `[skip ci]` to any commits, but still auto-commits them. 
* Wonder-Blocks: https://github.com/Khan/wonder-blocks/pull/2409
* Wonder-Stuff: https://github.com/Khan/wonder-stuff/pull/1100
* Perseus: https://github.com/Khan/perseus/pull/2052 (this PR!)
Issue: "none"
Land this PR
Merge `main` into an open Version Packages PR
Land that PR and ensure the release goes out
=> Update changesets' auto-commit feature to not suppress CI on commits

.changeset/happy-mugs-yell.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/angle.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
Updates terminology for angle graph - changes Initial and Terminal to Starting and Ending 
Issue: LEMS-2745
=> fix(LEMS-2745): update terminology for angle graphs

.changeset/hot-eels-arrive.md, packages/perseus/src/strings.ts
After our migration to Lingui (which included a new approach to loading in the Perseus strings in the `extract-perseus-strings.tsx` file), it was discovered that we now need to ensure that we always double escape our tex. 
This is a simple PR that adds these double escapes, and a comment for our future selves. 
Issue: LEMS-2746
- manual testing locally and on a znd
=> Bugfix - Ensure that all strings are double escaped.

.changeset/twenty-cats-invent.md, packages/perseus/src/__tests__/__snapshots__/renderer.test.tsx.snap, packages/perseus/src/styles/perseus-renderer.less, packages/perseus/src/widgets/dropdown/__snapshots__/dropdown.test.ts.snap, packages/perseus/src/widgets/dropdown/dropdown.tsx
With the recent change in how dropdown content is rendered, the use of the `<Renderer>` component brought along styling that is overly broad and caused text to be enlarged and shifted up. This bugfix adds styling that targets only instances of renderer styling within a dropdown.
Issue: LEMS-2742
1. Open any article that contains dropdown widgets, like this one in [Test Everything](https://www.khanacademy.org/internal-courses/test-everything/test-everything-1/te-dropdown/a/dropdown-with-labels).
(Note: this issue is only present in Articles - exercises are unaffected by this bug)
2. Dropdown answers and placeholders should appear centered within the border of the dropdown.
=> [Dropdown] Bugfix - Text in dropdown was shifted up after adding TeX support via Renderer

.changeset/many-cats-run.md, packages/perseus/src/util/parse-perseus-json/general-purpose-parsers/discriminated-union.test.ts, packages/perseus/src/util/parse-perseus-json/general-purpose-parsers/discriminated-union.ts, packages/perseus/src/util/parse-perseus-json/general-purpose-parsers/discriminated-union.typetest.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/grapher-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/interaction-widget.ts
Previously, the `discriminatedUnion` parser required you to specify the
discriminant via an object parser, which was confusing and verbose. Now you only
have to specify the discriminant key once, and provide the values for each
branch.
Issue: LEMS-2582
`yarn test`
=> Redesign discriminated union type parser

.changeset/chilled-lizards-rush.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/interactive-graph-editor.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-figure-select.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-figure-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-figures-section.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph.stories.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Remove the `interactive-graph-locked-feature-label` flag from the Perseus
repo now that the full graph aria label/description and standalone locked
labels have been out for a while now.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2274
`yarn jest`
=> Remove interactive-graph-locked-features-labels flag

.changeset/kind-jeans-move.md, packages/perseus/src/strings.ts
There's a larger issue related to TeX commands (specifically `\\text{}`) in our Perseus strings. While we investigate this issue, I've proposed that we simply remove these calls from our strings. 
As a result, these string will no longer match translations, but that is preferable as a temporary solution to the current issues with broken rendering. Given that these will no longer match translations any way, I've removed the `<code>` tag from one of the strings to closer match the second one. The use of the code tag here was unnecessary.
While the TeX commands will likely need a fix, I believe it would be good to permanently remove the `\\text` commands from these strings, and to simply request new translations for them. 
- manually tested in webapp for both strings
=> Temporarily fixing pi-based strings for Numeric Input

.changeset/soft-rocks-breathe.md, packages/perseus/src/strings.ts
Updates the interactive graph perseus strings - removes the object, context and message properties. Keeps strings
`yarn test`
=> remove object, context property and message property from perseus strings

.changeset/weak-geese-joke.md, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-ellipse-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts
Right now, the speech rule engine is not being used to generate
the the aria labels for negative coordinates when pressing the
"auto-generate" button for Interactive Graph locked figures in
the editor.
This means that the coordinates are read as "minus [coord]"
rather than "negative [coord]"
To fix this, I'm calling the speech rule engine on the
coordinates as well. And also the rotation on an ellipse.
Issue: none
`yarn jest packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-point-settings.test.tsx`
`yarn jest packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-line-settings.test.tsx`
`yarn jest packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-vector-settings.test.tsx` …
=> [Locked Figures Aria] Correct aria autogen for negative coords

.changeset/little-beds-tickle.md, packages/perseus/src/components/i18n-context.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx
Add the interactive Circle graph description to the full graph container.
This adds the "Interactive elements: Circle..." description to the outermost graph container.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1706
- Go to https://650db21c3f5d1b2f13c02952-iupnsmdbhn.chromatic.com/iframe.html?globals=&args=&id=perseuseditor-widgets-interactive-graph--interactive-graph-circle&viewMode=story
- Use a screen reader to get to the outermost graph container
- Confirm that it has the circle description after "Interactive elements:"
=> [SR] Circle - Add the interactive elements circle description to the whole graph container

.changeset/chilly-experts-juggle.md, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.tsx
Now that we're using `a11y.srOnly` styling for the hidden
aria descriptions, we don't need to use `textContent`, we
can just use `innerText`.
We also don't need the test for hidden content.
Issue: none
`yarn jest packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.test.tsx`
=> [SR][SR Tree] Update tree to use innerText

.changeset/hot-cougars-laugh.md, packages/perseus-core/src/data-schema.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/cs-program-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/grapher-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/iframe-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/interaction-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/measurer-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/plotter-widget.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/widgets-map.test.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/widgets-map.ts, packages/perseus/src/util/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-snapshot.test.ts.snap, packages/perseus/src/util/parse-perseus-json/regression-tests/data/cs-program-with-null-width.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/iframe-missing-allowFullScreen.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/iframe-missing-settings.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/interaction-element-missing-key.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/interactive-graph-locked-line-missing-showPoint1.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/measurer-missing-image.json, packages/perseus/src/util/parse-perseus-json/regression-tests/data/plotter-missing-scaleY-and-snapsPerLine.json, packages/perseus/src/widget-ai-utils/cs-program/cs-program-ai-utils.test.ts, packages/perseus/src/widgets/cs-program/cs-program.testdata.ts, packages/perseus/src/widgets/grapher/score-grapher.test.ts, packages/perseus/src/widgets/grapher/score-grapher.ts
This PR fixes the remaining cases where the parser couldn't handle some data in
our content corpus -- notably, in articles and international content. After this
PR is merged, we will be able to use the parser in Webapp!
Note that running the exhaustive test tool still produces some failures.
However, I suspect the failing content isn't published, because it either
doesn't render (crashes the page) or can't be scored (throws an exception when
you click the "check answer" button). We'll find out when we start logging
parser errors in production whether I'm right about this.
The remaining errors are:
```
(root).question.widgets["grapher N"].options.correct.coords -- expected array of length 2; got []
(root).question.widgets["matcher N"].options -- expected object; got undefined …
```
=> Enable parsePerseusItem to handle all published Perseus content

.changeset/strange-buses-run.md, packages/perseus/src/index.ts, packages/perseus/src/util/parse-perseus-json/index.ts, packages/perseus/src/util/parse-perseus-json/parse-perseus-json.test.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/perseus-article.ts, packages/perseus/src/util/parse-perseus-json/perseus-parsers/perseus-image-background.ts, packages/perseus/src/util/parse-perseus-json/regression-tests/parse-perseus-json-regression.test.ts, packages/perseus/src/util/parse-perseus-json/regression-tests/parse-perseus-json-snapshot.test.ts
This is the public API for Perseus JSON parsing that we'll call in Webapp.
See [ADR 773][1] for context on why this is needed.
[1]: https://khanacademy.atlassian.net/wiki/spaces/ENG/pages/3318349891/ADR+773+Validate+widget+data+on+input+in+Perseus
Issue: https://khanacademy.atlassian.net/browse/LEMS-2774
`yarn test`
=> Export Item and Article parsing functions from the 'perseus' package

.changeset/cool-shrimps-grin.md, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.tsx
By changing the text getting to `innerText` insted of
`textContent`, we actually stopped displaying the
descriptions.
Go back to using `textContent` so the descriptions
display again.
Issue: none
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-linear
- check that the screen reader tree shows all the
linear graph descriptions
| --- | --- |
| ![Screenshot 2025-01-13 at 10 12 52 AM](https://github.com/user-attachments/assets/5d6f9ce7-f692-4225-bb94-e748db867f2e) | ![Screenshot 2025-01-13 at 10 16 24 AM](https://github.com/user-attachments/assets/80528e07-84fb-4262-bcfb-936f21deb501) |
=> [SR][SR Tree] Show the descriptions again

.changeset/three-hats-melt.md, packages/perseus/src/widgets/graded-group/graded-group.tsx
In https://github.com/Khan/perseus/pull/2086 I started moving things into `perseus-score` which will not have access to translated strings. Instead we'll be returning error codes that can map to translated error messages. So far, I've only done this for KhanAnswerTypes so it's still an edge-case, but I found a place where we use error messages in https://github.com/Khan/perseus/pull/2102
=> Fix graded-group error message bug

.changeset/new-tomatoes-fly.md, packages/perseus/src/util/parse-perseus-json/exhaustive-test-tool/index.ts
This will help us find data issues where article content contains invalid or
strangely-shaped Perseus data.
Issue: LEMS-2582
Run the exhaustive test tool on a content snapshot that includes articles.
You should get 14 errors:
```
(root).question.widgets["interactive-graph N"].options.lockedFigures[N].size -- expected "small", "medium", "large"; got undefined
(root).question.widgets["grapher N"].options.correct.coords -- expected array; got null
(root).question.widgets["explanation N"][N] -- expected numeric string; got string
(root).question.widgets["image N"][N] -- expected numeric string; got string
(root).question.widgets["interactive-graph N"].options.lockedFigures[N].text -- expected string; got undefined
(root).question.widgets["interaction N"].options.elements[N].key -- expected …
```
=> Enable the exhaustive test tool for parsePerseusItem to test articles.

.changeset/slimy-scissors-smash.md, packages/perseus-editor/src/__tests__/editor.test.tsx, packages/perseus-editor/src/editor.tsx
WidgetOptions has a `key` field (which appears to be unused, but that's
a different discussion) which is often not present in the JSON data.
This field, when absent from the JSON, was getting set to `undefined` by
`parseAndMigratePerseusItem()`. The `undefined` value then overrode the
`key` prop which we intended to set on the WidgetEditor component, which
caused React to log an error about non-unique keys.
I've changed the order of the props so the keys we want to set
explicitly will override any fields parsed out of the widget JSON. This
is what we want anyway, since the JSON might contain absolutely
anything, and we don't want it to be able to set arbitrary editor props.
I discovered this bug while hooking up `parseAndMigratePerseusItem` in
webapp …
=> Fix a React warning about non-unique component keys in the editor

.changeset/happy-pets-breathe.md, packages/perseus/src/util/parse-perseus-json/general-purpose-parsers/object.test.ts, packages/perseus/src/util/parse-perseus-json/general-purpose-parsers/object.ts, packages/perseus/src/util/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-snapshot.test.ts.snap
Previously, when parsing typed objects from JSON, we would add
`[key]: undefined` for any fields that were specified in the parser schema but
were absent from the JSON. This was a difference from the behavior of
`JSON.parse()` that could cause bugs in some cases (e.g. if a parsed
object was spread into another object, it could overwrite existing
values with `undefined` when that was not intended).
Thus, to better match the behavior of `JSON.parse()`, we now omit
`undefined` values from the parsed object if they are not present on the
original object.
This PR was inspired by test failures on https://github.com/Khan/webapp/pull/28551.
I'm making this change out of an abundance of caution.
Issue: LEMS-2774
Test plan:
`yarn test`
=> Don't add undefined values to objects when parsing JSON

.changeset/friendly-tables-confess.md, packages/perseus/src/strings.ts
Our localization infrastructure requires that the names of the placeholders in the `strings` variable (the object with the English strings) matches the variable names in the same-named string generator function that appears in the `PerseusStrings` type.
This PR fixes two new strings so that their placeholder variable names match: `srRayEndpoint` and `srRayTerminalPoint`.
Issue: "none"
Do another release and integrate it again and rerun the localization script.
=> [🔥AUDIT🔥] Align variable names in SR strings for interactive graph

.changeset/eight-squids-repair.md, packages/perseus-core/src/data-schema.ts, packages/perseus/src/__testdata__/renderer.testdata.ts, packages/perseus/src/__testdata__/server-item-renderer.testdata.ts, packages/perseus/src/__tests__/renderer-api.test.tsx, packages/perseus/src/types.ts, packages/perseus/src/widget-ai-utils/mock-widget/mock-widget.test.ts, packages/perseus/src/widget-ai-utils/mock-widget/prompt-utils.test.ts, packages/perseus/src/widget-ai-utils/mock-widget/prompt-utils.ts, packages/perseus/src/widgets/mock-widgets/mock-widget-types.ts, packages/perseus/src/widgets/mock-widgets/mock-widget.tsx, packages/perseus/src/widgets/mock-widgets/score-mock-widget.ts, packages/perseus/src/widgets/mock-widgets/validate-mock-widget.test.ts, packages/perseus/src/widgets/mock-widgets/validate-mock-widget.ts
I recently merged `main` and the introduction of `MockWidget` caused some tests to break. I've fixed them in this PR and adjusted the MockWidget to be simpler (ie. not use KhanAnswerTypes) as I don't _think_ that's needed.
I also fixed up some related types so that the MockWidget does not exist in our production Widget types, only in tests. The new `MockWidget` illustrates this "test-only" expansion of the widget types.
`yarn test`
=> [Client Validation] Fixes after merging main

.changeset/cool-cherries-vanish.md, packages/perseus-core/src/index.ts
As we've moved Perseus logic around, we moved `addWidget` into `perseus-core`. However, we didn't export it from the package. This function is used by hosting applications and needs to be exported. 
Issue: "none"
Update host app and update import to import the function from `"@khanacademy/perseus-core"`.
=> Re-export widget id support function: addWidget

.changeset/wise-insects-occur.md, packages/perseus/src/strings.test.ts, packages/perseus/src/strings.ts, packages/perseus/src/widgets/graded-group/graded-group.tsx
Proposing a bug fix for error messages not showing up as translated: https://khanacademy.slack.com/archives/C06FULVQLSV/p1738014199191129?thread_ts=1738012970.693379&cid=C06FULVQLSV
**What I thought we were doing:** Originally I thought `strings` were getting replaced during the translation process (I don't know why I thought that). So we were mapping error codes to error strings directly off of `strings`.
**What we were actually doing:** `strings` isn't actually changed, it's used to make a new object that has all of the translated strings in it. So we were pulling the English strings off of the base object that was used to create a separate translated object.
**What this PR does:** instead of pulling from `strings`, we instead pass the translated strings into `mapErrorToString`. Then we …
=> Bugfix: error messages aren't displayed as translated strings

.changeset/six-cars-agree.md, packages/perseus-editor/src/__stories__/editor.stories.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.stories.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.testdata.ts, testing/renderer-with-debug-ui.tsx, testing/server-item-renderer-with-debug-ui.tsx, testing/side-by-side.tsx, testing/split-view.tsx
This PR is part of the Numeric Input Project. 
The purpose of this PR is to improve our storybook setup for our Numeric Input Widget. This includes the following work:
- Modernizing story structure 
- Hooking up argTypes with descriptions 
- Updating RendererWithDebugUI to also set customKeypad to the same value as isMobile 
- This allows us to ensure that our Widgets that use MathInput are properly updating when toggled into Mobile view
- Adjustments to SideBySide 
- Automatically collapse the Perseus JSON view. 
- Moved the PerseusJSON view below the Renderer View
- Rename to SplitView to better encapsulate the new design 
- Updated variable names to match
[Current (Live) Storybook Example](https://khan.github.io/perseus/?path=/docs/perseus-widgets-numericinput--docs) | [PR Storybook …
=> [its-a-numeric-story] Improving Numeric Input Storybook Stories

.changeset/rotten-kangaroos-fly.md, packages/perseus/src/widgets/numeric-input/__snapshots__/numeric-input.test.ts.snap, packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.test.ts, packages/perseus/src/widgets/numeric-input/numeric-input.testdata.ts
This PR is part of the Numeric Input Project. 
This is a bug fix that ensures that the Examples Tooltip for the Numeric Input widget only displays examples from the _correct_ answers. 
Issue: LEMS-2803
- Run tests 
- Creation of new snapshot test that verifies wrong answerFormats are not being provided.
=> Ensure that Numeric Input Examples only show for correct answers.

.changeset/poor-masks-return.md, packages/perseus/src/index.ts
They have been moved to `perseus-core`.
Issue: none
Test plan:
CI should be green.
=> Remove deprecated exports from the `perseus` package

.changeset/forty-meals-teach.md, packages/perseus-core/src/index.ts, packages/perseus-core/src/widgets/label-image/label-image-util.test.ts, packages/perseus-core/src/widgets/label-image/label-image-util.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/label-image/label-image.tsx
=> Create a function to get the public options for LabelImage

.changeset/curly-bikes-nail.md, packages/kmath/package.json
While working on some automation, I noticed that this package still points to its old repository (before we moved everything into this monorepo)
Issue: "none"
Review the change. Hpoe it's correct!
=> Fix 'repository' field in kmath's package.json

.changeset/honest-parents-press.md, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.tsx, packages/perseus/src/components/__tests__/number-input.test.tsx, packages/perseus/src/components/number-input.tsx, packages/perseus/src/components/range-input.tsx, packages/perseus/src/util/math-utils.test.ts, packages/perseus/src/util/math-utils.ts, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.test.ts, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-regression.stories.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts
Currently, if a graph has tick labels that are multiples of pi,
such as in a sinusoid graph, content authors have to set the
graph markings to "none" and load in a graphie background image
that has the graph with the desired tick markings.
This is not only inconvenient for content authors, it also means
that the screen reader will not read the correct coordinates for
these interactive graphs. It might say "2" when it should be
saying "2 pi."
Implementing a fix for this to improve the lives of our content
authors and our screen reader users.
- Editor
- Check if the value loaded into NumberInput is a multiple
of pi, and not already written in the "pi" format.
- If so, and if the `allowPiTrunacation` prop is true,
divide this number by pi and append "π" to the value.
- This will make it so …
=> [editor-pi] [Interactive Graph] Support tick labels that are multiples of pi

.changeset/dry-fans-study.md, packages/perseus-core/src/index.ts, packages/perseus-core/src/widgets/grapher/index.ts, packages/perseus-editor/src/widgets/grapher-editor.tsx, packages/perseus/src/widgets/grapher/util.tsx
This is an alternative for: https://github.com/Khan/perseus/pull/2146
In #2146 I tried to a direct move of logic from `perseus` to `perseus-core` to get the default widget options for Grapher. That required `defaultPlotProps` which required `maybePointsFromNormalized` which eventually required `kmath`. It was gross for a number of reasons:
1. I had to move a lot of utilities
2. I had to give `perseus-core` a dependency on `kmath` (and `perseus-core` probably shouldn't have dependencies)
3. There was a lot of misdirection and logic all to make one static object
Whatever, I was okay hacking my way through that. _However_ we ended up with a circular dependency: `kmath` depends on `perseus-core` which was now depending on `kmath`.
At this point I reflected on my life choices and thought "why …
=> Take 2: Grapher default widget options

utils/clean.sh
We've had instances where folks' local repo gets into a bad state. It's assumed that `yarn clean` will resolve this, but it hasn't in all cases because it doesn't delete `node_modules`.
This PR adds a `--all` option to `yarn clean` to demolish all `node_modules` folders in the local repo.
Issue: "none" 
`yarn`
`yarn clean`
`ls node_modules` # still exists
`yarn clean --all`
`find . -name node_modules -and -type d` # no results!
=> Add -all option to 'yarn clean' 

.changeset/great-cameras-play.md, .changeset/poor-masks-return.md, packages/perseus/src/index.ts
The removal of these functions was causing problems for people who wanted to
use a dev build of Perseus in webapp, because webapp is still importing them.
We need to update webapp to import these functions from perseus-core instead,
and then we can remove them from perseus.
Issue: none
`yarn test`
=> Restore deprecated exports of `@khanacademy/perseus`

.changeset/nasty-rockets-end.md, packages/perseus-core/src/index.ts, packages/perseus-core/src/widgets/cs-program/cs-program-util.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/cs-program/cs-program.tsx
CSProgram doesn't have any private options, so this is just the identity
function.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2770
`yarn test`
=> Add a function to get the public options for a cs-program widget

.changeset/pink-buttons-clap.md, packages/perseus-score/src/util/tex-wrangler.test.ts, packages/perseus-score/src/util/tex-wrangler.ts
Third time's the charm on this one. This ticket is part of the Numeric Input project. 
Numeric Input has different experiences on Desktop versus Mobile: 
1. Desktop allows users to enter basic math commands using their regular keyboard. Desktop does not display / visually support TeX, but CAN parse it as an answer. 
2. Mobile allows users to enter basic math commands using a keypad that crafts TeX to display the output using MathQuill  / Math Input. 
This diverged experience resulted in the possibility to hit an infinite loop on Desktop if the user tries to hand type `\frac` or `\dfrac` TeX commands , as the parser was unable to locate the next symbols to parse. This has likely been a bug since inception, but has become far more noticeable as we're now parsing answers on the fly to …
=> [3-quell-the-fracus] [Bug Fix] - Ensure that users hand typing tex into Numeric Inputs on Desktop do not cause an infinite loop.

.changeset/twenty-pianos-impress.md, .eslintrc.js, package.json, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.tsx, yarn.lock
This work is part of the implementation of [ADR#781 Enabling more lint rules for accessibility](https://khanacademy.atlassian.net/wiki/x/IoBVyg)
These changes includes:
- Updated dev dependency: `@khanacademy/eslint-config`
- Extending `@khanacademy/eslint-config/a11y` config in project's eslint config
- Currently, the a11y config enables the `aphrodite-add-style-variable-name` rule from `@khanacademy/eslint-plugin`. This is the first step to adding more a11y linting rules so that the naming convention for html elements is more predictable for [custom component mapping](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y#component-mapping) for `eslint-plugin-jsx-a11y` (see [rule docs](https://github.com/Khan/wonder-stuff/blob/main/packages/eslint-plugin-khan/docs/aphrodite-add-style-varia …
=> Extend initial a11y config for eslint

.changeset/eighty-bananas-sell.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/utils.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Add the aria labels and descriptions for the full graph and interactive elements in the Unlimited Polygon graph, based on the [SRUX doc](https://khanacademy.atlassian.net/wiki/spaces/LC/pages/3455713294/Unlimited+Polygon).
Issue: https://khanacademy.atlassian.net/browse/LEMS-2487
`packages/perseus/src/widgets/interactive-graphs/graphs/polygon.test.tsx`
Storybook
http://localhost:6006/iframe.html?globals=&args=&id=perseuseditor-widgets-interactive-graph--interactive-graph-unlimited-polygon&viewMode=story
=> [SR] Polygon (unlimited) - Add screen reader experience

.changeset/warm-olives-greet.md, packages/perseus/src/strings.ts
Two segment strings are missing the word "at"
Fixing them here.
Issue: none
N/A - will have to confirm on the webapp PR.
=> [SR] Segment - fix 2 strings with typos

.changeset/chilled-mugs-greet.md, packages/perseus-score/src/util/answer-types.ts, packages/perseus-score/src/widgets/numeric-input/score-numeric-input.test.ts
This PR is part of the Numeric Input project. 
This small addition ensures that users cannot be marked correctly for entering whole numbers when required to enter Improper fractions. 
Issue: LEMS-2802
- Tests pass 
- Creation of two new tests to ensure bug fix works, and there's no regressions for tex
=> [whole-fraction-fix] Ensure that whole numbers are not accepted answers for Numeric Inputs that require Improper fractions.

.changeset/soft-onions-dream.md, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-correct-answer.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/interactive-graph-editor.tsx
Right now, the SR Tree just gets the first mafs-graph container on the page and renders its SR content.
However, this does not work if there are also hint editors on the page. The hints will just show the
SR content for the first graph instead of reflecting their respective graph.
To fix this, I added a unique ID to the editor and passed that into the graph container and the SR Tree.
And SR Tree now finds by this unique ID rather than just the first graph on the page.
Issue: none
`yarn jest packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.test.tsx`
Storybook
- Go to http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-ray
- Click "Add a hint" at the bottom
- Copy the interactive graph question
- …
=> [SR Tree] Handle SR Tree when multiple editors are on the page

.changeset/funny-jeans-bake.md, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
When using a screen reader in the interactive graph widget, it would read
an empty image after the axis labels. This is bad practice, as it can be
confusing to screen reader users to hear random elements with no context.
To remove this, I had to wrap the Mafs graph in a `View` and add the
`aria-hidden` property, but only when the graph doesn't have locked figures.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2721
Storybook
- On Chrome or Firefox, go to http://localhost:6006/iframe.html?globals=&args=&id=perseuseditor-widgets-interactive-graph--interactive-graph-segment&viewMode=story
- Use a screen reader to go through an interactive graph
- Note that after reading "x, math" and "y, math" (the axis labels), it does NOT read an empty image.
- On Chrome or Firefox, go to …
=> [SR] Stop graph from exposing random empty image to screen readers

.changeset/slow-shoes-march.md, packages/perseus-core/src/data-schema.ts, packages/perseus-score/src/widgets/interactive-graph/score-interactive-graph.test.ts, packages/perseus-score/src/widgets/interactive-graph/score-interactive-graph.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts
This PR is part of the Interactive Graph project. 
It contains the work required to move the coordinate reversal logic from the `getGradeableGraph` function and move it directly into our scoring logic. This logic was initially left in `getGradeableGraph` while we waited for the legacy Angle graph to no longer be in use. 
The reason for this was that there were 2 conflicting bugs in the Angle graph previously:
1.  Bug 1 allowed graphs to be reflexive if the bottom coordinate was moved, even if `allowReflexiveAngles` was false.
2. Bug 2 failed to properly reverse the coordinates in the same situation, resulting in the answer being marked as incorrect. 
Unfortunately, the combination of these bugs meant that we we needed to keep the scoring logic unchanged until the feature flags for the new …
=> [LEMS-2190] Move coord reverse logic into scoring logic

.changeset/shiny-elephants-allow.md, packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
This PR is part of the Interactive Graph Project.
While recreating LEMS-2551, it was discovered that focus was not being set for mouse-based interaction. This PR fixes both that issue, and the issue from LEMS-2551 where deleting the points out of order would eventually result in a failure to move the focus to the next point.
https://github.com/user-attachments/assets/acf582ff-e564-4950-a997-204c01b75e5a
Issue: LEMS-2551
tests pass
=> [unlimited-focus] [Bug Fix] Ensure that Unlimited Graphs move focus properly when deleting points out of order.

.changeset/calm-cats-ring.md, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/point.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/ray.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
When getting the graphs' description strings via `renderGraphElements` in `mafs-graph.tsx`,
we're getting a component with a string with each component separately running the
Perseus i18n hook.
Instead, we can just gave `renderGraphElements` return a string, and we can pass down the
i18n info from the parent where the hook is called once.
This should be easier for people to follow when looking at the code in the future.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2800
`yarn jest` to run the specific graph tests (`[graphType].test.tsx`)
Storybook
- https://khan.github.io/perseus/?path=/docs/perseuseditor-widgets-interactive-graph--docs
- Check each graph's SR tree to confirm that the "Interactive elements: ..." text
is still correct.
=> [SR] Refactor - Update graphs to pass in i18n context

.changeset/pretty-spies-tan.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/use-control-point.tsx
Right now, we have hairlines showing when a user moves a point using a mouse, but the hairlines
don't show up when using keyboard.
Adding hairlines when the point is focused in this PR.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2308
`yarn jest packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-point
- Move the points around with mouse and confirm that that behavior has not changed - hairlines
should still be present.
- Tab to the points with keyboard and confirm that the hairlines now show up.
- Switch the graph to "none" markings, and confirm that the hairlines no longer show up.
| --- | --- |
| <img width="485" …
=> [LX] Add hairlines when point has focus

.changeset/calm-cats-ring.md, .changeset/neat-beds-smash.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/point.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/ray.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
This got missed when doing the angle SR work. We have to add the “interactive elements” description to the overall graph.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2839
`yarn jest packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx`
Storybook
- Go to http://localhost:6006/iframe.html?globals=&id=perseuseditor-widgets-interactive-graph--interactive-graph-angle&viewMode=story
- Confirm that the "Interactive elements: ..." section is there in the screen reader tree.
- Change the values of the correct graph and confirm that the SR tree updates to reflect them in the interactive elements.
=> [SR] Angle - Add the "interactive elements" overall graph description

.changeset/slimy-schools-brake.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-labels.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Right now if a person using a screen reader traverses through the graph, they hear "x, math" and "y, math" for the axis labels, or whatever the x and y labels are updated to by the content authors.
We need to add a description for this so people know what x and y are referring to.
- Added "X-axis" and "Y-axis" strings as `aria-label`s for the `AxisLabel` elements.
- This means that it reads the actual label as a child of this axis label group
- This is my preferred approach so that it already handles math speech wehen reading the
TeX label, and we don't have to manually use the speech rule engine again redundantly
Issue: https://khanacademy.atlassian.net/browse/LEMS-2844
`yarn jest packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx`
Storybook
- Go to any interactive graph …
=> [SR] Add aria-labels for x- and y-axis labels

.changeset/lazy-feet-return.md, packages/perseus/src/widget-type-utils.test.ts, packages/perseus/src/widget-type-utils.ts
Fixing the getWidgetSubTypeByWidgetId, to return null when a widget has no subtype.
Issue: LEMS-2809
`yarn test` and `yarn lint`. All tests should pass.
=> Fixing getWidgetSubTypeByWidgetId.

.changeset/spotty-humans-prove.md, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus/src/widgets/interactive-graph.tsx
There's a part in the interactive graph code where the equation string
getter function is called by a code that concatonates a string together
and uses that string as a function name to call.
For the sake of type safety and the wellbeing of our engineers, updating
this to a switch statement.
Issue: none
`yarn jest packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-editorpage--demo
=> [Interactive Graph] Replace string-based function call with switch statement

.changeset/tall-llamas-crash.md, packages/perseus-core/src/data-schema.ts, packages/perseus-core/src/parse-perseus-json/parse-perseus-json.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/hint.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/perseus-renderer.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/widgets-map.test.ts, packages/perseus-core/src/widgets/group/index.ts, packages/perseus-editor/src/__tests__/traversal.test.ts, packages/perseus-editor/src/widgets/group-editor.tsx, packages/perseus/src/types.ts
We aren't using `metadata`. As near as I can tell, [it was added in 2014][1] so content
creators could add "tags" to content, but I don't know why it was added or if it was
ever used.
We are seeing Perseus JSON parser errors in webapp because `metadata` is null in some
exercises. This PR fixes the errors by changing the type of `metadata` to `any`, marking
it deprecated, and removing references to it.
[1]: https://phabricator.khanacademy.org/D13929
Issue: none
- Install the build of Perseus from this PR
- Visit https://www.khanacademy.dev/internal-courses/test-everything/test-everything-1/te-group/a/group-article
- You should be able to view and edit the article without errors.
=> Deprecate `metadata` in renderer, hint, and Group widget data schemas

.github/workflows/node-ci.yml
When we migrated to pnpm, I thought i'd properly set up the Cypress install for CI (by caching `~/.cache/Cypress`). However, after landing that PR to `main`, I see that in some cases we can have a cache miss on that step but a cache hit on our `node_modules` folder. This leaves us with the Cypress npm package installed, but the Cypress binary missing.
This PR fixes it so that we ask Cypress to install, which will download the Cypres binary if it doesn't exist yet. 
Issue: LEMS-2825
Delete the Cypress cache in Github actions and then re-run the Cypress tests. They should pass and there should be a cache miss for the `~/.cache/Cypress` step but a hit for `node_modules`.
_UPDATE_: Confirmed the [test plan worked](https://github.com/Khan/perseus/actions/runs/13439890181/job/37551792130?pr=2260 …
=> Fix Cypress so it runs properly on Github Actions

.changeset/tricky-shoes-walk.md, packages/perseus-editor/src/index.ts
The ContentPreview component was created previously during our work to try to remove the iframe-based preview system. That work did not roll out, but access has been requested to this component for other work. As such, we are now exporting the component from the perseus-editor package.
Issue: LEMS-2886
- Confirm all tests and checks pass
=> Export the ContentPreview component from perseus-editor

.changeset/slimy-mirrors-sneeze.md, packages/perseus/src/widgets/interactive-graphs/graphs/circle.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
This PR is part of the Interactive Graph Project! 
The work in this PR ensures that users can move points across invalid locations for all graph types. This required updates to the following Interactive Graph types:
- Quadratic 
- Sinsoid
- Circle
- All Graphs that use Movable Line
- Segment
- Linear 
- Linear System
- Ray
NOTE: This PR does not change the functionality of the Polygon or Angle Graphs as I believe both have custom implementations that have already been implemented. 
Issue: LEMS-2014 
https://github.com/user-attachments/assets/317d5263-7fe9-450b-b2a9-8a5b19e17134
https://650db21c3f5d1b2f13c02952-ehxlgsxqwf.chromatic.com/
Issue: LEMS-2014
- All current tests pass
- New tests 
- Manual testing in Storybook
Author: SonicScrewdriver
Reviewers: SonicScrewdriver, nishasy, …
=> [i-like-to-move-it] Ensure that keyboard users can move points across invalid locations for all graphs. (#2264)

.changeset/empty-lobsters-wash.md, packages/perseus-core/src/utils/get-decimal-separator.test.ts, packages/perseus-core/src/utils/get-decimal-separator.ts
Marathi returns non-Arabic digits when using `Intl.NumberFormat(locale)`, which was resulting in our keypad typing the wrong character.
This has been fixed by adding the Devanagari digit to the match logic. I've run a local test with all of our supported languages to ensure no other languages are facing a similar issue.
I have also added some new tests for this function to help cover the main edge cases. I could be persuaded to add a list of the supported locales and expected outcomes, but that seemed like overkill and something that would be hard to keep "up to date" should the upstream standard change, or KA add more languages.
Issue: LEMS-2878
- Tests Pass
- New Tests
- Manual Testing
=> [mr-right] Fix issue related to Marathi Language in getDecimalSeparator

.changeset/smart-files-pump.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/circle.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
We're doing a final pass on strings now at the end of the phase 1
interactive graph screen reader work.
- Update the circle radius point’s label to “<Right/Left> radius endpoint at <coordinates>."
Issue: https://khanacademy.atlassian.net/browse/LEMS-2782
`yarn jest packages/perseus/src/widgets/interactive-graphs/graphs/circle.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-circle
=> [SR] Update Circle strings

.changeset/fair-humans-tie.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/linear.test.tsx
We're doing a final pass on strings now at the end of the phase 1
interactive graph screen reader work.
- Update the linear graph's grab handle to say it's going through
the points, rather than it being from one point to the other
(as that would make it a line segment instead).
Issue: https://khanacademy.atlassian.net/browse/LEMS-2782
`yarn jest packages/perseus/src/widgets/interactive-graphs/graphs/linear.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-linear
=> [SR] Update Linear strings

.changeset/clever-cameras-thank.md, packages/kmath/src/geometry.ts, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.test.tsx
We're doing a final pass on strings now at the end of the phase 1
interactive graph screen reader work.
- Linear system graph descriptions should include the point of intersection
between the two lines.
- Linear system lines' grab handle labels should have minimal line info
instead of just repeating the description.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2782
`yarn jest packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-linear-system
=> [SR] Update Linear System strings

.changeset/modern-ducks-cough.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
We're doing a final pass on strings now at the end of the phase 1
interactive graph screen reader work.
- Update the Sinusoid graph's extremum point string to convey whether
it's a minimum point, a maximum point, or straight line.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2782
`yarn jest packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx`
=> [SR] Update sinusoid strings

.changeset/sixty-singers-turn.md, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-sr-tree.tsx
It was a little unclear which graph the SR Tree was for.
Add a clarifying InfoTip explaning that it's for the
"correct answer" graph.
Issue: none
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-with-aria-label
=> [SR Tree] Add infotip with explanation about SR Tree

.changeset/flat-carrots-reply.md, packages/perseus-score/src/util/answer-types.test.ts, packages/perseus/src/components/simple-keypad-input.tsx, packages/perseus/src/components/text-input.tsx, packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap, packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap, packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap, packages/perseus/src/widgets/numeric-input/__snapshots__/numeric-input.test.ts.snap, packages/perseus/src/widgets/numeric-input/input-with-examples.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.stories.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.test.ts, packages/perseus/src/widgets/numeric-input/numeric-input.testdata.ts, packages/perseus/src/widgets/numeric-input/utils.test.ts, packages/perseus/src/widgets/numeric-input/utils.ts
This is a little PR that addresses some additional feedback points from the Numeric Input Refactor. 
This includes:
- Using useId() for generating ids in InputWithExamples 
- Removing underscores from InputWithExamples after it was converted to a functional component as part of the Numeric Input Refactor work. 
- Removing unnecessary constructors 
- Rename of `getTooltipContent` to `renderTooltipContent`
- Moving RenderProps to top of file for numeric-input.class.tsx 
- Removing unnecessary data from test data 
- Updating test name in utils.test.ts 
- Simplifying types from `NumericExampleStrings` after they were moved into the util file. 
- Commenting the reason for the `ariaLabel` setting to `undefined`.
- New tests in answer-types
- Tests Pass
- Manual testing in Storybook (Link to ZND …
=> [numeric-refactor-feedback-cleanup] Numeric Input Refector Feedback

.changeset/quick-dodos-warn.md, packages/kas/src/__tests__/comparing.test.ts, packages/kas/src/nodes.ts, packages/perseus-score/src/widgets/expression/score-expression.test.ts
See the ticket for the full break-down of the issue.
What I think was happening:
- KAS saw `f(2)`
- KAS looked for a variable, which it doesn't have (`f` is a function)
- KAS said "cool, I'll take a shortcut and just treat this as a number then"
- It tried to do math on `f(2)` like it was a Rational
I just removed the part of the code that was trying to take a shortcut.
Issue: LEMS-2777
- Added unit tests
- Repro steps for the UI are in the ticket
=> [LEMS-2777] Bugfix: KAS handling functions around plain numbers

.changeset/selfish-kangaroos-lie.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/hint.ts, packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap, packages/perseus-core/src/parse-perseus-json/regression-tests/item-data/hint-with-null-replace.json
This fixes a Perseus JSON parser error observed in production. `replace` is
null in some assessment items.
Issue: none
`yarn test`
=> Convert null to undefined in the `replace` field of hints

.changeset/beige-spoons-shave.md, packages/perseus-core/src/data-schema.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts, packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap, packages/perseus-core/src/parse-perseus-json/regression-tests/item-data/interactive-graph-locked-function-with-null-domain-element.json, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.test.ts, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/util.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-function.tsx
This fixes a Perseus JSON parser error observed in production. A null value for
in the JSON the upper or lower bound means infinity/unbounded, so we now convert nulls
to infinities during parsing. Note that the infinite values are converted back to
`null` when the JSON is serialized, so this preserves behavior.
Issue: none
`pnpm test`
Verify that locked functions with a domain of `[null, null]` display correctly
by running `pnpm storybook` and visiting the [locked function docs page][1].
Test that when you edit the domain of a locked function the correct JSON is
generated, and the graph displays correctly.
[1]: http://localhost:6006/?path=/docs/perseus-widgets-interactive-graph-locked-functions--docs
=> Default nulls to +/-Infinity when parsing the domain of a locked function

.changeset/calm-dolls-dance.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/graphs/angle.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx
Segment
- Update segment so that a singular segment doesn't have multiple layers of redundant labels (keep this for multiple segments)
Angle
- Update angle so the vertex point always reads the angle, not only when "show angles" is turned on.
Issue: none
`yarn jest packages/perseus/src/widgets/interactive-graphs/graphs/segment.test.tsx`
`yarn jest packages/perseus/src/widgets/interactive-graphs/graphs/angle.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-segment
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-angle
=> [SR] Tweak strings for Segment and Angle graphs

.changeset/wild-apes-repeat.md, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/components/__snapshots__/movable-line.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/arrowhead.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/hairlines.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/svg-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx
When using Safari + VoiceOver, the screen reader reads out every single internal part of every single element on the graph. For example, the arrow on a line is read out as "image" as well as the segment composing the line. This means that when traversing the graph in Safari, there are a whole bunch of empty "image"s being read out with no context. The context is provided by specific element's aria labels.
To remedy this, I added `aria-hidden` to all the visual elements that should not be read as "image" in all the graph types.
Issue: none
Storybook
- http://localhost:6006/?path=/docs/perseuseditor-widgets-interactive-graph--docs
- Go to every graph type and traverse through it with a screen reader
- Confirm there are no random empty "image" calls
=> [SR] Add aria-hidden to individual components of interactive graph elements

.changeset/serious-days-swim.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/use-control-point.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
This PR is part of the Interactive Graph project. 
The purpose of the PR is to ensure that dragging a point with a touch event also moves the focus to that point. This is to ensure that the focus always remains on the last element interacted with, which avoids confusion when the user tries to delete points or move them with the keyboard. 
NOTE: I wasn't able to fix a bug related to the hover state sizing of the control points, as I simply cannot seem to find where this is occurring. As a result, touch-dragging a point without any delay can result in the point not getting "bigger". However, the focus outline, hairlines, and focus itself all move to the correct element. I've attached a video below to demonstrate this.
https://github.com/user-attachments/assets/59e26360-b54e-4340-b49b-c4f9c32 …
=> [its-a-drag-to-tap-out] docs(changeset): Ensure that dragging a point also moves the focus for Interactive Graph

.changeset/calm-socks-cheer.md, packages/perseus/src/widgets/interactive-graph.tsx
Now that the Interactive Graph updates phase 1 is coming to a close,
we can mark the Interactive Graph widget as accessible.
And since the new mobile version is released, it also means that
Interactive Graph is no longer reserved for assessments only.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2522
- Bump the Perseus version in webapp using this PR version
- Check in local devserver that the interactive graph
"Requires screen or mouse?" checkbox is no longer
auto-checked and disabled.
| --- | --- |
| <img width="269" alt="Screenshot 2025-03-06 at 6 21 40 PM" src="https://github.com/user-attachments/assets/8241c597-36ce-465a-ba69-c00855410341" /> | <img width="268" alt="Screenshot 2025-03-06 at 6 21 25 PM" …
=> Mark interactive graph widget as accessible!

.changeset/rotten-cups-pay.md, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/__snapshots__/movable-line.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/vector.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-static.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css, packages/perseus/src/widgets/interactive-graphs/reducer/use-graph-config.ts
Right now, a static graph looks exactly the same as a regular graph that can be interacted with.
To distinguish graphs as disabled visually when in static mode, update the color so that the
graph elements use Wonder Blocks `offBlack50` when in static mode.
I also did some refactoring to make the way we code colors uniform across all the graphs.
NOTE: You may notice that `offBlack50` is not the best for contrast. However, it needs to be distinguishable
from our regular interactive blue so it's clearly disabled. When using a darker gray, it looks the same as
our WB blue in grayscale. We had to make a call here, and we decided to make it lighter and more
distinguishable even if it sacrifices color contrast.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2784
`yarn jest …
=> [LX] Make static graphs' interactive elements visually disabled

.changeset/small-gifts-float.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.tsx
There was a small bug where the 90 degree angles had the arc instead of the square marker
in the Polygon interactive graph, but only when `showAngles` was on.
Fixed it so that it uses the correct function and shows it appropriately.
Issue: none
- Start up `yarn dev`
- Look at the polygon question with the square and the angle labels showing
- Confirm that it shows the square indicators now
| --- | --- |
| <img width="531" alt="Screenshot 2025-03-10 at 4 01 30 PM" src="https://github.com/user-attachments/assets/0b7a84d5-f19d-46b7-99f8-fc80bfc39195" /> | <img width="522" alt="Screenshot 2025-03-10 at 4 01 41 PM" src="https://github.com/user-attachments/assets/780b34b9-e783-4be0-a909-8cfe2a7ef2f6" /> |
=> [Polygon] Show right angle markers when showAngles is on

.changeset/spotty-pans-yell.md, packages/math-input/src/components/input/__tests__/mathquill.test.ts, packages/math-input/src/components/key-handlers/handle-backspace.ts
When performing a backspace, our Math Input keypad appears to be deleting the entire contents of a parentheses node, which has been frustrating for our users. This functionality also occurs for logarithmic or trigonometric functions. 
For example: hitting backspace on `x+(9*9)` would result in only `x+` remaining.
When reviewing the code it appears that this functionality was set up deliberately, but I have been unable to find the justification or history why.
Given there's no clear reason for this feature, this PR is removing this special logic so that backspaces are handled with the default logic.
For example: hitting backspace on `x+(9*9)` would result in `x+(9*9`
Issue: MOB-5576
Manual testing
=> Ensure that keypad backspaces don't delete entire parentheses nodes at once.

.changeset/mean-items-share.md, packages/perseus-core/src/data-schema.ts, packages/perseus-core/src/index.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/free-response-widget.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/free-response-widget.ts, packages/perseus-core/src/widgets/free-response/free-response-util.test.ts, packages/perseus-core/src/widgets/free-response/free-response-util.ts, packages/perseus-core/src/widgets/free-response/index.ts, packages/perseus-core/src/widgets/logic-export.types.ts, packages/perseus-editor/src/widgets/__stories__/free-response-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/free-response-editor.test.tsx, packages/perseus-editor/src/widgets/free-response-editor.tsx, packages/perseus/src/widgets/free-response/free-response.testdata.ts
This commit adds a new scoringCriteria option to the Free Response
Widget editor. It allows users to input one or more scoring criteria
texts, which can be used when grading the answers to a Free Response
question.
This commit also changes the "Question" input to be a textarea instead
of an input element. This allows longer questions to wrap and be fully
visible even when the widget editor is narrow.
Issue: https://khanacademy.atlassian.net/browse/LIT-1663
- Run `pnpm test packages/perseus-editor/src/widgets/__tests__/free-response-editor.test.tsx`
- Open Storybook.
- Open the Free Response Editor stories.
- Verify that the rendered stories look right.
- Interact with the "Editable" story, verifying that it's possible to
add new criteria and delete existing ones.
- Verify that the …
=> Add scoring criteria to Free Response Widget

.changeset/ten-adults-act.md, packages/perseus-editor/package.json, packages/perseus-editor/src/widgets/label-image/answer-choices.tsx, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/components/zoomable-tex.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/styles/styles.less, packages/perseus/src/styles/widgets/interactive-graph.less, packages/perseus/src/styles/widgets/label-image.less, packages/perseus/src/styles/widgets/passage.less, packages/perseus/src/styles/widgets/plotter.less, pnpm-lock.yaml, testing/test-dependencies.tsx
In 2023, we deprecated our usage of KaTeX in favor of MathJax 3.
This PR cleans up references to KaTeX in Perseus.
Issue: LEMS-1608
- Deploy a ZND
- Verify that you can see math in an exercise
- ...and in the exercise editor
- ...and in the article editor.
- If you create a math element with invalid syntax, like `$#$`, you should see
a "TeX Errors" box appear that lists the errors and their locations.
=> Remove obsolete references to KaTeX

.changeset/quiet-insects-agree.md, packages/perseus-core/src/utils/split-perseus-item.ts, packages/perseus/src/widgets/dropdown/dropdown.stories.tsx, testing/renderer-with-debug-ui.tsx
Create a Storybook story for the Dropdown widget that renders with answerless data, is interactive, and is scorable.
Issue: LEMS-2930
- Confirm story renders, is interactive, and can be scored
=> Dropdown story with answerless data

.changeset/old-pens-hope.md, packages/perseus/src/widgets/radio/radio.ts
This quick bug-fix temporarily reverts a recent one-line change to fix a P1 bug for the Radio widget. 
The issue we were facing was that additional answers were showing as "correct" upon score even though they were incorrect. 
This bug is largely due to logic in the `radio-component.tsx` file on line 423 that uses the rubric to set the correct answer if it is not provided — as is often the case with our older content. 
`correct:  choice.correct === undefined
? !!reviewChoice && !!reviewChoice.correct
: choice.correct ` 
**The problem with this logic is that our choices have already been shuffled, but our rubric has not.** As a result of this index mismatch, any questions that have turned on both Multi Selection AND Randomization _could_ result in an additional answer or two being visually …
=> Bug fix: Fix Multiselect + Randomization only show correct for proper answers

.changeset/early-dodos-wink.md, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/sr-description-within-svg.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/ray.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx
Descriptions are not working in Safari or Firefox.
After a number of Slack discussions, it was determined that this was caused by the description blocks being defined within SVGs.
With a small amount of refactoring, we can make is so that the screen reader reads as expected across browsers.
Note: This does not include any changes for the outer graph descriptions, just the interactive elements and their surrounding container inside the graph SVG.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2914
`yarn jest`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph--interactive-graph-segment
- Go through every graph type in Storybook
- Confirm that the screen reader experience matches what's in the SR tree
=> [SR] Update graph elements so their aria-describedby is read in non-Chrome browsers

.changeset/beige-stingrays-cry.md, packages/perseus-core/src/data-schema.ts, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/interactive-graph-editor.tsx, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-labels.test.ts, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-labels.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-regression.stories.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/use-graph-config.ts, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
This PR redeploys [the labelLocation work](https://github.com/Khan/perseus/pull/2284) with several fixes:
1. A fix was applied to the InteractiveGraphBuilder to ensure that `labelLocation` will default to `undefined` for manual testing purposes. 
2. A fix was applied to th transform logic to account for `labelLocation` being undefined.
3. The transform logic was extracted out into a separate function for testing purposes. 
- manual testing 
- new tests
=> New labeLocation property for Interactive Graph with Bug Fixes 

.changeset/fair-ravens-guess.md, packages/perseus-core/src/data-schema.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/numeric-input-widget.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/numeric-input-widget.ts, packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap, packages/perseus-core/src/parse-perseus-json/regression-tests/item-data/numeric-input-with-simplify-accepted.json, packages/perseus-score/src/widgets/numeric-input/score-numeric-input.test.ts
Context: I'm seeing errors in Sentry because the perseus JSON parser doesn't
understand some of the values of `simplify` that exist in production data. This
PR ensures we accept and handle those values.
- I added tests to characterize the behavior of numeric input scoring for all
the values of `simplify` that are in production.
- I updated the perseus JSON parser to convert nonstandard `simplify` values
to equivalent ones.
Issue: none
`yarn test`
=> Numeric Input: Treat unrecognized `simplify` values as "required"

.changeset/grumpy-lamps-allow.md, packages/perseus-core/src/data-schema.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/free-response-widget.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/free-response-widget.ts, packages/perseus-core/src/widgets/free-response/free-response-util.test.ts, packages/perseus-core/src/widgets/free-response/free-response-util.ts, packages/perseus-core/src/widgets/free-response/index.ts, packages/perseus-editor/src/widgets/__stories__/free-response-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/free-response-editor.test.tsx, packages/perseus-editor/src/widgets/free-response-editor.tsx, packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap, packages/perseus/src/widgets/free-response/free-response.stories.tsx, packages/perseus/src/widgets/free-response/free-response.test.tsx, packages/perseus/src/widgets/free-response/free-response.testdata.ts, packages/perseus/src/widgets/free-response/free-response.tsx
This PR adds the ability to set the placeholder text in a Free Response Widget component.
Issue: [LIT-1668](https://khanacademy.atlassian.net/browse/LIT-1668)
- Open Storybook
- See the placeholder can be changed in the editor
- See the placeholder can be changed in the renderer
**NOTE:** The screenshots use something I typed in. The default value is "Please provide response here"
[LIT-1668]: https://khanacademy.atlassian.net/browse/LIT-1668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Free Response Widget] Add ability to customize placeholder

.changeset/silly-houses-dress.md, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/components/__tests__/__snapshots__/svg-image.test.tsx.snap, packages/perseus/src/components/image-loader.tsx, packages/perseus/src/widgets/image/image.stories.tsx, packages/perseus/src/zoom.ts
Our A11Y Partner has requested that the button role be added to our Image Widget, as images within it may be interactive if they require a zoom. 
This PR adds the role, fixes a related story for testing purposes, and updates several related tests. 
Issue: LEMS-2697
- Manual testing on Desktop/Mobile 
- Tests Pass
=> Adding button roles to the Image Widget to help improve A11Y.

.changeset/twenty-rivers-cry.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/perseus-item.ts, packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap, packages/perseus-core/src/parse-perseus-json/regression-tests/item-data/item-with-null-itemDataVersion.json
There are a few content items that have `itemDataVersion: null`, and these are
causing parser errors in production because the parser doesn't like `null`.
This PR updates the parser to accept `null` values for `itemDataVersion`.
`itemDataVersion` is already marked deprecated, and can be `undefined`, so it
seems harmless to allow `null` as well.
Issue: none
`pnpm test`
=> Allow `itemDataVersion` to be null when parsing Perseus assessment item JSON

.changeset/shaggy-ladybugs-begin.md, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/__snapshots__/movable-line.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/use-control-point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-static.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
Right now, when an interactive graph is not interactive (static graphs or after the question has been answered), there is no way for a screen
reader user to know that. The graph instructions are still there, and
the interactive elements sound the same.
Fixing that in this PR
- When a graph is not interactive, remove the interaction instructions
- When a graph is not interactive, give all interactive elements the
"aria-disabled={true}" property.
| --- | --- |
| <img width="1130" alt="Screenshot 2025-03-25 at 12 50 14 PM" src="https://github.com/user-attachments/assets/1e8c4148-0040-4101-b521-a492444e0042" /> | <img width="1174" alt="Screenshot 2025-03-25 at 12 49 34 PM" src="https://github.com/user-attachments/assets/1f39b80c-e3d2-4e4c-a069-02fa70996904" /> |
Issue: none …
=> [SR] Remove instructions for static graphs, mark interactive elements as disabled

.changeset/pretty-toys-help.md, .changeset/quick-mice-turn.md, packages/perseus/src/strings.ts, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-labels.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
We found out from the UXR that having the axis labels just there didn't really help. Instead, it would be better for them to be part of the overall graph description, which is specified by content authors.
Hiding axis labels from screen readers here.
Issue: none
- Go to http://localhost:6006/iframe.html?globals=&args=&id=perseuseditor-widgets-interactive-graph--interactive-graph-segment&viewMode=story
- Use a screen read to go through the graph
- Confirm that the axis labels are no longer read.
=> [SR] Move axis labels' screen reader text

.changeset/big-buttons-crash.md, packages/perseus-editor/src/widgets/__tests__/numeric-input-editor.test.tsx, packages/perseus-editor/src/widgets/input-number-editor.tsx, packages/perseus-editor/src/widgets/numeric-input-editor.tsx, packages/perseus-score/src/util/answer-types.ts, packages/perseus/src/components/number-input.tsx, packages/perseus/src/util.test.ts, packages/perseus/src/util.ts
In https://github.com/Khan/perseus/pull/2278 I removed jQuery from code we needed to run on the server. Unfortunately there are some subtle nuances between jQuery and native JS functions.
One of the differences is that `each` can exit the loop early while `forEach` cannot. I happened to trip on some untested code that was banking on that jQuery feature.
Issue: LEMS-2962
- Go to the [EditorPage in Storybook](https://khan.github.io/perseus/?path=/story/perseuseditor-editorpage--demo)
- Add a NumericInput widget
- In the input labelled "User input:" under "Answers" type "6/8"
- Note the title of the card "Correct answer:"
- BROKEN: It will say "Correct answer: 6"
- FIXED: It will say "Correct answer 3/4"
=> Fix `each` vs `forEach` bug

.changeset/four-cougars-work.md, packages/perseus-core/src/data-schema.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/free-response-widget.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/free-response-widget.ts, packages/perseus-core/src/widgets/free-response/free-response-util.test.ts, packages/perseus-core/src/widgets/free-response/free-response-util.ts, packages/perseus-core/src/widgets/free-response/index.ts, packages/perseus-editor/src/widgets/__stories__/free-response-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/free-response-editor.test.tsx, packages/perseus-editor/src/widgets/free-response-editor.tsx, packages/perseus/src/strings.ts, packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap, packages/perseus/src/widgets/free-response/free-response.stories.tsx, packages/perseus/src/widgets/free-response/free-response.test.tsx, packages/perseus/src/widgets/free-response/free-response.testdata.ts, packages/perseus/src/widgets/free-response/free-response.tsx
This PR adds the ability for content creators to set a character limit for the answers. If the user goes over that limit, then the field visually shows it as invalid.
The creator can choose to allow for unlimited characters if they would prefer.
Issue: LIT-1666
- Open Storybook
- In the editor
- modify the character limit
- toggle unlimited characters
- In the renderer
- type some characters to see the count update
- type enough to go over the limit, see the error state
- type a lot into the unlimited, see no error state
=> [Free Response Widget] Add optional character limit support

.changeset/angry-toes-crash.md, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-labels.test.ts, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-labels.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-regression.stories.tsx
This ticket is part of the Interactive Graph Project.
While working on LEMS-2718, it was discovered that the axis labels could "shoot off into space" as min-ranges climbed, or max-ranges plummeted. This PR makes sure to clamp these values so that the axis labels still roughly align with the tick labels. 
https://github.com/user-attachments/assets/dd5bb3b0-0976-4fcb-a3f1-1ad6897700f8
Issue: LEMS-2912
- New tests
- Manual Testing
=> Ensure Interactive Graph Axis Labels are clamped by graph dimensions

.changeset/nervous-points-compare.md, dev/flipbook.tsx, packages/perseus-editor/src/__stories__/editor-page-with-storybook-preview.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-figure-settings-actions.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-function-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/locked-polygon-settings.tsx, packages/perseus/src/widgets/definition/definition.tsx, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/phet-simulation/phet-simulation.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
- Updates WB deps to latest versions.
- Updates `IconButton` instances to match new WB changes (IconButton styles, `actionType` instead of `color`).
- Updates `Popover` to remove the deprecated `color` prop.
Issue: "none"
Make sure that the `IconButton` instances follow this mapping:
- `<IconButton kind="primary" />` => `<IconButton kind="tertiary" />`
- `<IconButton kind="secondary" />` => `<IconButton actionType="neutral" kind="tertiary" />`
- `<IconButton kind="tertiary" />` => `<IconButton actionType="neutral" kind="tertiary" /> (same as the prev. secondary styling)`
=> Update Wonder Blocks package to match IconButton refactor

.changeset/new-trains-swim.md, packages/perseus/src/index.ts
I noticed in webapp that the Perseus `mediaQueries` object is being used. It was unrelated to Perseus and so I fixed it. But it pointed to the fact that there's no reason for this object to be exported. 
I checked other packages in this repo and none of them use `mediaQueries`, so I'm changing things so that we don't export it anymore; it's an internal thing.
Issue: "none"
`pnpm typecheck`
Check consuming apps and ensure none use `mediaQueries`
=> Don't export mediaQueries - not used (and shouldn't be) outside of Perseus

.changeset/calm-avocados-retire.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.ts
I noticed Sentry errors related to this. We weren't parsing the `widgets` field
of `PerseusRadioChoice` consistently. The logic was different depending on the
version of the widget options. This PR makes it consistent.
Issue: none
Sentry errors related to this field should diminish after deploying.
=> Fix parsing of `widgets` field in `PerseusRadioChoice`

.changeset/khaki-bikes-care.md, packages/perseus/src/util.test.ts, packages/perseus/src/util.ts, packages/perseus/src/widgets/table/__snapshots__/table.test.tsx.snap, packages/perseus/src/widgets/table/table.stories.tsx, packages/perseus/src/widgets/table/table.test.tsx, packages/perseus/src/widgets/table/table.tsx, packages/perseus/src/widgets/table/test-util.ts
I probably could have kept cleaning this widget up, but...
- Table is `hidden`
- This display name for Table is: "Table (deprecated - use markdown table instead)"
- I did more than what I needed for SSS
The only thing it was really using `PerseusTableWidgetOptions.answers` for was to determine the number of rows/columns, but `PerseusTableWidgetOptions` has `rows: number` and `columns: number` so I just used those. Before switching things over however, I wrote some unit tests for current behavior and then made sure those tests passed with answerless data.
Issue: LEMS-2982
=> Answerless Table

.changeset/nervous-gifts-relax.md, packages/perseus/src/widgets/interactive-graphs/graphs/screenreader-text.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/screenreader-text.ts
We need to add `1` coefficient before pi-based values that start with negative pi,
because screen readers may not read the `-` sign, implying the value is positive
even when it's not.
By adding the `1`, it will read "minus one pi" which is at least correct in terms
of meaning, even if it doesn't totally match the spoken vocabulary.
In the [Slack conversation about this](https://khanacademy.slack.com/archives/C067UM1QAR4/p1744829758895619), I received confirmation from Charlie that
this is an acceptable approach.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3041
`pnpm jest packages/perseus/src/widgets/interactive-graphs/graphs/screenreader-text.test.ts`
Storybook
- Go to http://localhost:6006/iframe.html?globals=&args=&id=perseuseditor-widgets-interactive-graph--interactive-graph-si …
=> [SR][Pi ticks] Add a coefficient before pi-based values that start with negative pi

.changeset/friendly-seas-scream.md, packages/perseus/src/strings.ts
We held off on translations until now, beacuse the Interactive Graph strings were
still in flux. Now that they're finalized, we can send them in for translations.
I added context to all the strings that need to be translated so that
- it's clear for translators looking at the translation ticket what
the context is for each individual string.
- it'll be easy for us to create the translation ticket in the first place.
Since these are going to count as new strings, they'll trigger the
action on the PR that will create a translation ticket for us that's
pre-populated with all new strings.
NOTE: This PR is probably easier to review with the "Hide whitespace" option.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2660
- I looked at the PR diff, and then did a page search for every string …
=> [SR] Prepare strings for translation - Add context to interactive graph strings

.changeset/silly-crabs-pump.md, packages/perseus-core/src/parse-perseus-json/general-purpose-parsers/defaulted.test.ts, packages/perseus-core/src/parse-perseus-json/general-purpose-parsers/defaulted.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/hint.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/legacy-button-sets.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/measurer-widget.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/numeric-input-widget.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/perseus-image-background.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.ts, packages/perseus-core/src/parse-perseus-json/regression-tests/parse-perseus-json-regression.test.ts
I realized that the type of the `defaulted` parser encouraged non-idempotent
parsing. Essentially, a default value could be supplied that would cause a parse
error on a second pass through the parser. Example:
```ts
const parseMyObject = object({
myField: defaulted(number, () => "bork"),
})
```
The inferred type `ParsedValue<typeof parseMyObject>` would be:
```ts
type MyObject = {myField: number | string}
```
However, the parser doesn't consider a myField value of type `string` to be valid!
This contradicts the types! You will get an error if you try to parse
```ts
parseMyObject({myField: "bork"}, ctx)
```
because the parser for `myField` only accepts a number, null, or undefined as
input.
This is clearly not how we want parsers to behave. Parsing should be idempotent.
This PR fixes the …
=> Add tests to ensure Perseus JSON parsers are idempotent

.changeset/metal-ties-remain.md, packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
Update Radio Widget docs to include rationales in the test data
Issue: LEMS-3027
1. Navigate to the Radio Widget docs
2. Select Multi Select Simple
3. Click "Show Rationales" button
| ------- | ----- |
| <img width="500" alt="image" src="https://github.com/user-attachments/assets/ec996daa-36f1-402f-9b67-ba7a59c0b4ad" /> | <img width="500" alt="image" src="https://github.com/user-attachments/assets/a56e23ee-f865-41a6-9d06-9eb0aa2c7fa6" /> |
=> Update Radio Widget docs to include rationales in the test data

.changeset/early-planets-try.md, packages/perseus-editor/src/editor-page.tsx, packages/perseus-editor/src/hint-editor.tsx
Allow widgets within hints to expand/collapse with the "Widgets" toggle in the Exercise Editor. This was already working for widgets outside of hints, so this just extends the logic to allow for it to work within hints too.
Note that last time we made a change to these files we caused this: https://khanacademy.atlassian.net/wiki/spaces/ENG/pages/3317891139/widgetIsOpen+breaks+content+pipeline. I _think_ the same thing won't happen this time because of Matthew's fix, but I just wanted to bring it up, just in case!
Demo in Perseus Storybook:
https://github.com/user-attachments/assets/dde66ddb-3379-4fdc-9e32-984df2117c23
Demo in webapp with the npm snapshot:
https://github.com/user-attachments/assets/c987b86a-3c5d-4f97-9c3e-5f32c8152110
Issue: CP-9223
go to …
=> Allow widgets in hints to open/close with the Editor toggle

.changeset/soft-years-brush.md, packages/perseus-core/src/index.ts, packages/perseus-core/src/utils/item-has-hints.test.ts, packages/perseus-core/src/utils/item-has-hints.ts, packages/perseus-core/src/utils/item-has-rationales.test.ts, packages/perseus-core/src/utils/item-has-rationales.ts
In this PR, I introduce two new utilities to the perseus-core package for detecting whether a given parsed PerseusItem has hints (itemHasHints) and whether it has rationales (itemHasRationales).
Issue: https://khanacademy.atlassian.net/browse/TUT-1590
Test plan:
- pnpm test packages/perseus-core/src/utils
=> [TUT-1590] Add itemHasHints & itemHasRationales utilities

.changeset/new-tips-provide.md, .changeset/pretty-buses-listen.md, packages/perseus-editor/src/widgets/expression-editor.tsx, packages/perseus/src/components/button-group.tsx, packages/perseus/src/widgets/grapher/__snapshots__/grapher.test.ts.snap
I spent an hour cleaning up a bunch of UI stuff in the `expression` editor. Namely: 
* Change the 'considered' (`correct`, `incorrect`, `ungraded`) options to be a button group so it's more obvious that you can actually change it
* Moved tooltip `?` to be at end of field label instead of trailing input
* Added a gap between answers
* Stretch "Add new answer" to full width so it looks nicer
| --- | --- | 
| <img width="346" alt="image" src="https://github.com/user-attachments/assets/8731ac92-cb82-481a-91ed-fdcde14e6c05" />  |  <img width="345" alt="image" src="https://github.com/user-attachments/assets/149667a4-0242-42a3-9012-5425f916a7b9" /> |
Issue: "none" 
Review UI changes and code
=> Expression Editor: UI update to clarify how things work

.changeset/good-trains-dream.md, packages/perseus/src/components/simple-keypad-input.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/numeric-input/input-with-examples.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx, packages/perseus/src/widgets/numeric-input/numeric-input.tsx
The `numeric-input` widget uses two different input components depending on whether a custom keypad is enabled or not. We want to retain a ref to either of these inputs within the widget. Originally, the ref was defined as the union of these two components, but that leads to sporadic type check failures. 
This PR adjusts things so we define a common `interface` for these two components and then use that interface as the type for hte ref. This makes it so the ref is a very narrow type referencing only the fields that are used.
Issue: "none"
`yarn tsc --watch` (make some changes, save, then revert to ensure the type checking doesn't fail)
=> Use interface for shared ref type

.changeset/real-coats-march.md, packages/perseus-core/src/index.ts, packages/perseus-core/src/widgets/grapher/grapher-util.ts, packages/perseus/src/widgets/grapher/grapher.cypress.ts, packages/perseus/src/widgets/grapher/grapher.stories.tsx, packages/perseus/src/widgets/grapher/grapher.test.ts, packages/perseus/src/widgets/grapher/grapher.testdata.ts, packages/perseus/src/widgets/grapher/grapher.tsx
Making sure Grapher can work in an Answerless world. For the most part this PR:
- Updates all Cypress tests to test both answerful and aswerless¹
- Adds an Answerless story
- Removes Underscore from Grapher
¹ Grapher is an inaccessible widget that requires drag-and-drop behavior that [can't be tested with React Testing Library](https://github.com/testing-library/user-event/issues/440#issuecomment-685010755), which is why we use Cypress
Issue: LEMS-2985
Grapher should continue to work as it's always worked.
=> Answerless Grapher

.changeset/fluffy-onions-camp.md, packages/perseus-editor/src/editor-page.test.tsx, packages/perseus-editor/src/widgets/__tests__/orderer-editor.test.tsx, packages/perseus-editor/src/widgets/orderer-editor.tsx
We were facing a bug with the Orderer Editor where the state was always a step out-of-date. Thanks to @handeyeco 's insights, it sounds like we've deprecated `serialize`, and we're now handling everything in the onChange events. Unfortunately, the logic for `onOptionsChange` did not handle the updating of the dynamic options property, thus resulting in it being out of sync while editing pre-existing content. 
This PR adds the missing logic to `onOptionsChange`, while also modernizing it to remove underscore. 
Issue: LEMS-3082
- New tests for onChange response AND sort order 
- Confirmed fixes work upstream via snapshot testing
=> Ensure Orderer Editor updates Options property in change callback

.changeset/odd-ladybugs-remain.md, packages/perseus-editor/src/editor-page.tsx, packages/perseus-editor/src/item-editor.tsx
As I was working on the accessibility checks for our linting system I came across some things that can be cleaned up. So this PR cleans these things, mostly editor area pieces, some types, some long-deprecated and unused props:
* Remove references to long-deprecated concepts: `workArea`, `solutionsArea`, `hintsArea`. Perseus used to allow the hosting application to provide selectors to existing elements on the page. Today, the `ServerItemRenderer` and `Renderer` fully control the DOM within their respective root nodes, so these concepts are no longer needed.
* Remove unused field and create explicit type for `DefaultProps`
* Type editor props for `answerArea` correctly
* Remove deprecated props from EditorPage: `wasAnswered`, `gradeMessage`
Issue: "none"
`pnpm tsc`
`pnpm test`
Storybook …
=> Edit area cleanup

.changeset/seven-toys-lay.md, packages/perseus-core/src/parse-perseus-json/index.ts, packages/perseus-core/src/parse-perseus-json/parse-perseus-json.test.ts
The `parseAndMigratePerseusItem` originally accepted only a `string` and started the process by `JSON.parse()`ing it. As we start building more things that need to parse perseus items, it's becoming clear we want to be able to parse objects that are already deserialized. 
So this PR updates the function to accept either a `string` or `object`. 
Issue: LEMS-3054
`pnpm test`
=> Extend parseAndMigratePerseusItem to accept an object as well as string

.changeset/friendly-years-share.md, packages/perseus/src/perseus-api.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/phet-simulation/phet-simulation.stories.tsx, packages/perseus/src/widgets/phet-simulation/phet-simulation.test.ts, packages/perseus/src/widgets/phet-simulation/phet-simulation.tsx
This PR creates a fake fullscreen view in the mobile application for the PhET Widget, as we're currently unable to use the fullscreen API. It also adds a new apiOption for isMobileApp, which will allow Perseus to know when we're being served in one of the mobile applications. 
This PR will require updates in webapp in order to pass down the new isMobileApp variable as part of the apiOptions.
Additional support for the fullscreen API could _**possibly**_ be added to the Mobile application in the future, but there is currently no set release date or work for the next Mobile release. Given that, we've opted for a bit of a "hacky" temporary solution that will allow us to get the widget a little larger to improve usability. 
Unfortunately, full screen will not be supported in iOS web at this …
=> docs(changeset): New feature for PhET Widget to provide an option for full screen on mobile devices.

.changeset/tricky-parents-hide.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts, packages/perseus-core/src/utils/split-perseus-item.test.ts, packages/perseus-core/src/utils/split-perseus-renderer.test.ts, packages/perseus-core/src/widgets/interactive-graph/index.ts, packages/perseus/src/widgets/interactive-graph.tsx
This PR implements a fix to ensure that our parser can handle empty string values for our labelLocation property on our Interactive Graphs. 
I have also updated several locations to be very specific about the default value, to ensure that this issue doesn't persist with new content. 
Issue: LEMS-3122
- Tests pass 
- Including new test
=> Ensure that our parser can handle empty strings for labelLocation for Interactive Graphs

.changeset/eighty-swans-love.md, packages/perseus/src/components/scrollable-view.tsx, packages/perseus/src/widgets/radio/choice.new.tsx
This PR will add the proper tab navigation to the new radio widget after the horizontal scrollbar was added. Removing the visible blue focus in the entire row instead of just the choice icon.
| ------ | ------ |
| <img width="300" src="https://github.com/user-attachments/assets/e12c9939-a034-4975-a5a7-e36e0860e199" /> | <img width="300" src="https://github.com/user-attachments/assets/95a7cab1-1d46-47bd-8a28-23442530c987" /> |
**Note: Known Existing Issue**
When displaying an image as the content will cause an additional focus on the image.
| Before (Prod) | After |
| ------ | ------ |
| <img width="300" src="https://github.com/user-attachments/assets/87a82f00-01f0-48c9-b197-312f232ddff8" /> | <img width="300" src="https://github.com/user-attachments/assets/340d6a2f-5c46- …
=> Add tab navigation to new radio widget

.changeset/mean-trains-cover.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/categorizer-user-input.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/categorizer-user-input.typetest.ts
Added a user input parser and typetest for Categorizer
Issue: LEMS-3128
- Confirm categorizer still works as expected using Storybook
=> Add typesafe parser for Categorizer's user input type

.changeset/thick-weeks-kneel.md, packages/perseus/src/renderability.ts
Remove the manual traversal of subwidgets as the `traverse` function handles this logic.
Issue: LEMS-3142
Run `pnpm test` all tests should pass.
=> Removing manual traversal.

.changeset/dirty-singers-arrive.md, .changeset/nervous-cycles-try.md, packages/perseus-editor/src/widgets/free-response-editor.tsx, packages/perseus/src/widgets/free-response/free-response.tsx
This commit changes the getSaveWarnings() function definition in the
Free Response widget editor to be defined using public class field syntax of
the public method syntax. Previously, `this` wasn't being bound
properly, so the function was unable to read `this.props`. Additionally,
the Free Response widget is unhidden, so that it will appear in the widgets
dropdown in the exercise editor.
The commit also adds some more type annotations and changes all methods
on the widget editor to be defined in the same way.
Issue: https://khanacademy.atlassian.net/browse/AX-1005
- Load the PR's Perseus bundle in local webapp.
- Go to the exercise editor in devadmin and verify that there is a "Free Response"
option in the "Add a widget..." dropdown.
- Add a Free Response widget in the exercise editor …
=> Fix getSaveWarnings in Free Response widget

.changeset/sixty-impalas-warn.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/input-number-user-input.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/input-number-user-input.typetest.ts
Add a user input type parser for the Input-number widget 
Issue: LEMS-3141
- Confirm widget acts as expected via Storybook
=> Add typesafe parser for Input-number's user input type

.changeset/calm-knives-behave.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/label-image-user-input.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/label-image-user-input.typetest.ts
Add a user input type parser for the Label-image widget
Issue: LEMS-3135
- Confirm widget still acts as expected via Storybook
=> Add typesafe parser for Label-image's user input type

.changeset/little-goats-prove.md, packages/perseus-core/src/validation.types.ts, packages/perseus-score/src/widgets/radio/score-radio.test.ts, packages/perseus-score/src/widgets/radio/score-radio.ts, packages/perseus/src/widgets/radio/__tests__/radio.test.ts
This PR is part of the Radio Widget Upgrade Project. 
This work ensures that non-specific multi-select Radios don't trigger CHOOSE_CORRECT_NUM_ERRORs, and are instead marked as "incorrect". 
Issue: LEMS-2996
- New scoring test 
- Previous tests pass (after making them specific)
=> docs(changeset): Updates to Radio Scoring to ensure non-specific multiselect questions are marked correctly.

.changeset/metal-spies-double.md, packages/perseus/src/widget-ai-utils/group/group-ai-utils.test.ts, packages/perseus/src/widget-ai-utils/label-image/label-image-ai-utils.test.ts, packages/perseus/src/widget-ai-utils/label-image/label-image-ai-utils.ts, packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.ts
Add rationales to the getPromptJSON output of Radio widget and Label Image widget.
This is a small addition to the information that getPromptJSON already returns, and only affects these specific widgets.
The intent is to have rationales accessible when we use getPromptJSON to get the state of widgets.
Issue: TUT-2087
- Updated tests
- Run all tests
=> Add rationales to the getPromptJSON output of Radio widget and Label Image widget

.changeset/little-toys-share.md, packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
Temporary Remove RTL display in New Radio Widget to unblock Perseus from displaying the stories in RTL
Issue: none
- Confirm that widgets in storybook including the New Radio widget is no longer displayed in RTL
=> Remove RTL display in New Radio Widget to unblock Perseus from displaying the stories in RTL

.changeset/green-coins-applaud.md, .github/workflows/node-ci.yml, packages/perseus/src/__tests__/server-item-renderer.test.tsx, packages/perseus/src/server-item-renderer.tsx
The ServerItemRenderer (and the `<LoadingContext>`) call an `onRendered(true)` prop when all assets are loaded (things that are loaded/rendered asynchronously). However, in cases where the rendered item does not have any assets, it wasn't ever calling `onRendered(true)`. 
This PR updates the `ServerItemRenderer` to check if any assets were registered in `componentDidMount`. If not, we can safely call `onRendered(true)` knowing that the item is ready for interaction and fully rendered.
Issue: LEMS-3200
All tests pass. 
I will also take the snapshot PR and spin up a ZND to test the classroom link that was broken.
=> Fire onRendered callback at least once

.changeset/perfect-elephants-joke.md, packages/perseus/src/widgets/radio/__tests__/radio.test.ts, packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts
This micro-pr is part of the Radio Widget Project. 
All it does is add a test to help prevent regressions. :) 
Issue: LEMS-2931
- new test passes. 
-- (Also confirmed that the test does NOT pass if I revert the fix from the original PR https://github.com/Khan/perseus/pull/2307/files)
=> docs(changeset): Add test for protecting against edgecase regressions regarding undefined correct value in Radio Widget.

.changeset/spotty-planes-design.md, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/server-item-renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/graded-group-set/graded-group-set.stories.tsx, packages/perseus/src/widgets/graded-group-set/graded-group-set.test.ts, packages/perseus/src/widgets/graded-group-set/graded-group-set.testdata.ts, packages/perseus/src/widgets/graded-group/graded-group.stories.tsx, packages/perseus/src/widgets/graded-group/graded-group.test.ts, packages/perseus/src/widgets/graded-group/graded-group.testdata.ts, packages/perseus/src/widgets/graded-group/graded-group.tsx, packages/perseus/src/widgets/group/group.test.tsx, packages/perseus/src/widgets/group/group.tsx, packages/perseus/src/widgets/label-image/__tests__/label-image.test.ts, packages/perseus/src/widgets/label-image/label-image.tsx, packages/perseus/src/widgets/radio/__tests__/radio.test.ts, packages/perseus/src/widgets/radio/radio-component.tsx, packages/perseus/src/widgets/radio/radio.class.new.tsx, packages/perseus/src/widgets/radio/radio.new.tsx, testing/item-renderer-hooks.tsx
This PR started as part of the Radio Widget Project, and became a more holistic change to simplify Perseus. 
After much discussion across several teams, we've decided that we will now show all feedback/rationales/correctness information all at once, but only after a widget becomes "inactive" through one of these actions:
- User skips the question
- User answers correctly
- User requests hints (effectively skipping)
- Content Creator enables static mode
Previously, we were selectively showing rationals to users while they were still able to interact with the widgets — a feature which was causing several bugs across the widgets that supported it: 
- Radio Widget 
- Graded Group Widget 
- Label Image Widget 
This move allows us to:
- Solve numerous bugs/tickets in one fell swoop 
- …
=> Remove showRationalesForCurrentlySelectedChoices and replace with showSolutions where appropriate

.changeset/chatty-cats-pretend.md, packages/perseus-editor/src/__tests__/editor.test.tsx, packages/perseus-editor/src/__tests__/issues-panel.test.tsx, packages/perseus-editor/src/components/widget-editor.tsx, packages/perseus-editor/src/issues-panel.tsx, packages/perseus-editor/src/styles/perseus-editor.css
Replace custom icons with WB components for consistent styling in Perseus Editor
This PR updates the styling in the Perseus Editor to create a more unified and accessible experience across components.
- Replaced the anchor tag used for panel toggling with a Wonder Blocks IconButton.
- Applied consistent styles and toggle behavior across widget-editor.tsx and issues-panel.tsx.
- Partially implements styling and structure from [Mark Fitzgerald’s POC #2219](https://github.com/Khan/perseus/pull/2219) to align with design direction.
Issue: LEMS-3125
=> Replace custom icons with WB components for consistent styling in Perseus Editor

.changeset/mighty-kangaroos-grow.md, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.tsx
Right now, when a content author changes the range in the interactive graph settings,
the tick step, grid step, and snap step all update to a specific ratio of the range.
Sometimes content authors don't want this to happen. We've received a request to
stop the auto-updates.
In this PR, I'm stopping the auto-updates, and adding a button that can be clicked
if a content author wants the steps updated the way they used to be.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3217
https://github.com/user-attachments/assets/9903b0a7-f285-4ea4-acc4-644f7f3a0b39
`pnpm jest packages/perseus-editor/src/widgets/interactive-graph-editor/components/interactive-graph-settings.test.tsx`
Storybook
- Go to http://localhost:6006/iframe.html?globals=&args=&id=perseuseditor-widgets-interactive-graph--inte …
=> [CX] Stop steps from auto-updating when range is changed in Interactive Graph editor

.changeset/friendly-ties-glow.md, packages/perseus/src/widgets/radio/radio-question-builder.test.ts, packages/perseus/src/widgets/radio/radio-question-builder.ts
In order to make it easier to build out Perseus JSON for Radio tests,
we need a builder function.
Using the interactive graph question builder as inspiration, I created
a radio builder here.
NOTE: I will replace the existing testdata in a follow-up PR.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3187
`pnpm jest packages/perseus/src/widgets/radio/radio-question-builder.test.ts`
Double check the schema and confirm that everything that's not deprecated
or unused is possible to create using the builder.
Double check the existing `radio.testdata.ts` file and confirm that everything
is possible to create using the builder.
=> [Radio] | (DX) | Create a question builder for the Radio widget

.changeset/friendly-ties-glow.md, .changeset/proud-bananas-raise.md, packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts, packages/perseus/src/widgets/radio/radio-question-builder.test.ts, packages/perseus/src/widgets/radio/radio-question-builder.ts
Now that we have a new question builder, we can use it to replace the
existing testdata json blobs to make them more readable.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3187
`pnpm jest packages/perseus/src/widgets/radio/__tests__/radio.test.ts`
Look at all the radio stories in the RadioNew docs page:
http://localhost:6006/?path=/docs/perseus-widgets-radionew--docs
=> [Radio] | (DX) | Use the new question builder in testdata file

.changeset/four-news-visit.md, packages/perseus-editor/src/widgets/radio/editor.tsx
The "Multiple choice style guide" link in the editor needs to be updated
- Update the copy to say "Multiple choice best practices"
- Update the destination to https://www.khanacademy.org/internal-courses/content-creation-best-practices/xe46daa512cd9c644:question-writing/xe46daa512cd9c644:multiple-choice/a/stems
Issue: https://khanacademy.atlassian.net/browse/LEMS-3035
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--demo
- Add a radio widget
- Confirm that the link now says "Multiple choice best practices"
- Confirm that it goes to the Khan Academy lesson rather than a Google doc
=> [Radio] | (CX) | Update the style guide link

.changeset/eighty-kiwis-thank.md, packages/perseus-editor/src/widgets/free-response-editor.tsx, packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap, packages/perseus/src/widgets/free-response/free-response.tsx, utils/extract-css.js
Updates styles to use `semanticColor.core` WB tokens instead of the now
deprecated sc.text and sc.border tokens, which were previously used
for text and border colors.
This change is part of the ongoing effort to standardize our new `core` semantic
color tokens across repositories, so that we can have a consistent approach
with Design specs.
Docs: https://khan.github.io/wonder-blocks/?path=/docs/foundations-using-color--docs#core
Issue: "none"
Verify that the following components render without any visual changes:
- Free response editor
| BEFORE | AFTER |
|--------|--------|
| <img width="1294" alt="Screenshot 2025-06-19 at 3 37 50 PM" src="https://github.com/user-attachments/assets/6b5ecd86-d409-4049-9819-f09c78f15998" /> | <img width="1393" alt="Screenshot 2025-06-19 at 3 38 13 PM" …
=> Wonder Blocks: Remove deprecated semanticColor.text and semanticColor.border token instances

.changeset/fresh-olives-study.md, packages/perseus-core/src/index.ts, packages/perseus-core/src/widgets/sorter/sorter-util.test.ts, packages/perseus-core/src/widgets/sorter/sorter-util.ts, packages/perseus-score/src/widgets/sorter/validate-sorter.ts, packages/perseus/src/components/__tests__/sorter.test.tsx, packages/perseus/src/widgets/sorter/serialize-sorter.test.ts, packages/perseus/src/widgets/sorter/sorter.tsx
=> Sorter: renderer user input state

.changeset/ten-cheetahs-confess.md, packages/perseus/src/widgets/iframe/iframe.tsx, packages/perseus/src/widgets/iframe/serialize-iframe.test.ts
=> IFrame: renderer user input state

.changeset/loud-trains-relate.md, packages/perseus/src/widgets/cs-program/cs-program.tsx, packages/perseus/src/widgets/cs-program/serialize-cs-program.test.ts
=> CSProgram: renderer user input state

.changeset/large-swans-bake.md, packages/perseus/src/widgets/mock-widgets/mock-widget.tsx
=> MockWidget: renderer user input state

.changeset/early-walls-walk.md, packages/perseus-editor/src/widgets/plotter-editor.tsx, packages/perseus/src/widgets/plotter/plotter.stories.tsx, packages/perseus/src/widgets/plotter/plotter.test.tsx, packages/perseus/src/widgets/plotter/plotter.testdata.ts, packages/perseus/src/widgets/plotter/plotter.tsx, packages/perseus/src/widgets/plotter/serialize-plotter.test.ts
=> Plotter: renderer user input state

.changeset/eighty-rice-buy.md, packages/perseus/src/widgets/input-number/input-number.tsx, packages/perseus/src/widgets/input-number/serialize-input-number.test.ts
=> InputNumber: renderer user input state

.changeset/real-mails-thank.md, packages/perseus/src/widgets/orderer/orderer.tsx, packages/perseus/src/widgets/orderer/serialize-orderer.test.ts
=> Orderer: renderer user input state

.changeset/flat-wolves-drop.md, packages/perseus-core/src/types.ts, packages/perseus-core/src/validation.types.ts, packages/perseus/src/widgets/label-image/__tests__/label-image.test.ts, packages/perseus/src/widgets/label-image/__tests__/serialize-label-image.test.ts, packages/perseus/src/widgets/label-image/label-image.tsx
=> LabelImage: renderer user input state

.changeset/unlucky-dancers-compare.md, packages/perseus/src/widgets/number-line/number-line.stories.tsx, packages/perseus/src/widgets/number-line/number-line.test.ts, packages/perseus/src/widgets/number-line/number-line.testdata.ts, packages/perseus/src/widgets/number-line/number-line.tsx
The problem had to do with how we default/initialize `rel` (relationship for inequalities). The logic around how we do this is pretty confusing TBH, but I think I came to a good place?
Issue: LEMS-3247
- Go to the new story or the link in the ticket (prod/ZND)
- Note the arrow
- Correct: arrow is pointing right
- Broken: arrow is pointing left
- Hit "Switch direction"
- Correct: arrow should switch direction
- Broken: arrow does not switch direction
- Hit "Make circle open"
- Correct: circle should become unfilled
- Broken: circle stays filled
Fixed behavior:
https://github.com/user-attachments/assets/8d6fa9a0-d3bc-443b-b89a-c93abeaab9ec
Broken behavior:
https://github.com/user-attachments/assets/9872fe93-b1e6-4e5d-944c-f33ae36230c9
=> LEMS-3247: NumberLine inequality regression

.changeset/swift-jobs-poke.md, packages/perseus/src/styles/util.css, packages/perseus/src/styles/widgets/radio.css
This PR removes an old CSS hack that are no longer relevant in our codebase (it's for IE7!)
Specifically, I noticed the CSS compiler balking at: `*zoom: 1`. So I asked the Genie about it and here's the explanation it gave. 
> The `*` in `*zoom: 1;` is a CSS hack called the "star property hack" 
> or "IE7 hack". It's used to target Internet Explorer 7 specifically.
> 
> Here's what it does:
>   * The * prefix makes the property only apply to Internet Explorer 7 
>     and earlier versions. 
>   * Other browsers ignore properties that start with `*`.
>   * `zoom: 1` is a Microsoft-specific CSS property that triggers 
>     "hasLayout" in IE, which is needed for certain layout behaviors 
>     to work correctly.
>
> In this case, it's being used as part of a clearfix implementation. 
> The …
=> Remove long-outdated "star property hack"

.changeset/ten-lamps-breathe.md, packages/perseus/src/widgets/interactive-graph.tsx
The core of the problem is that IG doesn't treat "user input" as real "user input" - there's two layers:
1. The user input that represents the current state of the graph
2. The user input the represents the scoreable data that comes from `StatefulMafsGraph`
In my original PR, I passed the #1 user input up to Renderer which included all the coordinates. However StatefulMafsGraph hides additional data, in this case `closedPolygon`, which determines if `getUserInput` returns `null` or the coordinates the user has placed. This isn't ideal, but changing it would be tricky and is way beyond the scope of the PR.
Instead I'm leveraging the existing logic to convert StatefulMafsGraph state into a scoreable graph (`getGradableGraph`) via StatefulMafsGraph's `getUserInput`.
Issue: LEMS-3257
I can't …
=> LEMS-3257: Fix IG regression regarding user input

.changeset/tender-masks-tell.md, .changeset/wet-boats-turn.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/radio-widget.ts, packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap, packages/perseus-core/src/widgets/radio/derive-num-correct.test.ts, packages/perseus-core/src/widgets/radio/derive-num-correct.ts, packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx, packages/perseus-editor/src/widgets/radio/editor.tsx
We had 2 bugs reported related to the numCorrect value not correctly updating for the Radio Widget. 
This PR fixes two of these bugs by ensuring that we're recalculating the numCorrect value when we delete choices, or switch in and out of multiple selection mode. 
Unfortunately, I have not been able to recreate the third bug in the ticket. 
Issue: LEMS-3230
- New tests pass
=> docs(changeset): Fixed bugs related to numCorrect not updating properly for the Radio widget

.changeset/sharp-timers-notice.md, packages/perseus-score/src/util/answer-types.ts, packages/perseus-score/src/widgets/input-number/score-input-number.test.ts, packages/perseus-score/src/widgets/input-number/score-input-number.ts, packages/perseus-score/src/widgets/numeric-input/score-numeric-input.test.ts, packages/perseus-score/src/widgets/numeric-input/score-numeric-input.ts
This PR fixes a bug where users would be erroneously marked correct if they entered `16,000` when the answer is `16`.
The issue was that we weren't properly handling locale-specific decimal separators in the Numeric Input and Input Number Widgets. While `scoreExpression` was already passing the locale to get the appropriate decimal separator (albeit with KAS), the other two widgets were missing this functionality.
Changes made:
1. Added locale parameter to `scoreInputNumber` and  `scoreNumericInput` functions
2. Added logic to pass the locale-specific decimal separator to the validators
3. Added tests to verify correct behavior with different locales
This ensures consistent behavior across all three scoring functions and prevents incorrect grading when users enter numbers with thousands …
=> Ensure that we properly parse any decimals in the userInput's according to the user's locale

.changeset/tiny-apes-love.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts
There is currently an issue where a concave polygon will have its concave vertex jump between
its internal and external angle, only if the other vertices around it line up in the same
x and y values as each other. This is happening because of the raytracing method being
used to determine the angles, which has the wrong value when the rays intersect.
To fix this, I'm replacing the raytracing method with the cross product method to determine
if a particular vertex in the polygon is convex or concave.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3262
| --- | --- |
| ![image](https://github.com/user-attachments/assets/740be605-81dd-492a-811a-bfc9cb10edb8) | <img width="344" alt="image" src="https://github.com/user-attachments/assets/5cf567a6-13ab-45f0-be57-c4678d594 …
=> [Interactive Graph] [Polygon] Fix concave polygon vertex labels jumping between interior and exterior angles

.changeset/breezy-insects-shop.md, packages/perseus/src/widgets/python-program/python-program.tsx
I was looking at something unrelated and noticed this was kind of silly.
=> Remove getDOMNodeForPath from PythonProgram

.changeset/loud-cups-ring.md, packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-regression.test.ts.snap, packages/perseus-core/src/widgets/core-widget-registry.ts, packages/perseus-core/src/widgets/deprecated-standin/index.ts
This PR adds a missing widget registration to `perseus-core` for the `deprecated-standin` widget. Technically, this widget does nothing, but our default for widgets that don't have an explicit registration is to be _inaccessible_. This means that we would consider assessment items having a deprecated widget as inaccessible when, in fact, they are (because the `deprecated-standin` has no interactive elements). 
This PR has some snapshot updates caused by use having an entry in the core registry for the deprecated-standin widget now (specifically because when we apply defaults for a widget, we leave the widget options unchanged [if no widget is registered](https://github.com/Khan/perseus/blob/843d66257ceb32b7c3d3eea4dea47dfda58e7945/packages/perseus-core/src/widgets/apply-defaults.ts#L33), …
=> Mark `deprecated-standin` widget as accessible

.changeset/warm-sheep-join.md, packages/perseus-core/src/analytics.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Removing the deprecated analytics event PerseusInteractiveGraphWidgetRendered, in favor of the PerseusWidgetRenderedTI event we've been using
Issue: LEMS-2827
Run `pnpm test` should pass all tests.
=> [Analytics] Removing deprecated analytics event PerseusInteractiveGraphWidgetRendered

.changeset/pink-rats-matter.md, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-labels.tsx, packages/perseus/src/widgets/interactive-graphs/backgrounds/utils.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
The alongEdge graph label overflows out of the container on web, and is completely cut off on mobile.
This only happens for very specific cases where the y-axis tick labels are rendered outside the graph. This means when the x range is greater than 0, 0, or relatively close to 0.
To fix this, I added extra padding by the exact offset needed for these edge cases.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3282
| --- | --- |
| <img width="425" height="533" alt="Screenshot 2025-07-16 at 12 52 11 PM" src="https://github.com/user-attachments/assets/23c4141b-38f0-4f40-852b-53db95c980ab" /> | <img width="395" height="495" alt="image" src="https://github.com/user-attachments/assets/b887e77e-23bb-47d6-879d-c5eb3d2924f4" /> |
Observe how the y-axis label stays in the …
=> [Interactive Graph] Stop alongEdge labels from overflowing out of graph container

.changeset/strange-snakes-lay.md, packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts, packages/perseus/src/widgets/interactive-graphs/utils.ts
We received a request from content authors to allow users to move a point to
the edge of the graph, specifically for the case that a graph start at 0 in
both the x and y direction (like in physics) and a point needs to sit at (0, 0).
To allow this, I'm making it so that the bounds are not inset and the overflow
is not hidden ONLY FOR POINT GRAPHS.
I'll explore other graph types if specifically requested, but this is not possible
for most graph types because of their overflow.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3213
| --- | --- |
| <img width="368" height="388" alt="Screenshot 2025-07-16 at 3 30 45 PM" src="https://github.com/user-attachments/assets/00e5f058-75e5-4ae2-84a6-7dd770656ec9" /> | <img width="377" height="404" alt="Screenshot 2025-07-16 at 3 …
=> [Interactive Graph][Point] Allow points on Point graphs to sit on edge of graph

.changeset/spotty-needles-divide.md, packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx, packages/perseus-editor/src/widgets/radio/editor.tsx
Redo of https://github.com/Khan/perseus/pull/2659 because it got messed up in an accidental merge.
Small update to new editor UI.
Right now, the editor allows the ability to add multiple "none of the above" choices.
In this PR, I'm hiding the "Add none of the above" button if there is already
a "none of the above" answer choice.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3229
`pnpm jest packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-editorpage-widgets-radio--multi-choice
=> [Radio] | (CX) | Stop showing NOTA button if NOTA choice exists in the editor

.changeset/clever-melons-sparkle.md, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-regression.stories.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.stories.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph.testdata.ts
We've had bugs in Interactive Graph where certain labels are hitting the Javascript floating point issues. 
LEMS-3241
This PR fixes the floating point bug related to the point labels by ensuring that we're always showing the same number of significant digits as the snap step. This ensures that the labels are always a consistent length.
LEMS-3216
This PR also fixes LEMS-3216 with a very similar solution, in order to ensure the tick steps all have the same number of sig figs. 
Additionally, there's a minor bug-fix that was snuck in here to help fix a regression in a testing tool that's necessary to properly recreate some of these issues. All that was required to fix the issue was wrapping the new UserInputManager around the renderer in the interactive graph regression story file. 
Issue: …
=> docs(changeset): Bugfix to ensure Interactive Graph tooltips display points with the same granularity as the snapStep

.changeset/long-moose-refuse.md, packages/perseus-editor/src/hint-editor.tsx, packages/perseus-editor/src/widgets/__tests__/graded-group-editor.test.tsx, packages/perseus-editor/src/widgets/graded-group-editor.tsx, packages/perseus/src/user-input-manager.test.tsx, packages/perseus/src/user-input-manager.tsx
So this was a little weird. I went through the repro steps, got the JSON, copy/pasted it, and gave it a `PerseusArticle` type. According to the type, the editor was making invalid JSON:
``` JSON
"hint": {
"content": "((Hint))"
},
```
A hint is supposed to be a `PerseusRenderer` and that requires `widgets` and `images`. I think this was a long-time bug that just never showed itself:
``` TS
// hint-editor.tsx
// note it's a full PerseusRenderer 
const hints = this.props.hints.concat([
{content: "", images: {}, widgets: {}},
]);
// graded-group-editor.tsx
// note it's an incomplete PerseusRenderer
const hint = {content: ""} as const;
```
Anyway, the reason this bug manifested now is: `PerseusRenderer` is supposed to have `widgets` and my new code was expecting `PerseusRenderer` to have …
=> Bugfix: fix hints in GradedGroups

.changeset/old-geese-shop.md, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.test.ts, packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.tsx, packages/perseus/src/widgets/interactive-graphs/backgrounds/utils.ts
Right now, the minimum tick is usually ommitted to make space for the axis.
However, this is not necessary if the axis doesn't go through this spot.
We got a request from content to show the 0s if possible in a 0-start graph,
and this can easily done by just checking for this case.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3214
| --- | --- |
| <img width="542" height="531" alt="Screenshot 2025-07-23 at 4 38 51 PM" src="https://github.com/user-attachments/assets/8f0efa91-8018-4e4b-a323-a2a6888aac57" /> | <img width="528" height="523" alt="Screenshot 2025-07-23 at 4 38 55 PM" src="https://github.com/user-attachments/assets/b23c8295-4139-4bb7-8e85-72e4f230d379" /> |
`pnpm jest packages/perseus/src/widgets/interactive-graphs/backgrounds/axis-ticks.test.ts` …
=> [Interactive Graph] Show min tick when axis doesn't go through it

.changeset/slimy-sloths-listen.md, packages/perseus/src/widgets/graded-group/graded-group.tsx
A regression was introduced recently while implementing a new approach to user input, which also gave us greater specificity into which props we were passing down into the renderer. However, the `keypadElement` was hidden in that `this.props` monolith, and was no longer being provided to the Graded Group widget. This PR adds it back. 
You can test this by comparing the following two storybook pages. (Make sure to turn on mobile mode)
Production: https://khan.github.io/perseus/?path=/docs/widgets-graded-group-set--docs
This PR: https://650db21c3f5d1b2f13c02952-rikyqkpyck.chromatic.com/?path=/docs/widgets-graded-group-set--docs
Issue: LEMS-3324 
- Tests pass
=> docs(changeset): Bugfix for regression that causes keypad to no longer work in graded groups.

.changeset/honest-ghosts-attend.md, packages/perseus-editor/src/widgets/radio/auto-resizing-text-area.tsx, packages/perseus-editor/src/widgets/radio/radio-editor.module.css, packages/perseus-editor/src/widgets/radio/radio-option-settings.tsx
We got a request from content authors to dynamically resize the text area as they type
so that they don't have to manually resize the text area all the time.
There is actually already a ticket for this in Wonder Blocks for Wonder Blocks TextArea,
but I have this quick solution in the meantime. I put a TODO to make sure that we use WB
whenever it's ready.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3327
https://github.com/user-attachments/assets/ad67e558-e0db-474d-9f3a-38d51ba4faa4
https://github.com/user-attachments/assets/897470e2-e051-48df-8347-ab9a53c1c75e
Unfortunately there isn't really a way to unit test styles...?
Storybook
- http://localhost:6006/?path=/docs/widgets-radio-editor-demo--docs#single-choice-2
- Type a bunch of stuff in `content` and `rationale` text areas
- …
=> [Radio] | (CX) | Add dynamically resizing text areas to Radio editor UI

.github/workflows/node-ci.yml, packages/perseus-core/src/data-schema.ts
A small PR to tweak the diff format used for schema change notices. Switching to `--unified` diffs makes for much clearer output.
Issue: <none>
Compare output. Note that the change of `range` from `number[]` to `string[]` is split up in the **Before** but is together in the **After** (seems much more readable (to me at least)). 
| -- | -- |
| <img width="637" height="673" alt="image" src="https://github.com/user-attachments/assets/3c42cc21-d45b-4df5-8201-45ab40bfff9a" /> | <img width="907" height="806" alt="image" src="https://github.com/user-attachments/assets/e0643aef-2dd7-462b-9fe6-8e89ca573836" /> |
=> Schema change detection - change diff format

.changeset/tasty-jars-invent.md, packages/perseus-editor/src/__docs__/editor-page-with-storybook-preview.tsx, packages/perseus-editor/src/editor-page.test.tsx, packages/perseus-editor/src/editor-page.tsx, packages/perseus-editor/src/widgets/__docs__/interactive-graph-editor.stories.tsx
I kept noticing that the `frameSource` prop is a required prop but we don't do anything with it, so this PR finally removes it. It looks like at one point it was related to preview, but now we use the `previewURL` instead.
Issue: "none"
`pnpm tsc`
=> [Editor] Remove unused frameSource prop from EditorPage component

.changeset/thick-pots-relax.md, packages/perseus/src/widgets/radio/radio.ff.tsx
The preview in storybook was broken because of the following error
```
TypeError: Cannot read properties of undefined (reading 'choicesSelected')
```
Fixing that here.
| --- | --- |
| <img width="492" height="601" alt="Screenshot 2025-07-25 at 3 19 52 PM" src="https://github.com/user-attachments/assets/cbffc071-1419-4cd3-ba22-d783dc266caa" /> | <img width="476" height="827" alt="Screenshot 2025-07-25 at 3 20 04 PM" src="https://github.com/user-attachments/assets/b13f506e-8e8f-44cb-9219-52114c606339" /> |
Issue: none
- Go to http://localhost:6006/?path=/docs/widgets-radio-editor-demo--docs#multi-choice
- Confirm that the preview shows the Radio widget
- Confirm that the browser console has no errors
=> [Radio] | (DX) | Add null check in radio.ff.tsx

.changeset/poor-lamps-leave.md, packages/perseus-editor/src/widgets/__tests__/expression-editor.test.tsx, packages/perseus/src/widgets/__testutils__/renderQuestion.tsx, packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap, packages/perseus/src/widgets/graded-group/graded-group.test.ts, packages/perseus/src/widgets/graded-group/graded-group.testdata.ts, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx, packages/perseus/src/widgets/numeric-input/input-with-examples.tsx
This PR forms another small set of unit test cleanup/fixes. It includes: 
* Mock WB ToolTip differently so that it's a bit more dependable (avoids needing shared variables)
* Fix test names for expression-editor
* Add component names so they show up in React stack traces properly
* Fix graded-group tests to be a bit more accurate
Issue: "none"
`pnpm test`
=> More test cleanup

.changeset/five-pans-exist.md, packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.test.ts, packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.ts
Something's wrong with the way we're initializing user input or how Classroom is moving between questions: `userInput` shouldn't be null/undefined because it should be initialized by `getStartUserInput`. However it seems like TUT is running into a place where user input isn't initialized properly and it's blocking progression. This is a "hail mary" attempt to at least not block things from progressing.
Issue: [TUT-2738](https://khanacademy.atlassian.net/browse/TUT-2738)
[TUT-2738]: https://khanacademy.atlassian.net/browse/TUT-2738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `choicesSelected` bug in `getPromptJSON`

.changeset/weak-dots-wave.md, packages/perseus-core/src/parse-perseus-json/perseus-parsers/categorizer-user-input.test.ts, packages/perseus-core/src/parse-perseus-json/perseus-parsers/categorizer-user-input.ts, packages/perseus-core/src/validation.types.ts, packages/perseus/src/widget-ai-utils/categorizer/categorizer-ai-utils.ts, packages/perseus/src/widgets/categorizer/categorizer.tsx
Categorizer user input was typed as `number[]`. _Correct_ answers can only be `number[]` but incomplete user input could be `Array<number | undefined>`. To complicate things, `JSON.stringify` converts `[undefined, 2]` to `[null,2]` so the backend also needs to support `null`.
So fix the parser to handle number, undefined, or  null.
Issue: LEMS-3344
=> Categorizer UserInput parsing issue (null / undefined values)

.changeset/wild-hotels-help.md, packages/perseus/src/widgets/radio/__tests__/base-radio.testdata.ts, packages/perseus/src/widgets/radio/base-radio.tsx, packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx, packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx, packages/perseus/src/widgets/radio/radio-component.tsx
Consumes choice ids in radio widget 
- Accidentally swapped JIRA numbers - landed 3070 with changes for 3069; will be using 3069 for this change
Issue: LEMS-3069
In Local Dev, validated
- User able to answer question
- Content Author able to add, delete, update, move choices
Editor add, delete, update, move choice
https://github.com/user-attachments/assets/ff323649-2414-4aa9-a877-4ae454597a38
=> feat(LEMS-3069): Consumes choice Ids in radio widget

.changeset/lovely-tomatoes-speak.md, packages/perseus/src/widgets/expression/__docs__/expression.stories.tsx, packages/perseus/src/widgets/expression/expression.test.tsx, packages/perseus/src/widgets/expression/expression.tsx
The only thing the Expression transform was doing was using widget options to compute the keypad configuration. That's something it could just do internally in the widget.
Issue: LEMS-3199
=> Remove Expression transform

.changeset/olive-news-report.md, packages/perseus/src/styles/widgets/free-response.css, packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap, packages/perseus/src/widgets/free-response/free-response.stories.tsx, packages/perseus/src/widgets/free-response/free-response.tsx
This commit changes the styling on the Free Respone Widget to no longer
force bold styling of the question text. Instead, we will allow the
content creators to use Markdown to bold all or part of the question, if
they want to.
Issue: https://khanacademy.atlassian.net/browse/AX-1596
- Open the Free Response Widget in Storybook.
- View the question on the Primary story.
- Verify that it is not rendered bold.
- In the browser DevTools, inspect the question text.
- Verify that it is not surrounded by `<strong>` tags.
- In the browser DevTools, inspect the question text of the "Bolded
Question" story.
- Verify that it is surrounded by `<strong>` tags.
=> Remove forced bold from Free Response question

.changeset/lemon-avocados-report.md, static/storybook-styles/preview.css
Storybook styling was overriding widget styles in certain situations. This adjustment places the Storybook styling in a sublayer, giving widget styles higher priority.
View any Storybook story with lists or paragraph tags (like the Radio widget) and notice that font size and line height are determined first by the widget, then by this styling.
=> Adjust Storybook styling to not interfere with widget styles

.changeset/new-bugs-burn.md, packages/perseus-editor/src/widgets/radio/editor.tsx
This just provides more accurate keys to React.
As a result of that, the focus order stays on the same choice when keyboard nav
is used to press a reorder button.
Note: There is something that's not right with the choice IDs in the editor storybook
currently, but I was able to add some manually to test this locally. Anakaren is going
to look into why the IDs are not being generated by the parser in a separate ticket.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3322
https://github.com/user-attachments/assets/2fe74afe-b34f-4092-a0ee-a1af5003e0cd 
https://github.com/user-attachments/assets/1da4cbc2-b8e5-429e-b818-3440de5ba37f 
- Manually put choice IDs in packages/perseus-editor/src/__testdata__/radio.testdata.ts
- Go to http://localhost:6006/?path=/docs/widgets-radionew-editor-demo- …
=> [Radio] Use choice IDs for the choice keys in the editor

.changeset/five-wasps-drum.md, packages/perseus/src/widgets/radio/__stories__/choice-indicator.stories.tsx, packages/perseus/src/widgets/radio/__stories__/multiple-choice-option.stories.tsx, packages/perseus/src/widgets/radio/__tests__/choice-indicator.test.tsx, packages/perseus/src/widgets/radio/__tests__/multiple-choice-component.test.tsx, packages/perseus/src/widgets/radio/__tests__/multiple-choice-option.test.tsx, packages/perseus/src/widgets/radio/choice-indicator.new.tsx, packages/perseus/src/widgets/radio/choice.module.css, packages/perseus/src/widgets/radio/choice.new.tsx, packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx, packages/perseus/src/widgets/radio/multiple-choice.module.css
Screen readers can access all the information in the radio widget, but some enhancements are needed to ensure clarity of what is being read. Specifically:
- The word "Choice" is prefixed to the choice letter
- The full choice content is connected to the choice button in order to present a complete readout of the choice
- The rationale is referenced via `aria-describedby` as additional material, leaving it to the screen reader to determine how to surface that information for the choice
Additionally, the choice button is marked with `aria-disabled` when in review mode to indicate that the button is no longer able to be activated.
Issue: LEMS-3364
1. Launch Storybook locally
2. Navigate to Widgets => RadioNew => [Docs](http://localhost:6006/?path=/docs/widgets-radionew--docs)
3. Using a …
=> [Radio] Enhance content for screen reader access

.changeset/heavy-beers-carry.md, packages/perseus/src/styles/styles.css, packages/perseus/src/widgets/image/__snapshots__/image.test.ts.snap, packages/perseus/src/widgets/image/image.tsx
As part of an archaic mobile design rehaul, the image widget had the
title added to its caption section and bolded. The code for this is
somewhat convoluted, and this separate design is not necessary.
Uniting the desktop/mobile code by removing the custom mobile section.
Issue: https://khanacademy.atlassian.net/browse/LEMS-3381
| --- | --- |
| <img width="560" height="699" alt="Screenshot 2025-08-18 at 4 50 33 PM" src="https://github.com/user-attachments/assets/8e831868-91fc-45f5-bbd1-f613267d58db" /> | <img width="569" height="711" alt="Screenshot 2025-08-18 at 4 50 39 PM" src="https://github.com/user-attachments/assets/e9ccc04e-1a8e-4745-943e-1a74e3e7b2ad" /> |
| --- | --- |
| <img width="575" height="660" alt="Screenshot 2025-08-18 at 4 50 44 PM" …
=> [Image] (UX) Remove the custom mobile styling for title and caption

.changeset/odd-plums-juggle.md, packages/perseus/src/widgets/radio/choice-indicator.module.css
The transition of the indicator color from a background of white to blue/purple is long enough to make it appear that there is a delay of registering the selection when compared to the color change of the "Check" button. This CSS change speeds up the transition time in an effort to reduce the apparent lag between the two.
Issue: LEMS-3354
=> [Radio] Adjust the transition time of the indicator so that it doesn't appear out of sync with the "Check" button

.changeset/thick-dogs-double.md, packages/perseus/src/widgets/radio/__docs__/multiple-choice-interaction-regression.stories.tsx, packages/perseus/src/widgets/radio/__tests__/radio.testdata.ts, packages/perseus/src/widgets/radio/choice.module.css
The text of choice should change color when that choice is selected.
Issue: LEMS-3357
1. Open Storybook (either locally or linked in this PR)
1. Navigate to any example in Widgets => RadioNew => Docs
1. Choose any answer from the options shown
- Note that the text of the choice changed color (matching the selected theme)
=> [Radio] Bugfix - Choice text not changing color when selected

.changeset/gorgeous-eyes-cheat.md, packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
When the widget is in "static" mode, it should show the correctness of each choice, just like in "reviewMode".
Issue: LEMS-3356
1. Open Storybook (either locally or linked in this PR)
1. Navigate to the static examples:
- Widgets => RadioNew => Visual Regression Tests => Static => Single Select Static
- Widgets => RadioNew => Visual Regression Tests => Static => Multi Select Static
1. Note that correctness is shown for the options
=> [Radio] Bugfix - Correctness indicator was missing in static widget

.changeset/strong-candles-argue.md, packages/perseus/src/components/scrollable-view.test.tsx, packages/perseus/src/components/scrollable-view.tsx, packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx
Fix to allow users to still scroll the scrollable content when the fieldset is disabled and staticOverlayStyles is applied after the user checked the answer
**Before**
https://github.com/user-attachments/assets/c63567f9-771e-4b60-bb7c-7d0dd4e7ff20
**After**
Issue: LEMS-3406
1. Navigate to the [ZND link](https://prod-znd-250826-3249-4e4c9ff.khanacademy.org/math/early-math/cc-early-math-add-sub-basics/cc-early-math[%E2%80%A6]b-word-problem-within-10/e/addition-word-problems-within-10)
2. In a question with a scrollable view, select the correct answer
3. After the question is marked correct
=> [Radio] Fix to allow users to scroll content after multiple choice is checked

.changeset/silent-hairs-exercise.md, packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
This quick PR converts our new Multiple Choice Widget to be a fully functional component with a `useImperative` handle for returning `getPromptJSON`. 
When we delete the old radio files + feature flag, we will probably need to move other functions into the `useImperative` handle (such as `getSerializedState` or `focus`). However, both of these methods are deprecated, so we should look into it when we're cleaning up the project. 
Issue: LEMS-3446
- Tests pass in Perseus
- Tests pass in our Frontend 
- Manual testing in Storybook and in our Frontend
=> [functionally-equivalent] Updating (New) Radio widget to be fully functional. 

.changeset/dirty-cougars-marry.md, packages/perseus/src/components/__docs__/graphie.mdx, packages/perseus/src/components/__docs__/graphie.stories.tsx, types/assets.d.ts
Add documentation warning for using Graphie component
| ------- | ---- |
| <img width="742" height="305" alt="image" src="https://github.com/user-attachments/assets/cc6baca7-fe46-4a38-a5a2-6650bf563f77" /> | <img width="765" height="301" alt="image" src="https://github.com/user-attachments/assets/c139dde9-409a-47bd-aec4-91fdcbd88b4e" /> |
=> Add documentation warning for using Graphie component

.changeset/eight-trees-travel.md, packages/perseus-editor/src/__tests__/editor.test.tsx, packages/perseus-editor/src/widgets/__docs__/image-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/image-editor.test.tsx, packages/perseus-editor/src/widgets/image-editor/image-editor.module.css, packages/perseus-editor/src/widgets/image-editor/image-editor.tsx, packages/perseus-editor/src/widgets/image-editor/image-settings.tsx, packages/perseus-editor/src/widgets/image-editor/image-url-input.tsx
Make the Image widget editor UI nicer to look at and use.
- Replace existing inputs with Wonder Blocks components
- Make the spacing look nicer
Bonus:
- Add more tests
- Break out the image URL input into a new file
Issue: https://khanacademy.atlassian.net/browse/LEMS-3386
Case | Before | After |
| --- | --- | --- |
| Empty | <img width="391" height="474" alt="Screenshot 2025-08-27 at 12 59 50 PM" src="https://github.com/user-attachments/assets/bf13d446-9af6-4ae7-afa5-6c23feef9950" /> | <img width="386" height="505" alt="Screenshot 2025-08-27 at 1 00 08 PM" src="https://github.com/user-attachments/assets/cf93a284-5dba-4ef3-a57e-ad2dbf748c02" /> |
| Warning | <img width="396" height="525" alt="Screenshot 2025-08-27 at 1 00 30 PM" src="https://github.com/user-attachments/assets/0039bb9f-82ab …
=> [Image] | (CX) | Modernize the Image widget editor UI

.changeset/fast-ways-buy.md, packages/perseus-editor/src/widgets/__tests__/image-editor.test.tsx, packages/perseus-editor/src/widgets/image-editor/image-settings.tsx, packages/perseus-editor/src/widgets/image-editor/image-url-input.tsx
It seems like saving empty strings as undefined might introduce inconsistency in our data.
Since these have been saved as `""` for years, I'm going back to doing it that way so
it's easier to understand our data in the future.
[Discussion](https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1756321954129759)
Issue: none
`pnpm jest packages/perseus-editor/src/widgets/__tests__/image-editor.test.tsx`
=> [Image] | (DX) | Revert to old way of saving empty string data for the sake of data consistency

.changeset/purple-taxis-itch.md, packages/perseus-core/src/index.ts, packages/perseus-core/src/utils/random-util.ts, packages/perseus/src/__testdata__/renderer.testdata.ts, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/__tests__/widgets.test.ts, packages/perseus/src/mixins/widget-prop-denylist.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.test.ts, packages/perseus/src/widgets/expression/__docs__/expression.stories.tsx, packages/perseus/src/widgets/group/group.test.tsx, packages/perseus/src/widgets/group/group.testdata.ts, packages/perseus/src/widgets/passage/__tests__/passage.test.tsx, packages/perseus/src/widgets/radio/__tests__/radio.test.ts, packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx, packages/perseus/src/widgets/radio/radio-component.tsx, packages/perseus/src/widgets/radio/radio.ff.tsx, packages/perseus/src/widgets/radio/radio.ts, packages/perseus/src/widgets/radio/serialize-radio.test.ts, packages/perseus/src/widgets/radio/util.test.ts, packages/perseus/src/widgets/radio/util.ts, packages/perseus/src/widgets/radio/utils/general-utils.test.ts, packages/perseus/src/widgets/radio/utils/general-utils.ts
This is a modified copy of this PR: https://github.com/Khan/perseus/pull/2800
I had #2800 ready to go, but there was an urgent need to land #2799 quickly. Unfortunately this caused a lot of merge conflicts but also some shifts around the logic I was working on. I just decided to redo #2800 with a version that worked with the new user input format.
Issue: LEMS-3199
Nothing should change from the learner's perspective. Unit tests added to make sure there were no major regressions we're trying to support.
---
From the original PR:
> Why this PR exists
>
> We're removing transform and staticTransform to support Answerless/Answerful rendering for the Server Side Scoring project. Now widgets will receive all of their widget options as props.
How this affects Radio
>
> For the most part, Radio's …
=> Remove Radio transforms (take 2)

.changeset/flat-moles-drop.md, packages/perseus/src/widgets/radio/choice-indicator.module.css, packages/perseus/src/widgets/radio/choice.module.css
Reverts Khan/perseus#2859
Decision: Feedback from QA, it's valuable and better experience to have the visual feedback when user selects a choice, having the horizontal outlines when we have a choice selected. Having the slight visual bug on iOS when tap-dragging to keep that UI outline on both Android and iOS.
Issue: LEMS-3467
=> Revert "[Radio] Fix iOS mobile hover issue when use is dragging the screen left or right"

.changeset/swift-dancers-join.md, packages/perseus/src/components/fixed-to-responsive.tsx, packages/perseus/src/components/image-loader.tsx, packages/perseus/src/components/svg-image.tsx, packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap, packages/perseus/src/widgets/image/__snapshots__/image.test.ts.snap, packages/perseus/src/widgets/image/image.tsx
There's a bug that's causing image widgets to render super weirdly when they're in a "grouped question" drawer.
This is actually two separate issues:
- way too much spacing, causing the image to shift below the visible spacing
- width is going over 100% of the container space
Fixing them here by removing the spacer in `<FixedToResponsive>` when rendered within an Image widget, and constraining `<ImageLoader>` to 100% width and height when dimensions are not provided.
Issue: none
Load these changes into local frontend dev server and check the following two paths:
- `/ela/8th-grade-reading-and-vocabulary/x435b1de09a877dd7:to-your-health-long-passage-practice/x435b1de09a877dd7:reading-argumentative-texts-to-your-health/e/athletes-and-mental-health`
- …
=> Fix image widget sizing within grouped questions

.changeset/stupid-rockets-float.md, packages/perseus/src/widgets/numeric-input/input-with-examples.test.tsx, packages/perseus/src/widgets/numeric-input/input-with-examples.tsx
Fix rendering error in InputWithExamples, changing replaceAll to replace to be old browser compatible
Issue: LEMS-XXXX
=> [Numeric Input] Fix rendering error in InputWithExamples, changing replaceAll to replace to be old browser compatible

.changeset/great-houses-wonder.md, packages/perseus-linter/src/rules/image-widget.test.ts, packages/perseus-linter/src/rules/image-widget.ts
There's a linter error that shows up if there is TeX in an image caption:
> No math in image captions: Don't include math expressions in image captions.
This was likely added before we had adequate i18n support for math expressions, but this is no longer the case. It should be safe to remove this linter warning now.
Issue: none
`pnpm jest packages/perseus-linter/src/rules/image-widget.test.ts`
Storybook
`/?path=/docs/widgets-image-editor-demo--docs#populated-within-editor-page`
| ----- | ----- |
| <img width="534" height="503" alt="Screenshot 2025-09-29 at 1 50 24 PM" src="https://github.com/user-attachments/assets/13a258c3-30bf-41a8-8ff8-1d2aa68d2c65" /> | <img width="499" height="449" alt="Screenshot 2025-09-29 at 1 50 33 PM" …
=> [Image] | (CX) | Remove "math in caption" linter error

.changeset/brave-boxes-rule.md, packages/perseus/src/__docs__/hints-renderer.stories.tsx, packages/perseus/src/hint-renderer.tsx, packages/perseus/src/hints-renderer.tsx, packages/perseus/src/server-item-renderer.tsx
Turns out that HintRenderer is also rendered outside of any other renderer in the frontend app.
This means that it also needs to have `dependencies` as a prop so it can provide it via React context.
- Ensure tests pass
- Open a frontend PR to update the HintRenderer props and ensure the hint editor works in devadmin
=> Require dependencies as a prop for HintRenderer

.changeset/weak-candles-hammer.md, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/mixins/widget-prop-denylist.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/expression/__docs__/expression.stories.tsx, packages/perseus/src/widgets/passage/__tests__/passage.test.tsx, packages/perseus/src/widgets/radio/__stories__/base-radio.stories.tsx, packages/perseus/src/widgets/radio/__tests__/base-radio.test.tsx, packages/perseus/src/widgets/radio/base-radio.tsx, packages/perseus/src/widgets/radio/radio-component.tsx
Remove isLastWidgetUsed from Perseus as it was unused, and really only ever used for the Radio Widget. 
Issue: LEMS-3363
- Tests pass
=> docs(changeset): Remove the isLastUsedWidget property from Perseus, as it is not used.

.changeset/shy-cats-cheat.md, packages/perseus/src/widgets/radio/__docs__/multiple-choice-initial-state-regression.stories.tsx, packages/perseus/src/widgets/radio/__docs__/multiple-choice-interactions-regression.stories.tsx, packages/perseus/src/widgets/radio/__docs__/multiple-choice-static-regression.stories.tsx, packages/perseus/src/widgets/radio/choice.module.css
The choice borders next to a correct choice (when in review mode) should not be visible as it is distracting. This PR adjusts the styling to account for these situations.
Issue: LEMS-3456
1. Open Storybook (use the link in this PR)
2. View the regression stories that "show solutions"
- Single Select: Widgets => RadioNew => Visual Regression Tests => Initial State => Single Select Show Solutions
- Multiple Select: Widgets => RadioNew => Visual Regression Tests => Initial State => Multiple Select Show Solutions
3. Notice that the horizontal borders between choices is not visible above and below choices that are marked correct
=> [Radio] Bugfix - Borders next to correct choices should not show

.changeset/fifty-buttons-join.md, packages/perseus-editor/src/__tests__/editor.test.tsx, packages/perseus-editor/src/diffs/__tests__/item-diff.test.tsx, packages/perseus-editor/src/widgets/__tests__/image-editor.test.tsx, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/components/__tests__/svg-image.test.tsx, packages/perseus/src/widgets/image/image.test.ts, testing/image-loader-utils.ts
Adds a test to make sure the ItemDiff component will correctly render and load an Image.
A change to the dependencies API caused a regression last week, and this test would have caught it.
Unfortunately in order to ensure it catches the regression, some tricky image loading mocking has to be done.
- Ensure the tests pass
=> Test that the ItemDiff component will render an image diff

.changeset/lovely-pants-add.md, packages/perseus/src/widgets/definition/definition.tsx
Small update based on design feedback. Definition was previously using the `font.body.lineHeight.large`,  but after a Figma design was created, we decided the `medium` size provided a better experience.
Clicked Story Update
- Confirm checks pass
- Check manually in Storybook
=> Definition style update based on Figma designs

.changeset/violet-files-accept.md, packages/perseus/src/widgets/radio/__docs__/multiple-choice-interactions-regression.stories.tsx, packages/perseus/src/widgets/radio/choice.module.css
Articles have extra styling that is overly broad, which prevents content in a multiple choice content from turning blue when selected. This PR adds a style rule with higher specificity to override it.
Issue: LEMS-3485
=> [Radio] Bugfix - Selected choices don't turn blue when in articles
