Khan/perseus

CONTRIBUTING.md, src/editor.jsx, src/widgets/radio.jsx, stylesheets/perseus-admin-package/editor.less
While playing a bit with the radio widget, I realized that there was no way to mask the correct choice as 'none of the above' manually, as this is something that could happen only via the *Auto-none of the above* feature (or least I couldn't find how to do it!).
So I thought of adding under the correct choice a checkbox input that lets the contributor decide if he wants to hide it, only to reveal it when the user chooses correctly. There can be only one 'none of the above' choice at any given time, and if the user decides to use the "auto" feature, then that takes precedence over the manual choice.
The idea would be to give contributors more control over how the question is structured, I hope it's something that can be useful to you
@ariabuckles This PR contains a little amendment to the …
=> [Radio] Allow contributors to mark correct choice as 'none of the above'

src/widgets.js
This branch simply renames the variable "static" so that it does not conflict with the JavaScript keyword. This allows minification with the google closure compiler.
=> Rename variable from static

node/environment.js, webpack.config.js, webpack.config.node-perseus.js
Hello! I'm working through the lint updating that I mentioned (issue #65) and I ran into a problem when updating things to ES2015 syntax. The .js files aren't currently being run through Babel in the build system so Webpack is rejecting ES2015 code in them.
The attached commit is a quick fix to just treat .js files the same as .jsx files, which keeps things nice and simple. Would that be appropriate? The only problem I can think of with that approach is that it runs the .js files through the React compiler too, so it would allow React code to be (accidentally) added to the .js files without being caught by the build system.
Another thing probably worth mentioning is that this causes the .js dependencies in lib/ to get run through Babel/React too, which makes the build a little slower and …
=> Use Babel on .js files as well as .jsx

lib/raphael.js
`delete Raphael` will error in strict mode because deleting
variables is unsupported. I believe this should be
`delete window.Raphael`, which I have changed it to, but
it also should be irrelevant because no one actually calls
Raphael.ninja in perseus.
=> Raphael: Fix error in strict mode

README.md
I made a repo to include all of perseus' global dependencies, and demo
how to require that. This seems to be a lot of the questions we get in
issues, so maybe linking to this in the readme can help people there.
This commit adds a link to https://github.com/ariabuckles/perseus-configured
in the README so that people can more easily find all the globals necessary to
use this, and so that we can maybe link it in issue answers.
=> README: Add a link to perseus-configured

.github/workflows/node-ci.yml, config/build/rollup.config.js, package.json, packages/perseus-editor/package.json, packages/perseus/package.json
This also simplifies rollup.config.js.  We now assume that we're always building the browser.  I've also update the package.json files for each of the packages we're building to only set `main` and `module`.  This should avoid any issues that might have arose when consuming the module from the fact that there were essentially two different builds for the same package.
Issue: None
- yarn build:prodsizecheck
- push to GitHub, see that the "checks" pass
=> Simplify rollup.config.js

.eslintrc.js, packages/perseus/package.json, yarn.lock
This makes it so we don't have to rebuild every time we make a change to an export just to make eslint happy.
Issue: none
- rename 'foo' to 'foobar' and update all imporst
- yarn lint, see that there are no errors
=> Add eslint plugin to resolve package aliases

.github/workflows/release.yml
In #125 I copy/pasta'd the release workflow from khan/graphql-flow and failed to notice that one of the actions was pointing to a path that doesn't exist.  This audit updates the release workflow to use the same shared-node-cache action that we use in the other workflows in this repo.
Issue: None
- create a PR with a changeset after this lands
- land that PR
- see that the release workflow runs correctly to create a "Versions" PR
=> [🔥AUDIT🔥] Use the shared-node-cache action to set up node

packages/perseus-editor/package.json, packages/perseus/package.json
pre-publish checks for index.js in the dist folders.  Since we're only build the "browser" variant, we may as well have the files called index.js.
Issue: None
- yarn build
- node utils/pre-publish-check-ci.js
=> Tweak package.json files so that pre-publish check succeeds

.changeset/green-bags-study.md, packages/kmath/src/line.js, packages/kmath/src/point.js, packages/kmath/src/vector.js
`kmath` sometimes interchanges the idea of `$ReadOnlyArray<number>` with `[number, number]` (specifically a 2D array). This causes problems with clients that know they're passing in a tuple of two numbers but receive a `$ReadOnlyArray<number>` out.
This PR changes many of the functions (especially in vector.js) to use a generic type so that the returned vector's arrity matches the input argument(s).
Issue: LP-11430
`yarn flow` is good
`yarn test` is also good
=> Make Flow types much better

config/test/test-setup.js
We still have a few enzyme tests in our codebase. In the near future we'll migrate them (LP-11633), but for now it's relatively easy to get them passing.
Issue: "none"
`yarn test renderer-api_test matcher_test`
=> Set up React 16 Enzyme adapter for tests

config/test/test-setup.js, packages/kmath/.babelrc.js, packages/perseus-editor/.babelrc.js, packages/perseus/.babelrc.js
I attempted to update a snapshot by running something like `yarn test -u zoomable_test.jsx` and I got a babel error. Turns out the `.babelrc.js` in the perseus package dir was pointing at an non-existant file. 
Issue: "none"
`yarn test -u zoomable_test.jsx` doesn't fail
=> Fix path in `packages/perseus/.babelrc.js`

packages/perseus-editor/src/util/register-all-widgets-and-editors-for-testing_test.js
This test ensures that there is an editor for each widget. Editors are now in a different package so this test makes sense to live in the `perseus-editor` package.
Issue: "none"
`yarn test register-all-widgets-and-editors-for-testing_test.js`
=> Move widgets have editors to perseus-editor package

config/test/test-setup.js, packages/perseus/src/widgets/__tests__/definition_test.js, packages/perseus/src/widgets/__tests__/dropdown_test.jsx
I ended up having to revert to using real timers to make the tests pass.  It's possible this could be fixed with multiple calls to jest.runOnlyPendingTimers().  This is something we could explore in the future to avoid real timers.
Issue: None
- yarn test
=> Fix failing tests for dropdown and definition widgets

.github/workflows/node-ci.yml
Running the jest tests with coverage and the "Check Builds" both take a while (multiple minutes) so having them as separate jobs should help our checks complete more quickly.  I've also move `yarn coverage` into its own check and move the `jest test <CHANGED_FILES>` into the Flow/Eslint check. 
Issue: None
- watch the "Checks" output and see that the jobs completely more quickly
=> Speed up checks through better parallelization

packages/perseus/src/widgets/__stories__/unit.stories.jsx, packages/perseus/src/widgets/__stories__/video-transcript-link.stories.jsx, packages/perseus/src/widgets/unit.jsx
Migrates a bunch of fixtures to storybooks for perseus.
Issue: https://khanacademy.atlassian.net/browse/LP-11480
- Load storybook
- **You should see stories for things that were previously fixtures**
=> Migrate Perseus Fixtures to Storybooks (round 8)

.github/actions/filter-files/action.yml, .github/actions/full-or-limited/action.yml, .github/actions/json-args/action.yml, .github/workflows/node-ci.yml
Currently, eslint is giving warnings because we're passing it changed files that aren't .js files.
I'm bringing over the composite actions from the graphql-flow repo to fix this. I'm planning on extracting them out into a separate github actions monorepo soon, so this duplication is temporary.
Issue: https://khanacademy.atlassian.net/browse/FEI-4498
🤞
=> Bring over local actions from graphql-flow to clean up our linting/testing/type checking steps

.github/workflows/node-ci.yml, package.json
Adds a npm script to show ESLint timings by rule. Also, removes the `lint:ci` script as it was essentially a duplicate of the `lint` script. We now just use `yarn lint` in CI also.
Issue: "none"
`yarn lint`
=> Add lint:timing and unify our lint command(s)

package.json
I encountered a PR [check that failed](https://github.com/Khan/perseus/runs/6279901778?check_suite_focus=true) when we did the bundle size check (`perseus-renderer.less` imports `math-input`'s generated CSS from `dist/index.css`, but that file isn't generated during the size check... read on). The bundle size check only generates the ESM bundles. This complicates asset generation because Rollup places generates assets in the dir as the output file. 
So currently we end up with duplicated assets in `dist/` and `dist/es`. 
For now I've changed the bundle size check to generate all formats.
Issue: LP-11432
`yarn build:prodsizecheck` can run to completion
=> Always build everything for size check (otherwise we have missing assets in dist/)

.changeset/yellow-turkeys-call.md
I noticed the issue when I saw that the "Version Packages" PR was going to publish "kas" without the prefix.
- n/a
=> [🔥AUDIT🔥] Add @khanacademy prefix to kas package name

.flowconfig, config/test/test.config.js, packages/perseus/src/jipt-paragraphs.js, packages/perseus/src/perseus-markdown.jsx, packages/perseus/src/pure-markdown.js, packages/perseus/src/widgets/passage/passage-markdown.jsx, packages/simple-markdown/src/index.js
Lands after moving simple-markdown into the mono-repo.
Changes the imports to use the new @khanacademy prefix for the package.
Issue: https://khanacademy.atlassian.net/browse/LP-11429
- Build the repo
- **All should be well**
=> Change imports for simple markdown

config/test/test.config.js, packages/math-input/src/store/index.js
I noticed that some of our tests were failing if we hadn't already built the files.  We should be running tests from source only so that we don't have to rebuild every time we want to run the tests.  I've updated the jest config to read the .source field from the package.json in each of the packages so we shouldn't have to make any changes to this when we add new packages.
This also uncovered an issue with a redux import in one file.
- yarn clean
- yarn test
=> Ensure that have a module mapper entries for all packages in our jest config

packages/kas/package.json, utils/pre-publish-check-ci.js
The pre-publish CI check that we run caught this.  When I ran this check locally, I discovered it was also trying to publish 'underscore' because fast-glob found it (and other packages) in packages/kmath/node_modules.  I tightened up the path to only consider package.json files in immediate subdirs of packages/.  This fixed the 'underscore' issue and the check passes locally now.
Issue: None
- node utils/pre-publish-check-ci.js
=> [🔥AUDIT🔥] Make 'kas' package public

packages/simple-markdown/src/__tests__/simple-markdown_test.js, packages/simple-markdown/src/index.js
There was a minor typo which resulted in rules not have access to state in certain situations.
Issue: None
- yarn test simple-markdown
=> Fix failing simple-markdown tests

.changeset/friendly-zoos-smile.md, packages/math-input/src/components/provided-keypad.js, packages/math-input/src/index.js, packages/perseus-editor/src/components/link.jsx, packages/perseus/src/mixins/provide-keypad.jsx
After updating webapp to use the new packages, Flow is complaining about @khanacademy/math-input not exporting 'Keypad' even though it is.  Adding a '// @flow' comment to math-input's index.js fixes the issue.  I also noticed that there were some missing props on ProvidedKeypad so I added them.  Since this component spreads its props into one of its child components there's likely more props that could be added.  I only added the ones that people seemed to be using.
Issue: None
- yarn flow
=> Fix Flow types in math-input

.changeset/gorgeous-clouds-grin.md, packages/perseus/src/index.js, packages/perseus/src/types.js
The `useVideo` hook that is required in PerseusDependencies accepts a parameter type `VideoData`, but we don't export that. So this PR just fixes that. 
Issue: "none"
=> Export VideoData (used by PerseusDependencies)

.changeset/heavy-starfishes-check.md, packages/perseus/src/types.js, testing/test-dependencies.js
The `InitialRequestUrl` key in PerseusDependencies is quite big and much of it goes unused in Perseus. Trimming it down to teh absolute minimum we need so that we sidestep needing to pass in all these pieces of (unused) data (especially in non-webapp usages).
Issue: "none"
`yarn flow`
`yarn test`
=> Trim down InitialRequestUrl to only required fields

.changeset/five-wasps-raise.md, packages/perseus-editor/src/index.js
This one re-export was causing issues for webpack in webapp.
Issue: None
- yarn build
- copy files from packages/perseus-editor/dist into services/static/node_modules/@khanacademy/perseus-editor/dist (in webapp)
- see that the exercise editor loads without errors
=> Don't re-export Perseus from @khanacademy/perseus-editor

.changeset/stale-goats-joke.md, config/build/rollup.config.js, package.json, yarn.lock
The terser() plugin produces a bundle for @khanacademy/perseus-editor that webapp's webpack has trouble loading correctly.  While the build completes, when a page is loaded the imports this package, it failes with: 'TypeError: Object(...) is not a function'.
Disabling terser() fixes the issue.  I've created FEI-4557 to attempt to fix this in the future, possibly by upgrading to webpack 5 or tweaking the terser() config.
NOTE: The other packages that we publish do not appear to be affected by this issue.
Issue: None
- yarn build
- copy dist/ folder for perseus-editor over to webapp's static service
- in webapp delete genwebpack/.cache-loader
- restart the dev server
- load http://localhost:8088/devadmin/content/exercises/evaluating_expressions_1/47765362/xf536eb63390a6371, see that it …
=> Disable terser rollup plugin

.changeset/wild-shoes-juggle.md, packages/kas/package.json, packages/math-input/package.json, packages/simple-markdown/package.json
This should hopefully result in more packages being bumped.  In theory all packages should get bumped whenever there's a change to perseus-build-settings.
Issue: None
- land this audit and check to see what packages were auto-bumped in the "Version Packages" PR
=> [🔥AUDIT🔥] Add perseus-build-settings as a dev dep to packages that were misisng it

packages/perseus/src/widgets/dropdown.jsx
Tidies up the drowndown widget a bit.
- Removes single usage of underscore in favor of modern JS `map`
- Removes an ESLint error around prop ordering
- Set a default blank value, fixes a flow error
Issue: https://khanacademy.atlassian.net/browse/LP-11697
- Everything should work the same as before
=> Tidying up on Dropdown widget

.github/workflows/release.yml
There was an issue with storybook not being able to find a .css import from node_modules/math/index.css.  THis PR should fix that.
Issue: None
- yarn clean
- yarn build
- yarn build-storybook
- wait for release workflow to run
=> [🔥AUDIT🔥] Fix release workflow by building packages before building storybook

.changeset/happy-windows-repair.md, packages/math-input/src/index.js
@khanacademy/math-input clients sometimes use the CursorContext as part of using the math-input project. Instead of re-defining the values in the object, this PR adds it as an export from the main module.
Issue: MOB-4525
=> Export CursorContext

.changeset/rare-snails-prove.md, packages/math-input/src/components/input/cursor-contexts.js, packages/math-input/src/index.js
As it says on the title, just exporting more types needed by clients.
Issue: "none"
=> Export KeyConfigs and flow-type CursorContexts

.changeset/wild-pumas-whisper.md, packages/math-input/src/utils.js
This ticket was almost complete except for the icu part of it.  This PR finishes it off, but replace window.icu with wonder-blocks-i18n to determine the decimal separator.
Issue: LP-11658
- yarn test math-input
- yarn flow
=> LP-11658: Use wonder-blocks-i18n to determine the decimal separator

.changeset/thick-lizards-care.md, packages/perseus/src/widgets/definition.jsx
Now that we're using the WonderBlocks Popover widget, we don't need to manually add `margin` to the body. Leaving it in causes the popover anchor arrow to have a gap between it and the actual popopver. (see screenshots)
|---|---|
| <img width="300" alt="image" src="https://user-images.githubusercontent.com/77138/172737080-e15a867f-a98d-4d51-892c-6c15def4f2a0.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/77138/172737047-f9e7f899-98cf-47fb-a6fe-8a55cf7fe98b.png">| 
Issue: MOB-4532
Run storybook: `yarn storybook`
Navigate: **Perseus** >> **Widgets** >> **Definition** >> **Question 1**
Tap on one of the definitions. 
Note that the anchor is attached to the popover (no gap)
=> Remove old margin from definition body (Popover manages that now)

.changeset/nine-elephants-call.md, packages/perseus/src/types.js, testing/test-dependencies.js
It turns out that we don't ever use these in Perseus, so I'm removing them.
Issue: "none"
✅ `yarn flow`
✅ `yarn test`
✅ `yarn build`
=> Remove isPhone and isTablet keys in dependencies.

.changeset/pink-houses-build.md, packages/perseus/src/types.js, packages/perseus/src/widgets/__tests__/graded-group-set-jipt_test.jsx, testing/test-dependencies.js
I noticed that the `domInsertChecks` are not used at all in our Perseus code today, except for setting dummy values for tests. Removing it to trim down our Perseus dependencies where we can. 
Issue: "none"
`yarn test`
`yarn flow`
=> Remove unused JIPT.domInsertChecks

.changeset/bright-mayflies-remain.md, packages/perseus/src/definition-context.js, packages/perseus/src/renderer.jsx, packages/perseus/src/widgets/definition.jsx
Use React contexts to only show 1 definition at a time.
Issue: https://khanacademy.atlassian.net/browse/MOB-4547
- Open the storybook page with multiple definitions
- Open 1 definition
- Click the second definition
- **The first definition should automatically close**
=> Only show 1 definition at a time

.changeset/moody-mirrors-clean.md, packages/perseus/src/widgets/numeric-input.jsx
Found an unused function in numeric-input.jsx called getClasses. This specific function was not used in Perseus or webapp. Removed it to practice doing a PR.
Issue: none
Load the numeric input. Verify it looks correct.
=> removes unused function from numeric-input.jsx named getClasses

.changeset/yellow-cherries-pay.md, packages/math-input/less/main.less
We were seeing '@import' statements in built .css files which was causing some of the tooling in webapp to break since imports aren't a thing in CSS.  This PR fixes the issue by inlining MathQuill CSS in main.less.
Issue: None
- yarn build
- verify that dist/index.css for math-input and perseus packages no longer contains '@import'
=> Inline mathquill.css in math-input's main.less

.changeset/popular-paws-relate.md, .eslintrc.js, packages/kas/.eslintrc.js, packages/kmath/.eslintrc.js, packages/math-input/.eslintrc.js, packages/perseus-editor/.eslintrc.js, packages/perseus-editor/package.json, packages/perseus-error/.eslintrc.js, packages/perseus-linter/.eslintrc.js, packages/perseus-linter/package.json, packages/perseus/.eslintrc.js, packages/pure-markdown/.eslintrc.js, packages/simple-markdown/.eslintrc.js
It turns out that setting the "packageDir" option on this rule to be an array of all of the packages ends up checking the package.json in each of those directories when checking **any** file in the whole project.
What we want is to only consult the package.json that lives in packages/perseus/ when linting the files in that subdirectory.  Thankfully, eslint supports cascading config files.  This means we can add an .eslintrc.js in each of our packages' directories with only the 'import/no-extraneous-deps' rule.  Eslint will combine that with the .eslintrc.js at the root when linting files in each package directory.
Issue: None
- remove '@khanacademy/wonder-blocks-clickable' from packages/perseus/package.json
- see that widges/radio/choice.jsx now has a lint error for that import
=> Fix import/no-extraneous-deps config

.changeset/tough-kids-itch.md, packages/perseus/src/widgets/__tests__/radio/base-radio_test.jsx, packages/perseus/src/widgets/radio/choice.jsx
The problem being solved is that previously the multi-select radio widget would not deselect selected items. As a result, once all options were checked, it was not possible to deselect any. We found where the checked prop was being set and changed it to be a toggle based on the previous value of checked. We also set up a test for that functionality and created a copy of an older test to run outside of edit mode that tests selecting choices in single-select radio widgets.
Issue: LP-12636
Check functionality works as it should with checked options un-checking using Storybook
-Go to the multi-select section under the Radio widget
-Scroll down to multi-select within the docs tab (not the canvas)
-Try selecting and deselecting options to confirm they can be deselected
-Scroll up and confirm …
=> radio widget fix where multi-select options cannot be deselected 

.changeset/thick-cats-do.md, config/test/test.config.js
I was pairing with @handeyeco this morning and we noticed that test and stories files were showing up in the coverage reports generated by Wallaby.  We don't want them be included in the coverage report since they don't contain code that we're actually shipping.
Issue: None
- start wallaby
- wait for it generate a coverage report
- see that .stories.jsx and _test.js(x) files don't appear in the "files" tab
=> Don't collect coverage on tests or stories

.changeset/clean-sheep-add.md, .eslintrc.js, package.json, testing/test-tex.jsx, yarn.lock
Now that hooks are starting to get more use in Perseus, we should adopt the same lint rules that webapp is using for hooks.  This PR enables the following rules:
- react-hooks/rules-of-hooks: complains if hooks are used conditionally
- react-hooks/exhaustive-deps: complains if any deps are missing from useEffect's deps list.
It's okay to disable the 'exhaustive-deps' check, but it should be accompanied by a comment about why the rule is being disabled.
Issue: None
- yarn lint
=> Add lint rules from React hooks

.github/workflows/node-ci.yml
We're noticing that Codecov uploads are failing from time to time.  This is especially painful in the Perseus repo where we upload both jest and cypress coverage reports which are merged.  If both aren't uploaded it looks like we lost a bunch of coverage.  I'm not particularly hopeful that v3 will fix the issue since looking at the source code for the action doesn't reveal any retry logic.  We can try adding our own try logic to the action in the future, but I thought I'd give upgrading a try just in case it helps.
Issue: None
- watch CI and see what happens
=> Upgrade codecov action to v3

.changeset/mighty-doors-explode.md, packages/perseus/src/widgets/passage.jsx, packages/perseus/src/widgets/passage/__tests__/passage-markdown_test.jsx, packages/perseus/src/widgets/passage/get-line-height-for-node.js, packages/perseus/src/widgets/passage/passage-markdown.jsx, packages/simple-markdown/src/index.js
This work kind of spiraled out, so I thought I would stop here and try to land some of this. It's not a perfect win, but it's an improvement:
- `passage`: 76% to 85% (uncovered bits are mostly jQuery and Underscore)
- `passage-markdown`: 62% to 96%
Passage is kind of an extension of SimpleMarkdown that allows for adding special MD features like references (to a part of the passage, not a React ref) and footnotes. PassageMarkdown is the set of custom rules that extends SimpleMarkdown which is then used by Passage to render the content. Since Passage and PassageMarkdown are so tightly bound together, it was difficult to work on one without working on the other.
Passage relies a lot of JQuery and Underscore; I wanted to remove them, but I kept breaking tests. Might make another pass in a …
=> Stabilization: Add Flow types to passage and passage-markdown

.changeset/brave-birds-fail.md, packages/perseus/src/styles/perseus-renderer.less, packages/perseus/src/styles/widgets/passage.less, packages/perseus/src/widgets/definition.jsx
Updates perseus body font and passage font to match wonderblocks.
Issue: https://khanacademy.atlassian.net/browse/LP-12340
- Open storybooks
- Make sure everything is still readable
=> Update perseus fonts to match wonderblocks

.changeset/angry-cameras-share.md, packages/perseus/src/components/number-input.jsx, packages/perseus/src/components/simple-keypad-input.jsx, packages/perseus/src/index.js, packages/perseus/src/perseus-types.js, packages/perseus/src/util/answer-types.js, packages/perseus/src/util/math.js, packages/perseus/src/widgets/__tests__/numeric-input_test.jsx, packages/perseus/src/widgets/input-number.jsx, packages/perseus/src/widgets/numeric-input.jsx
- Brought flow types from ~60% to ~90%
- Created a shared `MathFormat` type
- Created a shared `PerseusNumericInputAnswerForm` type
- Converted `SimpleKeypadInput` from `createReactClass` to a class component since Numeric-Input was using it
- Tried to switch Underscore to Native JS as much as I could figure out
- Refactored string ref into a callback ref
Issue: LP-13032
Everything should work the same, but be typed better
=> Numeric-Input stabilization (Flow)

.changeset/tidy-gifts-fly.md, packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set_test.jsx.snap, packages/perseus/src/widgets/graded-group-set.jsx
This PR adds a tiny span tag that indicates which graded group is "current" to screen readers. It makes use of the a11y style for "srOnly". This was done as part of the work identified by the Level Access Accessibility Audit. 
Issue: LP-13084
- Existing tests 
- Manual testing
=> Tiny fix that communicates the "current" state to screen readers.

.changeset/olive-pillows-invent.md, packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set-jipt_test.jsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/graded-group_test.jsx.snap, packages/perseus/src/widgets/graded-group.jsx
Another microfix that updates the graded-group title to use the next darker level of gray so that it can pass our a11y requirements. This was done as part of the tasks that were generated out of the Level Access Accessibility Audit. 
Issue: LP-13083
make tesc
=> Ensure that there is sufficient contrast between the graded-group title and the background.

.changeset/polite-geese-compare.md, packages/perseus/src/styles/widgets/passage.less
Looks like we might have accidentally removed Passage's paragraph indent ([see here](https://github.com/Khan/perseus/pull/318/files#diff-297330f874ebfc461ddd29b11b74ad4ca681ecbda38db48fc3a84d516477a549L49)), so this is adding it back.
Issue: LP-13156
- I tried to add a unit test, but Jest doesn't like styles coming from CSS classes
- Look in Storybook and note that paragraphs are indented
=> add text-indent back to Passage

packages/perseus/src/widgets/radio/choice-icon/cross-out-line.jsx
Fixes alignment of crosscut line when a radio choice has multiple lines.
Issue: https://khanacademy.atlassian.net/browse/LP-13046
Before:
After:
- Open the storybook to the radio widget
- Turn on SAT Styling and crosscut
- Resize the screen until the radio option takes up multiple lines
- **The crossout line should line up with the radio button**
=> wip: fixup crossout

.changeset/green-guests-build.md, packages/perseus/src/styles/articles.less
There was a gradient background on some math that looked strange. It was probably part of a past design but doesn't fit with our current aesthetic needs.
Issue: https://khanacademy.atlassian.net/browse/LP-13105
- After these changes are deployed, load /internal-courses/test-everything/test-everything-1/categorizer/a/categorizer-article?modal=1
- **You shouldn't see a weird backgroud on the math**
[LP-13105]: https://khanacademy.atlassian.net/browse/LP-13105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove gradient background on math

.changeset/heavy-fireants-whisper.md, package.json
It's a rough edge for me that yarn start doesn't do the "main" thing in this project.
This PR fixes that by making it boot up storybook.
- run `yarn start`
- **You should see storybook startup**
=> Make yarn start boot storybook

.changeset/smart-ants-relate.md, packages/perseus/src/styles/perseus-renderer.less
Updates fonts so that they match the rest of Khan Academy.
Issue: https://khanacademy.atlassian.net/browse/LP-13214
- Load an exercise within the context of webapp
- **The paragraph font should use Lato**
[LP-13214]: https://khanacademy.atlassian.net/browse/LP-13214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update fonts from Noto -> Lato

.changeset/young-worms-explode.md, packages/perseus/src/styles/widgets/passage.less
Fixes passage refs not refering to the right line.
Issue: https://khanacademy.atlassian.net/browse/LP-13254
- Load a passage
- **The gutter lines should line up with the right line**
=> Fix Passage refs refer to the wrong line

.changeset/tender-planets-approve.md, packages/perseus/src/styles/widgets/passage.less
This fixes passage line numbers not lining up by using the exact same style we did before (screenshot is prod's computed style)
Because passage depends on exact styling we can't update it to wonderblocks without updating all of our content. That's a no-go so let's keep it as-is.
Working prod style:
Issue: https://khanacademy.atlassian.net/browse/LP-13254
This depends on the exact container we use in prod so it's not testable in a storybook.
- Deploy a ZND
- Load `/internal-courses/test-everything/test-everything-2-without-mastery/te-passage-ref/e/passage-ref`
- **Check that line numbers in the answer section line up with actual passage text**
=> Fix passage text by making it exactly like it was before

.changeset/loud-cougars-reflect.md, packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer_test.js.snap, packages/perseus/src/widgets/__tests__/__snapshots__/group_test.jsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/radio_test.jsx.snap, packages/perseus/src/widgets/radio/choice.jsx
Small CSS tweaks to properly shape/space the "cross out" button
LC-57
Also testing a color change.
=> Shape the "cross out" ellipsis button

.changeset/shiny-squids-sip.md, packages/perseus-editor/src/editor.jsx, packages/perseus-editor/src/widgets/radio/editor.jsx, packages/perseus/src/widgets/__tests__/radio/base-radio_test.jsx, packages/perseus/src/widgets/radio/base-radio.jsx, packages/perseus/src/widgets/radio/choice-icon/library-choice-icon.jsx
Basically what seemed to be happening was that onClick handlers were propagating upwards.
Also when I migrated BaseRadio from a class to a functional component I left a `this.` and for some reason none of our safeguards caught that.
Issue: LC-505
- Go to the content editor and make sure you can select items, update text without selecting items, and delete items
=> Radio editor bugfix: selection/deletion propagation issues

.changeset/four-spoons-pay.md, packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer_test.js.snap, packages/perseus/src/widgets/__tests__/__snapshots__/group_test.jsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/radio_test.jsx.snap, packages/perseus/src/widgets/radio/choice.jsx
Overwrite `user-select` in WB to allow users to select text in Radio's Choice.
Slack thread: https://khanacademy.slack.com/archives/C16T2PZBL/p1676915641662039
- Go to a page with a [Radio widget](https://www.khanacademy.org/internal-courses/test-everything/test-everything-2-without-mastery/te-radio/a/radio-article)
- Select the text in one of the Radio's choices
- [Use a tool](https://chrome.google.com/webstore/detail/read-aloud-a-text-to-spee/hdhinadidafjejdhmfkjgnolgimiaplp/related?hl=en) that reads selected text to confirm that it's able to read the text
=> allow users to select Radio Choice text

.changeset/mean-llamas-hammer.md, packages/perseus/src/widgets/input-number.jsx
This PR fixes a very long-standing bug in the `input-number` where we use the bang operator (`!`) to check if a value is true or false, but in doing so equate `null` to false becuase it's "falsey".
Ref: https://github.com/Khan/perseus/blob/old-master/src/widgets/input-number.jsx#L137..L161
That block of code seems to have been equating `null` to incorrect (which happens when `satStyling` is `false` always). I think the fix I've got is as minimal as I can make it and corrects the situation. 
Issue: LC-520
I imported these changes into local webapp (using the `services/static/tools/dev_update_perseus.sh` script) and then checked the following exercise: https://khanacademy.dev/math/algebra/x2f8bb11595b61c86:functions/x2f8bb11595b61c86:inputs-and-outputs-of-a-function/e/functions_matching_inpu …
=> LC-520: Make correctness checks explicit comparisons to true/false

.changeset/tall-points-check.md, .eslintrc.js, .storybook/main.js, packages/math-input/src/demo.js, packages/math-input/src/native-app.js, packages/perseus/src/components/__stories__/tex.stories.jsx, packages/perseus/src/interactive2/movable-point.jsx, packages/perseus/src/item-renderer.jsx, packages/perseus/src/mixins/provide-keypad.jsx, packages/perseus/src/util/react-render.js, testing/item-renderer-with-debug-ui.jsx, testing/multi-item-renderer-with-debug-ui.jsx
@zhiyi-zhang-duke [had a question](https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1674661600228329) of how to test KaTeX markup in Perseus content. I pointed him to our handy Storybook stories for our renderers.... and then we noticed that no KaTeX was actually rendered.
It turns out there are two, inter-related issues:
1. Our storybook configuration was picking up storybook files found in dependant npm packages (specifically the wonder-blocks packages)
2. We were configuring the helper renderers that we use in Storybook with test dependencies that mock out the `<KatexProvider>` which caused us to render the KaTeX markup literally instead of actually processing it with `katex`.
Issue: "none"
`yarn storybook` >> Perseus >> Components >> Tex >> Basic Operation
You should see a rendered …
=> Fix KaTeX rendering in Storybook

.changeset/mighty-apples-add.md, packages/perseus/src/styles/perseus-renderer.less, packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set-jipt_test.jsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set_test.jsx.snap, packages/perseus/src/widgets/__tests__/graded-group-set_test.jsx, packages/perseus/src/widgets/graded-group-set.jsx, packages/perseus/src/widgets/graded-group.jsx
Indicators ⚪⚪🟢⚪⚪⚪⚪ are now in explicit list markup and operable by keyboard.
- `<div>` replaced by `<ul>` and `<li>`
- `tabindex` has been added for keyboard navigation
- keyDown event handler has been added to navigate to problem on enter key
Also added some bonus a11y style changes per design request: https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1674230818950029
Issue: LP-13089
Issue: LP-13091
Added RTL tests to confirm keyboard navigation works as expected. Tested manually in Storybook as well.
=> Indicators are now in explicit list markup and operable by keyboard

.changeset/tricky-dolphins-film.md, packages/perseus/src/__stories__/hints-renderer.stories.jsx, packages/perseus/src/hint-renderer.jsx
This PR opens a series of PRs to remove custom code to support SAT from Perseus. 
This one removes `satStyling` support from the Hint Renderer. It was pretty minimal but just removes an `satStyling` check which suppresses the `X / Y hints` label in SAT.
I've also tweaked the HintsRenderer story so that we can see the `x / y` hints label (which was previously hidden under the storybook navigation panel.
Issue: LC-588
`yarn test`
`yarn flow`
=> [Remove SAT] Remove satStyling from hint-renderer

.changeset/old-scissors-rush.md, config/build/create-babel-plugins.js, config/build/create-babel-presets.js, config/build/rollup.config.js, package.json, packages/perseus/src/util/interactive.ts, yarn.lock
TS 5.0 (5.0.2) was recently release so we may as well try out the new version and see if we run into any issues.  It did pick up one issue with the types in interactive.ts which was easily correctly.
This PR also updates the settings of @babel/preset-env to match the settings used by wonder-blocks and webapp.  These changes only affect the esm modules that are generated.  I didn't want to mess with the cjs module settings since I think those are specially configured to work with old versions of Android.
Issue: None
- yarn tsc
- yarn build
- yarn build:types
=> Update TS to v5 and update @babel/preset-env to match other repos more closely

.changeset/metal-clouds-film.md
For some reason bumping "perseus-build-settings"'s version wasn't enough to bump all of the packages automatically that depend on it.  I'm guessing that's b/c it's listed as a dev dependency.
Issue: None
- n/a
=> [🔥AUDIT🔥] Bump all packages manually

.changeset/shaggy-cheetahs-promise.md, packages/math-input/less/overrides.less
This style was found as part of our MathJax investigation. It's currently not affecting anything, and could cause future confusion should we switch over to MathJax. This simple PR just removes the unused style. 
Issue: LC-670
Manual Testing
=> Removed archaic style that is no longer affecting anything so that it doesn't cause future confusion should we move away from katex.

.changeset/olive-cows-grab.md, packages/perseus/src/components/hud.tsx
Switches to true TypeScript types for `hud.tsx`
Issue: None
Reviewed the changes in Storybook
=> Type and modernize hud.tsx

.changeset/rude-lamps-itch.md, packages/perseus/src/components/graphie.tsx, packages/perseus/src/components/svg-image.tsx, packages/perseus/src/interactive2/types.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/util.ts, packages/perseus/src/widgets/grapher.tsx, packages/perseus/src/widgets/image.tsx, packages/perseus/src/widgets/number-line.tsx, packages/perseus/src/widgets/simulator.tsx
Switches to true TypeScript types for `graphie.tsx`.
Issue: "none"
Viewed the Graphie stories in storybook.
=> Remove prop-types from graphie.tsx

.changeset/gorgeous-games-collect.md, packages/perseus/src/components/math-output.tsx
Switches to true TypeScript types for `math-output.tsx`
Issue: None
Reviewed changes in Storybook
=> Type and modernize math-output.tsx

.changeset/mighty-jobs-beg.md, packages/math-input/src/components/keypad/geometry-page/index.tsx, packages/math-input/src/components/keypad/operators-page/index.tsx
Just fixing a minor oopsie in naming exports for pages.
LC-796
=> Fix a typo in exports

.changeset/plenty-pans-help.md, packages/math-input/src/index.ts, packages/math-input/src/math-input.stories.tsx, packages/perseus/src/mixins/provide-keypad.tsx, packages/perseus/src/widgets/__stories__/test-keypad-context-wrapper.tsx
- Export the v2 keypad as `Keypad`
- Rename the v1 keypad as `ProvidedKeypad` (this is going to require a change in Webapp!)
Functionality shouldn't change, the v2 keypad should be exported now
=> Export v2 keypad

.changeset/pink-ears-fold.md, packages/perseus/src/components/__tests__/sortable.test.tsx, packages/perseus/src/components/sortable.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/definition.tsx, packages/perseus/src/widgets/explanation.tsx, types/utility.d.ts
@jaredly raised how unsafe Record<string, empty> is since in https://khanacademy.slack.com/archives/C04KJCRM8QN/p1684345906827579.  This PR removes all uses of this unsafe type.  I'll work on creating a lint rule for it our lint config/plugin in wonder-stuff separately.
In most cases `Record<string, empty>` can be replaced with `Record<empty, empty>`.
Issue: None
- yarn tsc
=> Removes uses of Record<string, empty>

.changeset/stale-rabbits-wink.md, packages/math-input/.eslintrc.js, packages/math-input/package.json, packages/math-input/src/components/keypad-legacy/two-page-keypad.tsx, packages/math-input/src/components/keypad/index.tsx, packages/math-input/src/components/keypad/keypad-mathquill.stories.tsx, packages/math-input/src/components/tabbar/tabbar.tsx, yarn.lock
- Adds a story with an example of the v2 keypad in a popover, which is the final goal for desktop
- I needed to style tabbar in v2 differently, but I didn't want to break prod so I added a style prop
https://github.com/Khan/perseus/assets/16308368/724c1612-bf02-47bd-a388-4ad3c584acb1
=> Tabbar accepts style, create demo of using v2 keypad in popover

.changeset/bright-gifts-change.md, packages/perseus-editor/src/components/graph-points-count-selector.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
This is PR 6 in a series of PRs that restore some editor functionality that I [deleted](https://github.com/Khan/webapp/pull/3144) back in January of 2022. It obviously isn't used often, but it's [still needed](https://khanacademy.slack.com/archives/C6NS8DWJU/p1683664865635869)!
Previous PRs:
* #536
* #537
* #539
* #540
* #542
In this PR I re-introduce UI to configure the number of points in the graph
Issue: LC-813
Start storybook and select the "Point(s)" graph type. Now change the "Number of Points" selector and verify the right side output display to compare that it's updating the widget options correctly.
=> Allow editor to configure 'points' graph type

.changeset/stupid-shrimps-marry.md, packages/perseus-editor/src/components/segment-count-selector.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/widgets/interactive-graph.tsx
This is PR 8 in a series of PRs that restore some editor functionality that I [deleted](https://github.com/Khan/webapp/pull/3144) back in January of 2022. It obviously isn't used often, but it's [still needed](https://khanacademy.slack.com/archives/C6NS8DWJU/p1683664865635869)!
Previous PRs:
* #536
* #537
* #539
* #540
* #542
* #543
* #544
In this PR I re-introduce UI to configure the details of the 'segment' graph type.
Issue: LC-813
Start storybook and select the "Line (segments)" graph type. 
Change the "Number of segments" field.
Drag the segment start/end "knobs" around (ie. configure the line segments).
Verify the right side output display to compare that it's updating the widget options correctly.
=> Allow editor to configure 'line segment' graph type

.changeset/strong-parrots-live.md, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
A small PR to make the correct answer area more legible. Switched to have a background and border and use a monospace font so it's more legible.
Issue: LC-813
Check the design in storybook (or look at the screenshot).
| --- | --- |
| <img width="378" alt="image" src="https://github.com/Khan/perseus/assets/77138/767cc110-599e-443c-b687-2869bcba92f5">  | <img width="390" alt="image" src="https://github.com/Khan/perseus/assets/77138/6788479e-ec32-4dc2-860d-4572cb67afd5"> |
=> Tweak formatting of 'correct answer' in interactive-graph-editor

.changeset/cuddly-buckets-rush.md, packages/math-input/src/components/keypad/__tests__/Button.test.tsx, packages/math-input/src/components/keypad/__tests__/KeypadButton.test.tsx
Created Jest tests for the Button and KeypadButton components within math-input/src/keypad. Test for correct rendering of aria-label, callbacks, correct rendering of children.
Issue: LC-869 and LC-868
- Ran the tests locally via `yarn test`.
=> add KeypadButton, Button tests

.changeset/khaki-chairs-attack.md, packages/perseus/src/widgets/__tests__/numeric-input.test.ts, packages/perseus/src/widgets/numeric-input.tsx
This is kind of complicated and a super edge-case.
- IF a content creator didn't set an explicit answer form for a question using numeric-input
- AND the correct answer was close to a multiple of `pi/12`
- AND the submitted answer was within a small margin of error to the correct answer
- THEN the validator would think the learner was approximating pi - even if the question had nothing to do with pi
There's a lot of conversation in the ticket, but the tl;dr is we decided not to validate against pi unless it was explicitly set as an option.
Issue: LC-691
Original steps to repro:
1. Access Khan Academy.
2. Go to the exercise "Subtracting decimals: thousandths"
3. Look for this specific question: 52.389 – 7.1
4. Type anything between 45.282 and 45.288 as its answer.
5. This notification will …
=> Remove pi as a default answer form in numeric-input

.changeset/hungry-clouds-marry.md, packages/math-input/src/components/input/math-wrapper.ts, packages/math-input/src/components/input/mathquill-types.ts
Last week, before I saw that Matthew was doing the same thing, I had spent a small amount of time bringing in some Mathquill types and documentation from [the website](http://docs.mathquill.com/en/latest/Api_Methods/).
This PR brings in the changes I added on top of the start Matthew made... it mostly adds more docs from the website for the different config and API methods.
Issue: "none"
=> Convert comment types in Mathquill types so that VSCode/TypeScript understand them better

.changeset/slimy-gorillas-return.md, packages/math-input/src/components/keypad/button-assets.tsx, packages/math-input/src/components/keypad/index.tsx, packages/math-input/src/components/keypad/keypad-pages/extras-page.tsx, packages/math-input/src/components/keypad/keypad-pages/numbers-page.tsx, packages/math-input/src/components/keypad/shared-keys.tsx
Updates the layout of the v2 keypad per the ticket:
Changes to the keypad layout, explained as 0-indexed coordinates (top left button is x:0, y:0)
- On all pages movement key will be 4, 3
- On the Numbers page, add “Percent” to 3, 0 (only on Numbers page)
- On the Numbers / Pre-Algebra page, move “Fraction” to 3, 1
- On Geometry / Extras page, move “Fraction” to 3, 0
- Make “extras” key a 3x4 grid vs a 4x4 grid, to accommodate “Fraction” key
https://github.com/Khan/perseus/assets/16308368/a3127504-168d-49f4-bdc3-660670c95237
Issue: LC-976
=> Update MathInput v2 keypad layout

.changeset/spotty-radios-warn.md, packages/math-input/src/components/keypad/__tests__/keypad.test.tsx, packages/math-input/src/components/keypad/index.tsx
We decided to use the native popover button to dismiss the keypad in desktop. Will likely need this v2 keypad dismiss button in mobile. Making it optional using a prop.
https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1687960633274759
=> Make dismiss button optional

.changeset/thick-donuts-sell.md, packages/math-input/src/components/input/cursor-contexts.ts, packages/math-input/src/components/input/mathquill-helpers.ts, packages/math-input/src/components/keypad-legacy/expression-keypad.tsx, packages/math-input/src/components/keypad-legacy/fraction-keypad.tsx, packages/math-input/src/components/keypad/__tests__/keypad.test.tsx, packages/math-input/src/components/keypad/index.tsx, packages/math-input/src/components/keypad/keypad-mathquill.stories.tsx, packages/math-input/src/components/keypad/shared-keys.tsx, packages/math-input/src/types.ts
While flowgen is capable of converting TS enums to the appropriate POJO, it doesn't know how to update the uses of the enum.  It'll be difficult to update the tool to do this properly because it currently only converts a file at a time without looking at other files, but it would need to find the definition of the enum to know whether it has to do extra work to convert the usage properly.
TODO: Convert any other enums that are causing issues.
Issue: None
- yarn build:types
- yarn build:flowtypes
- check that the generated flow types work as expected in the [flow playground](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602e0hQhcMtCw18ufgAcqyMTXpyQ5LEZNCDx0+cvzOJtBQW49AOkMm+AhEWGhCKmZ6lgC+6hAi1AD0AFQABAACMDQQAO6pyYkAOlDFImB0mKl …
=> Convert CursorContext TS enum to POJO

.changeset/witty-singers-check.md, packages/perseus/src/util/tex.ts
There was a race between the code in Perseus that positions Graphie
labels and the code in webapp that updates MathJax CSS. If Perseus
measured the label's dimensions before MathJax updated its CSS, then the
measured dimensions of the label would be wrong and the label would get
positioned incorrectly.
To fix this, we measure and position the label when the TeX component
calls its onRender callback. The MathJax component doesn't call this
callback until the CSS is up to date.
Issue: https://khanacademy.atlassian.net/browse/LC-934
Test plan:
Follow the instructions in webapp to install a dev build of Perseus.
Visit
/math/arithmetic-home/multiply-divide/division-intro/e/dividing-with-visuals?devflagk=mathjax3
and run through the exercise several times. You should not see the
duplicated …
=> Fix positioning of Graphie labels when MathJax is used to render TeX

.changeset/tidy-timers-unite.md, packages/math-input/src/components/keypad/keypad-button.tsx, packages/math-input/src/components/tabbar/item.tsx
This is a minor PR to remove the doubled blue outline on the keypad buttons during hover/pressed/focused states. You should now see only a single blue outline around the buttons during hover/pressed/focused. This required overriding the clickable focus styling, but we've already come up with a custom (and cleaner) solution. 
BEFORE
AFTER
Issue: LC-999
manual testing
=> [Perseus] [Khanmigo] Adjust the focus styling on the keypad buttons

.changeset/slimy-apes-kick.md, packages/perseus-editor/src/editor.tsx, packages/perseus-editor/src/katex-mhchem/index.js, packages/perseus-editor/src/katex-mhchem/parser.js
Previously, any use of `\ce` in a TeX expression resulted in the
exercise editor displaying a KaTeX error, even though the expression
preview rendered fine (and was in fact being rendered by KaTeX). This
was because the preview and the error pane were using different KaTeX
configurations. The preview had the mhchem extension installed, and the
error pane didn't.
This commit fixes the issue by adding mhchem to the error checker's
KaTeX.
Issue: https://khanacademy.atlassian.net/browse/LC-997
Test plan:
Install the dev version of Perseus in webapp.
Edit an exercise. Add the following TeX somewhere:
`$\ce{Ba}$`
You should see "Ba" rendered in an upright font in the preview. The
"KaTeX Errors" pane should not display.
Change the TeX to `$\mbox1$`. The "KaTeX Errors" pane *should* display …
=> Fix spurious KaTeX errors in the exercise editor

.changeset/lazy-coins-dream.md, packages/math-input/src/components/keypad/__tests__/keypad-v2-mathquill.test.tsx, packages/math-input/src/components/keypad/__tests__/keypad.test.tsx, packages/math-input/src/components/keypad/index.tsx, packages/math-input/src/components/keypad/keypad-mathquill.stories.tsx, packages/perseus-core/src/analytics.ts, packages/perseus-core/src/index.ts, packages/perseus/src/dependencies.ts, packages/perseus/src/types.ts, testing/render-keypad-with-cypress.tsx
This PR introduces a new React Context for plumbing dependencies through Perseus. The context uses a new type `PerseusDependenciesV2` (so it doesn't conflict with the original `PerseusDependencies`). 
This PR also provides a React hook (`useDependencies`) for accessing dependencies. This hook will commonly be used in wrapper component to attach dependencies to the wrapped component (next PR). 
I also renamed `sendEvent` to `onAnalyticsEvent` as that feels more natural for a callback (especially event callback... a la 'onClick`). This causes a bit more churn but hopefully that's ok as we're early in the analytics journey.
Issue: LC-950
`yarn test`
`yarn tsc`
=> [Analytics] 1. Introduce DependenciesContext

.changeset/poor-gifts-warn.md, packages/perseus/src/types.ts, packages/perseus/src/widgets/expression.tsx, testing/test-dependencies.tsx
This PR should wrap up the analytics work for now. We remove the (now unused) `analytics` key on the legacy `PerseusDependencies` object/type. It also does a bit of tweaking of the `RenderProps` for the Expression widget by moving it to the top of the file with the other prop types. 
Issue: LC-950
`yarn tsc`
`yarn test`
=> [Analytics] 3. Move RenderProps up with other props and use widget options type for prop types

.changeset/chilly-badgers-guess.md, packages/perseus/src/__stories__/item-renderer.stories.tsx, packages/perseus/src/__testdata__/item-renderer.testdata.ts, packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer.test.tsx.snap, packages/perseus/src/styles/articles.less, packages/perseus/src/styles/khan-exercise.css, packages/perseus/src/widgets/__tests__/__snapshots__/group.test.tsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/radio.test.ts.snap, packages/perseus/src/widgets/radio/base-radio.tsx, packages/perseus/src/widgets/radio/choice.tsx
Switch from `pre-wrap` to `wrap` in exercises and elsewhere to accommodate `python` indentation syntax. Adjusts elsewhere to ensure users are able to view full code in various contexts.
https://github.com/Khan/perseus/assets/23404711/8ea0d017-d25b-4529-bab0-2128ec78e4d7
Issue: LC-966
- Run `yarn start` and check new CodeblockItem item renderer story.
=> LC-966: Disallow Wrapping Code Blocks

.changeset/ninety-rules-pretend.md, packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer.test.tsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/group.test.tsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/radio.test.ts.snap, packages/perseus/src/widgets/radio/base-radio.tsx
Changed the style of the instructions in the base-radio component to be sans-serif
instead of serif.
Issue: LC-492
- Ran `yarn storybook` and verified that the font is sans-serif
- Used npm image from PR as Perseus version in webapp and verified that the fonts work with a local frontend
=> Changed radio instruction font from serif to sans serif

.changeset/sharp-tables-itch.md, packages/perseus/src/styles/widgets/passage.less, packages/perseus/src/widgets/__stories__/passage-ref.stories.tsx, packages/perseus/src/widgets/__stories__/passage.stories.tsx, packages/perseus/src/widgets/__tests__/__snapshots__/passage-ref.test.ts.snap, packages/perseus/src/widgets/__tests__/__snapshots__/passage.test.tsx.snap, packages/perseus/src/widgets/passage.tsx
Switch from `className` to `id` in css selectors for passage wrappers in an effort to gain higher priority than article paragraph styles.
Change `line-height` on passage `em` elements to 0 since the italicized characters have a subtly different size. See second video for demo of how this resolves the problem.
https://github.com/Khan/perseus/assets/23404711/ae4902b7-128c-45ad-b2f6-56195852b50f
https://github.com/Khan/perseus/assets/23404711/7de0aaeb-891c-4a03-a97a-fa9f147d4892
Issue: LC-698
- Test in webapp with npm
=> Fix paragraph / line # alignment issue

.changeset/curly-ties-punch.md, packages/perseus/src/article-renderer.tsx, packages/perseus/src/interaction-tracker.ts, packages/perseus/src/types.ts
While improving types on a previous PR, I mistakenly typed `APIOptions.trackInteraction` as not taking any parameters. That's wrong. In fact, it takes an object with at least `id`, `typed`, and optionally `correct`, in addition to any extra args provided by the originating widget. 
This PR fixes this type issue.
Issue: "none"
`yarn tsc`
=> Better type trackInteraction function in APIOptions

.changeset/many-eagles-promise.md, packages/math-input/src/components/keypad/keypad.stories.tsx, packages/perseus-editor/src/widgets/__stories__/expression-editor.stories.tsx, packages/perseus/src/index.ts
I wanted to see what options are made available to content creators, so I made a story.
Issue: LC-1069
=> Add story for ExpressionEditor

.changeset/sour-bears-fail.md, packages/perseus/src/interaction-tracker.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/sequence.tsx
In #609 I clarified the trackInteraction API types. However, I missed defining that the `APIOptions.trackInteraction` argument object can have extra, arbitrary keys provided by the widget that originates the interaction. 
This PR adds that to the `trackInteraction` function type. 
Issue: "none"
`yarn tsc`
`yarn test`
=> Allow APIOptions.trackInteraction()'s arg object to have extra keys

.changeset/little-kids-know.md, packages/math-input/src/components/input/math-input.tsx, packages/math-input/src/full-math-input.stories.tsx
I missed a couple of spots where I should have been using the new `KeypadAPI` type
=> KeypadAPI: use it in more spots

.changeset/eighty-pillows-applaud.md, packages/perseus/src/styles/articles.less, packages/perseus/src/styles/widgets/interactive-graph.less, packages/perseus/src/styles/widgets/label-image.less, packages/perseus/src/styles/widgets/passage.less, packages/perseus/src/styles/widgets/plotter.less
Perseus styles KaTeX-rendered math in specific ways for different
scenarios (e.g. inline math, block math, and graphie labels). Before we
release MathJax 3 to users, it should do the same for MathJax-rendered
math.
See also: https://github.com/Khan/webapp/pull/15509
Issue: https://khanacademy.atlassian.net/browse/LC-1087
Follow the instructions in webapp's
`services/static/javascript/perseus/README.md` to install a dev build of
Perseus.  View math in the following situations with `?devflagk=mathjax3`
appended to the URL and verify that it looks like the math on prod:
- /devadmin/tex
- /devadmin/tex/testcases
- A math article, e.g. `/math/multivariable-calculus/thinking-about-multivariable-function/x786f2022:vectors-and-matrices/a/vectors-and-notation-mvc`
- A math exercise
- Graphie …
=> Update CSS for MathJax 3

.changeset/pretty-beers-pretend.md, .changeset/quick-tables-tell.md, packages/math-input/src/components/keypad-switch.tsx, packages/math-input/src/full-math-input.stories.tsx, packages/math-input/src/index.ts, packages/perseus/src/mixins/provide-keypad.tsx, packages/perseus/src/perseus-api.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/__stories__/test-keypad-context-wrapper.tsx
In order to switch between the v1 and v2 keypads in Perseus using a feature flag in Webapp, we're passing down a switch via API options.
The actual switching between keypads will be in the next PR.
=> Add useV2Keypad API option

.changeset/breezy-crabs-sip.md, packages/perseus-core/src/types.ts, tsconfig-build.json
I don't know what I'm doing, please feel free to give me guidance.
I added types to `perseus-core`, but didn't notice that Changeset didn't ask me to bump the version. When I tried to cut a release in Webapp I got a bunch of errors because the new types weren't there. I then realized `perseus-core` hadn't been released and that led me to believe that Changeset didn't have an awareness of `perseus-core`.
I just copy/pasted stuff randomly, changed something in `perseus-core`, and now Changeset is prompting me for a `perseus-core` version... 🤷
=> add perseus-core to tsconfig-build for changeset

.changeset/eleven-baboons-fry.md, packages/math-input/src/full-math-input.stories.tsx, packages/math-input/src/index.ts, packages/perseus/src/mixins/provide-keypad.tsx, packages/perseus/src/widgets/__stories__/test-keypad-context-wrapper.tsx
I forgot that Khanmigo is using the keypad that's not wrapped in a weird API, so I needed to re-export that.
=> add back a direct export of v2 keypad

.changeset/two-trains-smash.md, packages/math-input/src/components/keypad/keypad.tsx
We don't have to merge this if it's not popular, but I keep running into `sendEvent is not a function` and right now all `sendEvent` things are just stubbed out anywhat, so I thought maybe we could just make it optional for now.
=> make sendEvent optional

.changeset/moody-birds-search.md, packages/perseus/src/interaction-tracker.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/graded-group.tsx, packages/perseus/src/widgets/sequence.tsx
I've been working to get a proper type for the `trackInteraction` `APIOption`. I've migrated the `InteractionTracker` to be generic so that it only accepts extra arguments defined by the `WidgetProps<T,T,T>` (this means each widget can call `trackInteraction` with args it defines). 
In the `APIOptions` the `trackInteraction` callback now defines a union of all extra args that all widgets provide.
Issue: "none"
Build, build flow types, and then test it in webapp.
=> Rework args to trackInteraction so it works when we generate Flow types for it

.changeset/smart-turtles-rush.md, packages/perseus/src/styles/articles.less
PR https://github.com/Khan/perseus/pull/631 updated the font styling for
KaTeX to also apply to MathJax. These styles got broken by a merge, so
this commit fixes them up.
Issue: https://khanacademy.atlassian.net/browse/LC-1087
Test plan:
Follow the instructions in webapp's
`services/static/javascript/perseus/README.md` to install a dev build of
Perseus. View math in the following situations with `?devflagk=mathjax3`
appended to the URL and verify that it looks like the math on prod:
- /devadmin/tex
- /devadmin/tex/testcases
- A math article, e.g. /math/multivariable-calculus/thinking-about-multivariable-function/x786f2022:vectors-and-matrices/a/vectors-and-notation-mvc
- A math exercise
- Graphie labels
- The exercise editor (note the color contrast between math and the surrounding text …
=> Fix font size of MathJax 3 inline math

.changeset/lucky-insects-tap.md, packages/math-input/src/components/keypad/mobile-keypad.tsx
Pass `style` props to container so default styles can be overwritten
Issue: LC-1099
- Apply styles to MobileKeypad (v2 mobile keypad)
- Note the styles are applied to the keypad container
=> allow v2 keypad to have styles overwritten like v1

.changeset/brave-mugs-wonder.md, packages/math-input/src/components/input/mathquill-types.ts
`moveOutOf` was missing the `dir` parameter.
You can see in [this test](https://github.com/Khan/mathquill/blob/32d9f351aaa68537170b3120a52e99b8def3a2c3/test/unit/publicapi.test.js#L245) that it is expected to be present.
=> Fix MathQuill event type

.changeset/silent-berries-do.md, packages/math-input/src/components/keypad/mobile-keypad.tsx, packages/math-input/src/components/prop-types.ts, packages/math-input/src/full-math-input.stories.tsx, packages/math-input/src/index.ts, packages/perseus/src/__testdata__/article-renderer.testdata.ts, packages/perseus/src/article-renderer.tsx, packages/perseus/src/mixins/provide-keypad.tsx, packages/perseus/src/types.ts
I was adding some unit tests in a repo that uses the ArticleRenderer and noticed the types for ArticleRenderer were somewhat anemic. So given it was a late Friday afternoon I took a small detour and improved them. 
This PR improves our types for the article renderer a few ways:
* Move ArticleRenderer to TS Props from PropTypes
* Specify ProvideKeypad mixin types by defining 'this' parameter
* Move math-input's prop-types file to TS
Issue: "none"
`yarn test`
=> Migrated ArticleRenderer to Typescript types

.changeset/fluffy-beans-wink.md, packages/perseus-core/src/analytics.ts, packages/perseus/src/widgets/__tests__/expression.test.tsx, packages/perseus/src/widgets/expression.tsx
As I was integrating Perseus analytics in webapp, it became really difficult to work out how to provide the virtualKeypadVersion consistently when Perseus wasn't always providing it. After some thought, I figured out that we can pretty-reliably derive the keypad version. Given that we are actively moving to coalesce on a single keypad, I hope this is an acceptable approach for the short term. When we get to one keypad, we can delete this `virtualKeypadVersion` from the analytics anyways. 
Issue: LC-950
✅ `yarn typecheck`
✅ `yarn test`
=> Derive virtual keypad version

.changeset/nine-guests-sneeze.md, packages/math-input/src/components/keypad-legacy/keypad-container.tsx, packages/perseus/src/__tests__/item-renderer.test.tsx
Adds a ResizeObserver to trigger a keypad resize when the container size changes (like when the viewport changes).
Issue: [LC-1166](https://khanacademy.atlassian.net/browse/LC-1166)
Followup to: [LC-1126](https://khanacademy.atlassian.net/browse/LC-1126)
https://github.com/Khan/perseus/assets/16308368/76af5196-954a-4e73-92a7-e07a6f64fb81
- Go to [this page](https://prod-znd-230821-16131-868a711.khanacademy.org/internal-courses/test-everything/test-everything-1/expression/e/expression-exercise)
- Emulate tablet with dev tools (might need to refresh)
- Click the input to open the keypad
- Collapse the left column
- Click the input to open the keypad again
- The keypad should scale up/down depending on the available space in the column
[LC-1166]: …
=> Add ResizeObserver for legacy keypad

.changeset/purple-pianos-jog.md, packages/perseus/src/components/input-with-examples.tsx, packages/perseus/src/components/sortable.tsx, packages/perseus/src/hint-renderer.tsx, packages/perseus/src/index.ts, packages/perseus/src/item-renderer.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widget-container.tsx, packages/perseus/src/widgets/passage-ref.tsx
I noticed that we have two identical versions of `LinterContextProps`. It was moved into the `perseus-linter` package, but I suspect a merge resolution brought back the deleted copy.   
This PR deletes it again out of `@khanacademy/perseus` and updates imports to use the one that lives in `@khanacademy/perseus-linter`
Issue: "none"
`yarn test`
=> Remove moved (and duplicated) LinterContextProps

.changeset/beige-cobras-listen.md, packages/perseus-editor/src/components/section-control-button.tsx, packages/perseus-editor/src/widgets/input-number-editor.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/__tests__/server-item-renderer.test.tsx, packages/perseus/src/components/info-tip.tsx, packages/perseus/src/hints-renderer.tsx, packages/perseus/src/item-renderer.tsx, packages/perseus/src/multi-items/multi-renderer.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/server-item-renderer.tsx, packages/perseus/src/widgets/__tests__/renderQuestion.tsx, packages/perseus/src/widgets/expression.tsx, packages/perseus/src/widgets/grapher.tsx, testing/test-tex.tsx
Previously in Flow we had a simple type for exatracting prop types of a component while reatining their optionality: `React.ElementConfig<typeof MyComponent>`. In TypeScript the equivalent is alot uglier:
```javascript 
JSX.LibraryManagedAttributes<
typeof MyComponent,
React.ComponentProps<typeof MyComponent>
>
```
Wonder Stuff Core recently added a helper named `PropsFor<>` that works like Flow's `ElmeentConfig<T>` and so this PR adapts to use that new type.
One related fix I made was to remove the `context` object from the `Renderer`'s constructor. That's a deprecated pattern in React and I couldn't find any usages that do that. 
Issue: "none"
`yarn test` (just to be safe)
=> Convert all JSX.LibraryManagedAttributes to use PropsFor<>

.changeset/tricky-drinks-report.md, packages/perseus/src/__tests__/mock-asset-loading-widget.tsx, packages/perseus/src/__tests__/widgets.test.ts, packages/perseus/src/index.ts, packages/perseus/src/server-item-renderer.tsx, packages/perseus/src/widgets/expression.tsx
In #601 I worked out providing our new V2 PerseusDependencies to the Expression component by wrapping it in a `forwardRef<>` functional component and using a hook to get access to the dependencies. 
This worked, until we discovered that there is code in some consuming applications that calls static functions on our Widget components. 
This PR patches the exported functional component to provide the same 3 static functions. In the future, we will want a more robust solution, possibly moving this functionality into our renderers so that consuming applications don't deal with widgets directly.
Issue: LC-1180
`yarn test`
Wait for this PR to push a snapshot npm package and then integrate with Webapp and test.
=> Propogate 'static' functions for Expression on exported forwardRef component

.changeset/four-plants-divide.md, packages/perseus/src/index.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/server-item-renderer.tsx
Mea culpa.
In #694 I snuck in a seemingly tiny improvement to our Perseus types: switching the `item` prop on ServerItemRenderer to be a true `PerseusItem` (which it should be). 
However, in consuming apps there are many places where we pass in data that doesn't quite conform to this type. Many of these instances are in unit test data. 
Given that we have a somewhat urgent fix waiting on `main`, I'm reverting these small type changes and we can get them implemented in the future when we aren't trying to ship a bugfix as well. 
Issue: LC-1180
Once integrated into our client apps, `yarn typecheck` should pass without issues.
=> [🔥AUDIT🔥] Revert type changes made in #694

.changeset/dull-paws-build.md, packages/math-input/src/components/keypad-legacy/two-page-keypad.tsx, packages/math-input/src/components/keypad/keypad.tsx, packages/math-input/src/components/keypad/shared-keys.tsx, packages/math-input/src/components/tabbar/icons.tsx, packages/math-input/src/components/tabbar/index.ts, packages/math-input/src/components/tabbar/item.tsx, packages/math-input/src/components/tabbar/tabbar.stories.tsx, packages/math-input/src/components/tabbar/tabbar.tsx, packages/math-input/src/components/tabbar/types.ts, packages/math-input/src/types.ts
This is a very simple PR that updates the name of the TabbarItemType to the more accurate/descriptive KeypadPageType. 
**Reason:** After adding the Fractions page, not all of these elements are "TabbarItems" as we don't want the Fractions page to appear in the Tabbar. I decided on a name change as it seemed like the best course of action to ensure code readability. Otherwise the logic for showing the Fraction page would be much messier due to how we're currently switching between page views. This is also inline with our usage of the type on a few of variables/states called "selectedPage". 
Issue: LC-1160
manual testing
=> Updated TabbarItemType to KeypadPageType.

.changeset/hip-eagles-scream.md, packages/math-input/src/components/keypad/button-assets.tsx
The SVGs were a little too big and this was making the whole keypad too big. I don't think we want the buttons to have fixed dimensions since we stretch them in mobile, but if this keeps happening we may want to figure out how to lock the SVG size.
Just making the SVGs height/width smaller though scaled the icons down. That's why I had to zoom/recenter the viewboxes.
Issue: LC-1159
- Go to this story: `?path=/story/v2-keypad-with-mathquill--v-2-keypad-with-mathquill`
- Note the size of the keypad
- Go to the "extras" tab
- Note the size doesn't change
=> fix oversized letter buttons

.changeset/itchy-doors-greet.md, packages/math-input/src/components/keypad/mobile-keypad.tsx
This is a very simple little PR that adds "display: none" to our mobile keypad container when the keypad is closed. This ensures that the screen readers don't try to tab over the keypad while it's hidden from view. 
Issue: LC-1192
make tesc
=> Ensured that the mobile keypad is not visible to screen readers until it is opened.

.changeset/lovely-lies-attack.md, packages/math-input/src/components/input/mathquill-types.ts
"L" and "R" should stand in for `-1` and `1`, respectively.
=> Fix MathQuillDirection types

.changeset/tasty-forks-push.md, packages/math-input/src/components/input/math-input.tsx, packages/math-input/src/components/keypad/mobile-keypad.tsx, packages/math-input/src/full-math-input.stories.tsx
Ensured that the input span is focusable via tab navigation and that we cannot accidentally create a callback loop with our updated focus. 
I also implemented a couple of fixes to our full math input story so that it doesn't error when trying to callback, and blurs the input upon closing the keypad.
A separate fix will be implemented in WebApp that ensures that closing the keypad in an exercise moves the focus to the "Check Answer" button. It will be attached to the same ticket number (LC-1193) as it is directly related to the issue.
https://github.com/Khan/perseus/assets/12463099/b5b418f6-64b6-41e5-9d6d-1a7c13410a29
Issue: LC-1193
make tesc
=> Focus Fixes for our Mobile Expression Keypad and MathInput 

.changeset/tiny-lions-worry.md, packages/math-input/src/components/keypad-switch.tsx, packages/math-input/src/components/keypad/mobile-keypad.tsx, packages/math-input/src/full-math-input.stories.tsx, packages/perseus/src/mixins/provide-keypad.tsx, packages/perseus/src/widgets/__stories__/test-keypad-context-wrapper.tsx
I had missed plumbing the analytics prop through all the mobile keypad areas. So this PR adds them. ~In the case of the LegacyKeypad, I've not bothered to do analytics as that is going away soon!~ Changed my mind: https://github.com/Khan/perseus/pull/705
Issue: LC-950
`yarn test`
`yarn start` (all stories with mobile keypad still work, and should show the keypad open/close events in the Storybook "Actions" panel)
=> [Perseus Analytics] Plumb through onAnalyticsEvent to mobile keypad

.changeset/sour-days-attend.md, .changeset/tiny-lions-worry.md, packages/math-input/src/components/keypad-legacy/provided-keypad.tsx, packages/math-input/src/components/keypad-switch.tsx, packages/math-input/src/components/keypad/mobile-keypad.tsx, packages/math-input/src/full-math-input.stories.tsx, packages/perseus/src/mixins/provide-keypad.tsx, packages/perseus/src/widgets/__stories__/test-keypad-context-wrapper.tsx
This PR adds in the analytics (keypad open/closed) events for our legacy keypad. It won't be around much longer, but while it's here we'll be able to compare usage.
I agonized a bit that there are no tests, but this entire component area doesn't have any tests. I'll look a bit further, but might just leave it as this is a legacy (soon to be deprecated) component.
Issue: LC-950
=> [Perseus Analytics] Add keypad open/closed analytics to provided-keypad (legacy)

.changeset/lucky-maps-relax.md, packages/perseus-core/src/analytics.ts, packages/perseus/src/widgets/expression.tsx
This PR implements a new analytics event: `perseus:expression-focused`. This event is fired whenever the `expression` widget input receives focus. 
Issue: LC-861
`yarn test`
=> [Perseus Analytics] Add and implement 'perseus:expression-focused' event

.changeset/wet-toes-live.md, packages/math-input/src/components/keypad-legacy/keypad-container.tsx, packages/math-input/src/components/keypad/mobile-keypad.tsx
This is basically the same thing they're doing in Webapp, I just didn't notice it before.
Issue: LC-1213
Not really sure how to write tests for this...maybe I could mock the whole `window` object and just not include `ResizeObserver`? Originally I was going to do something like `window.ResizeObserver = undefined`, but interestingly:
``` JS
window.ResizeObserver = undefined
console.log("ResizeObserver" in window) // true
```
I was able to manually test with `delete`
``` JS
delete window.ResizeObserver
console.log("ResizeObserver" in window) // false
```
Just wasn't sure how to translate that to tests.
Manually testing the regression though:
- Use a mobile web browser or emulate mobile
- Use a browser that doesn't support ResizeObserver (Safari <13.1)
- Go to a page with an [Expression …
=> check for ResizeObserver before using it

.changeset/poor-bikes-complain.md, packages/perseus-core/src/analytics.ts
In #707 I introduced a new analytics event (`perseus:expression-focused`) and implemented in Perseus. I missed marking `@khanacademy/perseus-core` as having a change in the changeset and none of our tooling warned, so the release went out without bumping that package, or the dependencies that used it. 
This PR is an attempt to just get core to version, which should version the packages that depend on it. 
Issue: LC-861
`yarn test`
=> Bump perseus-core (missed in previous release)

.changeset/big-eagles-perform.md, .changeset/green-experts-jam.md, .changeset/ten-bags-battle.md, .github/workflows/node-ci.yml, packages/perseus-error/src/index.ts, packages/perseus-linter/src/index.ts, packages/pure-markdown/src/index.ts
While working on integrating the latest released Perseus changes, I noticed that there are still 3 packages that have changes in the repo that aren't up to date on npmjs.com:
npmjs.com
```
@khanacademy/perseus-error     => 0.2.1
@khanacademy/perseus-linter    => 0.3.2
@khanacademy/pure-markdown     => 0.2.2
```
Locally:
```
packages/perseus-error/package.json   "0.2.2" !!
packages/perseus-linter/package.json  "0.3.3" !!
packages/pure-markdown/package.json   "0.2.5" !!
```
So this PR "bumps" each package with a comment-only change in order to force these packages to be released to npm on the next release. 
Issue: LC-1165
Watch the next Version Packages PR that we land.
=> Change packages that are lagging on npmjs.com

.changeset/tame-kangaroos-eat.md, packages/math-input/src/components/keypad/mobile-keypad.tsx
I did this in another PR but then removed it because I thought Third had already solved the issue.
Basically we just need to add the `visibility: hidden` to `dynamicStyle` so it's hidden from the start.
Issue: LC-1273
- Emulate mobile
- Turn on v2 keypad
- Go to a page with MathInput
- The keypad should not flicker during the initial load
Before:
https://github.com/Khan/perseus/assets/16308368/e9a63104-ba88-4492-b09b-63e851888d57
After:
https://github.com/Khan/perseus/assets/16308368/d7b58289-8545-4e2f-b289-0a0bd7bdd928
=> Add hasBeenActivated to v2 keypad

.changeset/fresh-countries-sleep.md, packages/math-input/src/components/keypad/__tests__/__snapshots__/keypad.test.tsx.snap, packages/math-input/src/components/keypad/shared-keys.tsx
v1 keypad was using `FRAC` and v2 keypad was using `FRAC_INCLUSIVE`.
Issue: LC-1267
- Go to v1 keypad in "Expression" mode
- Type a number
- Hit the fraction button
- Note that the number does not become the numerator
- Go to v2 keypad in "Expression" mode
- Type a number
- Hit the fraction button
- Note that the number does not become the numerator (previously it did)
=> Bugfix: make FRAC buttons use the same FRAC

.github/workflows/node-ci.yml
Switches out `check-for-changeset`, a github action that looks for the presence of a changeset file, for `changeset-per-package`, a new action that verifies that there is a changeset entry for each package with changes.
For details, see [the action repo](https://github.com/Khan/changeset-per-package).
=> Verify that there is a changeset for every changed package

.changeset/wild-suns-explain.md, packages/math-input/src/components/keypad/mobile-keypad.tsx
Turns out the memory leak was a simple little typo on a react lifecycle. Fixing that allows us to properly call _ComponentWillUnmount_, which removes all of our event listeners and observers related to resizing the keypad.
https://github.com/Khan/perseus/assets/12463099/ea18a0c6-d700-4137-b8ce-cafebded9683
- make tesc
=> Fixing a typo in mobile-keypad's unmount lifecycle. 

.changeset/eleven-jokes-wait.md, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/__tests__/numeric-input.test.ts, packages/perseus/src/widgets/numeric-input.tsx
This PR fixes a bug where we were no longer validating against pi when `answer.strict=false` when pi was provided in the answerForms. It looks like this is a side effect that came about with a more recent bug fix that exposed a hard-to-find historical bug. Previously we were always validating against pi by default, but we changed this after having issue with several questions being incorrectly tagged as approximations of pi. 
I updated tests to make sure that we're still validating against pi when these conditions are met.
Issue: LC-1331
- new test
=> Ensured that we're still validating against pi when it is provided in the answerForms.

.changeset/tall-mangos-poke.md, packages/math-input/src/components/keypad-context.tsx, packages/math-input/src/components/keypad-legacy/provided-keypad.tsx, packages/math-input/src/components/keypad-switch.tsx, packages/math-input/src/components/keypad/mobile-keypad.tsx, packages/math-input/src/full-mobile-input.stories.tsx, packages/math-input/src/types.ts, packages/perseus/src/__tests__/item-renderer.test.tsx
1. [Webapp ~ Cleanup PR](https://github.com/Khan/webapp/pull/17025)
2. [Perseus ~ Bring StatefulKeypadContext into Perseus](https://github.com/Khan/perseus/pull/747)
3. **[> Perseus ~ Add "keypadActive" state](https://github.com/Khan/perseus/pull/748)**
4. [Webapp ~ Conditionally render Khanmigo button](https://github.com/Khan/webapp/pull/17063)
The main point of these PRs is to be able to tell Khanmigo when the keypad is open so it can stop putting a button over the keypad.
This PR is a good example of some of our problems in MathInput though: there wasn't really a single place for this state. v1 keypad stored this state in Redux, v2 keypad stored this in hooks, and the KeypadContext was just passing around refs to components that other components where calling methods on. I didn't scope …
=> Add keypadActive state to context

.changeset/fresh-peas-hang.md, packages/math-input/src/components/keypad-legacy/provided-keypad.tsx
While doing some performance tuning in webapp I noticed that this component is re-rendering because we are creating the callback props inline. This means that they'll always be different. Moving them to be instance functions fixes this. 
Issue: LC-1346
I was able to `yarn link` all the Perseus packages into webapp and then test. All re-renders of the `ProvidedKeypad` component stopped with these changes.
=> Prevent provided-keypad from re-rendering due to prop callabacks

.github/workflows/node-ci.yml
Ned [noticed](https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1696342746848549) that the git SHA posted to our "npm Snapshot: Published" comment doesn't look right. It's not! When this process was originally created, we used the `GITHUB_SHA` value. Github's [docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request) state: 
> Note that GITHUB_SHA for this event is the last merge commit of the pull request merge branch. If you want to get the commit ID for the last commit to the head branch of the pull request, use github.event.pull_request.head.sha instead.
So this PR switches to use `github.event.pull_request.head.sha` so that the commit pointed to is the latest commit on the PR, not the merge commit. 
Issue: "none"
Merge and check the next …
=> Fix SHA posted when updating npm snapshots

.changeset/lemon-bears-remain.md, packages/math-input/src/components/keypad/__tests__/__snapshots__/keypad.test.tsx.snap, packages/math-input/src/components/keypad/keypad.tsx
LC-1356
Removes "grid" role from keypad. Its presence without "row" and "gridcell" roles in child elements muddles the screen reader experience.
=> Remove "grid" role from keypad

.github/workflows/node-ci-main.yml, .github/workflows/node-ci.yml, .github/workflows/release.yml
LC-1268
Change all instances of `actions/checkout` to `v3`.
`v2` uses node 12, which is no longer supported.
`v3` uses node 16, which reached end of life last month, but it's the node version we currently use in Perseus.
`v4` is out but uses node 20, which we do not yet support.
=> Upgrade actions/checkout to v3

.changeset/nice-days-compete.md, packages/perseus/src/__stories__/article-renderer.stories.tsx, packages/perseus/src/__testdata__/article-renderer.testdata.ts, packages/perseus/src/__tests__/article-renderer.test.tsx, packages/perseus/src/article-renderer.tsx
It turns out we never set up our article renderer to return the focused element, which is required to be able to scroll the element above the keypad when the user focuses on it! 
This PR adds the missing logic to the article renderer, and also makes a couple of necessary modernizations as we were still using string refs. I've also created a new story for testing multiple inputs in a mobile article. Please note that the keypad does look a little strange in this view as we don't currently have the scrollable element logic in Perseus. 
(I suspect that eventually, we should probably move the scrollIntoView logic into Perseus.)
=> Updating Article Renderer to be able to return the focusedElement so that we can scroll these elements into view above the keypad.

.changeset/calm-pears-judge.md, packages/math-input/src/components/keypad-context.tsx
=> add useMemo to KeypadContext provider

packages/perseus/src/widgets/__stories__/label-image.stories.tsx, packages/perseus/src/widgets/__testdata__/label-image.testdata.ts
While talking with SarahB about the `label-image` widget I realized we don't have a basic `label-image` widget story. 
Now we do!
Issue: "none"
`yarn start`
Navigate to **Perseus** >> **Widgets** >> **Label Image** >> **Question 1** ([here](http://localhost:6006/?path=/story/perseus-widgets-label-image--question-1))
=> Add label-image stories to see the widget in action

.changeset/poor-lizards-glow.md, packages/perseus/src/widgets/transformer.tsx
Team-LC has noticed recently that the skip rate on our transformer widget was quite a bit higher than it is normally. After further investigation, we discovered that the "homothety"/dilation tool is spitting out a large barrage of errors and is no longer functional. We suspect this is likely the main cause for the increase in reports. 
@jeanettehead and I looked into the history of the file and noticed that a key line of code was accidentally shifted to be a part of a parent comment as part of a [PR that removed all references to flow in Perseus](https://github.com/Khan/perseus/pull/457).
`center: self.dilationCircle.centerPoint.coord`
It looks like a pesky little newline was accidentally (and likely automatically) removed, causing us to lose access to the required "center" property for …
=> Ensured we have access to transform.center when working with dilation in the Transform Widget 

.changeset/cool-days-sell.md, packages/perseus/src/styles/articles.less, packages/perseus/src/styles/perseus-renderer.less, packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set.test.ts.snap, packages/perseus/src/widgets/graded-group-set.tsx
LC-1291
Blocks some global list styles from affecting indicator dot `ul` container. This was causing a horizontal stretch in mobile, as well as other more subtle side effects.
Also, increases clickable area to 24 by 24 and adds hover/focus states. This required some refactoring of the current code. Now, instead of an `li` containing a `span`, it's an `li` containing a WonderBlocks `Clickable` containing a `span`... and when it's active, it contains another span! The interior span is to get around the background filling in the double border.
Style changes per this design:
https://www.figma.com/file/2lUPOSbOP8tbW7RLqbBFLh/Expression-Widget?type=design&node-id=5018-31744&mode=design&t=Ln3lgFaqAagSV97A-0
=> Fix horizontal stretch for graded group dots, + a11y tweaks

.changeset/itchy-toes-decide.md, packages/perseus-core/src/analytics.ts, packages/perseus/src/__tests__/widget-container.test.tsx, packages/perseus/src/error-boundary.tsx, packages/perseus/src/widget-container.tsx
Patrick and I discussed whether this event should have the `widgetId` on it. We agreed it should, but I forgot to add it back in. So here we go. 
I also realized that I missed a very important part of this implementation while adding missing tests. The part where we call the analytics. 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️   Added now!
Issue: LC-1383
`yarn test`
=> Add missed widgetId to 'perseus:widget-rendering-error' event

.changeset/shaggy-seals-sort.md, packages/math-input/src/components/aphrodite-css-transition-group/transition-child.tsx
@third noticed that our mobile keypad wasn't animating in the first time it was opened. Subsequent closes/opens were all animating correctly. 
I tracked it down to a change I made while porting the `AphroditeCSSAnimationGroup` in. Originally, there was a call like this to queue some styling changes on the element being transitioned for after the next paint: `setTimeout(doStyleChanges, 17);`. It seemed "off" that we were trying to identify when the next paint time would be by assuming 60 fps. So I changed it to use `requestAnimationFrame()`. What I didn't understand is that `requestAnimationFrame()` queues the function to run _before_ the next paint, not after! 
This PR fixes that by switching back to `setTimeout()`. But it doesn't fully revert to use the calculated duration for 60 fps …
=> Fix animation of mobile keypad after initial render

.changeset/chilled-jeans-sing.md, packages/math-input/src/components/keypad/__tests__/__snapshots__/mobile-keypad.test.tsx.snap, packages/math-input/src/components/keypad/mobile-keypad.tsx
Our keypadElement was only returning null to webapp after our new rendering improvements. This tiny PR should fix the issue so that we can use the keypadElement to scroll our inputs into view. 
=> Moving ref'd element above the animation so that it doesn't return null

.changeset/four-zoos-boil.md, packages/perseus/src/widgets/label-image/strings.ts
Just adds a single string for translation so that our international team can get a jump-start on internationalization.
Issue: LC-1447
=> Add string for translation

.changeset/spotty-snails-serve.md, packages/math-input/src/components/key-handlers/key-translator.ts, packages/math-input/src/components/keypad/__tests__/__snapshots__/keypad.test.tsx.snap, packages/math-input/src/components/keypad/__tests__/__snapshots__/mobile-keypad.test.tsx.snap, packages/math-input/src/components/keypad/__tests__/keypad.test.tsx, packages/math-input/src/components/keypad/button-assets.tsx, packages/math-input/src/data/key-configs.ts, packages/math-input/src/enums.ts, packages/math-input/src/utils.ts
We were supposed to be switching between `,` and `.`, but we didn't see that through when updating how we're rendering icons for the v2 keypad. This updates that and adds some unit tests.
Issue: LC-1453
- Use or simulate mobile web
- Go to an exercise with a MathInput
- Open the keypad by focusing the MathInput
- Note a `.` as the decimal separator (if you're in the US)
- Change your locale?
- Use or simulate mobile web
- Go to an exercise with a MathInput
- Open the keypad by focusing the MathInput
- Note a `,` as the decimal separator
=> Conditionally switch decimal separator based on locale

.changeset/great-kiwis-nail.md, packages/perseus-editor/src/styles/perseus-editor.less, packages/perseus/src/styles/khan-exercise.css
This PR fixes our #problemarea width and min height by removing the base setting. This CSS is not used anywhere, as the only two places the #problemarea exists (ItemEditor and in the mobile application) are both having to override these settings back to the baseline.  
Issue: LC-1475
manual testing + confirming code use.
=> Cleanup #problemarea CSS

.changeset/green-ligers-roll.md, packages/perseus/src/styles/perseus-renderer.less
On our mobile app, we're noticing that hints are rendering above our keypad due to this style that sets the z-index to 3. I don't think we need z-index here at all as the #problemarea is only used on Mobile and in the content editor - neither of which need the index. 
Rather than using .perseus-interactive, I'm now simply setting the position directly. The relative positioning is still important to ensure that the "+" symbol appears beside the "Next Hint" button. 
Issue: LC-1445
manual
=> Remove unnecessary Z-Index for #problemarea buttons/inputs

config/test/test-setup.ts, package.json, wallaby.js
When we moved Perseus out of webapp we brought along a mechanism to mock `console.*()` calls. I think the original intent was to make it an explicit choice to have console logging in our production code. 
In reality, this has caused more headaches than it has saved us. Also, our build system can strip out console logging if we need that in the future. 
Issue: "none"
=> Remove console mocking in tests

.changeset/calm-buses-sparkle.md, packages/perseus/src/widgets/__stories__/label-image.stories.tsx, packages/perseus/src/widgets/__testdata__/label-image.testdata.ts, packages/perseus/src/widgets/label-image.tsx
If an image is wider than it is tall, popovers and pills can only appear above or below markers.
Lessens changes of pills overlapping markers or each other.
Adds the number line story from Test Everything to verify.
Issue: LC-1504
https://github.com/Khan/perseus/assets/23404711/84093a82-d2eb-498c-8daf-553d1f164660
Check out the story.
=> For wide images, label image popovers go above or below markers to lessen chances of covering markers

.changeset/grumpy-sheep-own.md, packages/perseus/src/styles/widgets/label-image.less, packages/perseus/src/widgets/label-image.tsx, packages/perseus/src/widgets/label-image/answer-pill.tsx
Reverts all Perseus global mobile styles for WB answer pill
BEFORE:
AFTER:
Issue: LC-1515
Check pill in webapp in mobile web and editor view. Should have white lettering.
=> Fix dark typography on mobile view

.changeset/perfect-experts-doubt.md, packages/perseus/src/styles/widgets/label-image.less, packages/perseus/src/widgets/label-image.tsx, packages/perseus/src/widgets/label-image/__tests__/answer-pill.test.tsx, packages/perseus/src/widgets/label-image/__tests__/hide-answers-toggle.test.tsx, packages/perseus/src/widgets/label-image/answer-pill.tsx, packages/perseus/src/widgets/label-image/hide-answers-toggle.tsx
Moves switch to its own functional component in order to take advantage of WB id hook.
Also applies id hook to answer pill to prevent unlikely ID collisions that @jeremywiebe brought up.
Finally, switches the position of the switch and label and adds a bit of margin to make it less likely that the switch would be covered up by an answer pill.
Issue: LC-1517
Toggle now has accessible label when focused by screen reader.
=> Add accessible label to hide answers switch (also increase padding and prevent ID collisions)

.changeset/tame-maps-do.md, packages/perseus/src/styles/widgets/label-image.less
Fixes padding on correct pills.
The CSS was only targeting `button` tags with the given ID, but when the pill becomes non-interactive, it turns into a `div`.
Corrected the styles to account for this change.
Issue: LC-1525
Testing strategy:
Ensure pill padding is consistent in all states.
=> Fix padding on correct pill

.changeset/eight-worms-teach.md, packages/perseus/src/styles/khan-exercise.css
Remove /images/next-step.png and /images/previous-step.png from CSS imports
These are legacy, according to Jeremy unused, and cause problems with build pipelines.
Issue: LC-1462
=> Remove unused images in CSS

.changeset/good-brooms-explode.md, packages/perseus/src/widgets/label-image.tsx
We had custom dismissal logic that duplicated WB Popover's built-in functionality.
During our changes, something occurred to make our "document click" event listener see clicks on the marker as clicks on the document outside of our popover, and therefore set the "active index" to -1 just before we check of the active index matches the marker's index in order to dismiss it. Since the active marker index was always -1 when checked, the popover would not dismiss.
This change removes our custom logic and takes advantage of the same logic built into the Popover itself. Now everything dismisses as expected with document click, "esc" key press, and marker click.
Issue: LC-1543
Testing strategy:
Click the marker to open the answer choices dropdown, then click it again to dismiss.
=> Let WB handle popover dismissal; fixes dismissal bug

.changeset/loud-chefs-taste.md, packages/math-input/src/components/input/math-input.tsx, packages/math-input/src/components/input/scroll-into-view.ts
While investigating the blur issue from LC-1523, I discovered that we have some historical logic for caching our keypad bounds. None of that is necessary any longer. 
Fixing/removing this logic solves LC-1523 by ensuring that we are always getting the _current_ keypadBounds, which allows us to be able to click under the input again to blur it after the keypad has been closed/animated out of view.
It seems we've added a resize observer directly to the keypad, so we no longer need a bunch of event listeners in our MathInput either!
Issue: LC-1523
- Manual testing of multiple device orientations and resizes
=> Ensure that we're always getting the correct keypad bounds

.changeset/twenty-moles-nail.md, packages/math-input/src/components/keypad/__tests__/keypad.test.tsx, packages/math-input/src/components/keypad/shared-keys.tsx, packages/math-input/src/index.ts, packages/math-input/src/utils.test.ts, packages/math-input/src/utils.ts, packages/perseus/src/components/math-input.tsx
Basically just a helper that overwrites `convertDotToTimes` depending on specific locales.
Issue: LC-1454
Confirmed working in French at least 🤷 ([Webapp PR](https://github.com/Khan/webapp/pull/18609)). The exercise has `times` aka `convertDotToTimes` set to false, but still renders the times.
=> add locale to convertDotToTimes logic

.changeset/light-coats-wink.md, packages/perseus/src/widgets/label-image/hide-answers-toggle.tsx
Apparently, for a label to be a label, we have to specify that the label is a label.
Issue: LC-1561
Label is label
=> Make WB label into actual label tag

.changeset/angry-doors-argue.md, .changeset/smart-spoons-move.md, packages/perseus-editor/src/__stories__/item-editor.stories.tsx, packages/perseus-editor/src/__tests__/item-extras-editor.test.tsx, packages/perseus-editor/src/item-extras-editor.tsx, packages/perseus/src/__testdata__/graphie.testdata.ts, packages/perseus/src/__testdata__/server-item-renderer.testdata.ts, packages/perseus/src/__tests__/mock-asset-loading-widget.tsx, packages/perseus/src/index.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/__testdata__/expression.testdata.ts
- Add financial calculator checkboxes to Item Extras
- Add an indentation to dependent checkboxes
- Slight refactor to reduce redundant code
- Added item extras story
Issue: LC-1537
Testing strategy:
Check in new story that nothing has changed except new checkboxes added.
Clicking Financial Calculators checkbox should expand three checked options. Unchecking all options unchecks parent checkbox; unchecking parent unchecks options.
=> Add financial calculator checkboxes to Item Extras Editor

.changeset/clever-walls-lie.md, packages/perseus-editor/src/__stories__/item-editor.stories.tsx, packages/perseus-editor/src/__tests__/item-extras-editor.test.tsx, packages/perseus-editor/src/item-extras-editor.tsx, packages/perseus/src/perseus-types.ts
One of the fields added in #867 is redundant and does not need to be exposed outside of Perseus. Switched it to component state.
=> Remove unused field from PerseusAnswerArea

.changeset/blue-beds-fly.md, packages/math-input/src/components/input/math-input.tsx, packages/perseus/src/widgets/__tests__/expression-mobile.test.tsx
When users close the keypad using the "X" button, we retain focus on the input in order to vastly improve the user experience for screen readers. Unfortunately, this caused an issue where users would be unable to re-trigger the keypad until blurring the input. 
This PR adds some logic that allows us to open the keypad if our input is currently focused, and the keypadActive is currently set to false. 
Issue: LC-1524
- Manually tested by bumping perseus in webapp to this PR, and then reviewing both mobile web using Chrome Dev Tools and iOS Simulator Safari.
I can't seem to upload them without them resulting in downloadable files, so instead I'll add them to the Jira ticket.
=> Ensure that we can reopen the keypad by clicking/tapping an already focused math-input.

.changeset/two-birds-refuse.md, packages/perseus/src/question-paragraph.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/styles/widgets/label-image.less, packages/perseus/src/widgets/__stories__/label-image.stories.tsx, packages/perseus/src/widgets/__testdata__/label-image.testdata.ts, packages/perseus/src/widgets/label-image.tsx, packages/perseus/src/widgets/label-image/__stories__/answer-pill.stories.tsx, packages/perseus/src/widgets/label-image/answer-pill.tsx, packages/perseus/src/widgets/passage-ref-target.tsx
Rather than block paragraph styles from every avenue we come across, instead prevent them from being associated with the answer pill in the first place.
Adds a `inline` prop to `Renderer` that blocks the `paragraph` class from being added to answer pills.
Issue: LC-1569
Use NPM snapshot or link to check out editor and mobile view of label image widget exercises on webapp.
=> Prevent paragraph class from being added to answer pills

.changeset/proud-rockets-roll.md, packages/perseus/src/__tests__/error-boundary.test.tsx, packages/perseus/src/error-boundary.tsx
I was looking at our Sentry dashboard and noticed that _all_ Perseus rendering errors are grouped together under one event. This is largely due to the fact that the error boundary uses the same string for all errors it catches.
So this PR changes that error logging so that each different type of error caught by the boundary are logged as a different error (Sentry event). This will help us to triage/review errors in Sentry and not group all Perseus errors together in host applications.
Issue: "none"
=> Make Perseus error reports easier to triage

.changeset/curly-jobs-sit.md, packages/perseus-editor/src/widgets/__stories__/radio-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx
Trying to not modify _what_ I'm testing too much, just trying to add _some_ tests.
For some reason editing the text for the answers didn't trigger the `onChange` callback and I don't want to spend too much time on each of these, so I didn't test editing answers yet.
=> add some tests for the radio editor

.changeset/tender-tomatoes-flow.md, packages/perseus-editor/src/editor.tsx, packages/perseus-editor/src/widgets/__stories__/explanation-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/explanation-editor.test.tsx
Most of the functionality for this is buried in the `Editor` component and I don't want to go down that rabbit hole right now.
=> add tests for ExplanationEditor

.changeset/proud-roses-sneeze.md, packages/perseus-editor/src/__tests__/editor.test.tsx, packages/perseus-editor/src/editor.tsx
Adds a simple confirmation before proceeding with the widget deletion. This will hopefully prevent alot of frustration by avoiding losing work.
Issue: LC-1590
Run the tests.
=> Add confirmation before deleting a widget config

packages/perseus-editor/src/__stories__/editor.stories.tsx
I noticed that our `Editor` component stories live in the top-level "Editor" folder. This is not even the top-level editor (EditorPage is) so I've moved it into a folder like our other editor stories are. 
=> [🔥AUDIT🔥] Move Editor component into its own folder

.changeset/nasty-eels-explode.md, packages/perseus-editor/src/widgets/__stories__/definition-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/definition-editor.test.tsx
Seems like things that use `Changeable` are a little problematic to test since they're not calling the `onChange` callback as expected.
Looking into it, it seems like there are several tickets to refactor it: https://khanacademy.atlassian.net/browse/LC-394
=> add tests to DefinitionEditor

.changeset/empty-rabbits-mate.md, packages/perseus/src/__tests__/server-item-renderer.test.tsx, packages/perseus/src/article-renderer.tsx, packages/perseus/src/server-item-renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/__stories__/expression.stories.tsx
We have recently noticed a regression related to scrolling in the mobile application after fixing an issue related to our MathInput package not updating. The issue is that we're unable to properly calculate the keypadHeight using the new keypad mounting approach. 
This PR is a partial fix for that issue by simplifying the OnFocusChange method so that it returns the keypadHeight directly, rather than the DOMNode for the keypad. This will allow us to centralize the logic and keep things DRY across Mobile Web and our Mobile App. 
Issue: LC-1575
- updated unit tests accordingly
=> Update OnFocusChange logic so that it returns the keypadHeight rather than the entire DomNode for the keypad

.changeset/dry-mugs-camp.md, packages/perseus/src/styles/perseus-renderer.less, packages/perseus/src/styles/variables.less
This ensures that color-coded math expressions have accessible contrast
with the darker table rows.
Issue: https://khanacademy.atlassian.net/browse/LC-1577
Test plan:
Run storybook: `yarn storybook`.
Visit
`http://localhost:6006/?path=/story/perseus-renderers-item-renderer--label-image-item`
You should see a table of dog breeds. The background color of the
odd-numbered rows should be `#f7f8fa`.
=> Change table zebra-stripe color to Wonder Blocks offWhite

.changeset/shy-vans-wash.md, packages/perseus/src/__stories__/article-renderer.stories.tsx, packages/perseus/src/__tests__/server-item-renderer.test.tsx, packages/perseus/src/article-renderer.tsx, packages/perseus/src/server-item-renderer.tsx
When testing the previous keypadHeight fix during a Perseus deploy on webapp, it was discovered that the height being returned on initial render seems to be the entire view height rather than the height of our keypad. 
This PR returns us to the original setTimeout method and method call order, and ensures that we're always getting the correct keypadHeight returned. I've also updated some tests to handle the additional asynchronous call. While the setTimeout method isn't ideal, this should solve our scroll-breaking issue until we're able to completely move the scrolling logic into Perseus. 
- manual testing in webapp has shown that this has solved the issue
=> Updated tests to accommodate for new setTimeout method.

.changeset/lazy-tables-listen.md, packages/perseus/src/widgets/iframe.tsx, packages/perseus/src/widgets/input-number.tsx, packages/perseus/src/widgets/lights-puzzle.tsx, packages/perseus/src/widgets/matcher.tsx, packages/perseus/src/widgets/numeric-input.tsx, packages/perseus/src/widgets/radio.ts, packages/perseus/src/widgets/reaction-diagram.tsx, packages/perseus/src/widgets/sequence.tsx, packages/perseus/src/widgets/simulator.tsx, packages/perseus/src/widgets/table.tsx, packages/perseus/src/widgets/transformer.tsx, packages/perseus/src/widgets/unit.tsx
Currently, some widget display names (shown in the "add widget"
dropdown) do not match their type names (used in the editor).
This can be confusing for content writers when trying to find
and use widgets.
To fix this, some of the display names have been updated to
better match their type names. In addition, deprecated widgets
have been marked as such.
For the full list of updated names, see:
https://khanacademy.atlassian.net/l/cp/C5PWFNAe
Issue: https://khanacademy.atlassian.net/browse/LC-1566
- Go to the storybook page for EditorPage (http://localhost:6006/?path=/docs/perseus-editor-editorpage--docs)
- Click on the "Add a widget..." dropdown
- Confirm that the list of widget matches the non-deprecated widgets' display names
https://github.com/Khan/perseus/assets/13231763/f34d5a6d-d184-4ca …
=> Update widget display names to better match their type names

.changeset/ninety-toys-visit.md, packages/perseus-editor/src/components/__tests__/blur-input.test.tsx, packages/perseus-editor/src/components/blur-input.tsx, packages/perseus-editor/src/editor-page.tsx, packages/perseus-editor/src/editor.tsx, packages/perseus-editor/src/hint-editor.tsx, packages/perseus-editor/src/iframe-content-renderer.tsx, packages/perseus-editor/src/item-editor.tsx, packages/perseus-editor/src/widgets/example-widget-editor.tsx, packages/perseus-editor/src/widgets/example-widget.tsx, packages/perseus-editor/src/widgets/graded-group-editor.tsx, packages/perseus-editor/src/widgets/group-editor.tsx, packages/perseus-editor/src/widgets/input-number-editor.tsx, packages/perseus-editor/src/widgets/simple-markdown-tester-editor.tsx, packages/perseus-editor/src/widgets/simple-markdown-tester.tsx, packages/perseus-editor/src/widgets/table-editor.tsx
Perseus editor code still uses alot of string refs. I went through and converted the easy/simple ones to `React.createRef<>`s. 
Sorry: This is a large-ish PR, but I hope it's fairly straightforward to review.
* Convert all string refs in Example widget and editor to React refs
* Convert EditorPage itemEditor ref to a React ref
* Convert EditorPage hintsEditor ref to a React ref
* Remove unused manually-created <div> rendererMountNode
* Convert ItemEditor's frame ref to a React ref
* Convert ItemEditor's questionEditor ref to a React ref
* Convert ItemEditor's itemExtrasEditor ref to a React ref
* Convert all string refs in Editor to React refs
* Convert IframeContentRenderer's container ref to a React ref
* Convert all string refs in HintEditor to React refs
* Convert all string refs in …
=> Convert a _bunch_ of string refs to React refs

.changeset/shiny-pugs-jump.md, packages/perseus-editor/src/__tests__/hint-editor.test.tsx, packages/perseus-editor/src/hint-editor.tsx
Adds a simple confirmation before proceeding with the hint is deleted. This will hopefully prevent alot of frustration by avoiding losing work.
Issue: LC-1591
=> Add confirmation before deleting a hint

.github/workflows/node-ci.yml
I noticed that the upload-artifact actions were warning that they were set to run on Node v12 and would be automatically forced to run on Node v20 (now that @somewhatabstract has upgraded this repo! 🙇‍♂️ ). 
Upgrading these actions to latest to silence these warnings and take advantage of improvements in the new version.
=> Upgrade upload-artifact and download-artifact to v4

packages/perseus/src/widgets/__stories__/orderer.stories.tsx, packages/perseus/src/widgets/__testdata__/orderer.testdata.ts
Khan Academy content for early math often asks learners to demonstrate understanding of numbers by adding items to a box. Example: "Add 6 flowers to the box" ([live link](https://www.khanacademy.org/math/early-math/cc-early-math-counting-topic/cc-early-math-counting/e/counting-out-1-20-objects)).  The learner then uses the `orderer` widget to drop 6 flower images into the grey box. 
This PR adds a story that illustrates this usage of the `orderer` widget.
Issue: "none"
Navigate to the story and test it out.
=> Introduce orderer story that uses images

.changeset/yellow-games-run.md, packages/perseus/src/widgets/label-image/marker.tsx
Fix a small Safari-only bug. An icon was given a width and height of 0-- calculations were applied in icon.tsx that resulted in some odd behavior in Safari. We fix that by giving height and width of 1 instead. Since the path is empty, this makes no visual difference.
Would love to switch these to WB icons, but now is not the time.
Odd behavior in safari (can't click directly on markers in a line) should be fixed.
=> [🔥AUDIT🔥] Avoid divide by 0 bug from icon.tsx

.changeset/new-colts-sip.md, packages/math-input/src/components/input/mathquill-instance.ts, packages/perseus/src/widgets/__testdata__/expression.testdata.ts, packages/perseus/src/widgets/__tests__/expression.test.tsx, packages/perseus/src/widgets/expression.tsx
`sen` is used instead of `sin` in Portuguese. This change allows the
Expression widget to accept both spellings. We simply convert any
instances of `sen` to `sin` when evaluating the learner's answer.
Issue: https://khanacademy.atlassian.net/browse/LC-290
Test plan:
- Start storybook: `yarn storybook`.
- Visit
`http://localhost:6006/?path=/docs/perseus-widgets-expression--docs`.
Enter `sen(x)` in one of the input fields. The word `sen` should be
displayed in an upright font, indicating that it is an operator. `sin`,
`cos`, `tan` etc. should also be displayed in an upright font.
=> Make the Expression widget treat `sen` as equivalent to `sin`

.github/actions/shared-node-cache/action.yml, .github/workflows/node-ci.yml
This reorders the steps so the SSH key is available before the npm install included in the shared-node-cache action.
Issue: LC-1573
- Confirm checks pass
- After landing, confirm checks for PR #917 (updating MathJax in Perseus' Storybook) pass
=> Update order of steps in action.yml

.changeset/proud-donkeys-sip.md, packages/perseus/src/util/tex.ts, packages/perseus/src/widgets/__tests__/__snapshots__/grapher.test.ts.snap, packages/perseus/src/widgets/__tests__/__snapshots__/interaction.test.ts.snap, packages/perseus/src/widgets/__tests__/__snapshots__/interactive-graph.test.ts.snap, packages/perseus/src/widgets/__tests__/__snapshots__/number-line.test.ts.snap, packages/perseus/src/widgets/__tests__/__snapshots__/plotter.test.tsx.snap
There was a lot of code in this file related to our old KaTeX+MathJax2
renderer. Now that we have switched to MathJax 3, we can simplify things. I've
also deleted a couple functions that simply weren't used anywhere.
I changed the type of `processMath`'s `text` param to `string | number` because
the code that generates Graphie labels sometimes passes a number.
Issue: none
Test plan:
Review storybook stories that use TeX labels:
- Grapher widget
- Interactive Graph widget
- Number Line widget
The graph labels should display in the correct place.
=> Delete unused code from tex.ts

.changeset/shy-nails-crash.md, packages/perseus/src/util/graphie.ts, packages/perseus/src/util/interactive.ts, packages/perseus/src/widgets/interactive-graph.tsx
They don't depend on the Graphie object's state.
We deleted cartToPolar because it was unused.
Issue: none
```
yarn cypress:ci
```
Review the Grapher and Interactive Graph docs in Storybook.
=> Remove polar and cartToPolar from the Graphie prototype

.changeset/neat-shirts-fail.md, packages/perseus/src/index.ts, packages/perseus/src/util/parse-perseus-json.test.ts, packages/perseus/src/util/parse-perseus-json.ts
I feel a little silly about this PR, but I think it'll be useful. Just exporting a wrapper around `JSON.parse` so we have a one-stop shop for Parsing Perseus JSON needs.
Issue: LC-1656
- unit test
=> add parsePerseusJSON

.changeset/yellow-melons-perform.md, packages/perseus/src/util/graphie.ts
As I was moving methods into the Graphie class, I noticed that the shade and
fn2 params are never used. Removing them lets us simplify the code quite a bit.
View the Storybook docs for Grapher, Interactive Graph, and Number Line.
=> Remove unused parameters from plot and plotParametric

.changeset/grumpy-panthers-report.md, packages/perseus/src/util/graphie.ts, packages/perseus/src/util/interactive.ts
The previous behavior was that GraphUtils.svgPath would draw a path scaled for
the most recently-created Graphie. That was weird, and totally unnecessary.
There was only one usage of GraphUtils.svgPath, and I've changed it to call
svgPath on the appropriate Graphie instance instead.
Review Storybook docs for Interactive Graph, Grapher, and Number Line
=> Avoid exporting svgPath on GraphUtils

.changeset/angry-ladybugs-drive.md, .changeset/eleven-waves-smile.md, packages/perseus-editor/src/widgets/__stories__/image-editor.stories.tsx, packages/perseus-editor/src/widgets/image-editor.tsx, packages/perseus/src/index.ts, packages/perseus/src/mixins/changeable.ts, packages/perseus/src/widgets/label-image.tsx
Adds a new Storybook story for the Image Editor.
Converts the editor component from legacy `createReactClass` to a slightly more modern `React.Component<>` class. 
Check the component in storybook.
Review the component changes
=> ImageEditor improvements: Story, tests, refactor

.changeset/early-pillows-kiss.md, packages/perseus/src/__testdata__/renderer.testdata.ts, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/renderer.tsx, packages/perseus/src/types.ts
A major pain point that we've been hitting lately for several initiatives is that there was no way to determine the shuffle order of our answers, as it happens during the exercise rendering phase. 
This PR adds a callback to apiOptions so that we can "getWidgetsStartProps", which will provide us with the current shuffled order of the answers. 
Issue: LC-1638
- New test 
- Manual testing
=> Creation of a callback that can allow us to determine the shuffle order of various widget choices. 

.changeset/wet-bags-call.md, packages/perseus/src/index.ts, packages/perseus/src/util/parse-perseus-json.test.ts, packages/perseus/src/util/parse-perseus-json.ts
After digging more in the Webapp code, they're parsing more than just the PerseusItem.
Renaming this so it's more explicit about what it's for.
=> rename helper to parsePerseusItem

.changeset/short-maps-call.md, packages/kmath/src/__tests__/vector.test.ts, packages/kmath/src/point.ts, packages/kmath/src/vector.ts, packages/perseus/src/util/graphie.ts
The built-in APIs have better type support, and are idiomatic.
One underscore function that has no equivalent in vanilla JS is `_.zip`.
I've reimplemented zip so we can avoid importing underscore. This gets
us more robust typechecking around zip calls.
Test plan:
Review the Storybook docs for Grapher, Interactive Graph, and Number
Line.
=> Use built-in JS functions instead of underscore/jQuery functions

.changeset/nasty-suits-add.md, packages/math-input/src/components/keypad/__tests__/__snapshots__/keypad.test.tsx.snap, packages/math-input/src/components/keypad/shared-keys.tsx, packages/math-input/src/full-keypad.stories.tsx
When the PERCENT button isn't present, the FRAC button
seems to be out of focus order when tabbing through the
Keypad. Also, even if it shows up in left-to-right order
when the PERCENT button is there, it still divides the
add/subtract/multiply/divide block, which is not intuitive
for screenreader users.
In this PR, I fixed this by moving the FRAC button just
before the PLUS button.
I also added a story for Keypad that includes all the
buttons excluding the navigation pad.
Issue: https://khanacademy.atlassian.net/browse/LC-1015
https://github.com/Khan/perseus/assets/13231763/0fbf1ea0-5264-4f20-80f4-c7974b62ac46
https://github.com/Khan/perseus/assets/13231763/dd59fd35-ce55-45e0-9951-d91d486e3bf3
https://github.com/Khan/perseus/assets/13231763/37410cb5-f3fd-46ce-b735-591b2f5b40fc …
=> Keypad: Move the FRAC button before the add/subtract/multiply/divide block

.changeset/purple-avocados-relate.md, .changeset/twelve-peas-add.md, packages/perseus-editor/src/__tests__/integration.test.ts, packages/perseus-editor/src/index.ts, packages/perseus/src/__tests__/widgets.test.ts, packages/perseus/src/widgets.ts
We recently removed the `transformer` widget by replacing it with the `deprecated-standin` widget. Unfortunately, this registration had a typo. 
This is showing up in Sentry: https://khanacademyorg.sentry.io/issues/4929063013/?project=15744
This PR fixes the typo and adds a test to ensure our entry-point widget registrations are doing things correctly. 
See: https://khanacademy.slack.com/archives/CJSB0D3BN/p1706825855657239
Issue: "none"
`yarn test` passes
=> Fix deprecated-standin widget override of transformer widget

.changeset/plenty-tips-occur.md, packages/perseus/src/widgets/label-image.tsx, packages/perseus/src/widgets/label-image/marker.tsx
Moves marker label so that it's a sibling to the answer pill so that both are read. Also, ensures there is an explicit "button" label on Clickable so that we trigger the automated math label in MathJax Renderer.
https://github.com/Khan/perseus/assets/23404711/f63af37e-43e8-4b7f-b8d9-d37f737dcd16
Issue: LC-1701
Testing:
Open Safari with VoiceOver. Select an answer on Label Image Widget. Focus on marker and see that answer is read (and is accurate for math)
=> Label Image: screen reader reads answer alongside marker

.changeset/clever-steaks-bathe.md, .changeset/giant-cycles-call.md, packages/math-input/src/components/input/mathquill-instance.ts, packages/perseus/src/widgets/__tests__/__snapshots__/input-number.test.ts.snap, packages/perseus/src/widgets/__tests__/__snapshots__/numeric-input.test.ts.snap
The lowest-hanging fruit in our effort to internationalize the Desmos MathQuill accessibility features. Swaps out "Math Input" for our translated string, "Math input box".
Issue: LC-1706
Testing:
Screen reader should say "Math input box" or "Math input box: {some mathspeak}" when focused on math input.
=> LC-1706: Replace MathQuill's "Math Input" label with translated string

.changeset/wild-zoos-share.md, packages/perseus/src/__tests__/init.test.ts, packages/perseus/src/init.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets.ts
When we pushed out the removal of the `transformer` widget, we missed uncommenting the replacement line. This fixes it and adds a test to the Perseus init() function to ensure we do that.
Issue: "none"
`yarn test`
=> Fix Perseus so we register the transformer replacement

.changeset/bright-walls-tell.md, packages/perseus/src/interactive2/interactive-util.test.ts, packages/perseus/src/interactive2/interactive-util.ts, packages/perseus/src/interactive2/movable-helper-methods.ts, packages/perseus/src/interactive2/movable-line.ts, packages/perseus/src/interactive2/movable-point.tsx, packages/perseus/src/interactive2/movable-polygon.ts, packages/perseus/src/interactive2/movable.ts
This is in preparation for making Movable an ES6 class. I attempted to do that,
but ran into problems because normalizeOptions was doing spooky magic. Hopefully
this will make the next refactoring easier.
Review Storybook docs for Interactive Graph, Grapher, and Number Line
=> Test and simplify normalizeOptions

.changeset/gold-kings-dance.md, packages/math-input/package.json, yarn.lock
This PR is largely to force a math-input bump. I'm removing a dependency that isn't used anyways (`performance-now`).  It was introduced in [D27084](http://phabricator.khanacademy.org/D27084) and removed in #523.  Just cleaning up the unused dependency now.
Issue: "none"
=> Remove unused dependency 'performance-now' from @khanacademy/math-input

.changeset/short-otters-confess.md, packages/kas/package.json, packages/kmath/package.json, packages/math-input/package.json, packages/perseus-core/package.json, packages/perseus-editor/package.json, packages/perseus-error/package.json, packages/perseus-linter/package.json, packages/perseus/package.json, packages/pure-markdown/package.json, packages/simple-markdown/package.json
Source files (`.ts`) were causing typechecking problems in webapp. We're
not sure exactly why they just started happening recently, but it seems
related to our improved typing around Graphie and Raphael.
Issue: none
Upgrade Perseus packages to the new versions in webapp. There should be no type
errors when you run `yarn tsc -w` in services/static.
=> Only include 'dist/' in NPM packages

.changeset/metal-cameras-watch.md, packages/perseus/src/components/math-input.tsx
Currently, if a user has the keypad open and they click into the
input field, it automatically closes the keypad. This is not
the expected behavior - clicking outside the keypad should close it
EXCEPT when the clicked element is the math input.
In this PR:
- The math input field's `onClick` includes an `e.stopPropogation()`
in order for the keypad to not read that click outside itself.
This prevents the keypad from closing when the input is clicked.
NOTE: This will not fix the issue listed in the ticket, because that 
has to be done in [webapp](https://github.com/Khan/webapp/blob/master/services/static/javascript/guide/ui/math-editor.tsx#L278). To fix it, we can just copy the approach
from this PR.
Issue: https://khanacademy.atlassian.net/browse/LC-1410
Storybook
- Go to …
=> Stop propogation in math input field click in order to prevent keypad closing

.changeset/silent-ladybugs-pretend.md, packages/math-input/package.json, packages/math-input/src/components/input/__tests__/test-math-wrapper.ts, packages/math-input/src/components/input/math-wrapper.ts, packages/math-input/src/components/input/mathquill-types.ts, packages/math-input/src/components/key-handlers/handle-arrow.ts, packages/math-input/src/components/key-handlers/handle-backspace.ts, yarn.lock
Add types for MathQuill cursor and controller in
`mathquill-types.ts`.
We couldn't get these typed in mathquill.d.ts inside
the mathquill repo without it turning into a dumpster
fire of type errors. In Perseus, they're just using
type `any` since they're not defined in the mathquill API.
Since we don't want them to use type `any`, we can just
define them here in Perseus.
This PR includes
- Cursor and Controller types in mathquill-types.ts
- Updates to other files to match the new types
Issue: https://khanacademy.atlassian.net/browse/LC-1659
`yarn jest`
Storybook
- Go to http://localhost:6006/?path=/docs/math-input-components-v2-keypad-with-mathquill--docs
- Play around with the buttons and confirm that the input looks correct
- Confirm there are no console errors
=> Add Controller and Cursor types for MathQuill

.changeset/rich-glasses-type.md, packages/math-input/package.json, packages/math-input/src/components/input/mathquill-instance.ts, packages/math-input/src/utils.test.ts, packages/math-input/src/utils.ts, packages/perseus/package.json, yarn.lock
Swaps out MathQuill's hardcoded English MathSpeak for localized MathSpeak generated by MathJax/SRE
Issue: LC-1710
Testing:
Open Storybook and check generated labels. They should look the same!
If you can get Storybook into another locale supported by SRE, you'll see translated MathSpeak.
If you swap out the function in `createMathField` for something that returns "poot", all of the MathSpeak will be replaced with "poot".
=> Inject generated and localized MathSpeak into MathQuill

.changeset/ninety-socks-hang.md, dev/index.html, dev/index.tsx, dev/package.json, yarn.lock
Issue: https://khanacademy.atlassian.net/browse/LC-1741
```
yarn dev
open http://localhost:5173
```
You should see 9 interactive graphs. Toggling the "Mobile" switch should make
some of the points have 3D shadows.
Known issue: The sinusoid graph is broken in "mobile" mode, and if you turn
mobile mode on and off again, the graph remains broken.
=> Add more graph types to the dev UI

.changeset/eleven-colts-perform.md, packages/perseus/src/widgets/radio/choice.tsx
While removing `perseus-legacy` from webapp (https://github.com/Khan/webapp/pull/19729/files) Adam G asked about the string removals. I assumed (incorrectly) that they were just due to removal of deprecated/unsupported features. It turns out that some were changes we've made to Perseus over time where we missed wrapping user-facing strings in `i18n._()` after a refactoring. 
This PR restores the ones that I could identify by searching Perseus for the strings being removed in Khan/webapp#19729.
Issue: "none"
I searched each removed string in Khan/webapp#19729 in the Perseus repo. Each one that I found I ensured was now wrapped in `i18n._()` calls again.
=> Restore i18n._() support for radio widget's Choice component

.changeset/purple-beans-deliver.md, packages/perseus/src/util/graphie.test.ts, packages/perseus/src/util/graphie.ts, packages/perseus/src/util/interactive.ts
This PR adds unit tests for Graphie's `getMousePx` and `getMouseCoord`. The pair of these translate an event from a mouse click to graph-relative coordinates in pixel coords (`getMousePx`) and graph coords (`getMouseCoord`).
Issue: LC-1662
`yarn test`
=> Graphie: Add tests for getMousePx and getMouseCoord

.changeset/nine-jobs-punch.md, packages/perseus-editor/src/all-editors.ts, packages/perseus-editor/src/widgets/__stories__/python-program-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/python-program-editor.test.tsx, packages/perseus-editor/src/widgets/python-program-editor.tsx, packages/perseus/src/extra-widgets.ts, packages/perseus/src/index.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/__stories__/python-program.stories.tsx, packages/perseus/src/widgets/__testdata__/python-program.testdata.ts, packages/perseus/src/widgets/__tests__/__snapshots__/python-program.test.ts.snap, packages/perseus/src/widgets/__tests__/python-program.test.ts, packages/perseus/src/widgets/__tests__/python-program.ts, packages/perseus/src/widgets/python-program.tsx
This commit adds a new widget: python-program. This widget renders
an iframe which loads an embedded Python program page. The purpose
of this widget is to add runnable Python programs to articles in
the Python course.
Issue: CL-1472
Test Plan:
- Temporarily change the iframe URL to include http://localhost:8090/.
- Run the webapp dev environment.
- Start storybook.
- Visit the Python Program story and verify that the program loads and that the
buttons work.
- Visit the Python Program Editor story and verify that it renders the two input fields.
=> Add python-program widget and editor

dev/vite.config.ts
The dev UI was broken for fresh clones of the Perseus repo. Vite spewed
tons of errors that looked like:
```
[ERROR] Failed to resolve entry for package "@khanacademy/simple-markdown". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
```
I don't know why I'm not seeing this error in my local copy of the repo.
Removing the `node_modules/.vite` cache and `yarn install --force` was
not sufficient to repro. I can only repro on a fresh clone.
The fix involves creating aliases for all packages in the Perseus
monorepo so Vite knows where to find them. I took a similar approach to
the one used in `.storybook/main.ts`.
Issue: none
Test plan:
```
cd /tmp
git clone git@github.com:khan/perseus.git
cd perseus
yarn install
yarn dev
open …
```
=> Fix imports not working in Vite dev UI

.changeset/popular-laws-knock.md, packages/perseus/src/widgets/expression.tsx
Now that expression widget is screenreader accessible, we want to mark it as such.
This will make it so that the exercise editor will not auto-check and auto-disable the
"requires screen or mouse" checkbox when the expression widget is used.
This will change the value of `hasViolatingWidgets` in [item-controls.tsx](https://github.com/Khan/webapp/blob/6d54f60f3a3bbb0758e4d499f9eb123ff27d6ef5/services/static/javascript/perseus-one-package/item-controls.tsx#L670-L682) where the
checkbox is rendered.
NOTE: This will just make it so that the checkbox won't auto-disable. It will _not_
update the existing values to reflect Expression now being accessible. A backfill
will still be necessary for that with our current architecture.
Issue: none
N/A?
=> Set Expression widget's `accessible` field to true.

.changeset/fuzzy-nails-double.md, packages/perseus/src/__stories__/server-item-renderer.stories.tsx, packages/perseus/src/__testdata__/server-item-renderer.testdata.ts, packages/perseus/src/__tests__/server-item-renderer.test.tsx, packages/perseus/src/server-item-renderer.tsx, packages/perseus/src/types.ts, packages/perseus/src/widgets/__stories__/expression.stories.tsx, packages/perseus/src/widgets/__tests__/input-number.test.ts, packages/perseus/src/widgets/__tests__/numeric-input.test.ts, packages/perseus/src/widgets/input-number.tsx, packages/perseus/src/widgets/numeric-input.tsx
As part of our Khanmigo project, we want to be able to know what's currently been input into the widgets in our exercises. 
After some investigation, it was discovered that we already have a `interactionCallback` in our `apiOptions` that was being used to close a feedback popover in our numeric inputs. This PR updates that callback to now return the current user input data so that it can be utilized by Khanmigo to provide proactive hints and supportive content. 
Issue: LC-1754
- New Stories to manually test with 
- Updated server renderer test
=> Update our interactionCallback to return the current user input data for Khanmigo

.changeset/friendly-trees-drive.md, packages/perseus-editor/src/components/graph-settings.tsx, packages/perseus-editor/src/widgets/interaction-editor/interaction-editor.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/components/graph.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/grapher/util.tsx
- Update GraphSettings to be a React class instead of old `createReactClass` const.
- Add types
Tests coming in follow-up PR.
Issue: https://khanacademy.atlassian.net/browse/LC-1702
`yarn jest`
=> Update graph-settings.tsx to React class component

.changeset/old-humans-confess.md, packages/math-input/src/components/__tests__/integration.test.tsx, packages/math-input/src/components/input/math-input.tsx, packages/perseus/src/widgets/__stories__/number-line.stories.tsx, packages/perseus/src/widgets/__testdata__/number-line.testdata.ts
This PR fixes two issues related to the number line widget (MOB-5422 & MOB-5416). It also adds a storybook story to help test number-lines, as we didn't have anything showing the widget with "isTickCtrl" set to "True". 
MOB-5422 
This is solved by programmatically focusing on the input element during click and tap events so that the onKeyUp handler can be fired correctly for keyboard events. 
MOB-5416 
This is solved by fixing a callback in math input, where we were returning "false" rather than a proper callback. 
Issue: MOB-5422 & MOB-5416
- manual
=> [Bug Fixes] Numerous issues with the Number-line widget

.changeset/warm-camels-learn.md, packages/perseus-editor/src/components/graph-settings.tsx, packages/perseus-editor/src/widgets/interaction-editor/interaction-editor.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/components/graph.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/grapher/util.tsx
Revert "Update graph-settings.tsx to React class component (#1009)"
Reverting because this caused `this.setState` errors in the exercise editor.
Fix for the future: update the functions in GraphSettings to arrow functions.
=> [🔥AUDIT🔥] Revert "Update graph-settings.tsx to React class component"

.github/workflows/node-ci.yml
Today we note how to use the npm snapshot generally, but most folks are integrating their changes into webapp today so I'm  adding a note for how to use the script in webapp. 
Issue: "none"
=> [🔥AUDIT🔥] Add note for how to use npm snapshot in webapp

.changeset/blue-actors-pull.md, packages/perseus/src/__tests__/perseus-markdown.test.ts, packages/pure-markdown/src/__tests__/index.test.ts, packages/pure-markdown/src/index.ts
It was noticed that we're not properly previewing lists in the Translation Editor.
Leading to confusion for our translators as to how correctly translate the markdown.
The preview is even more confusing when lists are nested.
After investigating the code in both webapp and perseus repos, I found this commit from 2016: https://github.com/Khan/webapp/commit/0708615029644f6eb7d29a3d4c361344b281d577
Reverting it appears to resolve the preview issue when rendering in JIPT context.
The original commit summary reads:
> When translating perseus articles, we split up the text of the article
into paragraphs by splitting at double-newlines.
Yes indeed, we do this in two places:
- In [webapp](https://github.com/Khan/webapp/blob/c7fd0d7893c05e3a04d96b1154ac586e6e43d25d/services/static/javascript/mantic …
=> Parse markdown list when rendering in JIPT context

.changeset/beige-trees-itch.md, packages/perseus/src/__stories__/article-renderer.stories.tsx, packages/perseus/src/__testdata__/article-renderer.testdata.ts, packages/perseus/src/__tests__/article-renderer.test.tsx, packages/perseus/src/article-renderer.tsx
This is a continuation to https://github.com/Khan/perseus/pull/996, where "disabling" of the `list` rule was removed
from the markdown parser in order to correctly render lists in JIPT context.
However, that change broke Article preview rendering in the Translation Editor,
due to a mismatch in paragraph indexes. Causing the `jipt.js` integration to not
be able to attribute rendered strings to translations on Crowdin. This is fixed in: https://github.com/Khan/webapp/pull/19917
With these two changes in place the Translation Editor is now rendering markdown
lists correctly without any other regression.
Unfortunately this is not case for articles containing markdown lists rendered in
the WYSIWYG. These are regressed due to the same paragraph index mismatch,
as unlike the Translation Editor, …
=> Update ArticleRenderer to split sections into paragraphs in JIPT context

.changeset/cyan-dots-compete.md, packages/perseus/src/widgets/__tests__/__snapshots__/explanation.test.ts.snap, packages/perseus/src/widgets/__tests__/__snapshots__/graded-group.test.ts.snap, packages/perseus/src/widgets/__tests__/explanation.test.ts, packages/perseus/src/widgets/explanation.tsx
The explanation widget should respond to keyboard interactions such that both the Enter/Return key and the spacebar activate it. This bug calls out that the spacebar is instead scrolling the page (see "Before" video), which is the default browser behavior. Changing the widget container from `<Link>` to `<Clickable>` improves semantics and properly handles keystrokes (it is now a `<button>` element instead of an `<a>` element).
Issue: LC-212
1. Open the Perseus Storybook (locally: `http://localhost:6006/?path=/story/perseus-widgets-explanation--question-1`)
1. Using the keyboard, tab until the text "[Explanation]" is in focus.
* To avoid numerous tab keystrokes, you can click the "explanation" word prior to the widget, then press the tab key to advance focus to the widget.
1. With the …
=> Fix Spacebar Usage on Explanation Widget

.changeset/plenty-zoos-smash.md, packages/perseus-editor/src/components/__stories__/graph-settings.argtypes.ts, packages/perseus-editor/src/components/__stories__/graph-settings.stories.tsx, packages/perseus-editor/src/widgets/__stories__/interactive-graph-editor.argtypes.ts, packages/perseus-editor/src/widgets/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
Right now, there aren't really stories for GraphSettings
or InteractiveGraphEditor.
Adding them here so that it's easier to visually test
them later.
Note: I added prop comments in interactive-graph-editor.tsx
so that storybook automatically uses those props. I didn't do
that for graph-settings.tsx yet here, because that will be
converted to a React class soon. It will be easier to add the
prop comments after that conversion.
Issue: https://khanacademy.atlassian.net/browse/LC-1702
Graph Settings
http://localhost:6006/?path=/docs/perseus-editor-components-graph-settings--docs
InteractiveGraphEditor
http://localhost:6006/?path=/docs/perseus-editor-widgets-interactive-graph-editor--docs
=> Add stories for GraphSettings and InteractiveGraphEditor

.changeset/late-cooks-kick.md, packages/perseus-editor/src/components/__stories__/interactive-graph-settings.argtypes.ts, packages/perseus-editor/src/components/__stories__/interactive-graph-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/interactive-graph-settings.test.tsx, packages/perseus-editor/src/components/interactive-graph-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
We are going to be making changes to interactive graph, which will also require updating InteractiveGraphEditor and therefore GraphSettings. Since GraphSettings is also used for the Grapher and Interaction widgets, we don't want to change it too much. To avoid breaking changes, we're breaking graph settings related to interactive graph into its own file, interactive-graph settings.
This PR just involves copying the file over. Modernizing the file and additional changes will come in following PRs.
- Create the .tsx, .test.tsx, .stories.tsx, and .argtypes.tsx files for InteractiveGraphSettings, copied over from GraphSettings.
- Update the files to say `interactive graph settings` instead of `graph settings` where applicable.
- Add comments at the top of the files explaining which widgets …
=> Create InteractiveGraphSettings component (copied from GraphSettings)

dev/flipbook.tsx
Issue: none
```
yarn dev
open http://localhost:5173
```
- Click the "flipbook" link.
- You should be able to follow the instructions and get graphs rendering on the
page.
=> Add instructions to the flipbook UI

package.json
We just switched to using Vite with Storybook. Vite outputs files that have an underscore prefix and Github has some native Jekyll support that ignores these types of files. 
I found a Github issue where the poster found [the issue](https://github.com/storybookjs/storybook/issues/21711#issuecomment-1496464011).  That linked to a Github article explaining the behaviour. 
So this PR adds a `poststorybook-build` script to the `package.json` file which emits the `.nojekyll` file into the `storybook-static` folder before publishing. 
Issue: "none"
I have no way to test this without landing and releasing it, so that's how I'll test
=> [🔥AUDIT🔥] Fix Storybook deployed on GH Pages

.changeset/long-onions-build.md, packages/perseus/src/renderer.tsx
This PR is mostly to bump the changesets tool create the Version Packages PR so that I can do a release of the Github/Jekyll fix from #1035
Issue: "none"
=> [🔥AUDIT🔥] Document Widgets type in Renderer

.github/actions/shared-node-cache/action.yml, .github/workflows/node-ci.yml
I noticed warnings when looking at a Github action run about Node 16 reaching end of life soon.  This PR bumps two of the noted actions to their latest version so they run on Node 20. I'm not sure if there'll be more, but I'll tackle those in a second PR if there are. 
Issue: "none"
=> Update actions to Node v20 compatible versions

.changeset/nervous-news-cheat.md, packages/perseus-editor/src/components/interactive-graph-settings.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/perseus-types.ts
This PR is pretty much the same as https://github.com/Khan/perseus/pull/1009.
The changes from that PR got rolled back, and now interactive-graph-settings.tsx
has been split out as a copy of graph-settings.tsx.
Instead of updating graph-settings.tsx, we're keeping that as is as it will
only be used by deprecated components. interactive-graph-settings.tsx will
continue to be updated along with InteractiveGraph.
To make these updates easier, we're making InteractiveGraphSettings a
React class component instead of it using the old `createReactClass` const.
- Update InteractiveGraphSettings to be a React class
- Add types
- Use arrow functions so `this` binds correctly
Additional cleanup coming in a following PR.
Issue: https://khanacademy.atlassian.net/browse/LC-1702
`yarn jest …
=> Update interactive-graph-settings.tsx to React class component

.changeset/gold-bats-count.md, packages/perseus-editor/src/__tests__/item-extras-editor.test.tsx, packages/perseus-editor/src/item-extras-editor.tsx
Summary:
The financial calculator appeared to be unchecked if the component reloaded. This was caused by the `financialCalculatorOptionsExpanded` defaulting to "off" despite props. Instead, we will set it to "true" if any of the Financial Calculator Options are set to true.
Also fixes minor comment typos.
Issue: LC-1797
Testing:
Unit test that checks if expected items are present and checked passes-- did not pass before these changes.
To test in the editor experience, check Financial Calculator, click the Preview tab, then return. Financial Calculator appears to be unchecked, even though the checked state is true in the JSON data.
=> Fix fin calc editor bug

.changeset/purple-gorillas-attend.md, packages/math-input/package.json, yarn.lock
An apparent bug in yarn classic will attempt to install dev dependencies of deps installed using github URLs during github actions in webapp.
An error is thrown during build because a new dev dependency of MathQuill requires node 18 or higher, and webapp actions currently use 16
So, we need to run `yarn pack`, add the new tarball to a Github release, and install from a url instead
Issue: n/a
Testing:
No errors in Perseus nor in webapp CI
=> Change mathquill import from github url to tarball url

.changeset/empty-impalas-watch.md, packages/perseus/src/server-item-renderer.tsx
This PR fixes an issue where our hints or helpful popups were being immediately closed, in a glitchy manner. 
Previously I had a poor understanding of when we were intending to call the interactionCallback. Looking at several widgets (numeric-input, input-number), they had been calling the interactionCallback both on answer update AND on focus. After reviewing all the widgets, I suspect that the logic I saw in numeric-input/input-number was actually a bug and not how we want to be using the interactionCallback! 
As a result, I have removed the interactionCallback from the onFocus method in our server-item-renderer. While we will no longer be dismissing the popover **on focus** for numeric-input and input-number, I now believe that this historical functionality was unintended. 
Issue: …
=> Fixing InteractionCallback calling too frequently 

.changeset/grumpy-ducks-smell.md, .changeset/thin-deers-unite.md, packages/perseus-editor/src/__stories__/editor-page.stories.tsx, packages/perseus-editor/src/widgets/__tests__/expression-editor.test.tsx, packages/perseus/src/components/__tests__/math-input.test.tsx, packages/perseus/src/components/math-input.tsx, packages/perseus/src/util/debounce.ts, packages/perseus/src/widgets/__tests__/expression.test.tsx
Accounts for a bug in the editor in consuming webapp code, which uses the `facebook/flux` library and cannot handle immediate updates.
The new, accessible MathQuill update comes with a feature that reformats/disambiguates certain TeX and immediately updates itself. For example, `x^2` immediately updates to `x^{2}`.
LEMS-1805
Open any exercise with multiple "malformed" TeX in the editor. There are examples in [the ticket](https://khanacademy.atlassian.net/browse/LEMS-1805). The editor should load without `flux` throwing errors and halting the render.
=> Debounce Perseus Math Input Updates

dev/gallery.tsx, testing/renderer-with-debug-ui.tsx, testing/side-by-side.tsx
This PR improves our mobile support for our dev tooling (both Storybook and the custom Dev UI):
* Adds the `perseus-mobile` class to the parent div of the renderers. Some of our Perseus styling depends on an ancestor node having the `perseus-mobile` class in order to render for mobile.
* Adds a mobile switch to the `RendererWithDebugUI` component so we can manually flip to mobile rendering in Storybook (already exists in the Dev UI)
Finally, I've changed the`SideBySide` component slightly so that the right panel will move below the left panel on narrower screens. This will make inspecting a story with mobile emulation on much cleaner (the right panel, usually the Perseus JSON, would overlap the left panel previously).
Issue: "none"
=> Dev Tooling: Better mobile support

.changeset/light-baboons-smell.md, packages/perseus/package.json, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css, yarn.lock
Issue: https://khanacademy.atlassian.net/browse/LEMS-1672
Test plan:
```
yarn dev
open http://localhost:5173
```
- Check the "Segment" box in the feature flags dropdown.
- You should be able to drag the movable segment in the first graph with
the mouse.
- You should be able to tab to the segment and move it with the arrow
keys.
https://github.com/Khan/perseus/assets/693920/fc727409-0cf5-4c10-b0ca-b10c45451c62
=> Make the entire line of a movable segment draggable

.changeset/fluffy-goats-suffer.md, dev/flipbook.tsx, packages/perseus/src/__tests__/util.test.ts, packages/perseus/src/util.ts
Issue: LEMS-1814
```
yarn dev
open http://localhost:5173/#flipbook
```
Follow the onscreen instructions to get graph data into the flipbook.
Clicking the "Check answer" button should pop up an alert telling you
if you've answered the question correctly.
=> Add "Check answer" buttons to the interactive graph flipbook

dev/flipbook.tsx
Previously, the instructions took up a bunch of screen real estate by
default. Once someone has entered data in the flipbook, the instructions
have served their purpose and can go away.
I've also moved the instructions below the text input so the layout
doesn't shift when the instructions disappear.
Issue: none
Test plan:
```
yarn dev
open http://localhost:5173/#flipbook
```
Follow the instructions onscreen to get some data in the box. The
instructions should vanish. Delete everything from the box and the
instructions should reappear.
=> Hide the flipbook instructions when data is pasted

.github/workflows/release.yml
Updates the release notification slack channel from `#team-lc-perseus` to `#team-lems-perseus`. The Slack channel has already been renamed so this is safe to land/deploy as soon as it's approved. 
Issue: LEMS-1821
=> LC->LEMS: Update Slack notification channel name for Perseus releases

.changeset/two-flowers-heal.md, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
We changed it (accidentally) to offBlack16 in
https://github.com/Khan/perseus/pull/1067. This commit fixes it.
Issue: none
Test plan:
View the Mafs segment graph in Storybook (http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--segment-with-mafs-and-locked-points).
Verify that the segment is a darker gray than the gridlines.
=> Make Mafs line segment color offBlack64

.changeset/wicked-cameras-rescue.md, package.json, packages/perseus/package.json
The mathjax-renderer dependency is needed for Storybook test rendering. As such, it should be added to the root package.json instead of the Perseus package package.json. This commit makes that change.
Issue: LEMS-1820
- Confirm with Learning Equity that they are now able to upgrade
=> Fix MathJax dependency

.changeset/tricky-dolphins-double.md, packages/perseus/src/widgets/__tests__/explanation.test.ts, packages/perseus/src/widgets/explanation.tsx
This is relevant for e.g. SSR in webapp. Previously, we were seeing an
error during SSR when there was an Explanation widget on the page.
Issue: none
Test plan:
- Install a dev build of Perseus in local webapp
- `make serve-ssr`
- As a pre-phantom user (no cookies) with JS disabled in your browser,
visit
`/internal-courses/test-everything-qe-sandbox/xa527aaa0ed54bca0:test-everything-1/xa527aaa0ed54bca0:te-explanation/a/explanation-article`
- You should not see an error. The article should render.
=> Handle the case where matchMedia is not defined

.changeset/wet-yaks-pay.md, dev/gallery.tsx, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/__tests__/interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/index.ts, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/ray.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/types.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-reducer.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/types.ts
Adds `Ray` graph type behind a feature flag.
Also refactors tests to iterate over questions and reduce repetition.
https://github.com/Khan/perseus/assets/23404711/52c0a1d8-05f1-4fcc-a081-9eb917cf0796
LEMS-1823
Fire up `yarn dev` and activate the flag.
=> Migrate `Ray` graph type to Mafs

.changeset/swift-moles-happen.md, packages/perseus/src/types.ts
As noted by others in Slack, we get better comment visibility if types are documented with JSDoc style comments (`/** ... */`) instead of basic line comment` (`// ...`).
Issue: "none"
=> [🔥AUDIT🔥] Migrate code comments on types to JSDoc comments for better visibility

.changeset/gold-ears-repeat.md, package.json, packages/perseus/src/interactive2/objective_.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/server-item-renderer.tsx, packages/simple-markdown/package.json, yarn.lock
Very small change, but this upgrades the Perseus repo to TypeScript v5.4.2. 
Issue: LEMS-1846
`yarn tsc`
`yarn coverage:types`
`yarn build:types`
Install the snapshot package in one of the consuming applications and typecheck.
=> Upgrade to TypeScript 5

.changeset/violet-roses-unite.md, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Mark and I ran into an issue when testing these graphs and toggling between
different feature flag states.  When switching from the legacy interactive
graph to the Mafs version, the InteractiveGraph component wasn't remounted, so
the state of the legacy graph was preserved. This caused the line segment to
mysteriously disappear from a segment graph when the feature flag was switched
off!
To prevent similar gotchas in the future, this PR isolates the legacy graph code
in its own component, which is only rendered if the relevant Mafs feature flag
is turned off. This is a more accurate reflection of our intent.
Issue: none
- View the interactive graph gallery (`yarn dev`)
- Toggle the "Segment" feature flag on.
- Move the line segment on the first graph.
- Toggle the "Segment" feature flag …
=> Avoid rendering legacy interactive graph when we really want mafs

dev/flipbook.tsx
This makes it much easier to report bugs against specific questions. You can
copy the JSON into the bug report.
Issue: none
- `yarn dev`
- Visit http://localhost:5173/#flipbook
- Follow the instructions onscreen to load data
- You should see the JSON for the current question displayed at the bottom of
the page
=> Display question JSON in the interactive graph flipbook

.changeset/old-humans-confess.md, packages/math-input/src/components/__tests__/integration.test.tsx, packages/math-input/src/components/input/math-input.tsx, packages/perseus/src/__tests__/article-renderer.test.tsx, packages/perseus/src/widgets/__stories__/number-line.stories.tsx
This PR updates our Math Input to ensure that we're properly displaying the focus styling on the input when it is focused via a tab event. This was done by adding a state for `showInputFocusStyle` that is separate from the original `focused` state. 
This was required, as we have several cases where we _don't_ want to remove focus styling from the input, such as when the user moves the focus to the keypad by tabbing or clicking a button. The `focused` state will now indicate whether the input is the actively focused DOM element, and `showInputFocusStyle` will indicate whether we want the input to _appear_ focused. This allows for a smoother and more natural interaction between our Math Input and our Keypad. 
Issue: MOB-5431
https://github.com/Khan/perseus/assets/12463099/cc6ab02b-5c9b-46da- …
=> Ensure that our mobile math input can be visibly focused via tab

.changeset/three-jars-cheer.md, .eslintrc.js, .github/workflows/node-ci.yml, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/components/__tests__/zoomable.test.tsx, packages/perseus/src/widgets/video-transcript-link.test.tsx
After updating ESLint & Friends (#1096) to latest, we got a new testing-library/eslint-plugin-testing-library rule named: `testing-library/prefer-explicit-assert`. This rule requires that there is an explicit `expect()` to assert presenve of a DOM node instead of just using the implicit `getBy()`. 
🔉 I'm on the fence if this is a net benefit. **Please weigh in**.
Issue: LEMS-1847
Review the changes in this PR. Which looks better? Before or after?
=> Testing Library: enable prefer-explicit-assert rule and fix violations

.changeset/wild-points-float.md, packages/math-input/src/components/__tests__/integration.test.tsx
One test failed because of an `eslint` error due to new (and welcome!) rules.
An element was asserted as existing by only a query, which violates the rule. Also, the test didn't explicitly assert that the element was focused per the test title. This ensures that the expected element has focus.
=> Fix test following eslint changes

dev/flipbook.tsx, dev/gallery.tsx, dev/header.tsx
Makes header its own component, adds it to flipbook, and adds link back to gallery.
To keep item placement consistent and also to make header more flexible, items spread to take up header space and wrap when container becomes too narrow.
Row order is reversed so that the lone item in the flipbook nav is in the same place as in gallery (top right).
https://github.com/Khan/perseus/assets/23404711/3541b0d8-e64e-42a0-a197-da6e9483d5dc
=> Graph dev ui: add navigation back to gallery from flipbook

.changeset/tender-knives-jam.md, packages/perseus/src/widgets/interactive-graphs/legacy-grid.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Allows `markings` prop to determine whether the mafs grid renders. Previously, it was both `markings` and the presence or absensce of a "LegacyGrid". However, sometimes a grid was rendered in the component and the "LegacyGrid" just contained labels, and in this case we are not rendering a grid.
LEMS-1843
Run `yarn dev` and to open graph dev ui, navigate to `Flipbook`.
Paste in the following Perseus data:
```json
{"content":"Line segments $\\overline{PQ}$ and $\\overline{RS}$ undergo the translation $T_{(2,-12)}$. \n\n**Below, modify the other line segments to create the image of this translation.** \n\n\n[[☃ interactive-graph 3]]\n\n","images":{},"widgets":{"interactive-graph 3":{"alignment":"default","graded":true,"options":{"backgroundImage":{"bottom":0,"height":400,"left":0,"scale":1,"u …
```
=> Fix grid rendering bug

.changeset/twenty-ads-type.md, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts
Previously, there was a discrepancy between our `getDefaultSegments`
function and the equivalent code in the legacy InteractiveGraph.
`getDefaultSegments` was not "normalizing" the points correctly (see the
test added in this commit for an explanation of why we do this).
This commit ports the legacy behavior over.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1841
Test plan:
See the linked issue for repro steps. The bug should not repro!
=> Ensure default segments are positioned correctly on Mafs graphs

.changeset/hip-shoes-repair.md, dev/flipbook.tsx, packages/perseus/src/widgets/__tests__/interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graphs/mafs-supported-graph-types.ts
This lets you see the Mafs rendering of linear graphs side-by-side with the
legacy rendering in the flipbook UI.
Issue: none
```
yarn dev
open http://localhost:5173/#flipbook
grep -rl '"type":"linear"' data/questions/ | xargs cat | pbcopy
```
Paste the data on your clipboard into the flipbook. The graphs on the right
should be rendered by Mafs.
=> [🔥AUDIT🔥] Add linear Mafs flag to flipbook

.changeset/selfish-tips-dream.md, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Our legacy graph makes the grid non-square rather than fudge the ranges of the X and Y axes.
This commit makes Mafs graphs do the same.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1853
Paste the data below into the interactive graph flipbook. The ranges of the X and Y axes should be the same
for both the legacy and Mafs graphs.
```
{"content":"आप एक देश से दूसरे देश यात्रा करने के लिए सबके लिए खुले सड़क राजमार्ग पर गाड़ी चला रहे हैं, $60$ मील प्रति घंटा स्थिर गति में गाड़ी दौड़ रही है \n\n**रेखा का झुकाव इस संबंध को क्या दर्शाता है?**\n\nझुकाव [[☃ input-number 1]] है I\n\n **आलेख का अनुपातिक संबंध \n$d=60t\\,$ है Iजो आपकी यात्रा की दूरी $d$ (मील में ) समय $t$ की अवधि (घंटों में) बताता है जब से आप ने $60\\, \\text{mph}$ चलना शुरू किया था**\n\n\n\n\n\n\n\n[[☃ interactive-graph …
```
=> Fix aspect ratio for Mafs graphs with nonsquare bounds

.changeset/dull-shrimps-grow.md, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts
...and avoid returning coords if hasBeenInteractedWith is false.
The new structure allows us to avoid returning the coords property when
it is set on the initial graph. If coords is set, it makes the question
appear to have been answered even if the user never interacted with it.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1776
Test plan:
`yarn test`
Co-authored-by: Mark Fitzgerald <markfitzgerald@khanacademy.org>
=> Refactor getGradableGraph

.github/workflows/node-ci-main.yml, .github/workflows/node-ci.yml, .github/workflows/storybook.yml
This PR enables [concurrency](https://docs.github.com/en/actions/using-jobs/using-concurrency) for the `node-ci-main.yml` and `node-ci.yml` Github Action workflow files. 
For `node-ci-main.yml` concurrency is enabled but `cancel-in-progress` is `false`. This is so that all workflow jobs run for a landed PR before the next PR's changes are processed. This ensures that we get updated coverage metrics for every PR that is landed. 
For `node-ci.yml` concurrency is enabled _and_ `cancel-in-progress` is `true`. This should save us some Github Action processing time and $$$. 
Issue: LEMS-1761
There's not much to test other than watching how things go on subsequent PRs after this is landed. 
I checked that there are no steps that'd be affected by being interrupted in `node-ci.yml` and turning off …
=> Enable concurrency on most Github action workflows

.changeset/proud-eagles-hope.md, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/types.ts
This lets us remove some null checks.
The new types are more specific about exactly which fields are relevant
to the state. Previously, some of the state types included fields from
the graph definitions that were not needed. I'm hopeful that the new
types will be more straightforward for new contributors to the project
to understand.
Issue: none
Test plan:
`yarn tsc && yarn test`
=> Make `coords` required on interactive graph state types

.changeset/smart-otters-study.md, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/__tests__/interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-supported-graph-types.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-action.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/types.ts
Issue: https://khanacademy.atlassian.net/browse/LEMS-1776
Run this command to get data for point graphs with fixed numbers of points
onto your clipboard:
```
grep -rl '"type":"point"' data/questions/ | xargs cat | grep -v unlimited | pbcopy
```
Then paste the data into the flipbook (`yarn dev`,
`http://localhost:5173/#flipbook`).
You should be able to move the points and answer questions successfully.
There is a known bug with keyboard interaction on some of the graphs:
https://khanacademy.atlassian.net/browse/LEMS-1885
Co-authored-by: Mark Fitzgerald <markfitzgerald@khanacademy.org>
=> Port the "point" interactive graph type (with fixed number of points) to Mafs

dev/flipbook-model.test.ts, dev/flipbook-model.ts, dev/flipbook.tsx
This is more a POC to check interest, but I noticed that when I was making changes in Perseus that Flipbook wasn't keeping the questions data I had given it. That meant I had to:
1. Make a change
2. Wait for Flipbook to reload
3. Copy/paste data
4. Check my work
5. Repeat
By stashing the data in local storage, the data persists after a reload.
=> Flipbook: persist questions input in local storage while working

.changeset/five-crabs-teach.md, package.json, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-action.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/types.ts, packages/perseus/src/widgets/interactive-graphs/utils.ts
This doesn't actually implement the circle graph; that will be done
in a future PR.
This PR adds a library, `tiny-invariant`, which helps us narrow TypeScript types
in tests. We already depend on this library indirectly via react-router and Mafs,
so we don't need an ADR to use it.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1828
`yarn test`
=> Refactor the Mafs interactive graph state to accommodate circle graphs

.storybook/main.ts
Mark noticed that the new @phosphor icons were not showing up in Storybook on Github Pages (`khan.github.com/pereseus`). 
I tracked it down to a feature introduced in Vite 5 (vitejs/vite#15534), but it seems like it has bugs ([#15378](https://github.com/vitejs/vite/issues/15378) and [#15444](https://github.com/vitejs/vite/issues/15444)). 
I don't see how we could "quote" the URL as it's handed of to Wonder Blocks which seems to be handling the import correctly. 
So instead we'll just force Vite to never inline SVGs using Vite's `assetsInlineLimit` (https://vitejs.dev/config/build-options#build-assetsinlinelimit) option. 
Issue: LEMS-1887
I haven't tested on GH Pages yet, but I did the following and verified that there are now svg files in the build output folder:
```sh
yarn …
```
=> Storybook: Prevent Vite from inlining SVGs

.changeset/nice-pens-scream.md, packages/perseus/src/types.ts, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
I don't know if this is the preferred way to do things, but it works
https://github.com/Khan/perseus/assets/16308368/ade4f43a-798a-4b75-bd63-23b05d43b944
Issue: LEMS-1882
- In Perseus SB, go to: Interactive Graph Editor / With Locked point
- `?path=/story/perseus-editor-widgets-interactive-graph-editor--with-locked-points`
- Move a point
- Note the "Correct answer" field updates as you modify the graph
=> Mafs callback on change (interactive graph editor change bug)

.changeset/loud-suns-beg.md, packages/perseus/src/widgets/interactive-graphs/grid.test.ts, packages/perseus/src/widgets/interactive-graphs/grid.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Separate out Grid Step from Tick Step in Mafs charts
https://github.com/Khan/perseus/assets/16308368/51bdb324-a763-4859-9d68-906a394b7f32
Issue: [LEMS-1883](https://khanacademy.atlassian.net/browse/LEMS-1883)
- Go to "With Locked Points"
- `?path=/story/perseus-editor-widgets-interactive-graph-editor--with-locked-points`
- Change grid step and note it has minimal effect on tick step
- Change tick step and note it doesn't affect grid step
[LEMS-1883]: https://khanacademy.atlassian.net/browse/LEMS-1883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Split grid vs tick step

dev/gallery.tsx
This fixes a bug. Repro steps:
1. Run `yarn dev` and visit `http://localhost:5173`
2. Ensure all Mafs flags are turned OFF and the searchbar is clear.
3. Paste the text `poly` into the searchbar.
Expected: All graphs render without errors.
Actual: One graph crashes to the Renderer arrow boundary (red circle
with exclamation).
The bug happened because a segment graph component got reused for a
polygon graph. The component gets into a weird state when this happens
and crashes. Ensuring each graph has a stable key fixes the bug because
now each component renders the same graph for its whole lifetime.
Issue: none
Test plan:
Follow the repro steps above and confirm that the bug does not repro.
=> Ensure graphs in the dev gallery have stable React keys

data/find-questions.js, data/find-questions.ts
I thought maybe this would be helpful. I needed a way to find questions where grid step was greater than our tick step.
The idea is this can be modified as needed to help other people find the data they need.
I know `jq` exists, but I'd rather stick to my JS roots.
=> Helper: find questions in `data` that match a predicate

.changeset/breezy-mice-lick.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx
This is a holdover from the legacy interactive graph. 44px is WCAG AAA,
but there's no reason not to go up to 48px since that's the existing
behavior.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1895
Test plan:
View a segment graph in the dev UI. Inspect one of the point hitboxes.
It should be 48 by 48 pixels.
=> Increase the size of MovablePoint hitboxes to 48px

.changeset/strange-frogs-share.md, packages/perseus/src/types.ts
Nothing is done with the returned `widgets` for this function, and consuming the callback as typed requires some weird hacky implementation, like:
```
onWidgetStartProps: (widgets) =>
setWidgetsStateMap(widgets) as unknown as Perseus.PerseusWidgetsMap,
```
or
```
onWidgetStartProps: (widgets) => {
setWidgetsStateMap(widgets);
return widgets;
},
```
Correcting the type allows for its intended use, like:
```
onWidgetStartProps: (widgets) => setWidgetsStateMap(widgets),
```
or
```
onWidgetStartProps: setWidgetsStateMap,
```
=> Fix type for `onWidgetStartProps`

.changeset/tender-peaches-deny.md, dev/flipbook.tsx
The warning was logged to the JS console. It said that nesting a `<pre>` tag inside a `<p>` is not allowed.
This commit fixes the warning by using a `<div>` instead of a `<p>`.
Issue: none
Test plan:
- `yarn dev`
- `open 'http://localhost:5173#flipbook'`
- Follow the instructions onscreen to get some question JSON into the UI
No errors or warnings should be logged to the JS console.
=> Fix HTML validation warning in the dev UI

.changeset/cuddly-shrimps-rule.md, packages/perseus/src/__tests__/util.test.ts, packages/perseus/src/util.ts, packages/perseus/src/widgets/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graph.tsx
Repro steps for the bug:
- View a segment graph question (e.g. the JSON below)
```
{"content":"The graph of $y=h(x)$ is a line segment joining the points $(1,9)$ and $(3,2)$. \n\n**Drag the endpoints of the segment below to graph $y=h^{-1}(x)$.\n **\n\n[[☃ interactive-graph 1]]","images":{},"widgets":{"interactive-graph 1":{"alignment":"default","graded":true,"options":{"backgroundImage":{"bottom":0,"height":425,"left":0,"scale":1,"url":"web+graphie://ka-perseus-graphie.s3.amazonaws.com/a82b4098da55c75b68d2c1fd9f348923b8935ccb","width":425},"correct":{"coords":[[[9,1],[2,3]]],"type":"segment"},"graph":{"type":"segment"},"gridStep":[1,1],"labels":["x","y"],"markings":"none","range":[[-10,10],[-10,10]],"rulerLabel":"","rulerTicks":10,"showProtractor":false,"showRuler":false,"snapStep":[0.5,0 …
```
=> Fix bug when a segment endpoint is dragged after the question is graded

.changeset/forty-tomatoes-lick.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
We noticed that the focus ring on movable points was being clipped on Safari 17.2.1. This wasn't happening on Safari 16 (older) nor Safari Technology Preview (newer).
We were able to re-work how the focus ring was drawn and arrive at something that looks exactly the same but works on all browsers. 
Design spec: https://www.figma.com/file/JroPokeCLBv2VRIw3GPvY5/LC---Interactive-graph-widget?type=design&node-id=855-9644&mode=design&t=f6QWv1t1RXJtI6ky-4
Issue: LEMS-1889
`yarn start`
Navigate to: http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--segment-with-mafs-and-locked-points
Press `{tab}` on the keyboard until one of the movable points is focused.
Note that the focus ring (outside of the light-blue "halo") is a full circle and not clipped.
Co-authored-by: Ben …
=> Fix Safari clipping the focus circle on the movable point

.github/actions/shared-node-cache/action.yml, .github/workflows/gerald-pr.yml, .github/workflows/node-ci-main.yml, .github/workflows/node-ci.yml, .github/workflows/storybook.yml
This updates the workflows to use action versions that have been updated to use Node 20. This should mean no more Node 16 deprecation warnings.
Issue: FEI-5484
Put this up and check the workflows run without Node 16 deprecation warnings.
=> Update workflows to use Node 20-ready actions

.changeset/short-swans-accept.md, packages/perseus/src/widgets/__tests__/__snapshots__/explanation.test.ts.snap, packages/perseus/src/widgets/explanation.tsx
Adjust button styling to be left-aligned, and to use the line spacing of the surrounding text.
Issue: none
=> Adjust Button Styling to Match Intended UI from Content

.changeset/twenty-onions-love.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
Issue: https://khanacademy.atlassian.net/browse/LEMS-1892
- `yarn dev`
- `open http://localhost:5173`
- Enable Mafs for segment graphs
- tab to the line segment
- the line should be outlined in blue
=> Update focus style for line segments to match designs

.changeset/late-birds-smash.md, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
Add styling that provides the legacy padding at the top and the right of the graph.
Issue: LEMS-1901
=> Restore Padding Around Mafs Graph (Match Legacy Position)

.changeset/heavy-carrots-carry.md, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx, packages/perseus/src/widgets/interactive-graphs/index.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
This is pretty simple PR conceptually, but I think it's going to be really helpful for actual DOM unit tests (vs reducer/logic unit test). In a perfect world, the reducer would be the single source of all logic and the UI would be the visual representation of the output of that logic (state). However Mafs _also_ has logic in it; while I could test what the reducer would do given a certain action, I was having trouble testing the result of a user interaction with Mafs.
So this PR splits MafsGraph into two pieces:
- StatefulMafsGraph: which holds the `useReducer`
- MafsGraph: which basically holds everything else
The benefits:
- I can pass MafsGraph an initial state, so bootstrapping a test is a breeze
- I can mock and spy on a `dispatch` function to assert that I'm getting the actions I …
=> Split MafsGraph into two pieces to make it easier to test

.changeset/orange-ways-whisper.md, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
This works, but I don't know why and I don't know what repercussions there will be. I wasn't able to repro in FF, but I was in Chrome/Safari (this fix works for both). It makes me wonder if this is a browser bug.
It's overriding [this CSS](https://github.com/stevenpetryk/mafs/blob/adc9122f102dc18128644d752d07390a27b92a64/core.css#L4) from Mafs' first commit.
Before
https://github.com/Khan/perseus/assets/16308368/fa2c76aa-c3ee-4672-92ef-e784857fe276
After
https://github.com/Khan/perseus/assets/16308368/145584fe-cc32-44bb-9be2-83c7b99cf792
Issue: [LEMS-1906](https://khanacademy.atlassian.net/browse/LEMS-1906)
An alternative that seems to work: `.MafsView > svg { display: block; }`. Given the amount of spacing at the bottom, it looks suspiciously like this is `inline` spacing accidentally …
=> Possible fix for Chrome repositioning bug

.changeset/grumpy-coats-jump.md, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/interactive-graphs/axis-ticks.tsx, packages/perseus/src/widgets/interactive-graphs/grid.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
This PR adds a new approach to rendering our interactive graph axis tick labels. In order to ensure that we can support cases where the [tickSteps are less than the gridSteps](https://khanacademy.atlassian.net/browse/LEMS-1890), we're now manually rendering these labels. 
The labels have also been updated to render using the `MathJax_Main-Regular` (or `MJXTEX`) font. 
NOTE: There's still a bug regarding overlapping labels on the initial negative axis points, but that will be tackled in [LEMS-1891](https://khanacademy.atlassian.net/browse/LEMS-1891). 
Issue: LEMS-1878
- manual testing in flipbook using all edge cases 
- manual testing in webapp to ensure the fonts are still correctly identified 
[LEMS-1891]: https://khanacademy.atlassian.net/browse/LEMS-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
=> New Interactive Graph Axis Tick Labels (rendered with the MathJax font)

.changeset/dry-carrots-relax.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
Adjust cursor and point visuals to better convey that the point is being dragged.
Issue: LEMS-1894
1. Run `yarn dev` to start a local test server
1. View the page (`http://localhost:5173/`)
* Ensure that at least one graph type is selected in the "Mafs Flags" dropdown
1. Move your mouse to one of the movable points
* Notice the hover state of the point (larger dot, halo and white ring adjust accordingly)
1. Click onto and drag the movable point to a new location
* Notice that the halo is not visible, though the point is still larger (same as hover)
1. Release the mouse (no longer dragging or holding it down)
* Notice the halo has returned (if still hovering)
https://github.com/Khan/perseus/assets/13896410/e79f441a-7c58-46c1-8472-d57f02a41e67 …
=> Add Styling Specific to Dragging a Movable Point

.changeset/ninety-chairs-add.md, dev/gallery.tsx, packages/perseus/src/types.ts
We recently introduced feature flags into Perseus via `APIOptions`. These flags were originally loosely typed with the `Record<>` type, but this is problematic for a few reasons:
1. The host application does not know what flags are supported (or that the structure is nested)
2. The host has no way of knowing when a Perseus update drops support for a flag 
3. Inside Pereus, there's no way of knowing what flags might be passed in, so typos can easily cause a flag not to be used. 
So, this PR changes the flags field to be strongly and explicitly typed. Adding flags should be relatively trivial (if it's a Mafs flag, just add the flag name to the `MafsFlags` array, otherwise add it as you would to any Typescript type)
Issue: "none"
`yarn test`
`yarn tsc`
=> Change APIOptions' 'flags' field to be strongly typed

.changeset/purple-sloths-occur.md, packages/perseus-editor/src/__tests__/item-extras-editor.test.tsx, packages/perseus-editor/src/item-extras-editor.tsx
This is mostly tests since it seems to have tripped us up a couple of times.
The core of the change is to remove component state and compute whether to show FinCalc options using props. That way state can't become stale (because it doesn't exist).
Issue: LEMS-1914
https://github.com/Khan/perseus/assets/16308368/0a1aa82b-bd45-4ca0-962c-ec3a4eeb1326
- Go to the "Item Extras Editor" story: `/?path=/docs/perseus-editor-item-extras-editor--docs`
- Select "Show financial calculator"
- Note the checkbox is checked
- Note the child checkboxes are checked
- One-by-one deselect child checkboxes
- Note "Show financial calculator" stays checked as long as a child is checked
- Note "Show financial calculator" becomes unchecked when all children are unchecked
=> Bugfix: unable to select financial calculator in editor

.changeset/lovely-readers-vanish.md, packages/perseus/src/util/svg.test.ts, packages/perseus/src/util/svg.ts, packages/perseus/src/widgets/interactive-graphs/axis-arrows.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/arrowhead.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/svg-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/vector.tsx
The arrowheads now match the legacy graph.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1893
Test plan:
- `yarn dev`
- Visit: http://localhost:5173/?flags=linear%2Clinear-system&search=linear
The graphed lines should have arrowheads to indicate that the line
extends beyond the graph bounds. The arrowheads should stick to the
line as you move it and point in the correct direction.
=> Style the arrowheads on Mafs linear graphs

.changeset/breezy-jeans-invent.md, packages/perseus-editor/src/widgets/__tests__/radio-editor.test.tsx, packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer.test.tsx.snap, packages/perseus/src/perseus-types.ts, packages/perseus/src/renderer.tsx, packages/perseus/src/widgets/__stories__/radio.stories.tsx, packages/perseus/src/widgets/__tests__/__snapshots__/group.test.tsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/radio.test.ts.snap, packages/perseus/src/widgets/__tests__/radio.test.ts, packages/perseus/src/widgets/__tests__/radio/base-radio.test.tsx, packages/perseus/src/widgets/__tests__/radio/choice.test.tsx, packages/perseus/src/widgets/radio/choice.tsx, packages/perseus/src/widgets/radio/radio.tsx, testing/renderer-with-debug-ui.tsx
Summary
This is a completely backwards-compatible solution that provides an functional-React-friendly API alternative to `showRationalesForCurrentlySelectedChoices` while providing a way to reveal all rationales.
PRs will follow for `label-image`, `group`, and `graded-group`.
Naming it `showSolutions` instead of `showRationales` because for `label-image`, the method displays the correctness of each answer without rationales.
https://github.com/Khan/perseus/assets/23404711/67137a1c-1e3d-4632-9d24-524937c2b80c
Issue: TUT-425
Testing:
Unit tests added and storybook updated to reflect the changes!
=> Add `showSolutions`, implement for radio widget (others coming in following PRs)

.changeset/dirty-cobras-dance.md, packages/perseus/src/widgets/interactive-graphs/axis-arrows.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/types.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/use-graph-config.ts, packages/perseus/src/widgets/interactive-graphs/reducer/use-graph-model.ts
We use a React context to convey contextual information about an
interactive graph down the component tree. I think when this context was
introduced, we envisioned it being the one-stop shop for all information
about a graph, but it turns out that doesn't work well. The different
graph types have different state shapes, so getting state from the
context in the individual graph components would force us to add a bunch
of redundant conditionals to narrow the types.
As a result of this limitation, the context was only used in practice
for information that doesn't vary between the graph types.
This PR renames and restructures the context to clarify its role.
Issue: none
Test plan:
`yarn test`
=> Clarify the role of our graph context

.changeset/old-hornets-laugh.md, packages/perseus/src/widgets/interactive-graphs/__tests__/axis-ticks.test.ts, packages/perseus/src/widgets/interactive-graphs/axis-ticks.tsx, packages/perseus/src/widgets/interactive-graphs/grid.tsx
Sometimes our negative axis labels will overlap, which causes visual issues. 
The previous approach for this issue in graphie consisted of hardcoded logic that hid ALL instances of any axis labels for `-1`. Unfortunately, this logic only works properly if the tickStep is specially set to `1`.
This PR adds new logic that ensures that we **_only_** show the first negative axis tick label IF the gridStep is larger than the tick step. This should account for cases where there's clearly enough room to render the label, and alternative tickSteps such as 0.5. 
e.g. If our gridStep = 1 and our tickStep = 2, it means that there are 2 grid lines for every 1 tick. This allows enough room for both these tick labels to render. 
Issue: LEMS-1891
- new tests
=> New logic to handle bug regarding overlapping axis tick labels in Interactive Graph.

.changeset/sweet-mugs-listen.md, packages/perseus-editor/package.json, packages/perseus-editor/src/components/__stories__/color-circle.stories.tsx, packages/perseus-editor/src/components/__stories__/color-select.stories.tsx, packages/perseus-editor/src/components/__stories__/locked-point-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-point-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/color-circle.tsx, packages/perseus-editor/src/components/color-select.tsx, packages/perseus-editor/src/components/locked-figure-select.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/components/locked-point-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/index.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/styles/perseus-renderer.less, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/interactive-graphs/graph-locked-layer.tsx, packages/perseus/src/widgets/interactive-graphs/locked-point.tsx, yarn.lock
Update to locked points in preparation for locked lines:
- Use Wonder Blocks Accordion's AccordionSection to make the points info collapsible. This will take up less vertical space when necessary.
- Add `toggleable` and `onToggle` props to LockedPointSettings. This should be allow the future LockedLineSettings component to make the points show/hide.
- Add a story to demonstrate said toggleable functionality
- Refactoring to make LockedFiguresSection more universal, not point-specific
- Add more info in the header so the point is easily identifiable (coords, color, filled)
Issue: none
`yarn jest packages/perseus-editor/src/components/__tests__/locked-point-settings.test.tsx`
`yarn jest packages/perseus/src/widgets/__tests__/interactive-graph.test.ts`
`yarn jest …
=> Update locked points in preparation for locked lines

.changeset/clean-tips-reflect.md, .changeset/wicked-poems-grin.md, dev/gallery.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/types.ts
This PR adds the feature flag `interactive-graph-locked-features-m1` which gates access to locked features being built in Milestone 1 (M1) of the interactive-graph rebuild. 
This flag will gate access to adding/editing locked points and locked lines. 
Issue: "none"
=> Add flag for M1 locked features

.changeset/witty-readers-shout.md, dev/flipbook.tsx
There was a reference to `wonder-blocks-color` in `dev/flipboox.tsx` that got back into `main`. WB Color is deprecated and we should use the `@khanacademy/wonder-blocks-tokens` going forward for color definitions. 
Issue: "none"
`yarn tsc` is happy
=> [🔥AUDIT🔥] Fix up stale usage of wonder-blocks-color to use wonder-blocks-tokens

.changeset/twelve-llamas-tap.md, packages/perseus-editor/src/__stories__/editor-page.stories.tsx, packages/perseus-editor/src/__stories__/editor.stories.tsx, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/widgets/__stories__/interactive-graph-editor.stories.tsx
This PR enables the new `interactive-graph-locked-features-m1` feature flag for all `interactive-graph` editor stories (so that you can actually see the locked features as we build them). 
I also centralized our feature flags for `Perseus-editor` stories so it'll be just a bit easier as we start doing more graph types and M2 locked features. 
Issue: "none"
`yarn start`
Navigate to the [With Mafs](http://localhost:6006/?path=/story/perseus-editor-widgets-interactive-graph-editor--with-mafs) sory
Note that the locked figures editing tools appear below the graph
It should also be available in the [With Locked Points](http://localhost:6006/?path=/story/perseus-editor-widgets-interactive-graph-editor--with-locked-points) story.
=> Centralize where we control feature flags in perseus-editor for Storybook

.changeset/chilly-shoes-sniff.md, packages/perseus/src/widgets/__stories__/interactive-graph-regression.stories.tsx, packages/perseus/src/widgets/__stories__/interactive-graph.stories.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
In a future PR, we'll configure Storybook to run snapshot tests on these
stories, which should help us catch visual regressions in Mafs graphs.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1926
- `yarn storybook`
- `open http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--mafs-with-custom-axis-labels`
=> Add Storybook stories for Mafs visual regression testing

.changeset/tender-socks-live.md, packages/perseus/src/widgets/__tests__/__snapshots__/interactive-graph.test.ts.snap, packages/perseus/src/widgets/interactive-graphs/axis-arrows.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/arrowhead.tsx, packages/perseus/src/widgets/interactive-graphs/grid.tsx
The arrowheads had `stroke: inherit` set in their styles, but their
parent element had no stroke set, so the arrowheads weren't showing up.
This commit fixes that, and also fixes some other issues related to
arrowheads:
- The positions of the y-axis arrowheads were swapped
- The axis arrows were getting rendered twice.
Issue: LEMS-1893
Test plan:
- `yarn dev`
- visit http://localhost:5173/#flipbook
- Paste this data into the box:
```json
{"content":"आलेख पर रेखा खींचे जो संपत्ति के साथ $d$ और $t$ में आनुपातिक संबंध दर्शाती हैI इस कारण $t$ की $3$ इकाई में वृद्धि $d$ की  $8$ इकाई में हुई वृद्धि के समान है\n\n\n** $t$ के संबंध में $d$ की परिवर्तन की इकाई दर क्या है?** (यह है कि,$t$ में परिवर्तन की $1$ इकाई $d$ में परिवर्तन की कितनी इकाई के समान होगी?)\n\n परिवर्तन की इकाई दर [[☃ input-number …
```
=> Explicitly set the color of the axis arrows on Mafs graphs

.changeset/tasty-bananas-pump.md, .storybook/main.ts, dev/vite.config.ts
As part of the move away from `@khanacademy/wonder-blocks-i18n` we added some Storybook config to check if we're in a dev/storybook env and just use hard-coded (mock) strings. 
This config was applied in `.storybook/main.ts` but not to our custom dev server (in `/dev`). 
This PR moves the Vite config into `dev/vite.config.ts` so it works for both (we "inherit" the dev vite config in Storybook - maybe that's confusing and we should move it)
Issue: "none"
`yarn dev` - dev UI works
=> [🔥AUDIT🔥] Fix `yarn dev`

.changeset/mighty-rules-turn.md, packages/perseus/src/components/simple-keypad-input.tsx, packages/perseus/src/widgets/expression.tsx, packages/perseus/src/widgets/input-number.tsx
Ran across this error when going into production. Unfortunately, I'm not able to replicate it!
Issue: FEI-5550
I used an expression widget at:
/math/cc-fifth-grade-math/powers-of-ten/imp-comparing-decimal-place-values/quiz/powers-of-ten-quiz-2
And no matter what I could do (both desktop and mobile) I couldn't get the error to display. This at least makes sure that the error is handled if it does come up. It wasn't exactly clear to me which `.input.blur()` was undefined, so I tried to handle a few of them.
=> [🔥AUDIT🔥] Ensure that we don't error on blur.

.changeset/afraid-moons-live.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/utils.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/use-graph-config.ts
Our SVG drawings get clipped off at the bounds of the Mafs SVG
container. This was causing the arrowheads at the end of lines to get
clipped in certain circumstances, e.g. when a line intersects the edge
of the graph at a small acute angle.
The solution implemented in this commit is to draw the arrowheads a few
pixels inside the graph bounds. Note that the legacy interactive graph
takes a similar approach to solving this problem.
Issue: LEMS-1893
Test plan:
- `yarn dev`
- View the Mafs linear graphs at `http://localhost:5173`. Drag the lines
around. The arrowheads should remain visible.
=> Don't extend graphed lines all the way to the graph bounds

.changeset/lazy-poems-fix.md, packages/math-input/src/components/keypad/__tests__/keypad-v2-mathquill.test.tsx, packages/perseus-editor/src/components/widget-editor.tsx, packages/perseus/src/widgets/__tests__/interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts
When `hasBeenInteractedWith` was false and `getGradableGraph` was called, `getGradableGraph` would strip everything but `type` off of `initialGraph`. When this happened in the editor, it meant that certain properties were getting reset to their defaults.
https://github.com/Khan/perseus/assets/16308368/6bbba3de-7dae-4e01-bed6-c586747a3b15
Issue: [LEMS-1935](https://khanacademy.atlassian.net/browse/LEMS-1935)
- Go to the `Interactive Graph Edior > With Mafs` story
- Change type to "Line Segment(s)"
- Change "Number of segments" to 4
- Change "Marking" from "Graph" to "Grid"
- Note "Number of segments" stays on 4 (before it would reset to 1)
[LEMS-1935]: https://khanacademy.atlassian.net/browse/LEMS-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
=> Bugfix: changing graph markings resetting number of segments

.changeset/calm-icons-change.md, packages/perseus-editor/src/components/__stories__/locked-point-settings.stories.tsx, packages/perseus-editor/src/components/locked-figure-settings-actions.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/components/locked-line-settings.tsx, packages/perseus-editor/src/components/locked-point-settings.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx
Right now, the delete button ovelaps with other inputs
on prod. Moved the button to the bottom to give it
more space.
Added a window confirm to the delete button.
[Tentative design inspiration](https://khanacademy.slack.com/archives/C067UM1QAR4/p1714014186088429?thread_ts=1713986944.666589&cid=C067UM1QAR4)
Issue: none
`yarn jest packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx`
Storybook
http://localhost:6006/?path=/story/perseus-editor-widgets-interactive-graph-editor--with-locked-points
http://localhost:6006/?path=/story/perseus-editor-widgets-interactive-graph-editor--with-locked-lines
=> Move delete button in locked figure settings

.changeset/many-cougars-drop.md, packages/perseus/package.json, yarn.lock
Nisha noticed that some Mafs line types used different dash styles. We fixed this upstream in Mafs. Upgrading to Mafs v0.18.5 includes this fix.
| Line | Segment |
| --- | --- | 
| <img width="350" alt="image" src="https://github.com/Khan/perseus/assets/77138/b6c7f0c4-c01d-4776-973e-5be7c733867d"> |  <img width="350" alt="image" src="https://github.com/Khan/perseus/assets/77138/cc7f7836-eb71-4be6-86a4-f06e063be5a2"> |
Issue: LEMS-1930
`yarn start`
Navigate to [All Locked Line Segments](http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--all-locked-line-segments)
Navigate to [All Locked Lines](http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--all-locked-lines)
Note that the dash styles are the same.
=> Upgrade to Mafs 0.18.5 (includes consistent dash styles for lines)

.changeset/hungry-kangaroos-sell.md, config/build/rollup.config.js
For a while I've noticed warnings slide by in the console when running `yarn build`. I didn't take much notice of them as everything seems to work. 
The errors have to do with imports of the Phosphor icons.
Today, however, I dug in and the fix is quite simple. We have `@phosphor-icons/core` set as a `peerDependency` so we don't have to bundle them in our packages (webapp already does). As a result, we want to mark any imports from that package as external so the don't get inlined into our Perseus bundles. 
The fix was quite easy (just mark it as external 🙄).
Issue: "none"
`yarn build` -> watch for `.svg` warnings
=> Fix build warnings related to phosphor icons

.changeset/empty-yaks-hope.md, dev/flipbook.tsx, dev/package.json, yarn.lock
This little PR wraps the controls below the "Perseus JSON content" field of the Flipbook inside of a Toolbar. Subjective improvement? Maybe. :) 
Issue: "none"
Run `yarn dev` and flip to the Flipbook :eyes:
=> [Dev UI] Wrap flipbook navigation controls in Toolbar

.changeset/strange-crabs-bake.md, package.json, packages/math-input/package.json, utils/publish-snapshot.sh, yarn.lock
Previously, we were installing mathjax-renderer directly from a private
GitHub repository. This caused third-party clients of Perseus to be unable
to use Perseus, since they don't have access to that repository.
This commit fixes that by installing `@khanacademy/mathjax-renderer`
from NPM.
Issue: LEMS-1818
Test plan:
- Install the test build of Perseus in webapp.
- Update the version of `@khanacademy/mathjax-renderer` used in webapp to 1.7.2.
- Verify that TeX rendering works.
- Verify that `yarn.lock` lists no GitHub URLs for `@khanacademy/mathjax-renderer`.
=> Get `@khanacademy/mathjax-renderer` from NPM

.changeset/tame-days-worry.md, packages/perseus/src/styles/articles.less, packages/perseus/src/widgets/__stories__/interactive-graph-regression.stories.tsx, packages/perseus/src/widgets/__tests__/__snapshots__/interactive-graph.test.ts.snap, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
There was a bug in the exercise editor where the axis labels on Mafs interactive
graphs were too big.  The cause was the small-screen-specific styling changed
in this commit.
Issue: LEMS-1964
- View the visual regression test added in this commit.
- The axis labels should not overlap with the graph grid.
=> Prevent mobile styling from overriding graph axis label size

.changeset/honest-pens-count.md, packages/perseus-editor/src/__stories__/editor-page.stories.tsx, packages/perseus-editor/src/components/__stories__/locked-figures-section.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-point-settings.test.tsx, packages/perseus-editor/src/components/color-select.tsx, packages/perseus-editor/src/components/labeled-switch.tsx, packages/perseus-editor/src/components/locked-figure-select.tsx, packages/perseus-editor/src/components/locked-figure-settings-actions.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/components/locked-line-settings.tsx, packages/perseus-editor/src/components/locked-point-settings.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts
Update spacing in the Locked Point Settings and Locked Line Settings
accordions so that the settings fit better.
PR includes
- spacing updates
- lowercase letters to save space
- checkboxes changed to switches (based on this [UX guidance](https://blog.uxtweak.com/checkbox-vs-toggle-switch/))
- LabeledSwitch component to remove redundancy
- LockedFiguresSection stories
Issue: https://khanacademy.atlassian.net/browse/LEMS-1965
`yarn jest`
http://localhost:6006/?path=/story/perseus-editor-components-locked-figures-section--with-prod-width
Note: the font styles are ever so slightly off, probably because of global styles in prod vs dev
| Before | After ("solid") | After ("dashed") |
| --- | --- | --- |
| ![Screenshot 2024-04-26 at 4 54 42 …
=> Update spacing in locked figure settings

.changeset/eighty-items-repeat.md, .changeset/six-melons-knock.md, config/test/test.config.js, dev/flipbook.tsx, dev/package.json, packages/perseus/src/widgets/explanation.tsx, yarn.lock
With our migration to Mafs, we still need to draw any `interactive-graph` backgrounds. But, when we do, it can become difficult to determine which UI elements are coming from the background and which are drawn by Mafs. 
This PR introduces a little "status" icon that, when hovered, shows the background image, if there is one. If it is a Graphie, it provides a link to view/edit the Graphie in the graphie-to-png editor.
Issue: "none"
`yarn dev` 
Paste the following into the Flipbook:
```json 
{"content":"The graph of $y=h(x)$ is a line segment joining the points $(1,9)$ and $(3,2)$. \n\n**Drag the endpoints of the segment below to graph $y=h^{-1}(x)$.\n **\n\n[[☃ interactive-graph 1]]","images":{},"widgets":{"interactive-graph 1":{"alignment":"default","graded":true,"options":{"backgroundImag …
```
=> [Dev UI] Display info about background image of current question

.changeset/violet-peaches-tie.md, packages/perseus-editor/src/components/__stories__/device-framer.stories.tsx, packages/perseus-editor/src/components/__stories__/viewport-resizer.stories.tsx
I noticed that there were two components from the editor package that kept bubbling up to the top of the story listing in the "Perseus" area. 
This was caused by having a `/` (separator) character in the name. Removing that moves the `DeviceFramer` and `ViewportResizer` stories down into the PerseusEditor area. 
Issue: "none"
=> [🔥AUDIT🔥] Fix stories that had a separator in the top-level name

.changeset/thick-jars-train.md, packages/perseus-editor/package.json, packages/perseus-editor/src/components/interactive-graph-settings.tsx, yarn.lock
This PR introduces a small warning for content authors. Today, the ruler and protractor on our graph-based questions are not accessible. As a result, we want to encourage content authors to be cautious to enable these two options for `interactive-graph`s.
Note that this does not touch the `grapher` widget editor as that editor seemingly never allowed showing the ruler or protractor. I also checked our `en` content and none of our `grapher` widgets have `showRuler` or `showProtractor` set to `true`.
<details>
<summary>Content verification</summary>
```sh
$ rg -l "\"grapher\"" | xargs jq --slurp '.. | objects | select(has("type") and .type == "grapher" and .options.showProtractor == true)'
```
</details> 
Issue: LEMS-1963
Review the warning text.
=> Add warning that ruler/protractor are not accessible

.changeset/green-ladybugs-design.md, packages/perseus/src/widgets/interactive-graphs/locked-line.tsx
After the initial fix for our dashed line styles being inconsistent, I missed fixing it for our `ray` line type. This PR fixes the ray so that it uses the MAFS-provided CSS variable for the dash style.
Issue: LEMS-1930
* `yarn start`
* Navigate to: http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures
* Change the "Line" locked figure to be a "ray" and have a "style: dashed"
Note that the dash style looks correct. Switch the line "kind" to be a "line" and compare the dash style (it shouldn't change)
=> Fix dash style for 'ray' line types that I missed

.changeset/small-donuts-applaud.md, packages/perseus-editor/src/components/__tests__/locked-point-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/util.ts
SarahB suggested that the default color for locked figures
should be gray so that they don't look more interactive than
they need to.
Updating that here.
https://khanacademy.slack.com/archives/C067UM1QAR4/p1714408357638599?thread_ts=1714070893.730669&cid=C067UM1QAR4
Issue: none
`yarn jest`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures
- Add a new line and confirm it's gray, and its points are gray
- Add a new point and confirm it's gray
=> Changed locked figures default color to gray

.changeset/perfect-beans-attend.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/__tests__/__snapshots__/interactive-graph.test.ts.snap, packages/perseus/src/widgets/__tests__/interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/index.ts, packages/perseus/src/widgets/interactive-graphs/graphs/utils.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-supported-graph-types.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-action.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/types.ts
Roughing out the Mafs Circle Graph.
Learner Experience
https://github.com/Khan/perseus/assets/16308368/f9624567-8b44-4549-98a1-0bf4e413cab7
Editor Experience
https://github.com/Khan/perseus/assets/16308368/3cd23ff1-c917-4fa8-b662-8da4909c1890
Issue: [LEMS-1828](https://khanacademy.atlassian.net/browse/LEMS-1828)
- TODO
[LEMS-1828]: https://khanacademy.atlassian.net/browse/LEMS-1828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Circle Graph foundation

.changeset/curvy-falcons-crash.md, packages/perseus-editor/src/components/__tests__/interactive-graph-settings.test.tsx, packages/perseus-editor/src/components/interactive-graph-settings.tsx
This PR updates the banner warning content authors against using the ruler or protractor so that its only shown if one (or both) are enabled. This will cut down on visual clutter when neither are selected (which is most common).
Issue: LEMS-1963
`yarn start`
Navigate to the EditorPage story
Add an `interactive-graph` widget
Enable the ruler - note that the banner appears
Disable the ruler and enable the protractor - note that the banner appears
Enable both ruler and protractor - note that the banner appears
=> Only show ruler/protractor warning when either is enabled

.changeset/young-mirrors-care.md, packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer.test.tsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/group.test.tsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/radio.test.ts.snap, packages/perseus/src/widgets/radio/choice.tsx
We think `useUniqueIdWithMock` has a problem with certain languages
https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1715260865316979
=> Remove useUniqueIdWithMock for label/id in Choice

package.json, yarn.lock
John migrated Perseus to use the new Khan Academy localization system where translated strings are passed in. This removed the need/use for wonder-blocks-i18n.  This PR removes a dangling dependency that we no longer need. 
Issue: "none"
`yarn`
`yarn test`
`yarn tsc`
=> Remove unused wonder-blocks-i18n

.changeset/shy-pugs-shave.md, packages/perseus-editor/src/components/__tests__/locked-line-settings.test.tsx, packages/perseus-editor/src/components/locked-line-settings.tsx
It would be nice if the summary at the top of the locked line settings
accordion also showed what its kind is (line, segment, ray).
Adding that functionality here.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1993
`yarn jest packages/perseus-editor/src/components/__tests__/locked-line-settings.test.tsx`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures
- change the kind
- confirm that the summary updates
| Line | Ray | Segment |
| --- | --- | --- |
| <img width="376" alt="Screenshot 2024-05-09 at 11 39 53 AM" src="https://github.com/Khan/perseus/assets/13231763/737f259e-dde6-4180-9085-c8ae14a06aa8"> | <img width="368" alt="Screenshot 2024-05-09 at 11 40 10 AM" src="https://github.com/Khan/perseus/assets/13231763/e0e56f83-958d-4a20-9f5 …
=> Update LockedLineSettings to reflect line kind in the summary

.changeset/flat-feet-leave.md, packages/perseus/src/widgets/__stories__/interactive-graph-regression.stories.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/use-transform.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/use-transform.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
This brings the circle graph more in line with Sarah B's [Figma
designs](https://www.figma.com/file/JroPokeCLBv2VRIw3GPvY5/LC---Interactive-graph-widget?type=design&node-id=1150-51899&mode=design&t=rLzMLVWek25t36gx-0)
Issue: LEMS-1976, LEMS-1977
Play around with the circle graphs in the `yarn dev` UI.
Video:
https://github.com/Khan/perseus/assets/693920/ebcb0e39-1418-480e-8169-4b0b043d2e42
=> Add a "drag handle" to the center of graphed circles

.changeset/new-rings-boil.md, packages/perseus-editor/src/components/__tests__/locked-point-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/locked-point-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx
People would prefer for the locked figures to update on every change
instead of waiting until the input fields are blurred.
This should also resolve the firefox where the figures were not update on blur
after using the arrow buttons.
Implementing that in this PR.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1986
`yarn jest`
Storybook
- http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures
- Change the coordinates for locked points and locked lines
- Try typing all sorts of weird numbers and other characters
- negative numbers and decimal numbers are supported
https://github.com/Khan/perseus/assets/13231763/0e9b32d3-8807-4d45-901d-ab5e6c1beaf4
=> Update locked points onChange instead of onBlur

.changeset/giant-seals-camp.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/utils.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/utils.ts, packages/perseus/src/widgets/interactive-graphs/locked-line.tsx
The bug happened when `-0` was passed as a coordinate (yes, `-0` is a distinct
value in floating point, because the sign bit is stored separately from the
mantissa).
This PR patches the bug by handling horizontal and vertical lines as a special
case, and then refactors to a design where the special-casing is no longer
necessary. It's probably easiest to read the PR one commit at a time.
Issue: LEMS-1955
- `yarn dev`
- Play around with the linear graphs at `localhost:5173`
=> Fix a bug where line-ending arrows would flip around or vanish

.changeset/neat-shoes-poke.md, packages/perseus-editor/src/components/__stories__/locked-line-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-line-settings.test.tsx, packages/perseus-editor/src/components/line-swatch.tsx, packages/perseus-editor/src/components/locked-line-settings.tsx
Create a LineSwatch component so we can show the line styles
in the LockedLineSettings summary.
[Design convo here](https://khanacademy.slack.com/archives/C067UM1QAR4/p1715280767285859)
Issue: none
`yarn jest`
Storybook
- http://localhost:6006/?path=/docs/perseuseditor-components-locked-line-settings--docs
- http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures
| Solid | Dashed |
| --- | --- |
| <img width="377" alt="Screenshot 2024-05-14 at 12 05 24 PM" src="https://github.com/Khan/perseus/assets/13231763/770e4b07-df6b-4984-862f-d2f31a086675"> | <img width="385" alt="Screenshot 2024-05-14 at 12 05 18 PM" src="https://github.com/Khan/perseus/assets/13231763/256a5a32-ced3-4c88-a2a2-ca30a0d13cfb"> |
=> Show line style in locked line summary

.changeset/nice-bears-tickle.md, packages/perseus-editor/src/components/__stories__/color-select.stories.tsx, packages/perseus-editor/src/components/__stories__/locked-point-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-line-settings.test.tsx, packages/perseus-editor/src/components/__tests__/locked-point-settings.test.tsx, packages/perseus-editor/src/components/color-select.tsx, packages/perseus-editor/src/components/coordinate-pair-input.tsx, packages/perseus-editor/src/components/defining-point-settings.tsx, packages/perseus-editor/src/components/locked-line-settings.tsx, packages/perseus-editor/src/components/locked-point-settings.tsx
The more functionality we add, the more the inner "defining point" settings diverge
from the standalone locked point settings.
To make things easier for future additions (such as the upcoming validation work
disallowing length 0 lines), I think these should be two separate components
altogether.
This PR includes a bunch of refactoring, including
- The creation of DefiningPointSettings
- Removing props from LockedPointSettings that are no longer needed
- Breakout out the CoordinatePairInput into a new component since
it's the same between the two components. easier to reuse this way
- Moving the unique ID management into the inner components so the
parents don't have to manage them
- Stories updates
Issue: none
`yarn jest`
Confirm that everything behaves the same in the …
=> Split out DefiningPointSettings from LockedPointSettings

.changeset/beige-dolphins-promise.md, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-action.ts, packages/perseus/src/widgets/interactive-graphs/types.ts
The `range` and `snapStep` are available on the `state`. When pairing, Tamara
and I saw some surprising test failures that were caused by this duplication.
Our props and state got out of sync, and since some parts of the graph code
were getting snapStep from props, and other parts were getting it from state,
the resulting behavior was inconsistent.
This commit removes the duplication, ensuring that `range` and `snapStep` are
only passed to each component once.
Issue: none
- `yarn storybook`
- Visit http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph-editor--with-mafs
- Change the range of the graph and observe that the line segment is
constrained to the new range when you drag it around.
=> Remove range and snapStep from MafsGraph props

.changeset/angry-islands-cough.md, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/types.ts
It seems to be unused. `markings` is still available via the MafsGraph props.
It doesn't need to be part of the state because nothing you can do to the graph
can change it, and it's not needed to compute state updates.
Issue: none
=> Remove markings from interactive graph state

packages/perseus/src/__tests__/widgets.test.ts, packages/perseus/src/logging/log.test.ts, packages/perseus/src/widgets/__tests__/grapher.test.ts, packages/perseus/src/widgets/__tests__/plotter.test.tsx, packages/perseus/src/widgets/__tests__/radio/base-radio.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx
We had several tests that were calling setDependencies, which has the
possibility of contaminating tests that run afterward, since the dependencies
are not reset after every test.
This PR changes the tests to always stub getDependencies instead of calling
setDependencies. Jest automatically removes the stubs after every test.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1997
`yarn test`
=> Stub getDependencies instead of calling setDependencies in tests

.changeset/rare-oranges-count.md, packages/perseus-editor/src/components/locked-line-settings.tsx
This is just a nit. Putting Ray before Segment makes it so that
1. The options are in alpahbetical order
2. The options are in length order
Issue: none
Storybook
http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures
=> Alphabetically order locked line kind dropdown options

.changeset/wet-months-collect.md, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts
Previously, the code for initializing movable lines looked like it would
use `graph.coords` if that was provided, and fall back to default values
if not. That's not what it did, because the `??` operator has higher
precedence than the ternary operator. If any coords were passed, we'd
treat the graph as a linear-system graph.
I suspect the reason we didn't notice this bug is that `coords` is never
provided for `linear` or `ray` graphs. Linear and ray graphs always have
one line, and linear-system graphs always have two lines.
Issue: none
Test plan:
- `yarn dev`
- Go to `http://localhost:5173#flipbook`
- View the examples obtained by running each of:
```
ag -l '"type":"linear"' data/questions/ | xargs cat | grep -v 'grapher 1' | pbcopy
ag -l '"type":"ray"' data/questions/ | xargs cat | …
```
=> Clarify the code for initializing linear graphs

.changeset/late-eyes-think.md, dev/flipbook.tsx, dev/package.json
Previously, we were using version 4 in the dev UI, which caused
TypeScript errors on CI. TypeScript was finding the types for v5 when it
should have been using the types for v4.
Issue: LEMS-2002
Test plan:
View an interactive graph in the dev UI flipbook and use the "check
answer" button. It should pop up a banner that goes away after a couple
seconds.
=> Upgrade to @khanacademy/wonder-blocks-timing@5 everywhere

.github/workflows/node-ci.yml
Hopefully this fixes up our Node 18 vs 20 issues in Github actions for good.
From the [release](https://github.com/Khan/changeset-per-package/releases/tag/v1.0.3):
* Update node-version file by @mark-fitzgerald in https://github.com/Khan/changeset-per-package/pull/76
* Bump actions/setup-node from 3 to 4 by @dependabot in https://github.com/Khan/changeset-per-package/pull/34
* Bump github/codeql-action from 2 to 3 by @dependabot in https://github.com/Khan/changeset-per-package/pull/58
* Bump actions/upload-artifact from 3 to 4 by @dependabot in https://github.com/Khan/changeset-per-package/pull/59
* Bump eslint from 8.51.0 to 8.56.0 by @dependabot in https://github.com/Khan/changeset-per-package/pull/60
* Bump eslint-plugin-jest from 27.4.3 to 28.5.0 by @dependabot in …
=> Upgrade to changeset-per-package v1.0.3

.changeset/good-beers-tan.md, .changeset/tender-rules-juggle.md, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
Designs: https://www.figma.com/design/JroPokeCLBv2VRIw3GPvY5/LC---Interactive-graph-widget?node-id=1150-51899&t=kJh1CRKGniWKyer1-0
Issue: LEMS-1978
Test plan:
Visit http://localhost:5173 and turn on Mafs for the circle graph.
The circle should light up blue when hovered.
Note that there is currently an issue where axis numbers intercept the
hover gesture, so the circle will not be blue if your cursor is over an
axis number. This will be fixed in LEMS-2003.
=> Fill interactive circles with blue on hover

.changeset/olive-ligers-sniff.md, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
Previously, axis tick labels could intercept mouse events, leading to a
few problems:
- It was hard to drag an interactive point that was under one of the
labels.
- Hovering over a graphed circle wouldn't highlight the circle if your
cursor was also over a label.
- The cursor changed to a text cursor when you hovered over a label,
which was confusing/unexpected.
- The labels could be selected by dragging over them, which was
unexpected and not useful.
This commit fixes those issues by making axis tick labels unselectable
and invisible to mouse events.
Issue: LEMS-2003
Test plan:
View the Mafs circle graph on `localhost:5173`. Confirm that the issues
described above no longer occur.
=> Prevent axis tick labels from being selected or clicked

.changeset/grumpy-laws-arrive.md, .changeset/tidy-otters-lick.md, packages/perseus-editor/src/components/__tests__/interactive-graph-settings.test.tsx, packages/perseus-editor/src/components/interactive-graph-settings.tsx
The shared graph settings (like range, snap step, grid step, etc). take up a bunch of vertical space in the graph editor. Now that we're also adding locked figures, the editor is growing even taller and unwieldy. 
This PR adds a small heading above the common graph settings and enables "tap-to-toggle" on that header to expand/collapse the area. 
https://github.com/Khan/perseus/assets/77138/0ad4751f-3060-4964-a6de-16ef79bf9367
Issue: "none"
=> Interactive Graph Editor: Make shared graph settings collapsable to save space

.github/workflows/node-ci.yml
We recently moved to Node v20. In doing so, we added an `engines` key to our root `package.json`. This file is only used for local dev and controlling tooling versions and has nothing to do with the packages we publish. 
An example of a failed run looks like this: 
My working theory is that this job is getting the default Node version for the `ubuntu-latest` image (full list of installed software is [here](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#language-and-runtime)).  
In this PR I've added an explicit step that uses the `actions/setup-node` action and forces it to Node v20.  This seems to fix the situation (and align with my working theory of why it was broken). 
Issue: n/a
=> Try to force Node v20

.changeset/new-mirrors-shave.md, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
During the playtest we discovered that the axis tick grid lines are far too light on several different devices. This PR updates the gridlines to use a close approximation to OffBlack32.
As a result of increasing the contrast of these grid lines, I felt the axis tick labels were getting a little harder to read. After checking with design, I've added a white stroke to these labels. This greatly increases readability of our graphs.
Example of old graph contrast:
NOTE: There IS an issue with the contrast between our axis tick labels and the new gridlines.[ See the slack discussion here for more information](https://khanacademy.slack.com/archives/C067UM1QAR4/p1716408416655179). Currently, we have opted to keep the labels as-is until we can check in with design to take a more holistic look at …
=> Ensure there's enough contrast on the grid lines by switching to offBlack50

.changeset/great-glasses-sort.md, packages/perseus/package.json, yarn.lock
0.18.6 demands node version 20.11 or higher, which we don't yet have
everywhere (e.g. webapp's Jenkins server runs 20.5). By downgrading,
we lose a couple features we submitted:
- https://github.com/stevenpetryk/mafs/pull/159
- https://github.com/stevenpetryk/mafs/pull/160
However, I think temporarily sacrificing these features is an okay
tradeoff, because otherwise we cannot release Perseus into webapp.
Longer term, we may be able to convince Steven (the Mafs maintainer) to
relax the node version constraint to something like `>= 20`. I don't
think Mafs actually needs 20.11 specifically.
Issue: none
Test plan:
- Release a new version of Perseus
- Upgrade Perseus in webapp
- All tests should pass on webapp CI
=> Downgrade Mafs from 0.18.6 to 0.18.5

.changeset/brave-lions-melt.md, .changeset/wild-cobras-applaud.md, packages/perseus-editor/src/widgets/__stories__/expression-editor.stories.tsx, packages/perseus-editor/src/widgets/__stories__/label-image-editor.stories.tsx, packages/perseus-editor/src/widgets/__stories__/radio-editor.stories.tsx, packages/perseus/src/perseus-api.tsx, packages/perseus/src/perseus-types.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/definition.tsx, packages/perseus/src/widgets/explanation.tsx
This PR removes some code/APIOptions that are completely unused today. To verify, I checked the webapp and mobile source code. I also checked and these options are not used in Perseus so even if they were set by calling applications, they do nothing. 
It's time to go!
* Remove Empty type as its now centrally defined in `utility.d.ts` which is symlinked into each package src
* Remove unused and deprecated `inModal` APIOption
* Remove unused and deprecated `useDraftEditor` APIOption
Issue: "none"
=> Remove unused APIOptions and types

.changeset/wild-kids-care.md, packages/perseus/package.json, yarn.lock
This version fixes the issue we had with Mafs 0.18.6, which was that the
node version was pinned too strictly. It was causing webapp CI to fail
because an earlier node version was used there.
Mafs 0.18.7 declares support for node >= 20, which should work for us.
Issue: none
Test plan:
- Release Perseus
- Deploy the new version of Perseus into webapp
- webapp CI should pass
=> Upgrade Mafs to 0.18.7

.changeset/rich-spoons-deliver.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/axis-tick-labels.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
There was a bug where the axis tick numbers did not render in older versions of Safari
(Ben repro'd the issue on Safari 15.6). Third tracked it down to the `:before` pseudo-element that we were using to display the negative sign without affecting the alignment of the numbers below the tick marks. By removing the `:before`, we sacrifice the nice alignment,
but fix the Safari bug. In the future, we can consider other ways of achieving the alignment,
e.g. absolute positioning.
- Review Storybook on Safari 15.6
=> Remove :before pseudo-element to fix axis tick labels in Safari 15.6

.changeset/chilled-moose-walk.md, packages/perseus/src/widgets/__tests__/__snapshots__/graded-group.test.ts.snap, packages/simple-markdown/src/__tests__/simple-markdown.test.ts, packages/simple-markdown/src/index.ts
When navigating through an exercise with a SR, it sometimes notices the horizontal divider as shown in the video below. This is most noticeable in long passage practice where the horizontal line is used to format the passage. 
https://github.com/Khan/perseus/assets/30729058/5b1671a4-7911-4c23-aff2-9e4f856b6031
This PR adds `aria-hidden` to the horizontal line, so the screen reader will skip over it.
Issue: [LIT-754](https://khanacademy.atlassian.net/browse/LIT-754)
- Tests pass
- Here is how things would look in webapp:
https://github.com/Khan/perseus/assets/30729058/c28f02b1-f49c-4c8b-8183-147980b994fa
[LIT-754]: https://khanacademy.atlassian.net/browse/LIT-754?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [a11y] Hide horizontal divider from screen reader

.changeset/lucky-cups-learn.md, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/__testdata__/interactive-graph-random.testdata.ts, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/__tests__/interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graph.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/index.ts, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-supported-graph-types.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/types.ts
This PR adds the quadratic question type to the new Mafs-based Interactive Graph widget. It should function identically to the original implementation within Interactive Graph (with 3 control points). 
**Note:** [There is a bug](https://khanacademy.atlassian.net/browse/LEMS-2014) related to the "getValidDestination" method that is incompatible with the innate keyboard support of Mafs. If a user tries to use the keyboard to move the control point to an invalid location, the control point will simply refuse to move further in that direction. As keyboard support is part of an upcoming stage of work on Interactive Graph, I have opted to leave this bug for now. I believe that we will need to find some way to differentiate between a mouse event and a keyboard event to solve this issue. …
=> Add the `quadratic` question type for the new Mafs-based Interactive Graph

.changeset/eleven-carrots-relate.md, packages/perseus/src/components/svg-image.tsx, packages/perseus/src/widgets/__tests__/__snapshots__/group.test.tsx.snap, packages/perseus/src/widgets/__tests__/__snapshots__/image.test.ts.snap, packages/perseus/src/widgets/image.tsx
Fixing some issues around the accessibility of the image widget as it relates to alt text and aria-hidden usage. The fix is as follows:
- If the alt text and the caption are the same, set the alt text to "". This will ensure the image is still accessibility compliant, while avoiding reading out duplicate information. This is similar to a pattern that WCAG recommends for decorative images, https://www.w3.org/WAI/tutorials/images/decorative/.
- Remove hidden screen reader text blocks. This is unnecessary HTML content as we should make use of the alt text in images instead of re-creating it.
- Removing tabindex=0 and aria-hidden attribute on svg images. Non-interactive content should not be tabbable and like wise we shouldn't be aria-hiding images. If the images add no additional information …
=> [Accessibility Bug] Fixing alt and aria-hidden issues with image widgets.

packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx
The `interactive-graph-locked-figures.test.tsx` file was getting really long,
so I thought I would take a pass at streamlining it.
There are a bunch of things that are common amongst the different locked figures,
so I batched them into a `test.each` at the top. This should also help when adding
more features in the future (soon).
I also created a `renderEditor()` function that makes it so that all the tests
don't have to specify the `RenderStateRoot` wrapper, which was also needlessly
taking up space.
This only took it down from ~870 lines to ~600 lines If anyone has ideas for how to streamline it more, I'm all ears.
Issue: none
`yarn jest packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx`
=> [Interactive graph editor] Streamline locked figure tests

.changeset/beige-yaks-sin.md, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/css-cursor.ts, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx
You can only drag this particular point to the left and right. The new
cursor makes that apparent.
Issue: LEMS-1979
Test plan:
Paste this data into the flipbook:
```
{"content":"**Graph the circle $(x+2)^2+(y+1)^2=49$.**\n\n[[☃ interactive-graph 1]]","images":{},"widgets":{"interactive-graph 1":{"alignment":"default","graded":true,"options":{"backgroundImage":{"url":null},"correct":{"center":[-2,-1],"radius":7,"type":"circle"},"graph":{"type":"circle"},"gridStep":[1,1],"labels":["x","y"],"markings":"graph","range":[[-10,10],[-10,10]],"rulerLabel":"","rulerTicks":10,"showProtractor":false,"showRuler":false,"snapStep":[1,1],"step":[1,1]},"static":false,"type":"interactive-graph","version":{"major":0,"minor":0}}}}
```
The cursor should change to a left-right arrow when you hover over the …
=> Make the cursor for the circle edge point a left-right arrow

.changeset/eleven-ligers-accept.md, packages/perseus/src/util/geometry.test.ts, packages/perseus/src/util/geometry.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
The legacy interactive graph constrained vertex movement on polygon
graphs to prevent sides from crossing. As of this commit, we now do the
same for Mafs interactive graphs.
Issue: LEMS-1896
Test plan:
Run:
```
grep -rl '"type":"polygon"' data/questions/ | xargs cat | pbcopy
```
Paste the data into `http://localhost:5173#flipbook`.
Play around with the polygons and verify that you can't make their lines
cross.
=> Prevent the sides of a Mafs polygon from crossing

.changeset/pink-weeks-cheer.md, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/types.ts
This fixes an bug in the exercise editor. Previously, if you loaded an
existing exercise with an interactive graph and opened the interactive graph
widget editor, the graph displayed in the widget editor would *not* reflect the
correct answer.  This was inconsistent/misleading, because content creators
specify the correct answer for graphing questions by moving the elements on the
graph to the correct position.
The way this was implemented for the legacy interactive graph widget was pretty
straightforward: when initializing graph state, we used any coordinates for
interactive elements that were provided in the props. This commit makes Mafs
graphs do the same.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2021
- Deploy the dev build of Perseus into a webapp ZND.
- Visit …
=> Use coords from props to initialize Mafs graph state

.changeset/quick-jobs-jog.md, packages/perseus-editor/src/components/__stories__/locked-vector-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-figures-section.test.tsx, packages/perseus-editor/src/components/__tests__/locked-vector-settings.test.tsx, packages/perseus-editor/src/components/locked-figure-select.tsx, packages/perseus-editor/src/components/locked-figure-settings.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/components/locked-vector-settings.tsx, packages/perseus-editor/src/components/util.ts
Content editors need a way to add and edit a locked vector. This PR adds a settings section that is specific to vectors. While the output of a vector is extremely similar to that of a ray, the underlying data is much simpler (just color and coordinates). Therefore, a separate settings UI is being put in place to account for the simplified dataset.
Issue: LEMS-1950
1. Launch Storybook (`yarn start`)
1. Navigate to Perseus Editor => Widgets => Interactive Graph Editor => [With Locked Lines](http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph-editor--with-locked-lines)
1. Click on the "Add locked figure" drop-down at the bottom of the editor and choose "Vector"
* A vector with default settings should be added to the example graph
* A settings section should be added to …
=> Add/Edit Locked Vector for Interactive Graph

.changeset/poor-teachers-allow.md, packages/perseus-editor/src/components/__stories__/locked-circle-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-circle-settings.test.tsx, packages/perseus-editor/src/components/circle-swatch.tsx, packages/perseus-editor/src/components/coordinate-pair-input.tsx, packages/perseus-editor/src/components/defining-point-settings.tsx, packages/perseus-editor/src/components/locked-circle-settings.tsx, packages/perseus-editor/src/components/locked-figure-select.tsx, packages/perseus-editor/src/components/locked-figure-settings.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/components/locked-point-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx, packages/perseus/src/index.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/locked-circle.tsx
Adding/editing/deleting Locked Circle UI!
Note 1: I did not add restrictions to the range or radius here. I will add that in a later PR. 
Note 2: I'm planning to update this to "ellipse" in a follow-up PR.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1941
[Editor Page storybook with locked figures](http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures)
[Locked Circle Settings](http://localhost:6006/?path=/docs/perseuseditor-components-locked-circle-settings--docs)
=> Add locked circle UI

.changeset/poor-teachers-allow.md, packages/perseus-editor/src/components/__stories__/locked-ellipse-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-ellipse-settings.test.tsx, packages/perseus-editor/src/components/__tests__/util.test.ts, packages/perseus-editor/src/components/ellipse-swatch.tsx, packages/perseus-editor/src/components/locked-ellipse-settings.tsx, packages/perseus-editor/src/components/locked-figure-select.tsx, packages/perseus-editor/src/components/locked-figure-settings.tsx, packages/perseus-editor/src/components/util.ts, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx, packages/perseus/CHANGELOG.md, packages/perseus/src/index.ts, packages/perseus/src/perseus-types.ts, packages/perseus/src/types.ts, packages/perseus/src/widgets/__stories__/interactive-graph.stories.tsx, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/__tests__/interactive-graph.test.ts, packages/perseus/src/widgets/interactive-graphs/graph-locked-layer.tsx, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts, packages/perseus/src/widgets/interactive-graphs/locked-ellipse.tsx
Renaming all instances of locked circle to ellipse. This PR contains
_only_ the rename.
In the next PR, I'm also going to update it so that implements
a Mafs ellipse, which defines the radius in both the x direction
and the y direction.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1941
`yarn jest`
`yarn run lint`
I looked at every single instance of "circle" in the Persues repo
and made sure that none of them are related to locked figures.
=> [Interactive Graph Editor] Rename locked circle to locked ellipse

.changeset/weak-flowers-heal.md, packages/perseus-editor/src/__stories__/editor-page.stories.tsx, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/components/__stories__/locked-figures-section.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-figures-section.test.tsx, packages/perseus-editor/src/components/locked-figure-select.tsx, packages/perseus-editor/src/components/locked-figure-settings.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/types.ts
Now that locked figures m1 has been rolled out, we can remove the flag from
the code. After that, we can also remove the flag from Growthbook.
While I'm here, I also realized the m2 flag wasn't hooked up anywhere, so
I did that as well.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1999
Storybook
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures-current
- Confirm that locked ellipses and vectors don't show up in the UI
- check the settings are not there
- check that the "add locked figure" dropdown options are not there
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures-m-2-flag
- Confirm that locked ellipses and vectors show in the UI
- check that the settings are there
- check that the "add …
=> [Interactive Graph Editor] Remove m1 flag, hook up m2 flag for locked figures

.changeset/silly-beds-provide.md, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
The logic in isValidDestination is quite redundant and would be better served in the interactive-graph-reducer file along with other graphing movement logic.
In addition to this I added quadratic tests to the reducer test to ensure test coverage.
Task: https://khanacademy.atlassian.net/browse/LEMS-2023
=> [Interactive-Graph] Merging isValidDestination into interactive-graph-reducer

.changeset/strong-boats-sip.md, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx
Changing the second line in a Linear System from the color purple, to blue.
Issue: LEMS-2058
Before:
After:
To manually test, go to storybook, select Interactive Graph Editor and toggle to Linear System.
You will see that instead of the second line being purple, it will be blue now.
=> Removing purple color for second LinearSystem line.

.changeset/rotten-hotels-travel.md, .changeset/selfish-games-melt.md, packages/perseus-editor/src/components/__stories__/locked-ellipse-settings.stories.tsx, packages/perseus-editor/src/components/__stories__/locked-figures-section.stories.tsx, packages/perseus-editor/src/components/__stories__/locked-line-settings.stories.tsx, packages/perseus-editor/src/components/__stories__/locked-point-settings.stories.tsx, packages/perseus-editor/src/components/__stories__/locked-vector-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-ellipse-settings.test.tsx, packages/perseus-editor/src/components/__tests__/locked-figures-section.test.tsx, packages/perseus-editor/src/components/__tests__/locked-line-settings.test.tsx, packages/perseus-editor/src/components/__tests__/locked-point-settings.test.tsx, packages/perseus-editor/src/components/__tests__/locked-vector-settings.test.tsx, packages/perseus-editor/src/components/coordinate-pair-input.tsx, packages/perseus-editor/src/components/defining-point-settings.tsx, packages/perseus-editor/src/components/locked-ellipse-settings.tsx, packages/perseus-editor/src/components/locked-figure-settings.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/components/locked-line-settings.tsx, packages/perseus-editor/src/components/locked-point-settings.tsx, packages/perseus-editor/src/components/locked-vector-settings.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
We decided we no longer want to restrict the range on locked figures.
We trust the content authors to use the locked figures how they see fit.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1988
`yarn jest`
Storybook:
- Confirm that the arrow buttons no longer restrict the range
=> Revert "[Interactive Graph Editor] Restrict the range on locked figures (arrow buttons only) (#1323)"

.changeset/witty-moons-develop.md, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
Previously, graph specific properties, like number of sides and snapTo type for polygons, did not appear in the preview graph and did not persist or actually affect the preview graph. This makes it so the options selected affect the preview graph.
Issue: LEMS-2093
- Pull up http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph-editor--with-mafs
- Play around with the different types of graphs and confirm the options affect the preview graph
- Confirm moving the shape or lines around does not reset the options
- Confirm all tests pass
=> Make graph specific properties persist and display on preview graph

.changeset/chilled-hats-tan.md, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/initialize-graph-state.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-action.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
There was a bug in the exercise editor where the preview did not reflect
changes to the graph type or number of segments. This happened because
changes to the `graph.type` and `graph.numSegments` props were ignored.
We now reinitialize the graph state when those props change.
Issue: LEMS-2041
Test plan:
Deploy a dev build of Perseus into the a webapp ZND. Visit:
https://www.khanacademy.org/devadmin/content/exercises/linear-graph-exercise/x3239cabc044aa28b/x325a92c13bc37711
Change the graph type of one of the interactive graphs to "segment".
The preview on the right-hand side of the editor should update.
Change the number of segments on the graph. The preview should update.
=> Reset interactive graph state when the graph type or number of segments changes

packages/perseus-editor/src/widgets/__stories__/interactive-graph-editor.stories.tsx, packages/perseus/src/widgets/__stories__/interactive-graph.stories.tsx
Adding some more stories for better visibility and more testing opportunities.
Issue: LEMS-1985
Interactive Graph Editor: 
Interactive Graph:
- Check out the Polygon with Mafs story in the Interactive graph section (http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--polygon-with-mafs) and confirm it is there and uses Mafs
- Check out the With Mafs Polygon story in the Interactive graph editor section (http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph-editor--with-mafs-polygon) and confirm it is there and uses Mafs
=> Add polygon stories to interactive graph and the editor

.changeset/smooth-worms-wave.md, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
This is a fix for an issue in our Sinusoid graphs, where moving the points to the edge of the graph would cause the entire browser to crash. I believe that this was due the fact that we were bounding and snapping our points to the graph settings AFTER determining if the newDestination is a valid location, which means that points placed at the edge of the graph could end up in an invalid location. This made it possible to get the graph into a bit of an infinite state. 
By moving the boundAndSnap logic prior to checking whether it is a valid location, we can make sure that this loop is impossible. Repeating this order of operations for the Quadratic Graph actually manages to solve a separate issue that was considered a "Won't Do" earlier! :) 
Issue: LEMS-2064 & LEMS-2066
- Manual testing in …
=> Interactive Graph Bug Fix: Ensure that we're bounding and snapping BEFORE checking if the new destination results in a valid graph.

.changeset/nervous-owls-retire.md, packages/perseus/src/widgets/interactive-graph.tsx
Polygon graphs are almost fully migrated, but work on the unlimited sides feature is not slated to be completed until later. To allow us to move foward with Polygon QE and play testing, we are adding a fallback to the legacy graph for when `numSides` is set to `unlimited`. This can be easily removed once the unlimited sides feature is implemented.
Issue: LEMS-2105
- Open local host storybook and navigate to the [Interactive Graph Editor withMafs story](http://localhost:6006/?path=/story/perseuseditor-widgets-interactive-graph-editor--with-mafs)
- Confirm the Line Segment graph is using Mafs
- Change the graph type to Polygon and confirm it is also using Mafs
- Change number of sides to a new number. Confirm it is a Mafs graph. Change number of sides to unlimited. Confirm it is a legacy …
=> Fallback to legacy graph with unlimited sides polygon

.changeset/wild-gifts-grow.md, packages/perseus-editor/src/components/__stories__/locked-polygon-settings.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-polygon-settings.test.tsx, packages/perseus-editor/src/components/coordinate-pair-input.tsx, packages/perseus-editor/src/components/defining-point-settings.tsx, packages/perseus-editor/src/components/locked-ellipse-settings.tsx, packages/perseus-editor/src/components/locked-figure-select.tsx, packages/perseus-editor/src/components/locked-figure-settings.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/components/locked-point-settings.tsx, packages/perseus-editor/src/components/locked-polygon-settings.tsx, packages/perseus-editor/src/components/polygon-swatch.tsx, packages/perseus-editor/src/widgets/__stories__/interactive-graph-editor.stories.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor-locked-figures.test.tsx, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts
Adding/editing/deleting Locked Polygon UI!
Issue: https://khanacademy.atlassian.net/browse/LEMS-1943
[Editor page storybook](http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures-m-2-flag)
[Locked Polygon Settings](http://localhost:6006/?path=/docs/perseuseditor-components-locked-polygon-settings--docs)
| 3 points, default | > 3 points, nondefault settings |
| --- | --- |
| <img width="359" alt="Screenshot 2024-06-17 at 5 07 10 PM" src="https://github.com/Khan/perseus/assets/13231763/eb3730ad-26ab-4b5f-abb1-cba662ce0f1c"> | <img width="356" alt="Screenshot 2024-06-17 at 5 07 19 PM" src="https://github.com/Khan/perseus/assets/13231763/4721b4f3-d086-4220-af3a-3a0efd282307"> |
=> [Interactive Graph Editor] UI for adding/editing/deleting locked polygon

.changeset/funny-sheep-retire.md, packages/perseus-editor/src/components/locked-ellipse-settings.tsx, packages/perseus-editor/src/components/locked-figure-settings-actions.tsx, packages/perseus-editor/src/components/locked-line-settings.tsx, packages/perseus-editor/src/components/locked-point-settings.tsx, packages/perseus-editor/src/components/locked-polygon-settings.tsx, packages/perseus-editor/src/components/locked-vector-settings.tsx
The action buttons that were added in https://github.com/Khan/perseus/pull/1360
need to be behind the m2 flag. Adding the check here.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1951
Storybook
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures-current
- It should not have the action buttons in the locked figure settings
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures-m-2-flag
- Expand all the locked figure settings.
- They should all have the action buttons.
=> [Interactive Graph Editor] Put the action buttons under the m2 flag

.changeset/sour-coats-agree.md, packages/perseus-editor/src/__stories__/editor-page.stories.tsx, packages/perseus-editor/src/__stories__/flags-for-api-options.ts, packages/perseus-editor/src/components/__stories__/locked-figures-section.stories.tsx, packages/perseus-editor/src/components/__tests__/locked-figures-section.test.tsx, packages/perseus-editor/src/components/locked-figure-select.tsx, packages/perseus-editor/src/components/locked-figure-settings.tsx, packages/perseus-editor/src/components/locked-figures-section.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx, packages/perseus/src/types.ts
Adding the m2b flag and its prop to all the relevant components.
This way, it should be easy to use a simple conditional when we add
the upcoming locked figures (function graphs, labels, maybe polygon markings).
Issue: none
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures-current
- Confirm that only point and line show up in the settings
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures-m-2-flag
- Point, line, vector, ellipse, and polygon should show up
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--mafs-with-locked-figures-m-2-b-flag
- It should be identical to the m2 one for now.
=> [Interactive Graph Editor] Add locked features M2b flag

.changeset/shaggy-moles-promise.md, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/use-draggable.ts
We need the `useMovable` hook to do a couple things that Mafs doesn't
yet enable:
- let us handle keyboard events explicitly (needed for angle graphs, and
maybe polygons if we decide to continue supporting side-length
snapping). Currently, Mafs uses heuristics and search to convert
keyboard input into movement vectors based on the provided `constrain`
function, but this only works for grid-based snapping.
- get the movement vector in *pixel coordinates*. This is needed to
implement the protractor rotation handle. The protractor is a
fixed-size image that doesn't scale with the graph, so we really want
to be working in pixels - otherwise, we have to do a bunch of
confusing coordinate transformations.
We'll likely want to iterate on these features a bit before contributing
them back to …
=> Create our own wrapper around Mafs' `useMovable`

.changeset/sweet-zebras-impress.md, packages/perseus-editor/src/__stories__/editor-page-util.tsx, packages/perseus-editor/src/__stories__/editor-page-with-storybook-preview.tsx, packages/perseus-editor/src/__stories__/editor-page.stories.tsx
The preview iframe doesn't work in storybook, because in links to a local URL
to webapp when it's in prod. It has never worked in storybook.
We need to be able to see what the initial state of the questions on the editor
page would look like without making any changes to the actual preview (yet).
I've added a preview here that shows the question and the hints in the editor
page. This works for all widgets. It's sticky, so it follows as you scroll
down a long editor. You can also close it if it's taking too much space.
This is a prerequisite to viewing an interactive graph with initial coordinates.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2051
http://localhost:6006/?path=/story/perseuseditor-editorpage--demo
https://github.com/Khan/perseus/assets/13231763/c39db9c4-380d-4e3f-a556 …
=> [Storybook: Editor Page] Add a working preview for the editor page in storybook

packages/perseus/src/__stories__/server-item-renderer.stories.tsx
Super hacky, but a bad tool is better than no tool (maybe?)
https://github.com/Khan/perseus/assets/16308368/97f97f0a-7c72-45d5-8e2a-85256f39c24d
=> Interactive ServerItemRenderer story

.changeset/short-badgers-wonder.md, packages/perseus-editor/src/__stories__/editor-page.stories.tsx, packages/perseus/src/widgets/__stories__/interactive-graph-regression.stories.tsx, packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts, packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
I updated the builder utility with all currently migrated graph types. This
meant adding linear, linear system, ray, quadratic, and sinusoid.
I also added the ability to give them all starting coords. This is necessary
to prove that the starting coords can be set at all.
Now that it's clear they can be set, we can move onto adding the ability
to edit these coordinates in the editor UI in the next task.
NOTE: The task also includes start coords for the Points graph type, but
that doesn't seem to have the mafs flag on in storybook yet, so I didn't
include that here.
Issue: https://khanacademy.atlassian.net/browse/LEMS-2051
Storybook
- [segment](http://localhost:6006/?path=/story/perseuseditor-editorpage--interactive-graph-segment-with-starting-coords)
- [multiple …
=> [Interactive Graph] Update the builder with all currently migrated graph types

.changeset/chilly-dolls-agree.md, packages/perseus-editor/src/__stories__/editor-page.stories.tsx, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
There was an issue where some of the custom settings for segments, points, and polygon
graphs were not updating the right-side storybook preview for interactive graphs
in the EditorPage stories.
The issue is that the `onChange` functions in `interactive-graph-editor.tsx` were
updating the `correct` field, but they were not updating the `graph` field.
Updating the `graph` field as well in this PR.
Issue: none
Storybook
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--interactive-graph-segment-with-starting-coords
- Change the number of segments
- Confirm that the number changes in the right panel, and it matches the preview in the left panel
- Go to http://localhost:6006/?path=/story/perseuseditor-editorpage--interactive-graph-polygon
- Change the number of sides 
- …
=> [Interactive Graph Editor] Fix the editor preview for segments, points, and polygons

.changeset/olive-rivers-eat.md, packages/perseus/package.json, packages/perseus/src/widgets/interactive-graphs/graphs/use-draggable.test.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/use-draggable.ts
This copies Mafs' implementation of the `useMovable` hook into our own `useDraggable`
hook with no substantive changes.  In a future PR, I'll add the new features I need.
Context: We need the useMovable hook to do a couple things that Mafs doesn't
yet enable:
- let us handle keyboard events explicitly (needed for angle graphs, and
maybe polygons if we decide to continue supporting side-length
snapping). Currently, Mafs uses heuristics and search to convert
keyboard input into movement vectors based on the provided `constrain`
function, but this only works for grid-based snapping.
- get the movement vector in pixel coordinates. This is needed to
implement the protractor rotation handle. The protractor is a
fixed-size image that doesn't scale with the graph, so we really want
to be working …
=> Copy the implementation of `useMovable` into `useDraggable`

.changeset/lazy-readers-live.md, packages/perseus/src/init.ts
The `skipMathJax` parameter to `Perseus.init()` controls whether MathJax 2 gets configured
during the `init` call. This is gross because Perseus doesn't even import MathJax 2: it
depends on a global `MathJax` variable existing whenever `skipMathJax` is not passed.
`skipMathJax` is almost always being passed in webapp, except in a couple cases in the 
exercise editor where we need to use the legacy KaTeX+MathJax2 math renderer. The
story referenced in the TODO comment is about removing that legacy renderer from webapp
once all mobile app versions that use it have been deprecated. Once MathJax 2 is gone for
good, we should be able to remove `skipMathJax` and the code it controls from Perseus.
Issue: none
All CI checks should pass.
=> [🔥AUDIT🔥] Add TODO comment

.changeset/tricky-rice-nail.md, packages/perseus/src/widgets/interactive-graph.test.tsx, packages/perseus/src/widgets/interactive-graph.tsx
The point graph has two separate user experiences:
- fixed number of points, where you can drag points around, but not add
or delete them
- unlimited points, where you can add and delete points
We have built the first of these experiences in Mafs, but not the
second. We want to release Mafs graphs with fixed-numPoints before
implementing unlimited points.
This commit adds logic to make that possible with feature flags. It also
moves the existing (similar) logic for polygon graphs so all decisions
about which graph to render are made in one, testable place.
Issue: LEMS-2126
Test plan:
Deploy a webapp ZND. Visit
`/internal-courses/test-everything/test-everything-1/te-interactive-graph/a/survey-of-graph-types`
and verify that only the graphs that should use Mafs are doing so.
=> Add a feature flag for Mafs point graphs with fixed numPoints

.changeset/heavy-buckets-think.md, packages/perseus-editor/src/widgets/__tests__/interactive-graph-editor.test.tsx, packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
It turns out that the use of `graphKey` for remounting in
`interactive-graph-editor.tsx` is redundant, since this is also being
done by the `useEffect` in `mafs-graph.tsx`.
`graphKey` was also causing a warning to show up in the logs, possibly
from a remounting loop.
Here, `graphKey` is being removed altogether to stop the remounting issue.
[More info on Slack](https://khanacademy.slack.com/archives/C067UM1QAR4/p1719854190583499)
Issue: none
Storybook
- http://localhost:6006/?path=/story/perseuseditor-editorpage--demo
- Add an interactive graph
- Open the browser console
- Move the graph in the "correct" preview (quickly! Don't hold for time before dragging)
- Confirm the warning doesn't appear
- Change properties of the graph (e.g. number of segments)
- Confirm that the preview changes …
=> [Interactive Graph Editor] Remove the use of graphKey for remounting

.changeset/sour-cougars-draw.md, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx
There's always a console error saying that the circle graph drag handle
is missing the `key` prop.
Adding a `key` here.
Issue: none
Open the console and make sure the error isn't showing up anymore.
`yarn jest packages/perseus/src/widgets/__tests__/interactive-graph.test.ts`
Make sure the logs don't show the console error anymore.
=> [Interactive Graph: Circle] Add a key prop to the circle drag handle

.changeset/curvy-singers-check.md, packages/perseus/src/types.ts
Perseus renders point graphs with fixed numbers of points using Mafs
when the `mafs.point` flag is on. Previously, however, the apiOptions
type (used in the Renderer props) did not allow this flag to be passed.
This commit makes it so the flag can be passed without a type error.
Issue: none
- Check out this webapp PR: https://github.com/Khan/webapp/pull/23239
- Upgrade Perseus to the dev version built by CI for this pull request.
- Run the typechecker in webapp's static service.
- There should be no errors.
=> Add `mafs.point` flag to Renderer prop types

.changeset/new-eyes-repeat.md, packages/perseus/src/widgets/interactive-graphs/graphs/components/vector.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/utils.ts, packages/perseus/src/widgets/interactive-graphs/locked-figures/locked-line.tsx, packages/perseus/src/widgets/interactive-graphs/math/angles.test.ts, packages/perseus/src/widgets/interactive-graphs/math/angles.ts, packages/perseus/src/widgets/interactive-graphs/math/index.ts, packages/perseus/src/widgets/interactive-graphs/math/interpolation.test.ts, packages/perseus/src/widgets/interactive-graphs/math/interpolation.ts, packages/perseus/src/widgets/interactive-graphs/protractor.tsx
These math functions weren't tested, and had some lurking bugs which I've
now fixed.
Issue: LEMS-2135
`yarn test`
=> Move functions from protractor to `math/`

.changeset/ten-paws-wash.md, packages/perseus/src/widgets/interactive-graphs/axis-tick-labels.test.ts, packages/perseus/src/widgets/interactive-graphs/axis-ticks.test.ts
The tests for axis ticks looked lonely hanging out in `__tests__`, so I
moved them next to the associated production code. I also renamed one
file from `tests.ts` to `test.ts` - the name was preventing Jest from
running the tests in that file.
Issue: none
`yarn test`
=> Move tests next to implementation, and fix filename

.changeset/brave-rats-speak.md, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/utils.ts
It's only used by the polygon graph, and doesn't seem like a good candidate for
reuse (with a name like getLines, how would people find it?) so I moved it
closer to its usage site.
Issue: none
`yarn test`
=> Move getLines to polygon.tsx

.changeset/smooth-rice-speak.md, packages/perseus/src/widgets/interactive-graphs/index.ts, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/stateful-mafs-graph.tsx
Each of these components used different helper functions and types defined
alongside them.  I've moved each component into a separate file along with its
associated functions and types. This makes the files more cohesive, so it's
easier to see which groups of entities go together.
Issue: none
`yarn test`
=> Split StatefulMafsGraph and MafsGraph into separate files

config/test/log-on-fail-reporter.js, packages/math-input/src/components/keypad/__tests__/keypad-button.test.tsx, packages/math-input/src/components/tabbar/__tests__/item.test.tsx, packages/perseus-editor/src/__tests__/editor.test.tsx, packages/perseus-editor/src/widgets/__tests__/expression-editor.test.tsx, packages/perseus/src/__tests__/article-renderer.test.tsx, packages/perseus/src/__tests__/renderer-api.test.tsx, packages/perseus/src/__tests__/renderer.test.tsx, packages/perseus/src/__tests__/server-item-renderer.test.tsx, packages/perseus/src/components/__tests__/math-input.test.tsx, packages/perseus/src/components/__tests__/sortable.test.tsx, packages/perseus/src/components/__tests__/sorter.test.tsx, packages/perseus/src/components/__tests__/zoomable.test.tsx, packages/perseus/src/multi-items/__tests__/multi-renderer.test.tsx, packages/perseus/src/widgets/__tests__/explanation.test.ts, packages/perseus/src/widgets/__tests__/expression-mobile.test.tsx, packages/perseus/src/widgets/__tests__/expression.test.tsx, packages/perseus/src/widgets/__tests__/graded-group-set.test.ts, packages/perseus/src/widgets/__tests__/graded-group.test.ts, packages/perseus/src/widgets/__tests__/group.test.tsx, packages/perseus/src/widgets/__tests__/input-number.test.ts, packages/perseus/src/widgets/__tests__/interactive-graph.test.tsx, packages/perseus/src/widgets/__tests__/matcher.test.tsx, packages/perseus/src/widgets/__tests__/number-line.test.ts, packages/perseus/src/widgets/__tests__/numeric-input.test.ts, packages/perseus/src/widgets/__tests__/orderer.test.ts, packages/perseus/src/widgets/__tests__/passage-ref.test.ts, packages/perseus/src/widgets/__tests__/passage.test.tsx, packages/perseus/src/widgets/__tests__/radio.test.ts, types/global.d.ts
This PR is the part of a chain of PRs upgrading Perseus to React 18.
1. #1400
2. This PR --> #1401
3. #1402
4. #1403
It appears that React 18 and RTL are more sensitive to not having mutating calls wrapped in `act()`. The changes in this PR are all simple changes that wrap function calls that cause DOM changes in `act()` calls. There are a few special cases that are failing yet, but this PR cleans up the straightforward ones. 
Issue: LEMS-1802
`yarn test` should have many fewer test failures than PR #1400
Upcoming PRs will address the remaining test failures.
```sh
$ yarn test 
...
Test Suites: 20 failed, 1 skipped, 168 passed, 188 of 189 total
Tests:       104 failed, 14 skipped, 2469 passed, 2587 total
Snapshots:   22 failed, 1 file obsolete, 137 passed, 159 total
Time:        25.267 s, …
```
=> React 18: Wrap non-RTL actions in act()

.changeset/angry-plums-destroy.md, packages/perseus-editor/src/widgets/numeric-input-editor.tsx, packages/perseus/src/widgets/__tests__/interactive-graph.test.ts, packages/perseus/src/widgets/__tests__/radio.test.ts, packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.test.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/use-graph-config.ts, packages/perseus/src/widgets/passage/passage-markdown.tsx, yarn.lock
Our tests printed a lot of noisy warnings to the logs, which made it harder to
spot real test failures. This PR fixes up the code so the warnings are no
longer logged.
Each commit in the PR fixes a different warning. It's probably going to be
easiest to review it one commit at a time.
Issue: LEMS-2141
Run `yarn test`, and verify that no warnings are printed.
=> Fix console errors and warnings printed in tests

.changeset/sour-carrots-flash.md, packages/perseus-linter/src/__tests__/rule.test.ts, packages/perseus-linter/src/__tests__/rules.test.ts, packages/perseus-linter/src/rules/all-rules.ts, packages/perseus-linter/src/rules/profanity.ts
See: https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1720805367737349
Why:
- My understanding is that these linters are rules for content creators
- The linter only checked for 7 English words and only looking for the whole word
- While not a big concern, it _is_ code that has to run and be maintained
- Also it's code in our public codebase, so it feels weird to have
So...
- We're running it against people we trust
- It's not very effective at what it's trying to do
- And there are other reasons to remove it
So I just thought I'd remove it.
=> remove profanity rule

packages/perseus/src/components/__tests__/math-input.test.tsx, packages/perseus/src/widgets/__tests__/numeric-input.test.ts
This PR is the part of a chain of PRs upgrading Perseus to React 18.
1. #1400
2. #1401
3. This PR --> #1402
4. #1403
This PR fixes a few instances where there exists an RTL API for tests instead of making direct DOM object calls. RTL recommends this approach and this fixes a few more tests.
Issue: LEMS-1802
`yarn test` more tests pass
```sh
$ yarn test 
... 
Test Suites: 4 failed, 1 skipped, 184 passed, 188 of 189 total
Tests:       9 failed, 14 skipped, 2564 passed, 2587 total
Snapshots:   4 failed, 1 file obsolete, 155 passed, 159 total
Time:        24.056 s, estimated 25 s
Ran all test suites.
error Command failed with exit code 1.
```
```sh
$ yarn test 
...
Test Suites: 3 failed, 1 skipped, 185 passed, 188 of 189 total
Tests:       6 failed, 14 skipped, 2567 passed, 2587 total …
```
=> React 18: Use RTL functions instead of direct HTML DOM APIs

.changeset/pretty-hornets-cheer.md, packages/perseus/src/widgets/interactive-graphs/graphs/angle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/quadratic.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/ray.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/sinusoid.tsx, packages/perseus/src/widgets/interactive-graphs/mafs-graph.test.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-action.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts
I could never remember which actions are supposed to be used with which
graph type, so I thought I'd fix that. Now you don't have to guess: you
can type `actions.<graph type>` and your IDE will autocomplete the
available actions for you.
Issue: none
`yarn test`
=> Clarify which actions go with which graph type

.changeset/tricky-ravens-kneel.md, packages/perseus/src/widgets/interactive-graphs/graphs/linear-system.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/linear.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/ray.tsx, packages/perseus/src/widgets/interactive-graphs/graphs/segment.tsx, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-action.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.test.ts, packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
The name `moveControlPoint` was not an accurate description of what this action
was doing.  I've renamed it to `movePointInFigure` which hopefully makes it
clear what it's doing and why it takes 3 arguments.  The linear and ray graph
types were using this action, passing a `0` as the `figureIndex` argument
because those graph types only have one figure. I've wrapped the action
constructor for these graph types so they no longer have to pass the dummy
argument.
Issue: none
`yarn test`
=> Simplify and rename an interactive graph reducer action
