- src/widgets/dropdown.jsx
- stylesheets/perseus-admin-package/editor.less
Hey @ariabuckles :)
This should be a quick one, it's for issue #26 
* Added the green/red highlight for correct/incorrect choices
* Standardized the colors used in the editors
* Improved the styling of the editor a bit
> [Dropdown] Highlight incorrect/correct choices

- src/interactive2/movable-polygon-options.js
This change is only based on code inspection _not_ testing. I'm coming with other PR's that I've tested, but this one showed up by using eslint.
T
> Iteration over undefined variable

- src/widgets.js
- src/widgets/expression.jsx
- src/widgets/interaction.jsx
- src/widgets/measurer.jsx
- src/widgets/number-line.jsx
This fixes issues when using Perseus with babel 6
> Fix undefined variables

- packages/perseus-editor/.babelrc.js
- packages/perseus/.babelrc.js
We don't have any snapshot tests right now, but we will in the near future when we copy over all the code from webapp.  This PR should pro-actively address any issues with snapshot tests.
Issue: None
- yarn test
> [🔥AUDIT🔥] Add .babelrc.js files like we have in wonder-stuff

- .github/workflows/release.yml
- land the audit, see that the workflow works
> [🔥AUDIT🔥] Forgot to use actions/checkout in release workflow

- .changeset/beige-balloons-suffer.md
We landed a lot PRs without any changesets since we were making a lot of related changes.  Now that all that work has landed, let's publish.
Issue: None
- land the "Version Changes" PR after it gets created
- install the new packages in webapp and see what issues we run into
> Publish perseus and perseus-editor packages to npm

- .eslintignore
- LICENSE
As per Khan Academy's public and open source repositories stance, adding back in an MIT license.
Issue: "none"
> Add/update LICENSE

- config/build/rollup.config.js
Rollup builds packages in the order they are returned in the build config. Right now, because we get the list of packages using essentially a directory listing, they return in alphabetical ordering, which coincidentally is our build order. But this could easily change and break. 
So this PR introduces an ordering in our Rollup config based on `yarn workspaces info` (which gives us all packages in the workspace and their in-repo depdencies). This should ensure we always build in dependency order!
Issue: "none" (but related to #171)
`yarn build` orders according to dependencies
I also added a `zzz` package and then added it as a dependency on a few of the other packages in this repo. `yarn build` ordered the `zzz` package before any packages that depended on it.
> Use yarn workspaces to generate rollup build config with correct ordering

- packages/kas/package.json
- packages/perseus/package.json
I forgot to the save the changes to packages/kas/package.json and update packages/perseus/package.json to reference the kas under its new name.
- see that the "Release" workflow completes successfully after landing this PR
> [🔥AUDIT🔥] Finish the work of prefixing 'kas' with '@khanacademy'

- .github/REVIEWERS
- .github/workflows/gerald-pr.yml
Copied over from webapp
Issue: https://khanacademy.atlassian.net/browse/FEI-4403
🤞
> Add a workflow for gerald

- packages/perseus/src/perseus-markdown.jsx
- packages/simple-markdown/src/__tests__/simple-markdown_test.js
- packages/simple-markdown/src/index.js
Gentle cleanup by ignoring problems to start. We can pick off the problems one by one, similar to approach to web app when flow and lint where added.
Issue: https://khanacademy.atlassian.net/browse/LP-11660
- Flow and ESLint should be happy with the simple-markdown files
> Simple Markdown Cleanup

- packages/simple-markdown/src/index.js
Clean up!
Issue: https://khanacademy.atlassian.net/browse/LP-11660
> Remove Typescript types and comment types

- .changeset/loud-bikes-burn.md
- packages/simple-markdown/package.json
Now that simple-markdown has been migrated, we'd like to publish it.  This PR contains the final changes required for that.  Once this lands and the changeset bot generates a "Version Packages" PR for use we'll be able to publish it.
- node utils/pre-publish-check-ci.js
> Make simple-markdown public and add .changeset file

- .changeset/two-flowers-jam.md
- packages/perseus-editor/src/article-editor.jsx
- packages/perseus-editor/src/editor-page.jsx
- packages/perseus-editor/src/hint-editor.jsx
- packages/perseus-editor/src/iframe-content-renderer.jsx
- packages/perseus-editor/src/item-editor.jsx
This is based on work in https://github.com/Khan/webapp/pull/5575.  A separate PR will be required to update the perseus-stabilize branch in webapp to consume the changes from this PR.
Issue: FEI-4549
> FEI-4549: Pass a preview URL to load instead of content

- .changeset/smart-jars-hammer.md
- .storybook/preview.js
Fixup storybook by removing a duplicated RenderStateRoot.
- Run storybook
- **You should see all of the stories**
> Fixup storybook rendering

- .changeset/fluffy-glasses-guess.md
- packages/perseus-editor/src/widgets/reaction-diagram-editor.jsx
- packages/perseus/package.json
- packages/perseus/src/__tests__/__snapshots__/item-renderer_test.jsx.snap
- packages/perseus/src/__tests__/__snapshots__/server-item-renderer_test.jsx.snap
- packages/perseus/src/__tests__/renderer-api_test.jsx
- packages/perseus/src/components/input-with-examples.jsx
- packages/perseus/src/components/text-input.jsx
- packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer_test.js.snap
- packages/perseus/src/widgets/__stories__/definition.stories.jsx
- packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set-jipt_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/group_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/matrix_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/numeric-input_test.jsx.snap
- packages/perseus/src/widgets/numeric-input.jsx
- yarn.lock
Update numeric input styling.
Issue: https://khanacademy.atlassian.net/browse/LP-11703
- Run storybook
- **Numeric Input should work and look nicer**
> Wonderblockify numeric input

- .changeset/beige-adults-protect.md
- packages/perseus/src/widgets/__testdata__/base-radio_testdata.js
- packages/perseus/src/widgets/__tests__/radio/base-radio_test.jsx
- packages/perseus/src/widgets/radio/__stories__/base-radio.stories.jsx
- packages/perseus/src/widgets/radio/base-radio.jsx
As part of the radio stabilization effort, we're going to refactor the `BaseRadio` component to be a functional component with good tests and good Flow coverage. Per Kevin's request during my last large PR, I'm breaking up the process into multiple pieces. For this PR:
- Brought Flow coverage from 58% to 95% in base-radio
- Switched PropTypes to Flow
- Pulled styles out of the BaseRadio class because they were noisy
- The switch from PropTypes cause stricter checks in tests and stories, so those types were updated
Issue: LP-12657
Nothing user-facing should change, but the code should now have better Flow coverage
> Radio stabilization: base-radio (part 1: Flow)

- .changeset/purple-pens-jump.md
- packages/perseus/src/perseus-types.js
- packages/perseus/src/types.js
- packages/perseus/src/widgets/__testdata__/base-radio_testdata.js
- packages/perseus/src/widgets/radio.jsx
- packages/perseus/src/widgets/radio/__stories__/base-radio.stories.jsx
- packages/perseus/src/widgets/radio/base-radio.jsx
- packages/perseus/src/widgets/radio/widget.jsx
This is the first part of the stabilization workflow for the widget component of radio.
All the changes here are for increasing flow coverage. 
* Coverage increased from 67% to 100%.
* Removed use of the underscore library from widget.
Issue: LP-12736
No changes to users should be apparent other than increased flow coverage.
> increases flow coverage of Radio's widget component to 100%

- .changeset/slimy-cheetahs-do.md
- packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set-jipt_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/graded-group-set_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/graded-group_test.jsx.snap
- packages/perseus/src/widgets/graded-group.jsx
This is a micro-fix to add some aria tags to our error message container so that it will be read aloud for screen readers when it updates. This error message displays when the user tries to submit a blank answer when clicking "Check Answer". 
Issue: LP-13081
make tesc
> Provided an accessible alert method for content changes

- .changeset/large-keys-sit.md
- packages/perseus/src/styles/widgets/passage.less
- packages/perseus/src/widgets/__stories__/passage-ref.stories.jsx
- packages/perseus/src/widgets/__stories__/passage.stories.jsx
- packages/perseus/src/widgets/__testdata__/passage-ref_testdata.js
- packages/perseus/src/widgets/__testdata__/passage_testdata.js
- packages/perseus/src/widgets/__tests__/__snapshots__/passage-ref_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/passage_test.jsx.snap
- packages/perseus/src/widgets/__tests__/passage_test.jsx
- packages/perseus/src/widgets/passage.jsx
- packages/perseus/src/widgets/passage/get-line-height-for-node.js
Sheesh this one was a pain. The code around line numbering needs a refactor; change anything and things get out of alignment.
In the interest of getting the release out, I went ahead dug through dev tools to return things to how they generally are in prod. At the same time I hopefully simplified some of the code and added some Stories that will help debug things like this in the future.
Things that caused issues:
- The line numbers, paragraphs, and line measurer all have to have the same sizes
- They have to have the same line height
- I think they have to have the same text size
- Paragraphs need no margin or it has to be a multiple of the line height
I think ultimately the problem was this:
- We determine line height by appending an invisible div with class `paragraph` that matches …
> bugfix: passage numbers stop abruptly

- .changeset/heavy-boats-argue.md
- packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer_test.js.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/group_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/radio_test.jsx.snap
- packages/perseus/src/widgets/radio/__stories__/sat-styles.stories.jsx
- packages/perseus/src/widgets/radio/base-radio.jsx
- packages/perseus/src/widgets/radio/choice.jsx
Some small CSS tweaks to address some radio issues we've noticed when about to deploy. Also:
- added a class back that Webapp needs for testing
- added stories for SAT Radio
Issue: LP-13336
BEFORE
AFTER
> [🔥AUDIT🔥] some style tweaks

- .changeset/late-items-help.md
- packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer_test.js.snap
- packages/perseus/src/styles/articles.less
- packages/perseus/src/widgets/__tests__/__snapshots__/group_test.jsx.snap
- packages/perseus/src/widgets/__tests__/__snapshots__/radio_test.jsx.snap
- packages/perseus/src/widgets/radio/choice.jsx
We're having issues with SAT Radio text contrast, but I can't reproduce it locally. The only way I know how to test is to get it in a Webapp ZND. I think these are relatively safe changes (why wouldn't we want the text to be high contrast?)...
> Attempt to force high contrast text in Radio

- .changeset/soft-dolls-hear.md
- package.json
- yarn.lock
https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/83 is tracking this issue.
Issue: None
- yarn storybook, see that it builds without errors
> [🔥AUDIT🔥] Downgrade TS until issues with react-docgen-typescript-plugin are resolved

- .changeset/eighty-plums-melt.md
- packages/math-input/src/components/keypad/button.tsx
- packages/math-input/src/components/keypad/keypad-page-items.tsx
The codemod didn't convert these imports correctly so I had to do it manually.
Issue: None
- yarn tsc
> Fix React 'Node' imports

- .changeset/soft-students-invite.md
- packages/perseus/src/components/fixed-to-responsive.tsx
Switches to true TypeScript types for the FixedToResponsive component 
Issue: "none"
Checked out the component in Storybook
> Type and modernize FixedToResponsive

- .changeset/tame-toes-refuse.md
- packages/perseus/src/components/graph.tsx
- packages/perseus/src/perseus-types.ts
- packages/perseus/src/util/interactive.ts
- packages/perseus/src/widgets/interactive-graph.tsx
Switches to true TypeScript types for `graph.tsx`
\
Issue: "none"
I reviewed the component in Storybook
> Type and modernize graph.tsx

- .changeset/fluffy-poems-rush.md
- packages/perseus/src/components/inline-icon.tsx
Switches to true TypeScript types for `inline-icon.tsx`
Issue: None
Reviewed changes in Storybook
> Type and modernize inline-icon.tsx

- .changeset/curvy-apes-fix.md
- packages/perseus/src/components/__stories__/lint.stories.tsx
- packages/perseus/src/components/lint.tsx
Switches to true TypeScript types for `lint.tsx`
Issue: None
Reviewed changes in Storybook
> Type and modernize lint.tsx

- .changeset/rotten-impalas-unite.md
- packages/perseus/src/components/__stories__/sortable.stories.tsx
- packages/perseus/src/components/__tests__/sortable.test.tsx
- packages/perseus/src/components/sortable.tsx
- packages/perseus/src/util.ts
- packages/perseus/src/widgets/matcher.tsx
Switches to true TypeScript types for <Sortable> component 
Issue: None
Reviewed changes in Storybook
> Type and modernize sortable.tsx

- .changeset/dry-rivers-fix.md
- packages/math-input/src/components/keypad/button-assets.tsx
- packages/math-input/src/components/keypad/geometry-page/index.tsx
Added all missing keys for current views.
The v1 SVGs came out a little crunchy, but there are plans to replace them.
> Full key coverage for current pages

- .changeset/orange-beers-serve.md
- packages/math-input/src/components/input/__tests__/mathquill-helpers.test.ts
- packages/math-input/src/components/input/math-input.tsx
- packages/math-input/src/components/input/math-wrapper.ts
- packages/math-input/src/components/input/mathquill-helpers.ts
- packages/math-input/src/components/key-handlers/__tests__/handle-jump-out.test.ts
- packages/math-input/src/components/key-handlers/handle-jump-out.ts
- packages/math-input/src/components/keypad/__tests__/keypad.test.tsx
- packages/math-input/src/components/keypad/button-assets.tsx
- packages/math-input/src/components/keypad/index.tsx
- packages/math-input/src/components/keypad/keypad-mathquill.stories.tsx
- packages/math-input/src/components/keypad/shared-keys.tsx
Mostly tests because this part of the code scared me. Other than that it's implementing the "magic" cursor management button in the v2 keypad.
https://github.com/Khan/perseus/assets/16308368/d180ae06-05f4-49bb-8acf-fe87435eea82
Issue: LC-913
> "Magic" cursor management button

- .changeset/stupid-moles-heal.md
- packages/math-input/src/index.ts
> Export getCursorContextHelper

- .changeset/sweet-pugs-hear.md
- packages/math-input/src/components/input/math-input.tsx
- packages/math-input/src/components/keypad-legacy/index.ts
- packages/math-input/src/components/keypad-legacy/two-page-keypad.tsx
- packages/math-input/src/components/keypad/index.tsx
- packages/math-input/src/components/keypad/shared-keys.tsx
- packages/math-input/src/components/prop-types.js
- packages/math-input/src/components/tabbar/index.ts
- packages/math-input/src/index.ts
- testing/render-keypad-with-cypress.tsx
It's always been a little confusing to me trying to find the main export in the keypad dirs, so I thought this might help a little.
> kind of clean up how we organize in MathInput

- .changeset/smart-socks-talk.md
- packages/perseus-core/src/types.ts
Just a tiny change to see if I can bump the perseus-core version.
> Try to bump perseus-core

- .changeset/late-nails-warn.md
- packages/math-input/src/components/keypad-legacy/compute-layout-parameters.ts
- packages/math-input/src/components/keypad-legacy/keypad-button.tsx
- packages/math-input/src/components/keypad-legacy/keypad-container.tsx
- packages/math-input/src/components/keypad-legacy/store/actions.ts
- packages/math-input/src/components/keypad-legacy/store/layout-reducer.test.ts
- packages/math-input/src/components/keypad-legacy/store/layout-reducer.ts
- packages/math-input/src/components/keypad-legacy/store/types.ts
- packages/math-input/src/fake-react-native-web/view.tsx
- packages/math-input/src/full-math-input.stories.tsx
- packages/perseus/src/__tests__/item-renderer.test.tsx
This is ready, but it might be best to have me walk you through it. This is a broken experience in prod, so help make clear which pieces of feedback are blockers and what can be done after the patch is released.
https://github.com/Khan/perseus/assets/16308368/1cd54284-87f8-4fb6-9590-420c3bfa429a
Issue: LC-1126
I put up a ZND to test: https://prod-znd-230811-15949-8a7732e.khanacademy.org/internal-courses/test-everything/test-everything-1/expression/e/expression-exercise
> Allow keypad to be placed in a column

- .changeset/kind-tigers-beg.md
- packages/math-input/src/components/keypad/__tests__/keypad-button.test.tsx
- packages/math-input/src/components/keypad/__tests__/keypad-v2.cypress.ts
- packages/math-input/src/components/keypad/__tests__/keypad.test.tsx
- packages/math-input/src/components/keypad/__tests__/test-data-tabs.ts
- packages/math-input/src/components/keypad/keypad-button.tsx
- packages/math-input/src/types.ts
- testing/render-keypad-with-cypress.tsx
Adds event to callback in order to allow consumer to `preventDefault`
> Add event to `onClickKey` callback

- .changeset/afraid-lizards-arrive.md
- packages/perseus/src/error-boundary.tsx
- packages/perseus/src/renderer.tsx
Same as above! ~Guessing a change like this doesn't need a new changeset??~ Ok added a changeset.
Issue: LC-679
> ErrorBoundary additions to log widget type and component stack so these show up in sentry

- .changeset/wicked-mayflies-mix.md
- packages/math-input/src/components/input/math-input.tsx
- packages/math-input/src/components/keypad/mobile-keypad.tsx
- packages/math-input/src/full-math-input.stories.tsx
Revert "Focus Fixes for our Mobile Expression Keypad and MathInput  (#701)"
> try reverting PR to see what happens

- .changeset/tidy-radios-report.md
- packages/perseus/src/__tests__/__snapshots__/server-item-renderer.test.tsx.snap
- packages/perseus/src/hint-renderer.tsx
- packages/perseus/src/multi-items/__tests__/__snapshots__/multi-renderer.test.tsx.snap
- packages/perseus/src/styles/khan-exercise.css
- packages/perseus/src/styles/perseus-renderer.less
LC-1022
Removes legacy style overrides from `ul`
Accidentally fixes LC-1225 as well!
> Fix hints list item rendering

- .github/workflows/node-ci.yml
Makes filters conjunctive rather than disjunctive.
> Make filter action conjunctive rather than disjunctive in changeset check

- .changeset/config.json
- .github/workflows/node-ci.yml
- .github/workflows/release.yml
- package.json
- yarn.lock
Update log formatter to `changelog-github`
LC-1265
> Change log formatter to `changelog-github`

- .changeset/dull-goats-admire.md
- packages/perseus-editor/src/item-extras-editor.tsx
- packages/perseus/src/__tests__/item-renderer.test.tsx
- packages/perseus/src/item-renderer.tsx
The instruction was to do it in the simplest way. This is the simplest way for me, and it will be very little code to consume from webapp.
https://github.com/Khan/perseus/assets/23404711/a5ad1320-45c0-4450-9a59-2f84f7008b68
LC-1413
Fully unit tested.
> Add periodic table with key option to editor

- .changeset/big-rules-vanish.md
- .changeset/proud-fireants-play.md
- packages/math-input/package.json
- packages/perseus/src/widgets/label-image.tsx
- packages/perseus/src/widgets/label-image/answer-choices.tsx
- packages/perseus/src/widgets/label-image/marker.tsx
- packages/perseus/src/widgets/label-image/types.ts
- yarn.lock
Adds pills that appear when answer selected for Label Image Widget.
Issue: LC-1419
https://github.com/Khan/perseus/assets/23404711/34af491f-0252-4633-a133-e5416167f761
When robust Test Everything label image widget examples available, create ZND
> Label Image widget: Pill appears when answer selected

- .changeset/wise-peas-know.md
- packages/perseus/package.json
- packages/perseus/src/widgets/label-image.tsx
- packages/perseus/src/widgets/label-image/marker.tsx
- yarn.lock
Adds a switch to hide/show the new answer choice pills.
Issue: LC-1420
https://github.com/Khan/perseus/assets/23404711/2b98261b-2c1c-4ae3-95f5-e9b38456d367
> Add switch to hide answer choice pills

- .changeset/silent-insects-build.md
- packages/perseus/src/widgets/label-image.tsx
- packages/perseus/src/widgets/label-image/__stories__/answer-pill.stories.tsx
- packages/perseus/src/widgets/label-image/__tests__/answer-pill.test.tsx
- packages/perseus/src/widgets/label-image/answer-pill.tsx
Match marker color for correct & incorrect answers.
Also disables interaction for correct answers, matching marker behavior.
Isolates component and adds interactive story doc.
Issue: LC-1498
https://github.com/Khan/perseus/assets/23404711/64157cdc-ed97-4546-89e0-a5382ab3d2a5
Fire up storybook and play in the new story
> Pill color for correct & incorrect answers

- .changeset/heavy-books-yell.md
- packages/perseus/src/widgets/label-image/strings.ts
Somehow missed this when adding this file before.
String appears in CrowdIn
> [🔥AUDIT🔥] Wrap string in i18n function

- packages/perseus-editor/src/widgets/__tests__/expression-editor.test.tsx
While working on [this PR](https://github.com/Khan/perseus/pull/838) I started to get nervous so I decided to add tests.
Ignore the branch name, there is no ticket for this.
> Add tests for ExpressionEditor

- .changeset/young-emus-try.md
- packages/math-input/src/data/key-configs.ts
- packages/math-input/src/enums.ts
- packages/math-input/src/types.ts
> Remove some types

- .changeset/tricky-suns-sneeze.md
- packages/perseus-editor/src/widgets/__stories__/numeric-input-editor.stories.tsx
- packages/perseus-editor/src/widgets/__tests__/numeric-input-editor.test.tsx
- packages/perseus-editor/src/widgets/numeric-input-editor.tsx
Not after perfection or 100% coverage, just trying to lay some ground work
> add tests for NumericInputEditor

- .changeset/fair-kids-prove.md
- packages/perseus-editor/src/widgets/__stories__/dropdown-editor.stories.tsx
- packages/perseus-editor/src/widgets/__tests__/dropdown-editor.test.tsx
- packages/perseus-editor/src/widgets/dropdown-editor.tsx
Just like all of these, I'm not after perfection - I just want _something_. Trying to speed run the top 10 used widgets in one day.
> add some tests for DropdownEditor

- .github/workflows/release.yml
A tiny bump to ensure it runs well on Node v20
> [🔥AUDIT🔥] Upgrade JamesIves/github-pages-deploy-action to support Node v20

- .changeset/sweet-scissors-relate.md
- packages/perseus-editor/src/editor.tsx
- packages/perseus-editor/src/widgets/__stories__/sorter-editor.stories.tsx
- packages/perseus-editor/src/widgets/__tests__/sorter-editor.test.tsx
There wasn't a lot here to test that had accessible roles.
> add tests for SorterEditor

- .changeset/strong-pugs-sit.md
- packages/perseus-editor/src/widgets/__stories__/matcher-editor.stories.tsx
- packages/perseus-editor/src/widgets/__tests__/matcher-editor.test.tsx
There wasn't a lot here to test that had accessible roles.
> add tests for MatcherEditor

- .changeset/shiny-parents-destroy.md
- packages/perseus-editor/src/widgets/__stories__/categorizer-editor.stories.tsx
- packages/perseus-editor/src/widgets/__tests__/categorizer-editor.test.tsx
- packages/perseus-editor/src/widgets/__tests__/explanation-editor.test.tsx
Lacking things to hook onto on the inputs: https://khanacademy.atlassian.net/browse/LC-1587
> add tests for CategorizerEditor

- .changeset/calm-guests-unite.md
- packages/perseus-editor/src/widgets/__stories__/number-line-editor.stories.tsx
- packages/perseus-editor/src/widgets/__tests__/number-line-editor.test.tsx
- packages/perseus-editor/src/widgets/number-line-editor.tsx
Add some tests for NumberLineEditor
> add tests for NumberLineEditor

- .changeset/curvy-pandas-hunt.md
- packages/perseus-editor/src/widgets/__stories__/input-number-editor.stories.tsx
- packages/perseus-editor/src/widgets/__tests__/input-number-editor.test.tsx
- packages/perseus-editor/src/widgets/input-number-editor.tsx
I know it's depreciated, but it's still used quite often and it wasn't a lot of work to add.
> add tests for InputNumber

- packages/perseus-editor/src/widgets/__stories__/interaction-editor.stories.tsx
Prep work for LC-1541
Issue: LC-1541
> add story for interaction editor

- .github/workflows/node-ci-main.yml
- .github/workflows/node-ci.yml
- .github/workflows/release.yml
Another action that can be updated (will also mean it correctly runs on Node v20). 
Just watch the actions over the next few PRs.
> Upgrade actions/checkout to v4

- .changeset/red-beans-dress.md
- packages/perseus/package.json
- testing/test-mathjax.tsx
- yarn.lock
Adds generated labels to MathJax in Storybook so that we can effectively test accessibility without involving webapp.
Issue: LC-1635
> Add generated labels to MathJax in Storybook

- .changeset/large-ads-allow.md
- packages/perseus/src/util/graphie.ts
Issue: none
Review the Grapher and Interactive Graph docs in Storybook
> Remove dead code from graphie.ts

- .changeset/rich-dingos-kick.md
- packages/perseus/src/styles/widgets/image.less
Removes centering style from image widget.
Issue: LC-1571
> Left-align image widget

- .changeset/odd-turtles-vanish.md
- packages/perseus/src/util/drawing-transform.test.ts
- packages/perseus/src/util/drawing-transform.ts
- packages/perseus/src/util/graph-bounds.ts
- packages/perseus/src/util/graphie.ts
- packages/perseus/src/util/interval.ts
This change factors out some of the state of the Graphie object for better
cohesion.
Issue: none
View the docs for Interactive Graph, Grapher, and Number Line in Storybook
> Encapsulate transforms in DrawingTransform

- .changeset/wet-maps-cover.md
- packages/perseus/src/util/graphie.ts
This is a refactoring PR. It's probably easiest to read it one commit at a
time.
Issue: none
```
yarn test
yarn cypress:ci
```
View the 'Grapher' and 'Interactive Graph' docs in Storybook.
> Define Graphie as an ES6 `class`

- .changeset/witty-boats-report.md
- packages/perseus/src/util/graphie.test.ts
- packages/perseus/src/util/graphie.ts
These tests will cover the refactoring of the drawing tools (which will happen
in a future PR).
`yarn test`
> Add tests for Graphie drawing tools

- .changeset/cold-carrots-carry.md
- packages/perseus/src/util/graphie.ts
Issue: LC-1662
Review the Storybook docs for Interactive Graph, Number Line, and Grapher
> Define parameters of drawing functions explictly instead of using metaprogramming

- .changeset/weak-badgers-behave.md
- packages/perseus/src/util/geometry.test.ts
- packages/perseus/src/util/geometry.ts
- packages/perseus/src/util/graphie.test.ts
- packages/perseus/src/util/graphie.ts
- packages/perseus/src/util/interactive.ts
- packages/perseus/src/util/math.test.ts
- packages/perseus/src/util/math.ts
Test plan:
Review the Interactive Graph docs in Storybook
> Improve typechecking and fix @ts-expect-errors

- docs/architecture.md
This PR starts to build out some documentation about how Perseus works. I've left some placeholder headers for topics I plan to write on in the future (so don't expect everything to be filled in in this PR :) )
Issue: "none"
Read the docs
> [Docs] Architecture

- .changeset/loud-pens-laugh.md
- packages/kmath/src/__tests__/vector.test.ts
- packages/kmath/src/vector.ts
- packages/perseus/src/components/graph.tsx
- packages/perseus/src/components/graphie.tsx
- packages/perseus/src/perseus-types.ts
- packages/perseus/src/util/graphie.test.ts
- packages/perseus/src/util/graphie.ts
- packages/perseus/src/util/interactive.ts
- packages/perseus/src/widgets/measurer.tsx
- packages/perseus/src/widgets/plotter.tsx
Test plan:
Review the Storybook docs
> Fix @ts-expect-errors and `any` types in Graphie and nearby code

- .changeset/thick-impalas-try.md
- packages/perseus/src/interactive2/__tests__/movable-mock.ts
- packages/perseus/src/interactive2/__tests__/movable.test.ts
- packages/perseus/src/interactive2/movable.ts
- packages/perseus/src/util/graphie.ts
I had a few minutes yesterday so I started adding some tests around `Movable` as I know we'll likely be touching it for the `interactive-graph` work we're doing.
Issue: "none"
`yarn test`
> Tests for Movable

- README.md
I noticed that the README defines that we are on Node v12. That's dated so this PR updates to Node v20.
Issue: "none"
> [🔥AUDIT🔥] [Docs] Tweak some of the docs and make sure we declare the right version of Node

- .changeset/sixty-ants-return.md
- packages/perseus/src/widgets/interactive-graph.tsx
- packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
- packages/perseus/src/widgets/interactive-graphs/mafs-styles.css
Summary:
Minor bugfixes for Mafs to prepare for initial deploy.
- Moved sizing logic
- Changed color variables
Issue: N/A
Testing:
With feature flag on, graph with its own grid should render with no console errors.
> Bugfixes for Mafs

- .changeset/fair-flies-know.md
- packages/perseus/src/index.ts
While working on LEMS-1615, I realized I neglected to properly export the new functions properly. This is a minor patch PR to remedy that. 
Issue: LEMS-1615
n/a
> Fix missing exports

- dev/gallery.tsx
- dev/package.json
https://github.com/Khan/perseus/assets/23404711/43efa352-2e46-4780-a640-bd95ce79803d
Add search feature and query params to dev ui to prevent needing to reset state and scroll to graph on each fast module reload.
N/A
> Add query params to dev ui

- .changeset/beige-birds-crash.md
- packages/perseus/src/widgets/interactive-graphs/graphs/components/angle.tsx
- packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx
Show right angles any time a right angle is created, whether or not `showAngles` is true, which is the current behavior of `interactiveGraph`
LEMS-1857
> Polygon graph: how right angle whether `showAngles` is true or not

- .changeset/lucky-waves-doubt.md
- packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx
- packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point.tsx
- packages/perseus/src/widgets/interactive-graphs/graphs/polygon.tsx
- packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-reducer.ts
- packages/perseus/src/widgets/interactive-graphs/utils.test.ts
- packages/perseus/src/widgets/interactive-graphs/utils.ts
Use `snap` in `constrain` callback so Mafs can properly position points when navigating with a keyboard.
Issue: [LEMS-1885](https://khanacademy.atlassian.net/browse/LEMS-1885)
- In Flipbook
- Paste the below content
- Click a movable point
- Use your arrow keys to try an move it
- Note they move
```
{"content":"This one was always working [[☃ interactive-graph 1]]","images":{},"widgets":{"input-number 1":{"alignment":"default","graded":true,"options":{"answerType":"number","inexact":false,"maxError":0.1,"simplify":"required","size":"normal","value":6},"static":false,"type":"input-number","version":{"major":0,"minor":0}},"interactive-graph 1":{"alignment":"default","graded":true,"options":{"backgroundImage":{"bottom":0,"height":0,"left":0,"scale":1,"url":"","width":0},"correct":{"coords":[[ …
```
> Movable point bug: use snap in constrain callback

- .changeset/serious-candles-invent.md
- packages/perseus/src/widgets/interactive-graphs/__tests__/axis-ticks.test.ts
- packages/perseus/src/widgets/interactive-graphs/axis-ticks.tsx
- packages/perseus/src/widgets/interactive-graphs/grid.tsx
@nicolecomputer + @SonicScrewdriver co-authored this.
Adds graph tick marks.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1877
- Check out the graphs
> Graph tick marks

- .changeset/bright-forks-pump.md
- packages/perseus/src/__testdata__/server-item-renderer.testdata.ts
- packages/perseus/src/__tests__/server-item-renderer.test.tsx
- packages/perseus/src/server-item-renderer.tsx
Adds `showSolutions` to `ServerItemRenderer`
Quick follow-up to #1184
> Expose showSolutions prop on ServerItemRenderer

- .changeset/pretty-jokes-sort.md
- packages/perseus/src/components/math-input.tsx
- packages/perseus/src/components/simple-keypad-input.tsx
- packages/perseus/src/widgets/expression.tsx
- packages/perseus/src/widgets/input-number.tsx
This adds even more checks to ensure that we're only calling blur on something that has a blur function. Hopefully that will help to address this issue:
https://khanacademyorg.sentry.io/issues/5250261131/?project=15744&query=is%3Aunresolved&referrer=issue-stream&sort=new&statsPeriod=14d&stream_index=0
Issue: FEI-5550
I haven't been able to replicate this locally!
> Add additional blur checks.

- .changeset/dull-lamps-sneeze.md
- packages/perseus-editor/src/widgets/numeric-input-editor.tsx
Jeremy, you were right! Turns out there are some places that call the methods directly without using .bind(). I'm not sure I can find them all so I just changed all the methods to be bound. I hope that works!
Issue: FEI-5550
I've confirmed that this page renders correctly after this change:
http://localhost:8090/devadmin/content/exercises/lateral-and-total-surface-area-of-cylinders/x48fc188364f60f35/x18cc8eaa537fc877
> Change method binding for NumericInputEditor.

- utils/publish-snapshot.sh
Missed this! This will allow the snapshots to be created again.
> [🔥AUDIT🔥] Remove an extraneous extract-strings.

- .changeset/clean-comics-stare.md
- dev/flipbook.tsx
- dev/package.json
- yarn.lock
I changed the "Check Answer" button result to be displayed in a WB banner so that it doesn't require a second click to dismiss it. Now it just disappears after a short timeout. 
Issue: "none"
`yarn dev`
Paste some questions into the Flipbook 
Click "Check answer"
> [Dev UI] Display correctness in WB Banner

- dev/gallery.tsx
- utils/publish-snapshot.sh
Add a "Copy question" button to make it easy to copy/paste stuff from the gallery to flipbook.
https://github.com/Khan/perseus/assets/16308368/5e51b78b-e388-4c15-8860-1e488e865306
> Add a "Copy question" to the graph gallery dev tool

- dev/package.json
- package.json
- yarn.lock
This check was failing on everyone's branches, so fixing it here
https://github.com/Khan/perseus/actions/runs/9088536946/job/24978356027?pr=1268
Issue: none
`yarn run lint`
> Update WB toolbar depenency in dev

- .changeset/mighty-mayflies-whisper.md
- packages/perseus-editor/src/__stories__/flags-for-api-options.ts
- packages/perseus-editor/src/components/__tests__/util.test.ts
- packages/perseus-editor/src/components/locked-figure-settings.tsx
- packages/perseus-editor/src/components/locked-figures-section.tsx
- packages/perseus-editor/src/components/util.ts
- packages/perseus-editor/src/widgets/interactive-graph-editor.tsx
- packages/perseus/src/index.ts
- packages/perseus/src/perseus-types.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/__stories__/interactive-graph.stories.tsx
- packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts
- packages/perseus/src/widgets/__tests__/interactive-graph.test.ts
- packages/perseus/src/widgets/interactive-graphs/graph-locked-layer.tsx
- packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.test.ts
- packages/perseus/src/widgets/interactive-graphs/interactive-graph-question-builder.ts
- packages/perseus/src/widgets/interactive-graphs/locked-circle.tsx
View a locked circle!
This PR is kind of long, but that was necessary due to cascading type updates.
It's also a lot of tests.
Issue: https://khanacademy.atlassian.net/browse/LEMS-1940
`yarn jest`
Storybook
http://localhost:6006/?path=/story/perseus-widgets-interactive-graph--locked-circle
> [Interactive Graph] View locked circle

- .changeset/wild-spoons-shake.md
- packages/perseus/src/widgets/interactive-graphs/graphs/circle.tsx
- packages/perseus/src/widgets/interactive-graphs/mafs-graph.tsx
- packages/perseus/src/widgets/interactive-graphs/reducer/initialize-graph-state.test.ts
- packages/perseus/src/widgets/interactive-graphs/reducer/initialize-graph-state.ts
- packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.test.ts
- packages/perseus/src/widgets/interactive-graphs/reducer/interactive-graph-state.ts
for consistency and clarity.
It's probably going to be easiest to review this PR one commit at a time.
Issue: none
`yarn test`
> Refactor the interactive graph state initialization code

- .changeset/serious-bananas-build.md
- packages/perseus/src/widgets/interactive-graphs/axis-ticks.tsx
- packages/perseus/src/widgets/interactive-graphs/graphs/components/axis-tick-labels.tsx
- packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-point-view.tsx
> Resolve a couple TODO comments

- .changeset/little-paws-play.md
- packages/perseus/src/widgets/interactive-graphs/graphs/components/angle-indicators.tsx
- packages/perseus/src/widgets/interactive-graphs/math/geometry.test.ts
- packages/perseus/src/widgets/interactive-graphs/math/geometry.ts
- packages/perseus/src/widgets/interactive-graphs/math/index.ts
and add tests. There are some interesting edge cases!
Issue: LEMS-2135
`yarn test`
> Move `segmentsIntersect` to the math folder

- .changeset/giant-pants-build.md
> remove perseus-error from changesets

- .github/workflows/maintenance.yml
I mistyped the package name, and it's hard to test Github Actions without landing them first. :'( 
Issue: "none"
`npx update-browserslist-db@latest` works and matches what's in the YML now!
> [🔥AUDIT🔥] Fix mistype of update-browserslist-db package name

- .changeset/silly-ears-cheer.md
- packages/perseus-editor/src/widgets/cs-program-editor.tsx
- packages/perseus/src/components/__stories__/info-tip.stories.tsx
- packages/perseus/src/components/info-tip/index.tsx
- packages/perseus/src/components/info-tip/info-tip-base.tsx
While working on another issue, I noticed that InfoTip could use some touchups
> clean up info-tip

- .changeset/yellow-foxes-visit.md
- packages/perseus/src/widgets/interactive-graphs/protractor.tsx
This PR is for testing / confirming that feature branches work without issue. The reason for this test is that some engineers recalled having issues using feature branches in the past, and we want to verify that there's no issues before rebasing some upcoming work. 
The process for this will be to:
1. Create this PR into a test-featurebranch 
2. Get PR approved and land onto the feature branch 
3. Open up a PR for the test-featurebranch to verify that tests pass without issues. THIS SECOND PR WILL NOT BE LANDED AND SHOULD NOT BE APPROVED. (It will be indicated as such)
> Token change for testing PR process with feature branch

- .changeset/hot-ladybugs-dance.md
- packages/perseus-editor/src/widgets/numeric-input-editor.tsx
Revert rearranging inputs.
See: https://khanacademy.slack.com/archives/C04EA1QAKN0/p1723662734312249?thread_ts=1721833722.649819&cid=C04EA1QAKN0
Reverts change from: https://github.com/Khan/perseus/pull/1480
> Revert arrangement of inputs

- .changeset/selfish-kiwis-collect.md
- dev/gallery.tsx
- packages/perseus/src/widgets/__testdata__/interactive-graph.testdata.ts
Adds a finite point question so its easier to test infinite points vs. finite points.
Issue: LEMS-1816
- Visit the gallery
- **There should be a new question**
> Add a finite point question to gallery

- .changeset/heavy-falcons-bathe.md
- .changeset/rude-snails-kneel.md
- packages/perseus-editor/package.json
- packages/perseus-editor/src/__stories__/content-preview.stories.tsx
- packages/perseus-editor/src/__stories__/tex-error-view.stories.tsx
- packages/perseus-editor/src/content-preview.tsx
- packages/perseus/src/__testdata__/article-renderer.testdata.ts
This PR changes two things for the new `ContentPreview` component:
* We need to import React in files that use JSX even if not using it directly, otherwise things blow up in webapp. 
* Removing the need to pass strings into the component (we'll get them internally from the context)
I linked these changes into webapp and didn't see the `Uncaught ReferenceError: React is not defined` error.
> ContentPreview: fixes

- .changeset/swift-pumpkins-marry.md
- packages/perseus/src/widgets/phet-simulation.tsx
This PR is just to kick off the Github Actions to make sure the latest changes work. We can land still review and land this PR as it removes some lint suppressions that we shouldn't be using in modern React/Perseus code. 
The changes are all just code moving around based on ESLint rules. 
Issue: "none"
> PhET widget: testing Github actions

- .github/workflows/node-ci.yml
We talked about the tradeoffs in Slack: https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1724281433448859
I'm opening this PR as a draft to see if the snapshot gets published.
> Publish NPM snapshots for draft PRs

- .changeset/tall-poets-shop.md
- packages/perseus/src/widgets/dropdown/dropdown-validator.test.tsx
- packages/perseus/src/widgets/dropdown/dropdown-validator.tsx
- packages/perseus/src/widgets/dropdown/dropdown.tsx
- packages/perseus/src/widgets/dropdown/dropdown.types.ts
Split out validation logic for the Dropdown widget
Issue: LEMS-2357
Nothing should change, just moving code
> Split out validation logic for dropdown

- .changeset/real-candles-reflect.md
- packages/perseus/src/widgets/__shared__/noop-validator.test.tsx
- packages/perseus/src/widgets/__shared__/noop-validator.tsx
- packages/perseus/src/widgets/definition/definition.tsx
- packages/perseus/src/widgets/explanation/explanation.tsx
- packages/perseus/src/widgets/image/image.tsx
- packages/perseus/src/widgets/interaction/interaction.tsx
- packages/perseus/src/widgets/molecule/molecule.tsx
- packages/perseus/src/widgets/passage-ref-target/passage-ref-target.tsx
- packages/perseus/src/widgets/passage-ref/passage-ref.tsx
- packages/perseus/src/widgets/passage/passage.tsx
- packages/perseus/src/widgets/video/video.tsx
Consolidate validation logic for widgets that don't have anything to validate
Issues:
- https://khanacademy.atlassian.net/browse/LEMS-2370
- https://khanacademy.atlassian.net/browse/LEMS-2365
- https://khanacademy.atlassian.net/browse/LEMS-2366
- https://khanacademy.atlassian.net/browse/LEMS-2361
- https://khanacademy.atlassian.net/browse/LEMS-2358
- https://khanacademy.atlassian.net/browse/LEMS-2359
Nothing should change, just moving around some code.
> Add noop validator

- .changeset/angry-penguins-itch.md
- packages/perseus/src/__tests__/server-item-renderer.test.tsx
- packages/perseus/src/server-item-renderer.tsx
Please double check, but I didn't see that ServerItemRenderer's `scoreWidgets` was being used.
> Remove SIR's scoreWidgets

- .changeset/yellow-students-occur.md
- packages/perseus/src/mixins/widget-prop-denylist.ts
https://khanacademy.slack.com/archives/C3SLM30AW/p1727364716435589?thread_ts=1727349077.951369&cid=C3SLM30AW
I can't figure out how to test this, so I'm going to either try to spin up a ZND or YOLO it.
> Add widgetIsOpen to the prop denylist

- .changeset/sour-spoons-rush.md
- packages/perseus/src/widgets/matrix/matrix-validator.test.ts
- packages/perseus/src/widgets/matrix/matrix-validator.ts
- packages/perseus/src/widgets/matrix/matrix.tsx
Split out validation logic from Matrix
Issue: LEMS-2363
Nothing should change, just splitting out code
> Matrix: split out validator

- .changeset/curly-beers-live.md
- packages/perseus/src/widgets/grapher/grapher-validator.test.ts
- packages/perseus/src/widgets/grapher/grapher-validator.ts
- packages/perseus/src/widgets/grapher/grapher.tsx
- packages/perseus/src/widgets/grapher/util.tsx
Grapher's validation logic was already split out, but this moves things around so it's consistent with other components (and adds tests)
Issue: LEMS-2360
Nothing should change, just moving coe
> Grapher: move / test validator

- .changeset/angry-readers-battle.md
- packages/perseus/src/widgets/number-line/number-line-validator.test.ts
- packages/perseus/src/widgets/number-line/number-line-validator.ts
- packages/perseus/src/widgets/number-line/number-line.tsx
Split out the validation logic for NumberLineValidator
Issue: LEMS-2478
Nothing should change, just moving code
> Split out NumberLineValidator

- .changeset/young-yaks-develop.md
- packages/perseus/src/widgets/plotter/plotter-validator.test.ts
- packages/perseus/src/widgets/plotter/plotter-validator.ts
- packages/perseus/src/widgets/plotter/plotter.tsx
Split out the validation logic from the Plotter widget
Issue: LEMS-2481
Nothing should change, just moving code
> Split out Plotter validator

- .changeset/dirty-walls-brake.md
- packages/perseus/src/widgets/table/table-validator.test.ts
- packages/perseus/src/widgets/table/table-validator.ts
- packages/perseus/src/widgets/table/table.tsx
Split out validation logic for the table widget
Issue: LEMS-2482
Nothing should change, just moving code
> Split out Table validator

- .changeset/soft-snails-give.md
- packages/perseus/src/widgets/matcher/matcher-validator.test.ts
- packages/perseus/src/widgets/matcher/matcher-validator.ts
- packages/perseus/src/widgets/matcher/matcher.tsx
Splits out validation logic from Matcher
Issue: LEMS-2479
Nothing should change, just moving some logic
> Split out Matcher validator

- .changeset/flat-ravens-promise.md
- packages/perseus/src/validation.types.ts
- packages/perseus/src/widgets/definition/definition.tsx
- packages/perseus/src/widgets/deprecated-standin/__tests__/deprecated-standin.test.ts
- packages/perseus/src/widgets/deprecated-standin/index.tsx
- packages/perseus/src/widgets/explanation/explanation.tsx
- packages/perseus/src/widgets/image/image.tsx
- packages/perseus/src/widgets/interaction/interaction.tsx
- packages/perseus/src/widgets/interactive-graphs/interactive-graph-validator.test.ts
- packages/perseus/src/widgets/passage-ref-target/passage-ref-target.tsx
- packages/perseus/src/widgets/passage-ref/passage-ref.tsx
- packages/perseus/src/widgets/passage/passage.tsx
- packages/perseus/src/widgets/phet-simulation/phet-simulation.tsx
Just some small tweaks to clean things up
> Validator-related cleanup

- .changeset/unlucky-toys-lie.md
- packages/math-input/src/components/keypad/__tests__/keypad.test.tsx
- packages/math-input/src/components/keypad/keypad.tsx
- packages/math-input/src/components/keypad/mobile-keypad-internals.tsx
- packages/math-input/src/components/keypad/shared-keys.tsx
- packages/math-input/src/types.ts
- packages/perseus-editor/src/widgets/__tests__/expression-editor.test.tsx
- packages/perseus-editor/src/widgets/expression-editor.tsx
- packages/perseus/src/components/__tests__/math-input.test.tsx
- packages/perseus/src/components/math-input.tsx
- packages/perseus/src/perseus-types.ts
- packages/perseus/src/widgets/expression/expression.stories.tsx
- packages/perseus/src/widgets/expression/expression.test.tsx
- packages/perseus/src/widgets/expression/expression.tsx
Reverts addition of POC code to perseus
> revert scientific option for keypad

- .changeset/funny-panthers-itch.md
- packages/perseus/src/util/parse-perseus-json.ts
Adding logic to make cheating more difficult to implement.
Issue: LEMS-2503
> Enhance anti-cheating logic

- README.md
See: https://github.com/Khan/perseus/pull/1699
> Document c8 in README

- .changeset/ninety-hairs-crash.md
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/interactive-graph.tsx
- packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx
- packages/perseus/src/widgets/interactive-graphs/mafs-supported-graph-types.ts
Adding feature flag for the polygon unlimited sides work.
Issue: LEMS-1839
Ideally no code should be effected by this new feature flag. This is here so future POC and rollout of experience is behind the proper flag.
> Add feature flag for polygon with unlimited polygon.

- knip.config.ts
- package.json
- yarn.lock
The Knip config helps us ignore false positives from Knip
> Add Knip config

- .changeset/real-insects-film.md
- dev/flipbook-model.ts
- knip.config.ts
- package.json
- packages/math-input/src/components/input/mathquill-helpers.ts
- packages/math-input/src/components/input/scroll-into-view.ts
- packages/math-input/src/enums.ts
- packages/perseus-editor/src/components/dropdown-option.tsx
- packages/perseus/src/util/math.ts
- packages/perseus/src/widgets/expression/expression.tsx
- packages/perseus/src/widgets/interactive-graphs/graphs/components/movable-line.tsx
- packages/perseus/src/widgets/interactive-graphs/graphs/point.tsx
- packages/perseus/src/widgets/interactive-graphs/protractor.tsx
- packages/perseus/src/widgets/molecule/molecule.tsx
- yarn.lock
Knip found a bunch of exports for things that didn't need to be exported.
> Knip 6: remove needless exports

- .changeset/stupid-years-move.md
- knip.config.ts
- package.json
- packages/math-input/src/components/tabbar/item.tsx
- packages/perseus-editor/src/components/checkbox.tsx
- packages/perseus-editor/src/components/dropdown-option.tsx
- packages/perseus-editor/src/widgets/interactive-graph-editor/locked-figures/line-stroke-select.tsx
- packages/perseus-editor/src/widgets/label-image/behavior.tsx
- packages/perseus/src/components/math-input.tsx
- packages/perseus/src/components/sortable.tsx
- packages/perseus/src/definition-context.tsx
- packages/perseus/src/perseus-types.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/interactive-graphs/mafs-supported-graph-types.ts
- packages/perseus/src/widgets/label-image/answer-choices.tsx
- packages/perseus/src/widgets/orderer/orderer.tsx
- yarn.lock
If a type is only used in the file it's declared in, there's no need to export it.
> Knip 10: remove needless type exports

- .changeset/pretty-cherries-rescue.md
- knip.config.ts
- package.json
- packages/math-input/src/components/input/mathquill-types.ts
- packages/perseus/src/perseus-types.ts
- packages/perseus/src/types.ts
- yarn.lock
Remove unused types.
Part of my Knip experiment. Knip identified this as unused and I tried my best to verify that, but please double check!
> Knip 11: remove unused types

- .changeset/polite-pigs-look.md
- .changeset/slow-mails-vanish.md
- packages/math-input/src/components/i18n-context.tsx
- packages/perseus/src/components/i18n-context.tsx
Reverts #1784 because it broke (static) Storybook
> Revert process check (#1784)

- .changeset/pretty-worms-drop.md
- packages/perseus-editor/src/editor-page.tsx
- packages/perseus-editor/src/stateful-editor-page.tsx
- packages/perseus/src/renderer.tsx
- packages/perseus/src/util.ts
Some small changes, code pruning and typing.
> Some small cleanup tweaks

- .changeset/tough-socks-fail.md
- packages/perseus/src/__tests__/renderer.test.tsx
- packages/perseus/src/__tests__/server-item-renderer.test.tsx
- packages/perseus/src/renderer.tsx
- packages/perseus/src/server-item-renderer.tsx
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/expression/expression.tsx
- packages/perseus/src/widgets/input-number/input-number.tsx
- packages/perseus/src/widgets/matrix/matrix.tsx
- packages/perseus/src/widgets/number-line/number-line.tsx
- packages/perseus/src/widgets/numeric-input/numeric-input.tsx
- packages/perseus/src/widgets/table/table.tsx
Pretty sure based on the comments, [searching for uses](https://github.com/search?q=org%3AKhan%20getGrammarTypeForPath&type=code), and [this message](https://khanacademy.slack.com/archives/C02NN49RF/p1627234916002000) that this is just dead code.
> Remove getGrammarTypeForPath

- packages/perseus/src/prompt-types.ts
- packages/perseus/src/widget-ai-utils/group/group.test.ts
- packages/perseus/src/widget-ai-utils/group/group.testdata.ts
- packages/perseus/src/widget-ai-utils/group/prompt-utils.test.ts
- packages/perseus/src/widget-ai-utils/group/prompt-utils.ts
- packages/perseus/src/widgets/group/group.tsx
Adds the getPromptJSON function for Group widget along with tests.
Issue: TUT-930
- Make sure tests pass
- Check if any test cases should be added
> Add prompt JSON utility functions for Group widget

- .changeset/sharp-pianos-flow.md
- packages/perseus/src/util/is-real-json-parse.test.ts
- packages/perseus/src/util/is-real-json-parse.ts
- packages/perseus/src/util/parse-perseus-json.ts
This enables the logic to be tested.
Issue: none
`yarn test`
> Move isRealJSONParse to its own file

- packages/perseus/src/prompt-types.ts
- packages/perseus/src/widget-ai-utils/graded-group/graded-group.test.ts
- packages/perseus/src/widget-ai-utils/graded-group/prompt-utils.test.ts
- packages/perseus/src/widget-ai-utils/graded-group/prompt-utils.ts
- packages/perseus/src/widgets/graded-group-set/graded-group-set.tsx
- packages/perseus/src/widgets/graded-group/graded-group.tsx
Adds getPromptJSON and tests for the GradedGroup widget.
Issue: TUT-930
- Make sure tests pass
- Are there any other tests we should write?
> Add prompt JSON utility functions for GradedGroup widget

- packages/perseus/src/prompt-types.ts
- packages/perseus/src/widget-ai-utils/graded-group-set/graded-group-set.test.ts
- packages/perseus/src/widget-ai-utils/graded-group-set/prompt-utils.test.ts
- packages/perseus/src/widget-ai-utils/graded-group-set/prompt-utils.ts
- packages/perseus/src/widgets/graded-group-set/graded-group-set.tsx
Adds the prompt utility function and tests to the GradedGroupSet widget.
Also removes a type we didn't need from prompt-types.ts
Issue: TUT-930
- Ensure tests pass
- Think if there are any other tests we should add
> Add getPromptJSON function to the GradedGroupSet widget

- .changeset/smooth-goats-joke.md
- packages/perseus/src/index.ts
We'll want access to this type in web app. Export it so it is available.
- Ensure tests pass
> Export the WidgetPromptJSON type from the main package

- .changeset/mean-fans-boil.md
- packages/perseus/src/server-item-renderer.tsx
A super small refactoring of the `componentDidUpdate` to reduce some duplication.
`yarn test`
> SSS: Remove duplicate nullness check on answerableCallback

- .changeset/smooth-hairs-jam.md
- .changeset/tiny-fireants-bake.md
- packages/perseus/src/__tests__/renderer.test.tsx
- packages/perseus/src/components/__tests__/__snapshots__/svg-image.test.tsx.snap
- packages/perseus/src/components/__tests__/svg-image.test.tsx
- packages/perseus/src/components/svg-image.tsx
- packages/perseus/src/index.ts
- packages/perseus/src/renderer-util.test.ts
- packages/perseus/src/util/graphie-utils.test.ts
- packages/perseus/src/util/graphie-utils.testdata.ts
- packages/perseus/src/util/graphie-utils.ts
- packages/perseus/src/widget-ai-utils/graded-group-set/graded-group-set-ai-utils.test.ts
- packages/perseus/src/widget-ai-utils/group/group-ai-utils.test.ts
- packages/perseus/src/widget-ai-utils/image/image-ai-utils.test.ts
- packages/perseus/src/widget-ai-utils/interactive-graph/interactive-graph-ai-utils.test.ts
- packages/perseus/src/widget-ai-utils/label-image/label-image-ai-utils.test.ts
- packages/perseus/src/widgets/graded-group-set/graded-group-set.test.ts
- packages/perseus/src/widgets/grapher/grapher.test.ts
- packages/perseus/src/widgets/group/group.test.tsx
- packages/perseus/src/widgets/image/image.test.ts
- packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
- packages/perseus/src/widgets/interactive-graphs/interactive-graph.test.tsx
- packages/perseus/src/widgets/label-image/__tests__/label-image.test.ts
- packages/perseus/src/widgets/radio/__tests__/__snapshots__/radio.test.ts.snap
- packages/perseus/src/widgets/radio/__tests__/radio.test.ts
This PR updates our approach to loading graphie images for svg-image + a fix for a bug that was introduced while addressing PR feedback. 
An error will be thrown if the labels are not found, but should not impede users. Many tests were added using the failed cases provided on the ticket, in order to ensure that this new approach works for nearly all use cases. 
Issue: [LEMS-2524](https://khanacademy.atlassian.net/browse/LEMS-2524)
- New svg-image tests + test mocking error logger 
- New graphie-utils tests that include (most) of the test cases provided.
[LEMS-2524]: https://khanacademy.atlassian.net/browse/LEMS-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix for svg-image loading 

- .changeset/thick-ducks-hug.md
- packages/kas/src/nodes.ts
Fix for: https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1734539991949319
> Bump all packages to reset releases

- .changeset/nasty-wasps-float.md
This is a version bump to trigger a release so we can test release protections.
Issue: FEI-6062
1. Land this and wait for the Version Packages PR to be created
2. Merge that PR
3. Update #2044 and #2039 with the latest `main`
4. Watch as the various workflows occur and verify that the snapshot releases don't publish things they shouldn't
> [🔥AUDIT🔥] docs(changeset): Bump version for testing release protections.

- .changeset/metal-spiders-impress.md
Bumping a version so we can trigger a release and perform one last test of the workflow PR, #2044.
Issue: FEI-6062
Land this to main, trigger the release by merging the Version Packages PR.
Then quickly merge main into the #2044 branch and see if the release protections are triggered as we expect, including the comment on the PR.
> [🔥AUDIT🔥] docs(changeset): Bump version for one last test of the release protections.

- packages/perseus-core/src/utils/grapher-util.ts
- packages/perseus-score/src/widgets/plotter/score-plotter.ts
- packages/perseus-score/src/widgets/plotter/validate-plotter.ts
- packages/perseus-score/src/widgets/sorter/score-sorter.ts
[Original comment](https://github.com/Khan/perseus/pull/2113#discussion_r1919335906)
I made a separate PR because I made this mistake in a couple of PRs so I thought I'd knock them out all at once.
Issue: LEMS-2737
> Revert changes to underscore's isEqual

- .changeset/six-bats-hang.md
- packages/perseus-core/src/index.ts
- packages/perseus-core/src/widgets/expression.ts
- packages/perseus-core/src/widgets/expression/expression-upgrade.ts
- packages/perseus-core/src/widgets/expression/index.ts
- packages/perseus-core/src/widgets/logic-export.types.ts
- packages/perseus-editor/src/editor-page.tsx
- packages/perseus-editor/src/widgets/expression-editor.tsx
- packages/perseus/src/index.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets.ts
- packages/perseus/src/widgets/expression/expression.test.tsx
- packages/perseus/src/widgets/expression/expression.tsx
> [LEMS-2737/default-expression] move expression upgrade logic

- .changeset/wise-plants-lick.md
- packages/perseus-core/src/index.ts
- packages/perseus-core/src/widgets/number-line/number-line-util.test.ts
- packages/perseus-core/src/widgets/number-line/number-line-util.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/number-line/number-line.tsx
Issue: https://khanacademy.atlassian.net/browse/LEMS-2768
`yarn test`
> Create a function to get the public options for the NumberLine widget

- .changeset/dull-jobs-crash.md
- packages/perseus-core/src/index.ts
- packages/perseus-core/src/widgets/table/table-util.test.ts
- packages/perseus-core/src/widgets/table/table-util.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/table/table.tsx
Issue: https://khanacademy.atlassian.net/browse/LEMS-2766
`yarn test`
> Create a function to get the public options for a Table widget

- .changeset/curvy-donuts-applaud.md
- packages/perseus-core/src/index.ts
- packages/perseus-core/src/widgets/interactive-graph/interactive-graph-util.test.ts
- packages/perseus-core/src/widgets/interactive-graph/interactive-graph-util.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/interactive-graph.tsx
Issue: https://khanacademy.atlassian.net/browse/LEMS-2755
`yarn test`
> Create a function to get the public options for an InteractiveGraph widget

- .changeset/five-rivers-fail.md
- packages/perseus-editor/src/widgets/numeric-input-editor.tsx
It was requested that this string be clarified.
Issue: LEMS-2816
- tests pass
> [message-nit] Minor string adjustment

- .changeset/brave-mice-cheer.md
- packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx
[sigh-seus] Match main for most recent SSS changes.
[sigh-seus] Remove ts suppression
Issue: LEMS-XXXX
- tests pass
> [sigh-seus] docs(changeset): Fixing changes that did not migrate automatically while rebasing feature branch.

- .changeset/old-maps-begin.md
- packages/perseus-core/src/index.ts
- packages/perseus-core/src/widgets/grapher/grapher-util.test.ts
- packages/perseus-core/src/widgets/grapher/grapher-util.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/grapher/grapher.tsx
Issue: https://khanacademy.atlassian.net/browse/LEMS-2759
`yarn test`
> Create a function to get the public options for a Grapher widget

- .changeset/lazy-shirts-fix.md
- packages/perseus-core/src/index.ts
- packages/perseus-core/src/widgets/matrix/matrix-util.test.ts
- packages/perseus-core/src/widgets/matrix/matrix-util.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/matrix/matrix.tsx
Issue: https://khanacademy.atlassian.net/browse/LEMS-2762
`yarn test`
> Create a function to get the public options for a Matrix widget

- packages/perseus-core/src/widgets/radio/radio-util.test.ts
Adding more context to a unit test. Only adding a comment.
Issue: none
> Add note to radio-util test regarding radio's widget key

- yarn.lock
> [REVERT] Reverting Update browserslist (#2181) Commit

- .changeset/stale-coins-remember.md
- packages/perseus-core/src/parse-perseus-json/general-purpose-parsers/test-helpers.ts
- packages/perseus-core/src/parse-perseus-json/perseus-parsers/expression-widget.ts
- packages/perseus-core/src/parse-perseus-json/perseus-parsers/legacy-button-sets.ts
- packages/perseus-core/src/parse-perseus-json/perseus-parsers/legacy-button-sets.typetest.ts
- packages/perseus-core/src/parse-perseus-json/regression-tests/__snapshots__/parse-perseus-json-snapshot.test.ts.snap
- packages/perseus-core/src/parse-perseus-json/regression-tests/data/expression-with-scientific-notation.json
- packages/perseus-core/src/parse-perseus-json/regression-tests/parse-perseus-json-regression.test.ts
- packages/perseus-core/src/parse-perseus-json/result.test.ts
- packages/perseus-core/src/parse-perseus-json/result.ts
Issue: https://khanacademy.atlassian.net/browse/LEMS-2861
`yarn test`
> Accept 'scientific' as a buttonSets value when parsing Expression widgets

- .changeset/orange-books-smoke.md
- packages/perseus-score/src/widgets/expression/score-expression.test.ts
I just made this to use as a demo in [this conversation](https://khanacademy.atlassian.net/browse/LEMS-2892) but it seems like it would be useful to have anyway.
> TeX scoring in Expression test

- .changeset/unlucky-swans-fetch.md
- packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.test.ts
- packages/perseus-core/src/parse-perseus-json/perseus-parsers/interactive-graph-widget.ts
[parser-label-location] docs(changeset): Adding LabelLocation to parser
Tests pass (including new one)
> Update Interactive Graph Parser for Label Location

- .github/workflows/node-ci.yml
It's not a shell script, it's not a python script...it's a javascript!!!
https://github.com/Khan/webapp/pull/31126#discussion_r2032164572
> Update CI message

- .changeset/poor-boats-crash.md
- packages/perseus-core/src/feature-flags.ts
- packages/perseus-core/src/index.ts
- packages/perseus/src/types.ts
Add flags in APIOption, this will be used for feature flags that can be passed from consuming application.
Issue: LEMS-3039
> Add flags in APIOption, this will be used for feature flags that can be passed from consuming application.

- .changeset/fluffy-rockets-smell.md
- packages/perseus-core/src/feature-flags.ts
- packages/perseus/src/types.ts
Update APIOptions flags type to make it more explicit to Perseus
Issue: LEMS-3039
> Update APIOptions flags type to make it more explicit to Perseus

- .changeset/fresh-games-doubt.md
- packages/perseus/src/widgets/radio/__stories__/radio.new.stories.tsx
I moved something used by Stories right when Third was adding a Story.
> fix broken Story import

- .changeset/green-suns-wait.md
- .github/CODEOWNERS
- packages/perseus/src/widgets/radio/radio-component.new.tsx
- packages/perseus/src/widgets/radio/radio-component.tsx
Add codeoweners for the radio widget
Issue: LEMS-2993
> Add codeowners for radio widget

- .changeset/chilly-stingrays-poke.md
- packages/perseus/src/__tests__/server-item-renderer.test.tsx
I was looking at something for someone and noticed that this test could be cleaner.
> Minor test cleanup

- .changeset/late-ghosts-jam.md
- packages/perseus/src/widgets/radio/choice-none-above.new.tsx
- packages/perseus/src/widgets/radio/radio.new.tsx
[based] Somehow some of the file imports were missed or reverted for the new radio work. This PR fixes the imports to all use the new files! 
- tests pass
> docs(changeset): Ensure new radio project files are properly linked to the new files.

- .changeset/light-pandas-happen.md
- packages/perseus-core/src/accessibility.test.ts
- packages/perseus-core/src/accessibility.ts
- packages/perseus-core/src/index.ts
While integrating this into webapp, I noticed that the `violatingWidgets()` function is very poorly typed. This PR adds better typing so it'll be easier to use correctly.
Issue: LEMS-3053
`yarn tsc`
> Add isItemAccessible function and enhance types

- .changeset/spicy-beers-fix.md
- packages/perseus/src/widgets/group/__snapshots__/group.test.tsx.snap
- packages/perseus/src/widgets/group/group.tsx
During a 1/1 Jeremy noticed some code that's not used anymore.
> Remove dead code in Group

- .changeset/mighty-buses-taste.md
- packages/perseus-editor/src/editor-page.tsx
- packages/perseus-editor/src/editor.tsx
- packages/perseus-editor/src/hint-editor.tsx
- packages/perseus-editor/src/item-editor.tsx
- packages/perseus-editor/src/widgets/group-editor.tsx
- packages/perseus-editor/src/widgets/radio/editor.tsx
- packages/perseus-editor/src/widgets/video-editor.tsx
- packages/perseus/src/mixins/changeable.ts
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/explanation/explanation.tsx
- packages/perseus/src/widgets/graded-group-set/graded-group-set.tsx
- packages/perseus/src/widgets/graded-group/graded-group.tsx
- packages/perseus/src/widgets/grapher/grapher.tsx
- packages/perseus/src/widgets/group/group.tsx
- packages/perseus/src/widgets/image/image.tsx
- packages/perseus/src/widgets/interaction/interaction.tsx
- packages/perseus/src/widgets/passage-ref-target/passage-ref-target.tsx
- packages/perseus/src/widgets/passage-ref/passage-ref.tsx
- packages/perseus/src/widgets/passage/passage.tsx
- packages/perseus/src/widgets/table/table.tsx
- packages/perseus/src/widgets/video/video.tsx
Due to my recent work on user input, ChangeHandler didn't need to include as much user input stuff in the type. While I was looking at that, I deprecated some things (see [LEMS-3245](https://khanacademy.atlassian.net/browse/LEMS-3245)) and removed some unused Changeable stuff.
Nothing should change, tests and types should pass.
[LEMS-3245]: https://khanacademy.atlassian.net/browse/LEMS-3245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Clean up some change handler stuff

- .changeset/lucky-mails-repair.md
- packages/perseus/src/widgets/plotter/plotter.stories.tsx
- packages/perseus/src/widgets/plotter/plotter.test.tsx
- packages/perseus/src/widgets/plotter/plotter.testdata.ts
- packages/perseus/src/widgets/plotter/plotter.tsx
[LEMS-3251/plotter-dot] fix plotter dot problem
Issue: LEMS-3251
https://github.com/user-attachments/assets/2826bcbb-b29e-4ec0-a1cc-5c3434d81faa
> Bugfix: Plotter dot graph crashing

- .changeset/modern-cobras-bake.md
- packages/perseus/README.md
I'm just trying to trigger a new Version Packages PR
> Change some text in README to trigger Version Packages

- .changeset/thirty-tigers-greet.md
- packages/perseus/src/widgets/explanation/__snapshots__/explanation.test.ts.snap
- packages/perseus/src/widgets/free-response/__snapshots__/free-response.test.tsx.snap
- packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set-jipt.test.ts.snap
- packages/perseus/src/widgets/graded-group-set/__snapshots__/graded-group-set.test.ts.snap
- packages/perseus/src/widgets/graded-group/__snapshots__/graded-group.test.ts.snap
- packages/perseus/src/widgets/interactive-graphs/__snapshots__/interactive-graph.test.tsx.snap
- pnpm-lock.yaml
- pnpm-workspace.yaml
Just running `utils/sync-dependencies.ts`
> Sync Dependencies

- .changeset/tame-gorillas-cry.md
- packages/perseus-editor/src/__docs__/editor-page-with-storybook-preview.tsx
- packages/perseus-editor/src/content-preview.tsx
- packages/perseus/src/index.ts
See: https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1754085809456379
The Renderer in the SB preview needed UserInputManager for state
> Wrap StoryBook preview in UserInputManager

- .changeset/wet-icons-switch.md
- .storybook/theme.ts
Fix storybook theme, change use of WB colors due to dependency issue.
> Fix storybook theme, change use of WB colors

- .changeset/gorgeous-deers-poke.md
- .storybook/README.md
- packages/perseus-core/src/widgets/radio/radio-util.ts
> random change to trigger version packages workflows

- .changeset/tall-clouds-report.md
- packages/perseus/src/widgets/input-number/input-number.test.ts
- packages/perseus/src/widgets/input-number/input-number.tsx
InputNumber's transform was just filtering stuff that got through. We don't care, pass it all through.
Issue: LEMS-3199
> Remove transform from InputNumber

- .changeset/lovely-vans-sneeze.md
- packages/perseus/src/widgets/numeric-input/numeric-input.class.tsx
- packages/perseus/src/widgets/numeric-input/numeric-input.test.ts
- packages/perseus/src/widgets/numeric-input/utils.test.ts
- packages/perseus/src/widgets/numeric-input/utils.ts
> Remove NumericInput transform

- .changeset/popular-lobsters-sell.md
- packages/perseus/src/widgets/radio/__docs__/a11y.mdx
- packages/perseus/src/widgets/radio/__tests__/choice-indicator.test.tsx
- packages/perseus/src/widgets/radio/choice-indicator.new.tsx
- packages/perseus/src/widgets/radio/multiple-choice-component.new.tsx
There are some accessibility techniques in this widget that should have explanations to help our future selves. Additional coding tweaks were made to aid in accessibility.
> [Radio] Add comments explaining accessibility coding, add attributes to aid in accessibility

- .changeset/cold-balloons-protect.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
Sync dev deps with frontend commit d4b0e2d03e01cddb67d7fd3f84fd2a4b566fea85
Issue: LEMS-XXXX
> Sync dev deps with frontend

- .changeset/spotty-books-pay.md
- packages/perseus/src/widget-ai-utils/group/group-ai-utils.test.ts
- packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.test.ts
- packages/perseus/src/widget-ai-utils/radio/radio-ai-utils.ts
- Gives KM access to choice ids by adding them as part of options in Radio AI Utils
Issue: LEMS-3471
[ZND](https://prod-znd-250902-3109-4a5bdf7--classroom.khanacademy.org/learner/class)
Fix validated by Tony!
> adds choice ids as part of options for KM

- .changeset/fast-mangos-trade.md
- packages/perseus/src/types.ts
- packages/perseus/src/widgets/expression/__docs__/expression.stories.tsx
- packages/perseus/src/widgets/matcher/matcher.tsx
- packages/perseus/src/widgets/radio/multiple-choice-widget.new.tsx
- packages/perseus/src/widgets/radio/radio-component.tsx
- packages/perseus/src/widgets/table/table.tsx
I should have done this as part of https://github.com/Khan/perseus/pull/2864, but there were some issues when I tried it initially. This fixes some issues and hacks around the Radio issue (with a ticket to return and fix it).
> Remove onChange from UniversalWidgetProps

- .changeset/tiny-rocks-whisper.md
- packages/perseus-core/src/validation.types.ts
- packages/perseus-editor/src/widgets/number-line-editor.tsx
- packages/perseus/src/widgets/explanation/explanation.tsx
- packages/perseus/src/widgets/number-line/number-line.tsx
[resolving-the-unexplainable] The goal of this PR is to solve the several issues that are causing LEMS-3474. 
Unfortunately, our Explanation Widget allows scorable widgets to be nested inside its content. This is not a very well known feature of the widget, and we missed adding the User Input Manager to it as a result. 
This PR adds in the User Input Manager to the Explanation widget, while also fixing several small issues related to how the Number Line Widget accesses the User Input. 
Issue: LEMS-3474
- Manual testing 
- Existing tests pass
> docs(changeset): Fixing several issues related to User Input in our Explanation and Number Line Widgets

- .changeset/swift-wolves-serve.md
- packages/perseus/src/widgets/image/image.tsx
Add feature flag check for decorative props in Image Widget
Issue: LEMS-3450
> [Image] Add feature flag check for decorative props in Image Widget
